### ISSUE TITLE
gem command freezes by a file lock.

### ISSUE THREAD

**Issue by jnory** [rubygems/rubygems#1036]
Hi,

In our environment, "gem install" command always freezes.

Since the reason of the freeze seems to be occurred by a file lock of $HOME/.gem/specs/api.rubygems.org%80/latest_specs.4.8, I comment out the code of the file lock, and it works well.

The modifications are:
rubygems.rb

``` ruby:rubygems.rb
  def self.read_binary(path)
    open path, 'rb+' do |f|
      #f.flock(File::LOCK_EX) <= COMMENT OUT
      f.read
    end

  rescue Errno::EACCES
    open path, 'rb' do |f|
      f.read
    end
  end
```

remote_fetcher.rb

``` ruby:remote_fetcher.rb
  def cache_update_path uri, path = nil, update = true
    mtime = path && File.stat(path).mtime rescue nil

    data = fetch_path(uri, mtime)

    if data == nil # indicates the server returned 304 Not Modified
      return Gem.read_binary(path)
    end

    if update and path
      open(path, 'wb') do |io|
        #io.flock(File::LOCK_EX) <= COMMENT OUT
        io.write data
      end
    end

    data
  end
```

Although the above modifications work well, It may occur other problems. 
Does anyone have more suitable idea?

Our environment is:
Ubuntu 14.04 LTS

Ruby is installed by rbenv. version is:
% gem -v
2.2.2
% ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

Thanks,

**Comment by mooreryan** [comment]
I'm also having trouble with those two lines of code that @jnory commented out. I think it is related to this pull request: https://github.com/rubygems/rubygems/pull/1005. In my case, the issue seems to be when trying to use gem install when on an nfs mounted drive, e.g.,
```
$ gem install trollop
ERROR:  While executing gem ... (Errno::ENOLCK)
    No locks available @ rb_file_flock - ~/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/trollop-2.1.1.gemspec
```
I followed the stack trace of this error to the same two lines that @jnory commented out and removing the locks fixed the error for me as well.

Does ruby have anything like `stat -f -L -c %T my_file` to perhaps check if you're trying to lock a file on an nfs mounted drive?
