### ISSUE TITLE
$ gem install *.gem should do topo sort

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#108]
At least, I've had hints that it doesn't... we don't have a test for it, that's for sure.

From: http://rubyforge.org/tracker/index.php?func=detail&aid=29231&group_id=126&atid=578

**Comment by copiousfreetime** [comment]
This appears to still be an issue. When doing an installation of multiple gems on the command line, the gems are individually installed in isolation. The set of all gems on the command line is not aggregated into a single installation set.

It looks like this could be implemented by updating [`InstallCommand#install_gems`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/install_command.rb#L292-L313) to create a `Gem::RequestSet` and installing in the same manner as [#install_from_gemdeps](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/install_command.rb#L209).

In general, I think this issue is a consolidation of all the inputs to installation and a normalization of them to use a `RequestSet`. 

We would need to make sure we still support ignoring dependendencies.

**Comment by bronzdoc** [comment]
This has been ide for too long i'm going to close it, if still interested please let us know in a new issue.
