### ISSUE TITLE
--no-document rdoc,ri causes error

### ISSUE THREAD

**Issue by swills** [rubygems/rubygems#1147]
Using the --no-document rdoc,ri flag causes error:

```
root@11amd64-default:/wrkdirs/usr/ports/www/rubygem-rails/work/rails-3.2.19 # /usr/local/bin/gem21 install rails-3.2.19.gem -l --no-update-sources --install-dir /wrkdirs/usr/ports/www/rubygem-rails/work/stage/usr/local/lib/ruby/gems/2.1 --ignore-dependencies --bindir=/wrkdirs/usr/ports/www/rubygem-rails/work/stage/usr/local/bin --no-document rdoc,ri
install
Successfully installed rails-3.2.19
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
root@11amd64-default:/wrkdirs/usr/ports/www/rubygem-rails/work/rails-3.2.19 # /usr/local/bin/gem21 install rails-3.2.19.gem -l --no-update-sources --install-dir /wrkdirs/usr/ports/www/rubygem-rails/work/stage/usr/local/lib/ruby/gems/2.1 --ignore-dependencies --bindir=/wrkdirs/usr/ports/www/rubygem-rails/work/stage/usr/local/bin
install
Successfully installed rails-3.2.19
Parsing documentation for rails-3.2.19
Done installing documentation for rails after 0 seconds
1 gem installed
root@11amd64-default:/wrkdirs/usr/ports/www/rubygem-rails/work/rails-3.2.19 #
```

This also doesn't happen if you use --no-rdoc --no-ri.

**Comment by duckinator** [comment]
Hi! So, this issue's a year old, but I'll explain what's up in case you or anyone else runs into a similar problem in the future and finds this issue:

It looks like either you were using the `--no-document` flag improperly, or its usage has changed in the past year.

The way `--document` and `--no-document` work, you want to specify either `--no-document` _or_ `--document [TYPES]`, as opposed to what you were doing.

I'm not sure what it was doing before to yield that error, but now it treats `gem install x --no-document rdoc,ri` the same as `gem install x rdoc,ri --no-document` and raises an error about being unable to install the `rdoc,ri` gem.

I'm closing this issue, since it can be resolved by simply removing `rdoc,ri` from the command line arguments. Sorry it took so long for you to get a response!
