### ISSUE TITLE
native extensions installed in 3 places

### ISSUE THREAD

**Issue by swills** [rubygems/rubygems#1170]
For example, cool.io version 1.2.4 installed with gem 2.4.5, I get:

```
/usr/local/lib/ruby/gems/2.1/extensions/amd64-freebsd-11/2.1/cool.io-1.2.4/http11_client.so
/usr/local/lib/ruby/gems/2.1/gems/cool.io-1.2.4/lib/http11_client.so
/usr/local/lib/ruby/gems/2.1/gems/cool.io-1.2.4/ext/http11_client/http11_client.so
```

same file in all 3 places. Is this necessary? Seems like it shouldn't be. Lots of other gems show same behavior, just picked a random one as an example.

**Comment by copiousfreetime** [comment]
Those 3 files are currently appear to be as designed, from my quick review of the rubygems code pertaining to this:
* `ext/http11_client/http11_client.so` is the source file made by the extension that is then installed
* `extensions/amd64-freebsd-11/2.1/cool.io-1.2.4/http11_client.so` is the destination directory
* `lib/http11_client.so` is installed because `Gem.install_extension_in_lib` is true, and is probably overridden by other ruby engines and platform customizations. It appears this option is schedule for removal in Rubygems 3.

I hope that does an adequate job of explaining the current state.
