### ISSUE TITLE
installing gems via Gemfile gemspec

### ISSUE THREAD

**Issue by mpapis** [rubygems/rubygems#1204]
exactly the same steps as in https://github.com/rubygems/rubygems/issues/1141 but there is new error (https://github.com/rubygems/rubygems/issues/1141#issuecomment-71127935):

> Unable to resolve dependency: user requested 'asciidoctor-doctest (= 1.5.2.dev)'

**Comment by jirutka** [comment]
It’s already described in #1141, but to be more clear; minimal steps to demonstrate the problem:

```sh
$ mkdir foo
$ cd foo
$ echo "Gem::Specification.new do |s|\n  s.name = 'foo'\n  s.version = '0.0.1'\n  s.add_runtime_dependency 'activesupport', '~> 4.2'\nend" > foo.gemspec
$ echo "source 'https://rubygems.org'\ngemspec" > Gemfile
$ gem install --file Gemfile
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: user requested 'foo (= 0.0.1)'
```

Rubygems failed, because it’s trying to resolve the gem, we have just created, in the Rubygems repository. This behaviour is wrong.

Exactly the same problem appears when you have already published gem, but you bump version for upcoming development.

**Comment by mpapis** [comment]
closing in favour of #1033
