### ISSUE TITLE
Installation of packages behind proxy that uses authentication

### ISSUE THREAD

**Issue by codingant007** [rubygems/rubygems#1313]
When I try `gem install <package>`

This error occours.
```
ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?): https://user:pass@202.141.80.24:3128/";

```
In [this issue](https://github.com/rubygems/rubygems/issues/360) it has already been concluded that the NTLM proxy wasn't supported back then in 2012. 
Many uses who are behind authentication based proxy are handicapped by this. 

I'm not totally sure of my interpretation of the problem. If it is right someone please take some time to resolve this.
Thank you.

**Comment by tenderlove** [comment]
Well, it seems like maybe the URI you're trying to use isn't formatted correctly.  Can you take the proxy URL and do something like this:

```
irb(main):007:0> x = "https://t.alamanda:IwontSAYgetlosT@202.141.80.24:3128/"
=> "https://t.alamanda:IwontSAYgetlosT@202.141.80.24:3128/"
irb(main):008:0> URI(x)
=> #<URI::HTTPS https://t.alamanda:IwontSAYgetlosT@202.141.80.24:3128/>
irb(main):009:0>
```

If that works, then the proxy should too, unless it's an NTLM proxy.  If your problem is that you can't authenticate against an NTLM proxy, then you should be getting a different error.

**Comment by copiousfreetime** [comment]
Closing this for now. @codingant007 if you still have this issue please reopen.
