### ISSUE TITLE
Set up Homu

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#1501]
In  #1496 it was decided that we're going to use homu.io, not LGTM.co.

Going off of Homu's website, I believe all that needs to happen is somebody with admin access to the repository registering rubygems/rubygems on http://homu.io/n/.

Somebody that actually has experience with Homu (@indirect?) may know of other steps that need to be taken, if anyway.

**Comment by krainboltgreene** [comment]
@indirect: I think I just realized homu doesn't really have much of an advantage in the post-protect branch world.

If you protect the default branch (master, core, whatever) you're not allowed to merge at all if the target has commits the source doesn't have.

One of Homu's value propositions is that it pulls down both branches, performs a merge, and then tells you if the merge results in :green_heart:, right? But in the case of protected branches, you never have to worry about if this branch will break master, because it's not allowed to go in until it has all of master.

Thoughts?

**Comment by segiddins** [comment]
But it saves you from constantly having to manually rebase

**Comment by krainboltgreene** [comment]
Does homu push up it's rebase?

**Comment by segiddins** [comment]
Yes, it performs the actual merge and pushes to master once the build passes

**Comment by krainboltgreene** [comment]
Oh, I meant does it push to the source. Yeah, see that won't work for a post-protect-branch world. It'll appear like you can't merge it until homu does it for you, and only if you give homu permissions to explicitly push to protected branches.

**Comment by segiddins** [comment]
No, it'll work with protected branches.

**Comment by krainboltgreene** [comment]
Only if you give homu permissions that no one else would have.

**Comment by segiddins** [comment]
Nope. since protected branches just require passed status checks, which will happen on the merge commit, and then homu fast-forwards that commit to the merge target

**Comment by duckinator** [comment]
@krainboltgreene when we're pairing later today, do you want to throw together a test repo and determine + document here how Homu behaves and if there are any potential pain spots with adopting it?

**Comment by indirect** [comment]
Homu is registered and set up--we have not enabled branch protection yet, but if we do it will allow any commit that has been tested, whether pushed by a developer or by Homu.
