### ISSUE TITLE
Compiling native extensions fails while clang is installed, succeeds when gcc is installed

### ISSUE THREAD

**Issue by tmsbrg** [rubygems/rubygems#1508]
I'm not sure if this is a bug with Gems or with some underlying system like Rake, but I thought I'd report it here first as people here would know that better than me.

My system:
Debian testing
clang 3.6.2-3
ruby 2.2

What I did:
1) Try to install Jekyll with `sudo gem install jekyll`
2) Get a confusing error building native extensions for ffi-1.9.10.gem ([full output](http://pastebin.com/2mVEvsLR))
3) Find in `/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/ffi-1.9.10/mkmf.log` that it's trying to compile directly with gcc(original log lost now)
4) Installing GCC fixes the issue

What I expected:
Ruby tries to install native extensions with whatever compiler I have. On Debian at least it can do that by using `cc` instead of `gcc` to build, as cc is always linked to the preferred compiler on the system.

Wat I got:
Ruby failed because I didn't have GCC, and gave a confusing error message to boot(I thought I had to install autotools or something because it said it couldn't create the Makefile)

**Comment by tenderlove** [comment]
Ruby uses the compiler used to compile itself.  Try `ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]'` to see the compiler used.  The reason it does this is because it can only guarantee the extension to work if the compilers are the same.  For example, if the Ruby you're using is cross compiled for windows using a special compiler, using system `gcc` to compile an extension for *that* Ruby wouldn't make sense.

If you reinstall your Ruby with clang, it should clear this up.

**Comment by rapito** [comment]
> Ruby uses the compiler used to compile itself. Try `ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]'` to see the compiler used. The reason it does this is because it can only guarantee the extension to work if the compilers are the same. For example, if the Ruby you're using is cross compiled for windows using a special compiler, using system `gcc` to compile an extension for _that_ Ruby wouldn't make sense.
> 
> If you reinstall your Ruby with clang, it should clear this up.

I just had a similar issue upgrading a small server I have on ubuntu-bionic from ruby 2.4 to ruby 3 and rails 7. 
A lot of gems for rails were failing to install natively such as bigdecimal and such... 
Installing rails with clang solved the issue instead of gcc.

Glad this comment was here, else I would still be trying to patch those undeclared compiled options being used.
