### ISSUE TITLE
Gems installer for Windows does not support ruby path with spaces

### ISSUE THREAD

**Issue by Demurgos** [rubygems/rubygems#1525]
I'm having a problem.

My current problem is that I need to manually fix the path to ruby in `rubyDir/bin/myGem.bat` because there is an error in the script automatically generated. This problems is caused by an improperly escaped path to the ruby executable. It arises when the installation directory contains spaces: my installation directory is `C:\Program Files\Ruby22`.
This is the error I get when trying to use a gem:
````txt
C:\Windows\system32>sass --version
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
````

Here is the generated file for `gem install sass`:
````bat
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@""C:\Program Files\Ruby22\bin\ruby.exe" "C:/Program Files/Ruby22/bin/sass" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@""C:\Program Files\Ruby22\bin\ruby.exe" "%~dpn0" %*
````
The path should only be surrounded by one double quotes at the beginning, but here there are 2 double quotes at the beginning. Here is the expected version:
````bat
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\Program Files\Ruby22\bin\ruby.exe" "C:/Program Files/Ruby22/bin/sass" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\Program Files\Ruby22\bin\ruby.exe" "%~dpn0" %*
````

I do not know Ruby, but I think that the issue is located [around this line](https://github.com/rubygems/rubygems/tree/master/lib/rubygems/installer.rb#L730).

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current envrionment details:

```
$ gem env version
2.4.5.1
```

**Comment by segiddins** [comment]
I believe this is a known issue, and at the moment is reccomend installing ruby in a path without spaces until it gets fixed.

**Comment by copiousfreetime** [comment]
I'm assuming that you are are installing via http://rubyinstaller.org/ ?

Currently, the ruby installer FAQ explicitly says not to install in `C:\Program Files` -- https://github.com/oneclick/rubyinstaller/wiki/faq#no_pgmfiles

I'm sure that goes against much of the windows way of doing things, unfortunately that's the way it currently stands with ruby and windows.

If you install ruby via the installer, in a path without spaces in it (I believe it does this by default) and then do `gem install sass` and this problem still exists, then please reopen this issue.

**Comment by Demurgos** [comment]
That's right, I used Ruby Installer.

I see that the FAQ states to not install in `Program Files` but the answer is very far from being satisfying: it could at least explain why this one software is so different (considering other similar software like MinGW, Node or the JDK don't need it). It should at least be displayed during the installation if it's not planned to be fixed...

The reason why I opened this issue here is because this is the single problem I have encountered with ruby installed in `Program Files` (it's quick to fix manually so I usually go with it, but today I was annoyed by this again and decided to post). There may be other issues with path and spaces, but this one seems easy to fix. While aiming to support a standard Windows install, you have to start somewhere.

I mostly used ruby for its gems so I may need to take a closer to the language to understand exactly what's the problem here and fix it, but if I send a PR would it be at least considered or just rejected "because the FAQ states you should not used `Program Files`" ?

(I already tried to install it at the root to check if it works (it worked) but I preferred to reinstall it in it's proper directory and keep fixing the .bat)

**Comment by copiousfreetime** [comment]
@Demurgos I completely understand your frustration. I did a little more searching, and there is one item in the https://github.com/oneclick/rubyinstaller/wiki/Troubleshooting that says that spaces may be a problem because of the devkit gcc compiler. I would ask over in the rubyinstaller issues about what needs to be done to fully support spaces in the path for ruby on windows.

On the pure rubygems front, if there needs to be updates to the bin file generation for windows, the code that generates the .bat file is in https://github.com/rubygems/rubygems/blob/9d78c0c3b83060605542c3fdddc3a1ec091db856/lib/rubygems/installer.rb#L726-L739. Feel free to submit a pull request to fix any bugs you find.

**Comment by copiousfreetime** [comment]
@Demurgos here is more information on spaces in paths for ruby on windows -- https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#requirements

**Comment by Demurgos** [comment]
Thank you for your help, I'll try to fix it and send a PR.

**Comment by ams-tschoening** [comment]
I would like to mention that this is NOT a Windows-only issue, paths with spaces can happen on all platforms. It's only that this kind of bugs is triggered easily in Windows because of its default directory naming. But that doesn't change a thing about that not supporting paths with spaces is a bug in all software.

Instead of creating a FAQ telling people to avoid it, one should simply track all of those bugs and fix them at some point. Especially because so many of them are simply missing quotes in some shell scripts and make files, the latter is why I landed here. :-/

	C:\Program Files\Ruby\2.6.5\bin>gem install solargraph
	Fetching backport-1.1.2.gem
	Successfully installed backport-1.1.2
	Fetching benchmark-0.1.0.gem
	Successfully installed benchmark-0.1.0
	Fetching bundler-2.1.4.gem
	Successfully installed bundler-2.1.4
	Fetching e2mmap-0.1.0.gem
	Successfully installed e2mmap-0.1.0
	Fetching jaro_winkler-1.5.4.gem
	Temporarily enhancing PATH for MSYS/MINGW...
	Building native extensions. This could take a while...
	ERROR:  Error installing solargraph:
	        ERROR: Failed to build gem native extension.

	    current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	C:/Program\ Files/Ruby/2.6.5/bin/ruby.exe -I C:/Program\ Files/Ruby/2.6.5/lib/ruby/2.6.0 -r ./siteconf20200204-13668-p6lmwi.rb extconf.rb
	creating Makefile

	current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	make "DESTDIR=" clean
	Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

	current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	make "DESTDIR="
	Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

	make failed, exit code 2

	Gem files will remain installed in C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4 for inspection.
	Results logged to C:/Users/tschoening/.gem/ruby/2.6.0/extensions/x64-mingw32/2.6.0/jaro_winkler-1.5.4/gem_make.out

Things even fail if one tries to use Junctions to make Ruby available in a path without spaces, while actually storing it using platform standards.
