### ISSUE TITLE
Sources with https protocol

### ISSUE THREAD

**Issue by lucasmior-hp** [rubygems/rubygems#1532]
- [x] Installing a library
  - [x] The command line `gem`

Hey, I'm trying to add others repositories with **https** protocol  as a source registry but I cannot add it. I tried using http but doesn't work too

```
$ gem sources -a https://my_url/gems
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 
$ gem sources -a http://my_url/gems
bad response Service
```
```
$ gem env version
2.4.3
```
There some solution to do it?

**Comment by duckinator** [comment]
Hi! So, that error means that the SSL certificate cannot be verified by the OpenSSL library. I know of two common potential causes of this:

1. Using self-signed certificates. There is no way to verify these, so verification will fail.
2. Something related to Certificate Authority bundles. (I don't know the exact details of this.)

I don't actually know how to resolve either of these problems, sadly, but hopefully this gives you a starting point with debugging it.

**Comment by ph** [comment]
@lucasmior-hp I believe @duckinator is correct, you are probably trying to use a self signed certificate to connect to your own gem server. You have to use the `ssl_client_cert`  and `ssl_ca_cert` in your `.gemrc` also take note that bundler has his own variables too you have to set.

Its been a long time since I dealt with that scenario, but I think this gist might help you
https://gist.github.com/Integralist/acda6e7647e0e23a001c
