### ISSUE TITLE
Gem::Version objects can be == with different hashes

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1617]
```ruby
Gem::Version.create('1.0') == Gem::Version.create('1.0.0') # => true
Gem::Version.create('1.0').hash == Gem::Version.create('1.0.0').hash # => false
```

**Comment by elifoster** [comment]
I'm fairly certain this is because there isn't actually a `Gem::Version#==` method. There's `eql?`, but no `==` alias for it. Using `eql?` with those two Gem::Version objects returns false.

**Comment by segiddins** [comment]
@elifoster see `<=>`

**Comment by elifoster** [comment]
I must be missing something. What about that method?

**Comment by drbrain** [comment]
<=> plus including Comparable gives all the comparison methods, <, <=, ==, >=, >

Like defining #each plus including Enumerable

**Comment by drbrain** [comment]
I'm worried that making the two different versions have the same Hash may result in confusion or bugs.

Version `1` and `1.0.0` are ==, but if `1` becomes a Hash key first users may be confused if their `1.0.0` turns into `1` if the use the keys of the Hash for, say, output to screen or for building gem names (even though they should be using the method on Gem::Specification).

I'm unsure how big of an issue this will be in practice, though.  I don't think anything in RubyGems itself displays versions based on the Hash keys because the values have an object with the unmerged version for display or gem download name purposes.

**Comment by segiddins** [comment]
@drbrain yeah I thought about that, but in general using hash keys as a value isn't all that common.

As for actually 'fixing' this, my first idea is to use a `normalized segments` approach, stripping out all 0s. It might also mean we could make `==` faster

**Comment by drbrain** [comment]
@segiddins I agree, I wanted to have it noted so we could look out for it.
