### ISSUE TITLE
add way to disable "may be overly strict if <gem> is semantically versioned" for gems that are not promised to be semantically versioned

### ISSUE THREAD

**Issue by matkoniecz** [rubygems/rubygems#1636]
I'm having a problem or would like to suggest a feature.

My current problem is unfixable warning spam during building gem.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

On building gem part of output is

```
WARNING:  pessimistic dependency on rest-client (~> 1.8.0) may be overly strict
  if rest-client is semantically versioned, use:
    add_runtime_dependency 'rest-client', '~> 1.8', '>= 1.8.0'
WARNING:  pessimistic dependency on sys-filesystem (~> 1.1.4) may be overly strict
  if sys-filesystem is semantically versioned, use:
    add_runtime_dependency 'sys-filesystem', '~> 1.1', '>= 1.1.4'
WARNING:  pessimistic dependency on rmagick (~> 2.15.2) may be overly strict
  if rmagick is semantically versioned, use:
    add_runtime_dependency 'rmagick', '~> 2.15', '>= 2.15.2'
```

Unfortunately it is not clear whatever I may assume that this gems are semantically versioned (see https://github.com/rmagick/rmagick/issues/249 https://github.com/djberg96/sys-filesystem/issues/19 https://github.com/rest-client/rest-client/issues/503).

So this strict versioning is intentional.

I want to be able to mark dependencies as "not promised to be semantically versioned", so this warning will cease. From looking at https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb it seems that there is no way to do that.

Maybe gems itself should declare in their metadata whatever semantic versioning is promised?

**Comment by segiddins** [comment]
You can use a >= and < dependency to ignore the warbing

**Comment by drbrain** [comment]
This warning is designed to improve the RubyGems ecosystem as a whole by encouraging authors adopt semantic versioning. I'm not sure a gem author should be able to disable or suppress this warning.  Gem authors have a higher level of responsibility and burden than other users of RubyGems so they should be prepared to consider the recommendations we are providing.

There are two ways this encourages improvement of Ruby, the first is encouraging authors to communicate with one another by providing friction in the release process, which was successful.  You filed the issues against rmagick, sys-filesystem and rest-client 15 hours ago.  The sys-filesystem author said ["use ~> 1.1"](https://github.com/djberg96/sys-filesystem/issues/19#issuecomment-225195793).

The second way, you will find, is friction from users when they can't use your gem because, in the future, the other gems they use require sys-filesystem 1.5, rmagick 2.18 and rest-client 1.9.  You will get bug reports about your dependencies being too specific.

Building a gem should be either rare or automated.  If you are building a gem every day then release would be automated and you wouldn't see the warnings.  If you are building a gem every once-in-a-while then the warning is important.
