### ISSUE TITLE
Remove external tool dependency

### ISSUE THREAD

**Issue by lynnco** [rubygems/rubygems#1646]
Bundler and RubyGems have separate release systems. We'd like to combine them into a single release system, so that we don't have to maintain two.

**Comment by drbrain** [comment]
What tool is more comprehensive, pluggable, upgradeable than hoe?  The entire release process is built around it, so switching to anything else means we will have to maintain all its properties by hand.

**Comment by segiddins** [comment]
@drbrain I personally find hoe to be difficult to work with, we don't use very many of its features, and we've already had to start hacking around it

**Comment by djberg96** [comment]
What can hoe do that we can't do with rake? Genuinely curious.

@segiddins Can you provide an example of something we've had to hack around?

**Comment by segiddins** [comment]
And now we have bundler vendored, we could even switch to using those release tasks.

**Comment by drbrain** [comment]
The bundler release tasks are broken due to the many missing dependencies:

* `build` must depend on `release:guard_clean` or you may package files that are not checked-in.
* `release:rubygem_push` must depend on `build` or you may try to push a package that is not built.
* `release:source_control_push` must depend on build or you may try to tag a package that cannot be built.
* `release:rubygem_push` must depend on `release:source_control_push` or you may push a gem with no tag.

The bundler release tasks are missing features that allow actions to happen after the release is tagged and uploaded to rubygems.org including uploading the tarball and zip file to S3, updating the blog,  updating the guides.

**Comment by drbrain** [comment]
Oh, I forgot, bundler release tasks don't use Gem::PackageTask so don't have a place to build the tarball or zip file we need to upload to S3.

**Comment by djberg96** [comment]
Well, since rubygems and bundler are merging, would it make sense to modify bundler to use Gem::PackageTask instead of whatever it's doing now?

**Comment by segiddins** [comment]
@drbrain all I can say is, as the person doing releases for the past few months, using hoe has not been seamless and it hasn't been easy for me to fix the issues I've been having </personal opinion>

**Comment by indirect** [comment]
@segiddins [This commit](https://github.com/rubygems/rubygems/commit/2f7eed9fedde0b910558b0cbf09825863678ab9b) was the fix after a new version of Hoe broke the build, right?

**Comment by segiddins** [comment]
@indirect no that commit was the fix for bundler having other files that match the version regexp and hoe picking the wrong one

**Comment by indirect** [comment]
Ah, okay.

@drbrain @djberg96 I'm the one who said we should eventually remove Hoe, but at the time I wasn't thinking about how customized the RubyGems release process is. This ticket is effectively a note to our future selves for after the merger is farther along. At that point, I'd like to re-evaluate how best to combine Bundler's release tasks and Hoe's release tasks into something that is both sufficient for RubyGems and easy to expose to existing gems that depend on the Bundler tasks.
