### ISSUE TITLE
Pessimistic major version, unexpected behavior

### ISSUE THREAD

**Issue by camertron** [rubygems/rubygems#1684]
Hey guys,

I was pairing with a coworker today when we ran into this curiosity:

```ruby
Gem::Requirement.new('~> 2').satisfied_by?(Gem::Version.new('3'))  #=> false
```

I'm guessing this would be surprising to a number of Ruby developers, especially since the pessimistic operator works differently for minor and patch version segments:

```ruby
Gem::Requirement.new('~> 2.1').satisfied_by?(Gem::Version.new('2.1'))  #=> true
Gem::Requirement.new('~> 2.1').satisfied_by?(Gem::Version.new('2.0'))  #=> false
```

Is this on purpose?

Environment:
Ruby 2.1.6
Rubygems 2.2.3

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
Whoa! This is surprising to me, too. I can't even find anywhere that this is documented. I guess a reason you might not actually need it is because it is semantically identical to `>= 2`. Go ahead and use that as a workaround for the time being, but I think we should actually make `~> 2` work the same as `>= 2` instead of the same as `~> 2.0`.

**Comment by camertron** [comment]
Cool, thanks @indirect 😄

**Comment by segiddins** [comment]
It works this way since `~>` is defined as matching when `{ |v, r| v >= r && v.release < r.bump }`, and `Gem::Version.new('2').bump` can't really be anything other than `3` -- theres no such thing as a 0-segment version.

**Comment by drbrain** [comment]
This has been expected behavior for some time ([test here](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_requirement.rb#L290-L293)).

See [Gem::Requirement#satisfied_by?](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/requirement.rb#L239-L244) which uses the [~> operation](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/requirement.rb#L24) which uses [Gem::Version#bump](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/version.rb#L214-L229).  See explanation above by @segiddins.

This was documented [starting in RubyGems 2.3.0](https://github.com/rubygems/rubygems/commit/fca24a695d2ee3a0bdb9702b752b34d44def6a53), but was expected behavior long before that, you'll see that Gem::Version#bump has had the same behavior [back to 2005](https://github.com/rubygems/rubygems/blob/f554bc5/lib/rubygems/version.rb#L163-L168).

See also #896.

**Comment by indirect** [comment]
Thanks for clarifying @drbrain! I've opened a new ticket about adding documentation for this to the section of the RubyGems guide about versions at rubygems/guides#159.

**Comment by sevenseacat** [comment]
I came across this issue today, and found it confusing. I ran the current behaviour past a couple of other developers, and all were surprised by it - does this 'adding an implied `.0`' follow the principle of least surprise? Why is there this exception to the rule of how `~>` works? This seems like a bug to me.
