### ISSUE TITLE
Feature Request: Add ability to specify expiration length with gem cert command

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1719]
The cert I generated (using gem cert --build) expired after a year. 

I would like the ability to add the length of time before the cert expires, in days. At the moment it looks like it's fixed at one year. Perhaps a "-t/--time" command line switch.

**Comment by bronzdoc** [comment]
Would `-d/--days` make more sense?

**Comment by djberg96** [comment]
@bronzdoc Works for me!

**Comment by grempe** [comment]
Just in case anyone is landing on this issue looking for a way to generate longer duration certs for signing ruby gems.

Until this code is released (or if you a pinned to an older version of rubygems), I created a tiny script that simply monkey-patches the `Gem::Security::ONE_YEAR` constant to be a multiple of years instead of hard-coded to a single year.

I have tested it on a single release of my own and it seems to be ok. Use at your own risk of course. Its a pretty simple change though.

https://gist.github.com/grempe/f2a9822578d46c0545b614ced20d5695

See also:

https://github.com/djberg96/sys-uname/issues/5#issuecomment-253396998
