### ISSUE TITLE
Add "webhook" command from gemcutter

### ISSUE THREAD

**Issue by sferik** [rubygems/rubygems#178]
All the gemcutter commands were merged into rubygems in version 1.3.6 except `yank` and `webhook`. It seems like we should just merge these into rubygems and then kill the gemcutter gem.

**Comment by krainboltgreene** [comment]
Two bikeshed counter arguments:

  - Advanced features being separated has some value
  - It adds more "weight" to a single command

Frankly though I do agree it's kinda annoying to have to google this stuff every time, remember to install gemcutter, and then look at the documentation.

**Comment by copiousfreetime** [comment]
The `yank` command appears to have already been migrated over in 2012, seems reasonable to migrate over webhooks and deprecate gemcutter. 

Since the webhooks are a part of the official rubygems.org ecosystem, it seems reasonable that the official client for rubygems.org should support the full api.

In fact, this may spawn an additional issue. Checking for parity between what rubygems.org provides at the api level and making sure that rubygems cli has support for it.

**Comment by bronzdoc** [comment]
This has been idle for too long, if you still interested in this feature please let us know and i'll reopen it
