### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by TaylorHuston** [rubygems/rubygems#1797]
I'm having a problem or would like to suggest a feature.

My current problem is:
SSL error when trying to run bundle update

Error can be temporarily fixed by changing Gem source from https to http

```
Could not verify the SSL certificate for
https://rubygems.org/quick/Marshal.4.8/simple_form-0.4.0.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```
I've gone through this guide
http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

As well as running 
`gem update --system`
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [i386-mingw32]
  - INSTALLATION DIRECTORY: D:/Ruby22/lib/ruby/gems/2.2.0
  - USER INSTALLATION DIRECTORY: C:/Users/taylo/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: D:/Ruby22/bin/ruby.exe
  - EXECUTABLE DIRECTORY: D:/Ruby22/bin
  - SPEC CACHE DIRECTORY: C:/Users/taylo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - D:/Ruby22/lib/ruby/gems/2.2.0
     - C:/Users/taylo/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - E:\cmder\bin
     - C:\Program Files\Git\bin
     - C:\Program Files\Git\usr\bin
     - C:\Program Files\Git\share\vim\vim74
     - E:\cmder\vendor\conemu-maximus5\ConEmu\Scripts
     - E:\cmder\vendor\conemu-maximus5
     - E:\cmder\vendor\conemu-maximus5\ConEmu
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\ProgramData\Oracle\Java\javapath
     - D:\Program Files\Java\jdk1.8.0_73\bin
     - D:\Python27\
     - D:\Python27\Scripts
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
     - C:\WINDOWS\system32\config\systemprofile\.dnx\bin
     - C:\Program Files\Microsoft DNX\Dnvm\
     - C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
     - C:\Program Files\Git\cmd
     - D:\Program Files\nodejs\
     - D:\Program Files (x86)\Heroku\bin
     - C:\Users\taylo\AppData\Roaming\npm
     - C:\Program Files (x86)\GtkSharp\2.12\bin
     - D:\AndroidSDK\platform-tools
     - C:\Program Files (x86)\Skype\Phone\
     - D:\Program Files\TortoiseHg\
     - D:\Ruby22\bin
     - D:\Program Files (x86)\Brackets\command
     - D:\Applications\Atlassian\atlassian-plugin-sdk-6.2.6\bin
     - C:\Users\taylo\AppData\Local\Microsoft\WindowsApps
     -
     - E:\cmder
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by tilo** [comment]
+1 what is the status of this?

The described procedure, and even manually copying the PEM file does not seem to work

I will also abide by the code of conduct. :-(

**Comment by drbrain** [comment]
@TaylorHuston that error message is from bundler. What error do you get with `gem install`?

**Comment by drbrain** [comment]
@tilo what error did you get with `gem install`? We cannot guess how to fix your error.

**Comment by rawlins** [comment]
I had a similar issue today, and the problem seems to be with `rvm` installation process interacting with macports.  On macports, the default setup for the openssl cert file is that it comes from the package `curl-ca-bundle`; openssl's cert.pem is a symlink to a file in the macports curl installation.  `rvm install` apparently overwrites the openssl cert.pem file and therefore the target of this link with something that is out of date (asking for root password to do it even), leading to the following error with rubygems 2.6.8 (seen when manually installed):

    ERROR:  SSL verification error at depth 2: certificate has expired (10)
    ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA expired at 2014-01-28T12:00:00Z
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

After running `sudo port uninstall curl-ca-bundle` and `sudo port install curl-ca-bundle` in succession `gem install` now works again.  This fix works before the manual upgrade of rubygems as well, so installing ruby from rvm, running the above two port commands, and then doing `gem update --install` works to getting current rubygems.  After this fix on a clean rvm ruby install I can replicate the above ssl error by doing `sudo port uninstall curl-ca-bundle` and then `rvm osx-ssl-certs update all`.

Two side-notes that complicated debugging:
* The official docs for dealing with SSL errors reference rubygems 2.6.7, not 2.6.8 ([http://guides.rubygems.org/ssl-certificate-update](http://guides.rubygems.org/ssl-certificate-update)).
* The instructions for manually installing a certificate at the above link had no impact on any version of anything I tried it on, with or without the macports cert package, with any version of rubygems.

**Comment by bronzdoc** [comment]
Closing due to lack of response
