### ISSUE TITLE
Please consider an API endpoint for listing all available gems.

### ISSUE THREAD

**Issue by vincentwoo** [rubygems/rubygems#1828]
Hi everyone! I noticed that the current API does not appear to offer an endpoint to simply enumerate all gems that exist (but that it does allow [search](http://guides.rubygems.org/rubygems-org-api/#gem-methods)). I also noticed that one can potentially scrape all gems available through the [web view](https://rubygems.org/gems).

For my purposes (attempting to make a Ruby sandbox with essentially every Ruby gem installed) being able to enumerate the world would be very useful. Any chance that could be something we add to rubygems.org?

**Comment by djberg96** [comment]
I noticed that a `gem list --remote --verbose` shows me this:

    GET https://api.rubygems.org/latest_specs.4.8.gz

I'm guessing that we decompress and parse the information locally from there, so presumably you could do the same. But yes, I can how it would be nice to have an endpoint to just get a listing.

**Comment by vincentwoo** [comment]
Cool! Is that something a beginner could potentially contribute, or would one have to be pretty deep into rubygems design to write a PR for?

**Comment by djberg96** [comment]
@vincentwoo I think this is actually a rubygems.org issue, not a rubygems issue, since we'll dealing with the web server response. So you'll want to post there.

https://github.com/rubygems/rubygems.org

I've no idea as to the degree of difficulty. It could just be a matter of setting up a Rails route for all I know. Then again, it may be more complicated. :)

**Comment by vincentwoo** [comment]
No problem! Sorry I had the wrong repo.
