### ISSUE TITLE
RubyGems should have a Gemfile

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1897]
Developing RubyGems depends on specific versions of specific gems. RubyGems is unable to provide the versions requested by the rubygems-update gemspec, resulting in activation errors while attempting to run the tests. Behold:

```
$ cd rubygems/rubygems
$ rake newb
git submodule update --init
rake aborted!
Gem::LoadError: can't activate rake-10.5.0, already activated rake-12.0.0
```

To resolve this, RubyGems should include a Gemfile, allowing users to activate a set of gems compatible with developing the current version of RubyGems.

**Comment by segiddins** [comment]
This would be a nightmare to maintain, for the same reason bundler doesn't have a gemfile despite the same requirements. A set of binstubs would probably be more appropriate.

**Comment by indirect** [comment]
I'd be fine with binstubs that do the right thing; a Gemfile would work fine for running the right version of rake to parse the rakefile to generate the correct command to run the tests ¯\_(ツ)_/¯

**Comment by valk** [comment]
Ahh, if anyone comes here, the "solution" is to ```gem uninstall rake``` and remove the versions in conflict.

**Comment by indirect** [comment]
You can also force the correct version of rake by running `rake _10.0.1_ newb`, with the required version number inside the underscores.

**Comment by shevegen** [comment]
Actually it would be nice if we could also easily convert from Gemfile to individual .gemspec files and vice versa. This is obviously not hugely relevant to the issue that indirect has filed here but I was just thinking about it, also because I suggested a while ago to ruby-core that the specific versions for bindings to some libraries, such as readline, openssl etc..., should also on the homepage, as part of the documentation, state which versions they support, e. g. whether the versions supported include openssl-1.0.2k and openssl-1.1.0f. And I also suggested that this could be stored as part of .gemspec itself, which would probably be the best place to store it, but this requires some modifications to the format (probably a new entry there). I mention this only because I was reminded that the differences between Gemfiles and a list of .gemspec files (when viewed as a dependency), does not appear to be such a huge difference to me, so I +1 upped the suggestion above.

If we would have a 1:1 converter/generator, or at the least one that keeps all the relevant entries, then this should be quite helpful in general.

**Comment by colby-swandale** [comment]
This issue has been satisfied by the removal of hoe and having a proper setup tasks to allow for easy setup without any errors.

**Comment by hsbt** [comment]
@colby-swandale I agree with you.

**Comment by indirect** [comment]
👍🏻
