### ISSUE TITLE
Could not push updated version of already yanked gem 

### ISSUE THREAD

**Issue by shivabhusal** [rubygems/rubygems#1937]
I'm having a problem or would like to suggest a feature.

My current problem is : I could not push my `mygem.gemfile` to the server. The situation is, I have already yanked the particular version. Its been listed as `yanked` in the site `rubygems.org` but when I try to push the gem it asks me to yank the version again.

![image](https://cloud.githubusercontent.com/assets/8004593/26668185/49001b1c-46c8-11e7-80dc-c150cc8fe998.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.12
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
Hi @shivabhusal, thanks for writing up your problem! Unfortunately, this is intentional. It is impossible to push a new gem with the same version number once that version has been yanked. We don't allow pushing the same version again because that would make it possible to change what a user installs from moment to moment without their knowledge, which is really bad from a security standpoint.

You will need to increment the version number of your gem, and push a new version.
