### ISSUE TITLE
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rest-client (LoadError) 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require' 	from wp.rb:13:in `<main>'

### ISSUE THREAD

**Issue by M45KL** [rubygems/rubygems#2040]
i just got a problem with my ruby
```
root@kali:~# ruby wp.rb
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rest-client (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from wp.rb:13:in `<main>'
```
what happen ? i just want to open thats exploit from exploit-db

if you can answer, help me :D sorry for my bad english

**Comment by shevegen** [comment]
Perhaps try "gem install rest-client".

https://rubygems.org/gems/rest-client

There is also restclient without the '-', which is probably the wrong one:

https://rubygems.org/gems/restclient

I mention this because I remember some other project causing some confusion to me; I installed the wrong restclient variant there ... :\

By the way, what is wp.rb? If it is something you can share, it may help other people try to help you with that problem.

**Comment by colby-swandale** [comment]
@M45KL were you able to follow @shevegen's suggestion?

**Comment by colby-swandale** [comment]
ping @M45KL

**Comment by crawford97** [comment]
I am having the same issue, were you able to fix this?

**Comment by da-edra** [comment]
I'm having this exact same problem.

**Comment by da-edra** [comment]
@crawford97 I was missing NodeJS, it works after installing it.

**Comment by franczakPawel** [comment]
huj wam w dupe
