### ISSUE TITLE
Can't install gems on windows because of SSL

### ISSUE THREAD

**Issue by TrianglesPCT** [rubygems/rubygems#2113]
Got ruby(Ruby 2.4.2-2 (x64))here: https://rubyinstaller.org/downloads/

 Run: gem install jekll, fails because of some SSL cert nonsense.

 Update rubygems to latest etc etc

 Still doesn't work, same error.

 Followed all the work arounds, none of them worked.

The only thing that worked was disabling SSL: gem source --add http://rubygems.org/

 This is ridiculous, it should not require so much fiddling just to get this working on Windows.

If you can't get SSL working properly on windows, disable that stupid thing.

**Comment by segiddins** [comment]
> If you can't get SSL working properly on windows, disable that stupid thing.

Please be polite, this comes across as very aggressive. We're happy to help you try to debug the issue. Can you please share the exact error that's being printed, along with the output of `gem env`? Thanks

**Comment by Siva454** [comment]
Hello Segiddins,

Hi Everyone,
Could you please help on this issue ? I am trying to install wbench for client /browser performance .....

DevTools listening on ws://127.0.0.1:12114/devtools/browser/ec8bf90a-f504-4905-a
f25-e401a51dac5a
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in connect_nonblock': SSL_conne ct returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLE rror) from C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:inssl_socket_conn
ect'
from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:948:in connect' from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:indo_start'
from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:876:in start' from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:inrequest'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/timi
ngs/app_server.rb:9:in result' from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc hmark.rb:28:inapp_server_results'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in block (3 levels) in run' from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/brow ser.rb:34:invisit'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in block (2 levels) in run' from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc hmark.rb:18:intimes'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:18:in block in run' from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc hmark.rb:17:intap'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:17:in run' from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc hmark.rb:4:inrun'
from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/bin/wbench:43:i
n <top (required)>' from C:/Ruby24-x64/bin/wbench:23:inload'
from C:/Ruby24-x64/bin/wbench:23:in `

'Posted on the wbench concern page(https://github.com/desktoppr/wbench/issues/42) - No response and No one is ready to provide an answer

Kindly help me on this issue

-------------------------------------- gem version -----------------------------------


H:\>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.13
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby24-x64/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: H:/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: C:/Ruby24-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby24-x64/bin
  - SPEC CACHE DIRECTORY: H:/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby24-x64/lib/ruby/gems/2.4.0
     - H:/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby24-x64\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Progra~1\Oracle\11g\product\11.1.0\client_1\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Symantec\Workspace Virtualization\
     - C:\Program Files (x86)\HP\Virtual User Generator\strawberry-perl\perl\bin

     - C:\Program Files (x86)\QuickTime\QTSystem\
     - C:\Program Files (x86)\Sennheiser\SoftphoneSDK\
     - C:\Program Files (x86)\Symantec\VIP Access Client\
     - C:\Program Files\Common Files\ThinPrint\
     - C:\Program Files (x86)\Google\Chrome\Application
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Progra~1\Oracle\11g\product\11.1.0\client_1\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Symantec\Workspace Virtualization\
     - C:\Program Files (x86)\HP\Virtual User Generator\strawberry-perl\perl\bin

     - C:\Program Files (x86)\QuickTime\QTSystem\
     - C:\Program Files (x86)\Sennheiser\SoftphoneSDK\
     - C:\Program Files (x86)\Symantec\VIP Access Client\
     - C:\Program Files\Common Files\ThinPrint\
     - C:\Program Files\Git\cmd
     - C:\Program Files (x86)\Google\Chrome

**Comment by segiddins** [comment]
Could you take a look at our SSL troubleshooting guide and see if there's anything helpful in it? http://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#certificate-verify-failed

**Comment by Siva454** [comment]
Still no luck.....

H:\>wbench https://q1secure.qa.moneygram.com/
2017-12-17 13:45:03 WARN Selenium [DEPRECATION] :timeout= is deprecated. Use #re
ad_timeout= and #open_timeout= instead.
[7692:5504:1217/134505.215:ERROR:configuration_policy_handler_list.cc(92)] Unkno
wn policy: DnsPrefetchingEnabled
[7692:5504:1217/134505.340:ERROR:configuration_policy_handler_list.cc(92)] Unkno
wn policy: DnsPrefetchingEnabled

DevTools listening on ws://127.0.0.1:12755/devtools/browser/5c564b38-2806-43fb-b
ff5-1c0b0adc0b96
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_conne
ct returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLE
rror)
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_conn
ect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:948:in `connect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:876:in `start'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/timi
ngs/app_server.rb:9:in `result'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:28:in `app_server_results'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in `block (3 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/brow
ser.rb:34:in `visit'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:18:in `times'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:18:in `block in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:17:in `tap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:17:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:4:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/bin/wbench:43:i
n `<top (required)>'
        from C:/Ruby24-x64/bin/wbench:23:in `load'
        from C:/Ruby24-x64/bin/wbench:23:in `<main>'

H:\>

**Comment by tjouan** [comment]
@Siva454 your issue is not the same as the OP. It seems you installed
the gem successfully, and that the error happens when you use "wbench"
gem. RubyGems is used to load this gem here, but apparently
successfully.

The report you linked was created only a few days ago, give it some
time, and if it's not updated in a few weeks/months, try contacting
authors or maintainers by mail.

But RubyGems worked correctly in your case, it does not seem related
to the error you get.

**Comment by Siva454** [comment]
@tjouan ....Thank you

**Comment by shevegen** [comment]
I think RubyGems' assumption is to require openssl. This may even be the case with local .gem files, but I don't remember. I do, however had, remember that I need openssl on my local ruby version for two reasons primarily:

- Batch-install (remote) gems (but perhaps local ones too? I forgot if openssl is needed for local gems)

- Make use of open-uri, at the least for many remote websites these days

I think in some cases it may be more convenient for a user to still be able to install a gem.

I remember that because of "gem" not always working, I added code in one of my ruby projects where I can still extract a .gem file and then use oldschool setup.rb to install that project.

Although not necessarily related to the threadstarter, perhaps rubygems gem itself could have convenient fallbacks mode:

a) to be able to extract a gem even without openssl being available

and

b) to also install remote gems without openssl being available

I understand that b) currently does not work, most likely; and the opinion by the rubygems maintainers may be that people need to go through the steps, in order to ensure that everything is safe and works well - but this also then presents a hard block to ruby hackers who are REALLY sure that they want to do something, and then they are confronted with a situation where openssl MUST work. Which I do not think should be the case necessarily - lots of functionality in ruby will still work even without openssl. And there are other ways to obtain .gem files too, such as via a browser (you could also find gems on non-https locations too).

TrianglesPCT actually gave a workaround:

      gem source --add http://rubygems.org/
 
Note that he explicitely disables https - and then it **works**. So, IMHO, rubygems "gem" in THAT particular situation, is actually adding to a problem rather than solving it, since users are already able to bypass that problem anyway. (I myself rarely run into these issues anymore, largely because I have most gems available locally anyway - but I still would consider it important that users can easily workaround issues like that; at the least gem could add some information to workarounds, without having to google, similar in spirit to the "did you mean" gem, like "how about this to solve it" :D ).

**Comment by MSP-Greg** [comment]
@TrianglesPCT 

1. I have used several revisions of OpenSSL 1.0.2 & 1.1.0 with trunk builds and RI2 2.4 builds without issue.  I have code that connects with ssl sites (not thru RubyGems) that is run several times a day, both locally and on Appveyor.

2. Several gems test with RI2 2.4 and trunk on Appveyor (as RubyGems does), and almost all of them have 'development' gems that are installed.  Granted, the gems are often cached, but many gems are revised frequently.

3. In the course of my work & testing, I am often uninstalling & installing gems, both locally and on Appveyor.  Again, no issues...

So, it should work.  Questions:

4. Do you have any code that connects to ssl sites?  If so, does it work?

5. Is this issue intermittent?

@segiddins a) do the rubygems tests try a connection to RubyGems.org (if available)?  b) I've always meant to check, does Rubygems use its own ca file for verification?  Or the system ca file if it exists, etc?

Thanks, Greg

**Comment by MSP-Greg** [comment]
@TrianglesPCT 

> fails because of some SSL cert nonsense.

Please give us more info than that.  Please attach if it's lengthy...

**Comment by segiddins** [comment]
The tests don’t hit the network, and I believe we (.only?) use the bundled CA file.

**Comment by MSP-Greg** [comment]
@segiddins

> The tests don’t hit the network, and I believe we (.only?) use the bundled CA file.

Sorry, don't know whether you mean bundled with RubyGems, or bundled with the Windows build?

Interesting.  FYI, RubyInstaller builds (2.3 and earlier) did not come with a bundled ca cert file, and required the user to set an ENV item to point to it.  RubyInstaller2 builds (2.4 and I assume 2.5 shortly) come with a bundled cert with OpenSSL already pointed to it...

**Comment by segiddins** [comment]
Bundled with RubyGems

**Comment by colby-swandale** [comment]
ping @TrianglesPCT were you able to resolve your issue?
