### ISSUE TITLE
Give option to generate Windows bin stubs regardless of host OS

### ISSUE THREAD

**Issue by oxygene** [rubygems/rubygems#2120]
I stumbled across the fact that when working with jruby on a Linux system, no Windows stub files are generated for installed gems. This is reasonable for a native ruby installation, but it would be nice to also generate windows stubs in a jruby environment because this would make the jruby folder portable also across OS types as long as there is a JRE available.

Please see the discussion over at https://github.com/jruby/jruby/issues/4907

Being on a Windows host, currently also shebang scripts are generated, so the situation is a little bit assymetrical. I also noticed that when being on a Windows system the setting for shebang style seems to be ignored because I then get a `#! jruby` shebang even though jruby configures to be using `/usr/bin/env`. Should I open another issue for this?

**Comment by shevegen** [comment]
I agree. Users should be able to generate stub files for any target platform desired; developers could work on one platform, but also may want to test for another platform as well.

I think headius already showed the code that could generate it in that other discussion.

What syntax could rubygems use in order to allow for this (if it is approved)? A naive one I would pick is --generate-windows-stubs but I really lack imagination here. :P

I guess it may be useful to hear any comment from a rubygem team core committer about it.

**Comment by segiddins** [comment]
Something like `--all-platform-binstubs` would make sense to me
