### ISSUE TITLE
Appveyor & Travis branch restrictions

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2451]
Please consider removing the branch restrictions in the appveyor.yml & .travis.yml files.

Some people do not have local access to all tested platforms, so testing one's fork may be desired.  In Appveyor it's relatively easy to test any branch, but not so on Travis.  And Travis is where the RuboCop testing is.

For testing here, the only people that can create a branch are the members, so...

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I don't see any harm by doing this, but i need to investigate if this will not brake bors(our merging bot) for now you can test the fork by configuring the fork in your own travis account :grimacing:

**Comment by MSP-Greg** [comment]
@bronzdoc 

Thanks.  I wasn't sure about bors.

>  for now you can test the fork by configuring the fork in your own Travis account

I've actually got several repo forks running in Travis, but I'm not a Travis guru.   Appveyor will allow one to override yml branch restrictions, but I don't think Travis will.

Travis has a 'trigger build' option, but it's 'beta' and (at present) won't allow one to override yml restrictions.

If you know how, please feel free to explain or point me to somewhere that explains how...

I can test anything windows locally, but if the code isn't Windows specific and it's more than a few lines, I really like to check Travis.  It's a pita to do it in master, then move the commits to another branch for a PR...

**Comment by MSP-Greg** [comment]
@bronzdoc

Last PR I did I wanted to check my fork with Travis, and I had to add the `-stable` prefix.  Would be helpful to remove them...

**Comment by MSP-Greg** [comment]
Today I ran into this issue.

Having these branch name restrictions means contributors cannot run CI in their forks, since it's a branch push for a fork...

**Comment by deivid-rodriguez** [comment]
Branch name restrictions are setup so that we don't run unnecessary builds for example against master or stable branches right after merging a PR. Thanks to using `bors-ng` we can skip all these unnecessary (and duplicated) builds.

Is it too inconvenient for you to open a "Draft PR" when you want to check the CI?

**Comment by MSP-Greg** [comment]
> Is it too inconvenient for you

Actually, the inconvenience is placed on all the people watching the repo getting emails every time someone needs to change a PR due to code or test changes/additions, CI failures, etc.

In another repo, I got ten emails today for one PR that isn't ready, and the submitter keeps pushing commits to it.  That's inconvenient...

**Comment by deivid-rodriguez** [comment]
Regarding people watching the repo, CI failures, test code and so on are part of the regular maintenance of every library. If you choose to watch a repo, that comes with it. This is even less of a problem since you can also choose the "releases-only watch mode". So, I think we're good there.

Also, if you want to work on your own fork, you can still manually edit the CI files to temporarily add whatever branch you're working on.

**Comment by MSP-Greg** [comment]
Switch to GitHub Actions...
