### ISSUE TITLE
Gem::Platform pre-compiled, 'universal'

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2461]
Gem::Platform has three properties - cpu, os, & version.  

On standard Ruby Windows, version is not used, and most pre-compiled gems are cpu/os specific.  But, a cpu agnostic gem can be built that would work with both x64 & x86 cpu's.  I don't know if I've ever seen one in the wild.

I believe the only 'pro' is that a cpu agnostic gem could be installed with `--user-install` and be used by both x86 & x64 Ruby builds (with matching ABI).  The 'con' is that they would be larger gem files (and a larger install), as they contain double the number of *.so files. 

So ---

1. Is there an equivalent of  a 'universal/cpu agnostic' pre-compiled gem on other platforms?
2. Is version used on other platforms, in what way does it restrict installation, and are 'cpu agnostic' gems used/built/available?
3. Is there anywhere to find more general Gem::Platform information?
4. Given the above, what version should RG install if there are both 'universal/cpu agnostic' and 'cpu agnostic' gems available?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
Just some comments that don't directly answer your questions...

I think the original intention of Gem::Platform for extensions never really materialized in the wild. There's really no reason to ship precompiled binaries most of the time, and just let the extension build as-needed. At least, I've never seen code that depended on CPU architecture.

Only Windows ever really benefited from this in the early days, before MS shipped free versions of Visual Studio and/or most users didn't have mingw tools installed. Even for the win32-api gem, where I was shipping precompiled binaries, I would just build them all in advance in a single gem and install the correct one based on the user's platform instead of creating a bunch of different gems for each platform.

In practice I've ended up using `Gem::Platform` + 'universal' when I want to create platform-specific gems that are not actually extensions, but which have different dependencies. For example, in the sys-uptime gem I create two separate releases because the non-Windows version has an ffi dependency: https://github.com/djberg96/sys-uptime/blob/ffi/Rakefile.

**Comment by MSP-Greg** [comment]
@djberg96 

> some comments that don't directly answer your questions

I appreciate them anyway.  Sorry for the delay; this topic is messy for me, as I'm familiar with Windows, but not other platforms.

> There's really no reason to ship precompiled binaries most of the time, instead just let the extension build as-needed.

I've seen quite a few users having issues building extension gems.  In particular, there are two popular gems that build with OpenSSL, and Windows Ruby versions vary with what version of OpenSSL they're built with.  As to RubyGems & platform specific gems, I'd just like RG to correctly install them, report them, and use the Ruby version constraint when doing so.

Re `win32-api`, one of the only `universal-mingw` gems I've come across, it's even built with trunk (2.6) support.  I use trunk a lot...

I did notice the `if File::ALT_SEPARATOR` statement in `sys-uptime`.  Most use a `/mswin|mingw/` match, but `File::ALT_SEPARATOR` is simpler...

**Comment by MSP-Greg** [comment]
This issue ties into how/should the RG `--platform` option work, and also whether `universal` gems are of practical use.  From a Windows perspective, 32 bit builds of Ruby are being used by fewer and fewer people.

Hence, I'm closing.
