### ISSUE TITLE
Better handling of the `required_rubygems_version` constraint in gemspecs

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#2575]
My current problem is that the `required_rubygems_version` constraint in gemspec does not have a user friendly fallback behavior.

Currently the `gem` CLI will try to install the latest available version, and fail if the running rubygems version does not satisfy the `required_rubygems_version` constraint set by that version's gemspec.

A better behavior would be that rubygems automatically selects the newest version of the gem that satisfies the running rubygems version, and does not fail at all.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
As mentioned in PR #2616, I have code that partially addresses this issue.  Today I noticed there are two remaining issues, `gem update` & `gem outdated`.  I don't think `gem install` requires changes, as I used for real-world testing.

The current  `gem update` makes use of NameTuples, I assume in an attempt to speed up the process.  

This isn't helpful with the `required_rubygems_version` constraint, so the code needs to be rewritten.

1. So, assuming I'm going to be the one fixing `Gem::Commands::UpdateCommand`, does anyone a have any issues with making it a subclass of `Gem::Commands::InstallCommand` with changes as needed?   The changes hopefully only  involve the 'initial dependencies', along with filtering the result set.  I think...

2. Currently console output includes info about gems that are not updated. Should that info be included when using the `--explain` option?

3. Past issues have mentioned the lack of platform info when using `--explain`.  This is also an issue with 'update' if a gem changes platforms with update.  IOW, it may change from Gem::Platform.local to Gem::Platform::RUBY, or vice-versa.  Should `--explain` output be changed to make a platform change apparent?

Haven't looked at `Gem::Command::Outdated`, but it may only need changes to `Gem::Specification.outdated_and_latest_version`...

**Comment by MSP-Greg** [comment]
Interesting that there has been very few comments about an issue with such a large effect on Ruby.

I've done a bit of work in this (both code & tests), and it's expanded quite a bit beyond the earlier PR.  

Some issues:

1. The proper solution would be to add `required_rubygems_version` info to the RG servers tuple system.  I assume this is something that could not been done until at least RG 4.

2. The cache data contained in 'latest_specs.4.8' is almost worthless, as the most recent version of a gem may have a `required_rubygems_version` similar to ">=2.6.0", so it would not contain an installable gem for previous Ruby versions.

3.  Quite a few changes are needed to the current code due to the assumption that the 'best installable gem' can be found from tuple information.

4. Generally, the goal has been to sort and filter tuples as much as possible, then use specs only to verify `required_rubygems_version` and determine the 'best installable gem'.

At present, code changes exist in:
```
dependency_installer.rb
resolver.rb
resolver/installer_set.rb
spec_fetcher.rb
```

Changes pass existing tests, in addition to new tests.

**Comment by MSP-Greg** [comment]
@segiddins

Sorry for the ping, but I thought you might know the answer.

The `required_rubygems_version` (RRV) code I have is passing all existing tests along with the additional tests I've written.   Since RRV's are not part of the 'tuple' system, specs are needed for their determination, which obviously affects the speed.

If a gem has more than one Gem::Dependency for it, is resolution done via dependency 'intersection' or thru the intersection of tuple sets?

**Comment by segiddins** [comment]
> If a gem has more than one Gem::Dependency for it, is resolution done via dependency 'intersection' or thru the intersection of tuple sets?

I'm not sure what you mean by intersection?

**Comment by bronzdoc** [comment]
> Since RRV's are not part of the 'tuple' system, specs are needed for their determination, which obviously affects the speed.

While working on https://github.com/rubygems/rubygems/issues/2900 I stumble on this.

> The required_rubygems_version (RRV) code I have is passing all existing tests along with the additional tests I've written.

@MSP-Greg I think i came with similar code, but agree that the best approach maybe add RRV to the index(i guess? Otherwise would be slower.

**Comment by MSP-Greg** [comment]
@bronzdoc

Boy, a little foggy on this one.  I'll see if I can review it some more.

Here the discussion is about `required_rubygems_version`, but most of what I recall was about `required_ruby_version`.

Maybe use 'RRGV' for `required_rubygems_version` and 'RRV' for `required_ruby_version`?

I may have accidentally confused the two.  If so, sorry.  I know one thing I was hoping for is that RRV checks would be moved from Bundler into RG, but that was best done by using the API that Bundler was using, versus the older version used in RG...
