### ISSUE TITLE
Do not sort requirements

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#2627]
#2230 makes requirements sorted, but that is wrong IMO. Let me show you example:

~~~
$ cat testing_gem.gemspec | grep dependency
  s.add_runtime_dependency('test_runtime', ["~> 1.0", ">= 1.0.0"])
  s.add_development_dependency('test_development', ["~> 1.0", ">=1.0.0"])

$ gem buil testing_gem.gemspec 
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from testing_gem.gemspec:36.
  Successfully built RubyGem
  Name: testing_gem
  Version: 1.0.0
  File: testing_gem-1.0.0.gem

$ gem spec --ruby testing_gem-1.0.0.gem | grep dependency
      s.add_runtime_dependency(%q<test_runtime>.freeze, [">= 1.0.0", "~> 1.0"])
      s.add_development_dependency(%q<test_development>.freeze, [">= 1.0.0", "~> 1.0"])
      s.add_dependency(%q<test_runtime>.freeze, [">= 1.0.0", "~> 1.0"])
      s.add_dependency(%q<test_development>.freeze, [">= 1.0.0", "~> 1.0"])
    s.add_dependency(%q<test_runtime>.freeze, [">= 1.0.0", "~> 1.0"])
    s.add_dependency(%q<test_development>.freeze, [">= 1.0.0", "~> 1.0"])
~~~

This roundtrip should keep the order IMO. I have the requirements specified in that order in my .gesmpec file on purpose. Ther `~> 1.0` is actually the main constraint. The `>= 1.0.0` is there just because something was broken and I am not that interested in this constraint.

And of course, such change which does not improve anything breaks my test suite [[1]]:

~~~
 1) Failure:
TestGem2Rpm#test_print_dependencies [/builddir/build/BUILD/gem2rpm-1.0.1/usr/share/gems/gems/gem2rpm-1.0.1/test/test_gem2rpm.rb:74]:
--- expected
+++ actual
@@ -1,8 +1,7 @@
-# encoding: UTF-8
-"rubygem(test_runtime) >= 1.0
+"rubygem(test_runtime) >= 1.0.0
+rubygem(test_runtime) >= 1.0
 rubygem(test_runtime) < 2
-rubygem(test_runtime) >= 1.0.0
+rubygem(test_development) >= 1.0.0
 rubygem(test_development) >= 1.0
 rubygem(test_development) < 2
-rubygem(test_development) >= 1.0.0
 "
~~~

IOW I would appreciate if only `Gem::Requirement#as_list` is sorted as it used to be.

[1]: https://github.com/fedora-ruby/gem2rpm/blob/master/test/test_gem2rpm.rb#L59

**Comment by voxik** [comment]
BTW the ordering influences rubygem.org presentation as well. Because apparently rubygems.org took the dependencies as they were specified in metadata, but that order now differs from the .gemspec files. That is also wrong IMO. See thor in railties:

https://github.com/rails/rails/blob/v5.2.2/railties/railties.gemspec#L37
`s.add_dependency "thor", ">= 0.19.0", "< 2.0"`
https://rubygems.org/gems/railties/versions/5.2.2
`thor < 2.0, >= 0.19.0`


https://github.com/rails/rails/blob/v6.0.0.beta1/railties/railties.gemspec#L40
`s.add_dependency "thor", ">= 0.20.3", "< 2.0"`
https://rubygems.org/gems/railties/versions/6.0.0.beta1
`thor >= 0.20.3, < 2.0`

Apparently, the 6.0.0beta1 was generated by older RubyGems. Looking at ther 5.2.2, I am not even sure the sorting does what it is supposed to do.

**Comment by deivid-rodriguez** [comment]
I double checked that undoing the sorting included with that PR does not seem to break anything. Also I see how presentation in rubygems.org can be more confusing after the sorting, since it can "hide" the main requirements as you say.

But it's weird, regarding the roundtrip you mention in the first message, #2230 seems to actually _fix_, not break that. See the diff https://github.com/rubygems/rubygems/pull/2230/files#diff-6d1d09cbeb26123575a4efe6dc0ddab2 in the test expectations.

In particular, I tried adding this test to current master and it passed:

```ruby
def test_to_ruby_requirement_stability
  _, gem = util_gem 'a', '1' do |s|
    s.add_dependency 'b', ['~> 1.0', '>= 1.0.4']
  end

  spec = Gem::Package.new(gem).spec

  assert_includes spec.to_ruby, '"~> 1.0", ">= 1.0.4"'
end
```

So, I'm confused.

**Comment by deivid-rodriguez** [comment]
Nevermind, I should've used your exact example. Since the sorting sorts by version first, my example stays sorted while yours doesn't. Your example is not very meaningful, though, since `"~> 1.0", ">=1.0.0"` seems just redundant? The other more meaningful cases seem to work fine

Whatever the case, I agree that the sorting seems unnecessary here?

**Comment by voxik** [comment]
Right, my example is not really meaningful. It comes just from testcase in my project. Thx for the PR

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2652
