### ISSUE TITLE
Gem.remove_unresolved_default_spec doesn't delete spec's files from @path_to_default_spec_map

### ISSUE THREAD

**Issue by x-yuri** [rubygems/rubygems#2681]
I'm having a problem.

My current problem is... I've been trying to figure out what this line of code is [for][1], and noticed that [`Gem.remove_unresolved_default_spec`][2] doesn't necessarily undo what [`Gem.register_default_spec`][3] does. Doesn't undo in case of the new format. I believe it was broken by this [commit][4].

[1]: https://github.com/rubygems/rubygems/blob/v3.0.3/lib/rubygems/core_ext/kernel_require.rb#L40
[2]: https://github.com/rubygems/rubygems/blob/v3.0.3/lib/rubygems.rb#L1283-L1287
[3]: https://github.com/rubygems/rubygems/blob/v3.0.3/lib/rubygems.rb#L1251-L1270
[4]: https://github.com/rubygems/rubygems/commit/cc6d4c31

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
3.0.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

On a side note, could you by any chance explain [the line][1]? I believe the method was added in the following [commit][5]. Do we really need to undo registering a default spec? Also judging from the commit, it seems there's no way to require a file from standard library if there's a file by that name in a default gem. Is it not an issue because standard library and default gems are both maintained by language developers?

[5]: https://github.com/rubygems/rubygems/commit/02627781

**UPD** Also, for one reason or another some of the default gems (`bundler`, `irb`, `rdoc` in `ruby-2.6.0`)—supposedly, those with executables—have gem dirs (`lib/ruby/gems/<version>/gems`), but gem dirs contain only executables. And corresponding specifications list only the executables. As such requiring such gem's files resolves to the default gem version, not the lastest as is the case with the rest of the gems. That for one makes `puma` fail to restart under `ruby-2.6.0`.

**Comment by deivid-rodriguez** [comment]
Hello @x-yuri!

The motivation for the default spec specific logic is to allow users to require specific versions of a default gem. If we directly require them, the default version will always be used even if the user installs a higher version. To fix that issue, we keep track of all files belonging to default gems, and their associated specification, so in case on of them is required, we go through the gem activation logic, which activates the highest version in the system which is not necessarily the one provided in the default load path.

As per the specific line of unregistering the default gem specification after it's required, I think it's just for efficiency. If we don't do that, we will try to activate the default gem every time it is required. However, since the unregistration itself also has a cost, it is maybe counterproductive to do it and it's better to just remove the line and the method... :thinking:.

I actually fixed a bug in the unregistration in #2741, but I'm now thinking we can probably kill the whole thing instead?

**Comment by deivid-rodriguez** [comment]
Actually ended up killing this code, so I think this can be closed.
