### ISSUE TITLE
[HELP] Getting file contents in Gem.pre_install

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#2723]
I'm working on a rubygems plugin where I would like to read the contents of a specific file before installation via Gem.pre_install.

However, I do not know how to read the contents of the file without writing it to the filesystem first, which I would like to avoid if possible. I assume I would use `Zlib::GzipReader` somewhere along the way, but it's not immediately apparent how to use it in this fashion.

You can see what I'm trying to do here: https://github.com/djberg96/secure-manifest/blob/master/lib/rubygems_plugin.rb

Is this possible?

**Comment by djberg96** [comment]
@drbrain Don't suppose you know, do you?

**Comment by drbrain** [comment]
It looks like the `pre_install` hook runs before the gem is even downloaded, per [these tests](https://github.com/rubygems/rubygems/blob/01e701dc7d3ec72c14dc79d7af5b5f5fb6ffbb25/test/rubygems/test_gem_installer.rb#L749-L766).  You'd probably need to download the gem yourself into a temporary location in order safely to compare manifest.

I'm not sure if copying it from the temporary directory into the cache dir will cause the installer to skip a second download or not.

**Comment by djberg96** [comment]
Although, looking at those tests, they still don't really tell me if it's available as an IO stream object in memory somewhere.

**Comment by drbrain** [comment]
Reading more closely in Gem::Installer I think the gem is downloaded somewhere because [the spec is accessed](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/installer.rb#L302) [from the package](https://github.com/rubygems/rubygems/blob/342f29393cf8f56680700efdf2defbdbbae78a60/lib/rubygems/installer.rb#L280-L281) before the pre-install hooks run, try getting the package with `package = installer.instance_variable_get :@package`.

I would compare against Package#contents instead of Specification#files because it looks like [extracting the files](https://github.com/rubygems/rubygems/blob/342f29393cf8f56680700efdf2defbdbbae78a60/lib/rubygems/package.rb#L388) from the data.tar.gz doesn't verify against the files list in the specification.  Also, I think #contents is the method you're looking for?

**Comment by djberg96** [comment]
@drbrain Ok, thanks, I'll take a look. Any chance we could make the `@package` variable accessible via an `attr_reader`?

**Comment by djberg96** [comment]
@drbrain So, wait, is it just a matter of comparing `Package#contents` vs `Specification#files` then?

**Comment by djberg96** [comment]
Quick aside, seems the specification files include directories as distinct entities, while the package contents do not, so there would have to be some sort of handling.

**Comment by bronzdoc** [comment]
@djberg96 can this be closed?

**Comment by djberg96** [comment]
@bronzdoc Yep, got the answers I needed, thanks.
