### ISSUE TITLE
Proposal to consider 'feature complete' status in a gemfile

### ISSUE THREAD

**Issue by skatkov** [rubygems/rubygems#2734]
In a discussion at rubytoolbox project https://github.com/rubytoolbox/rubytoolbox/issues/477 we discussed if we can provide **feature complete** status in gemfile. We think it could help improve public attitude towards open source towards more healthier and sustaible way.

You can find more discussions in issue or reddit thread.
https://www.reddit.com/r/ruby/comments/bc2ih3/rubytoolbox_the_case_of_gems_not_needing_active/

It would be great to hear if you consider such a change useful.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ x ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

**Comment by simi** [comment]
It seems to me more you're trying to solve your own particular problem at general level. Anyway I think `Gemfile` is not the right place for this (since it is just "dependency manifest"). This information can be easily stored at [gemspec metadata level](https://guides.rubygems.org/specification-reference/#metadata). 

I think usually projects reaching some first milestone (which can be actually first **feature complete** version) bump to  1.0 version after initial development. Even with having this information stored somewhere you should check the sources as well and there will be no guarantee you can easily rely on. Also **feature complete** expectation can be different.

As I wrote in my first sentence, at your situation I would try to rethink the approach. If I see some gem not having new commits for few months but I consider it still valuable for our project I can explain that to my colleagues to make it thru review.

**Comment by andhapp** [comment]
Is `feature complete` same as `stable`? A `feature complete` gem will definitely be useful, however, a `feature incomplete` yet `stable` gem will be useful too. I will use a gem that's stable not feature complete yet because it has features that work for me and if it's stable, I will give it a whirl.

**Comment by andhapp** [comment]
What's the main purpose to propose this? This will give a developer more confidence in using it, yes?

**Comment by skatkov** [comment]
@simi don't get me wrong, but everything people do involves their own interest. It's really strange to expect a human to take his time from family, work and hobbies to lobby something that doesn't affect himself. So I'm not sure what exactly your implying by that first sentence.

**Comment by hackhowtofaq** [comment]
> It seems to me more you're trying to solve your own particular problem at general level. 

I do not agree with this sentence and I cannot understand how did you conclude that?
Everybody benefits from this.

**Comment by simi** [comment]
Just to focus on the main proposal, as I wrote I think `Gemfile` is not the best place for this, it will fit the `gemspec` and there's already metadata column you can populate this info with.

I (and other people as well) had some different ideas how to be able to get some metric at https://github.com/rubytoolbox/rubytoolbox/issues/477. I think the discussion about that can be done in there.

> It seems to me more you're trying to solve your own particular problem at general level.

That's just my feeling about the origin of this case caused by @skatkov experience. I'm taking a look at this proposal as a gem maintainer. Let's say there will be unified gem spec metadata where you can populate this info. I will probably never populate it since I have no idea when to say my gem is `feature complete`. Since this issue is coming from `rubytoolbox` I think it can be solved at that side. There are some proposals to change `project score` which will include this kind of "unmaintained" gem at first sight, but still actively used.

If you spot this kind of gem, you can also go and reach the author, try to ask what's the status. If needed you can provide your help to keep the gem maintained or at least submit pull request to mention the status of gem in README. That can fix some particular problem (at the gem level) instead of fixing this at general level.

**Comment by skatkov** [comment]
@simi appreciate your input! I'm closing this.
