### ISSUE TITLE
gem typosquatting prevention

### ISSUE THREAD

**Issue by adrianomitre** [rubygems/rubygems#2875]
I would like to suggest a feature to prevent [Typosquatting programming language package managers](https://incolumitas.com/2016/06/08/typosquatting-package-managers/).

I suggest that RubyGems should make it difficult to publish gems whose names are too similar to some pre-existing popular gem. "Too similar" may be defined as having a [Levenshtein distance](https://rosettacode.org/wiki/Levenshtein_distance#Ruby) of 1. "Popular" may be defined simply as having more than some threshold of downloads in some period, e.g., more than 1k downloads in the last month.

RubyGems could automatically refuse such submissions by stating that in order to prevent malicious gem typosquatting, in case of high lexical similarity to a pre-existing popular gem, manual authorization by admins is required, which may be requested by email with proper justification.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [x] Other (Security)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
I imagine step 1 of enforcing this would be disallowing case-sensitive gem names...

**Comment by adrianomitre** [comment]
Maybe the problem is not case-sensitivity _per se_, but allowing two gems whose name differ only in terms of case.

Something along the following lines could implement @djberg96's idea of step 1?
```ruby
def disallow?(new_gem_name)
  pre_existing_gem_names.map(&:downcase).include?(new_gem_name.downcase)
end
```

**Comment by duckinator** [comment]
A variant of the levenshtein distance aspect of this issue was added in https://github.com/rubygems/rubygems.org/pull/2037 ("Invalidate gem name using levenshtein distance for gems with ten million downloads"), back June of this year. This, as of that PR ,applies to anything similar to existing gems with >10 million downloads total.

There's also https://github.com/rubygems/rubygems.org/pull/1357 , from June 2016, which made the name check case-insensitive. This is for creation only, as there's at least once instance of case-only-difference from prior to that PR (`saikuro` vs `Saikuro`).

**Comment by duckinator** [comment]
@adrianomitre does my previous comment address everything, or do you have potential ideas for changes/tweaks?

**Comment by adrianomitre** [comment]
@duckinator Your [previous comment](https://github.com/rubygems/rubygems/issues/2875#issuecomment-522192286) addressed everything. Thanks!
