### ISSUE TITLE
Incorrect TTY detection

### ISSUE THREAD

**Issue by pirj** [rubygems/rubygems#3048]
Wondering if it's possible that RubyGems [incorrectly detects](https://github.com/rubygems/rubygems/blob/15706d3e853f9d1fd7b6ddbdcf38cf9a83a345b9/lib/rubygems/user_interaction.rb#L2530) that it's a [TTY](https://github.com/rubygems/rubygems/blob/15706d3e853f9d1fd7b6ddbdcf38cf9a83a345b9/lib/rubygems/user_interaction.rb#L210) and doesn't fall back to [default `false`](https://github.com/rubygems/rubygems/blob/cc3a02724b28fcd7d32f77c8cea837218cd975cc/lib/rubygems/installer.rb#L264)?

[Example failure](https://travis-ci.org/rspec/rspec-rails/jobs/625945517) from [`rspec-rails`](https://github.com/rspec/rspec-rails/blame/7d68eb2306f3495d62618318e8839cf20f2a463d/script/update_rubygems_and_install_bundler#L9).

**Comment by bronzdoc** [comment]
Hey @pirj
 
Can you describe more about your problem? thanks

**Comment by deivid-rodriguez** [comment]
The problem is related to the issues we had when TravisCI setups would prompt the user to ask for confirmation before overwriting the `bundler` binstub.

According to how `rubygems` seems to be coded, the expected behaviour would've been that, if the current environment is not a tty like in a CI enviromennt, rubygems would refuse to overwrite the binstub and raise an error. TravisCI was asking for confirmation instead of raising an error right away, so something is not working properly regarding tty detection.

Note that this issue is specific to TravisCI (it doesn't happen on Github Actions), so it might as well be an issue with the TravisCI environment itself and not rubygems.

**Comment by pirj** [comment]
@rkh @svenfuchs would you be interested to take a look?

**Comment by hsbt** [comment]
This is the 3rd party issue. If you found the issue of rubygems, Please reopen this. Thanks.
