### ISSUE TITLE
Add option to `plugin install` for local plugins

### ISSUE THREAD

**Issue by kerrizor** [rubygems/rubygems#3209]
I ran into this when working on [bundler-dependency_graph](https://github.com/kerrizor/bundler-dependency_graph) `bundle plugin` currently supports `--git` and `--source` (rubygems) options, which both expect a URL. I had mixed success providing it with a `file://` URL, but a full-fledged `--file` option that accepted a filepath would've sped things along.

**Comment by jaredbeck** [comment]
I've also had "mixed success" with the "Running your plugin locally" section of the [How to write a Bundler plugin](https://bundler.io/v2.0/guides/bundler_plugins.html) instructions.

```
bundler plugin install my_plugin --source file:///Users/jared/git/my_plugin/ --verbose
Gem::RemoteFetcher::FetchError: Errno::ENOENT: 
\ No such file or directory @ rb_sysopen - /Users/jared/git/my_plugin/specs.4.8.gz
/Users/jared/..../rubygems/remote_fetcher.rb:274:in `rescue in fetch_path'
....
```

The instructions do not say anything about this mysterious `specs.4.8.gz` file 👻 .

Using `--git` instead of `--source` works, but the requirement to make a commit every time does slows down local development slightly.

**Comment by deivid-rodriguez** [comment]
We now have a proper `--path` option thanks to @ccutrer's work at https://github.com/rubygems/rubygems/pull/6960, so closing!
