### ISSUE TITLE
scoped source for dependencies of gems

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#3220]
bundler recommends declaring an explicit source for gems that are not on rubygems, but that does not work if the gem that needs the alternate source is a dependency:

``` Ruby
# Gemfile
source 'https://rubygems.org'
gem 'a'
```

``` Ruby
# a.gemspec
gem.add_runtime_dependency 'rails-assets-jquery'
```

is there any nice way of dealing with this ?
like `source 'https://rails-assets.org', math: /^rails-assets-/` ?

**Comment by ArmandoAssuncao** [comment]
I tested in version `2.2.17` and the message: `Warning: the gem 'xxx' was found in multiple sources.` is gone. But I have not seen the code/updates, so not know if some source is now has priority.

**Comment by deivid-rodriguez** [comment]
Could you show an example? If the situation is really ambiguous, or if you're using multiple global gem sources, bundler should still show the warning.

**Comment by deivid-rodriguez** [comment]
Since dependency confusion issues have been solved, I believe this request now essentially comes down to https://github.com/rubygems/rubygems/issues/2731 and https://github.com/rubygems/rubygems/issues/4441. I don't think we should introduce any source matching syntax to the Gemfile to solve that issue, so I'll close this in favour of those other tickets.
