### ISSUE TITLE
Bundler could not find compatible versions for gem "bundler" (rails 4)

### ISSUE THREAD

**Issue by vfonic** [rubygems/rubygems#3259]
I have both bundler 1.17.3 and 2.1.2 (well, I just uninstalled 2.1.2).

I cloned this repo: https://github.com/sheharyarn/s3_direct_upload_example
And ran `bundle install`.

Then I got the following error:
> Bundler could not find compatible versions for gem "bundler":
>   In Gemfile:
>     rails (= 4.0.0) was resolved to 4.0.0, which depends on
>       bundler (>= 1.3.0, < 2.0)
> 
>   Current Bundler version:
>     bundler (2.1.2)
> This Gemfile requires a different version of Bundler.
> Perhaps you need to update Bundler by running `gem install bundler`?
> 
> Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails (= 4.0.0)', in any of the sources.

I do have bundler 1.17.3, which fits the required criteria. But perhaps, for this case, where there's no bundler version ("bundled with" [Gemfile.lock](https://github.com/sheharyarn/s3_direct_upload_example/blob/master/Gemfile.lock#L130)) specified in the `Gemfile.lock`, bundler should use v1, instead of v2, as it's guaranteed that that `Gemfile.lock` was generated by bundler v1.

What do you think?

Or maybe try to see if bundler v2 could install, if not, switch back to v1.

Either way, it would be great to use the version that works.

Thanks!

**Comment by deivid-rodriguez** [comment]
I understand the request here, and make sense, but I feel it's too late now to bother too much with this, since most people are moving forward to modern bundler versions. We _did_ implement proper error messages as suggested as an alternative through this PR: https://github.com/rubygems/rubygems/pull/4308.

That seems good enough for me, so I'll close this as fixed by #4308. But let me know if you disagree or believe we should make further changes regarding this on our side!
