### ISSUE TITLE
superfluous sudo when exe contains executables

### ISSUE THREAD

**Issue by hadmut** [rubygems/rubygems#3286]
Hi, 
I just found the reason for a flaw that breaks my scripting with  2.0.1 and 2.0.2

Test case:
- make sure there's no GEM_HOME variable set (i.e. force bundler to use sudo to install gems)

- create a fresh gem with   bundle gem somename   and enter some usefull values in the gemspec where bundle wants it to have

- run   rm Gemfile.lock ; bundle 
it works and will probably use sudo to install gems not yet existing. If so, run it again to see, that once all required gems are installed, bundle does not start sudo to do anything. Everything's fine. 

now do 
mkdir exe
touch exe/something
git add exe/something

and run bundle again. 

Now bundle tries to do some sudo command (strace says it just runs "true") without doing anything, but requiring the user to enter the password every time the bundle runs, even if it should do nothing and just run and terminate.

**Comment by deivid-rodriguez** [comment]
Hi @hadmut. Could you share a docker image that reproduces this error? It seems quite weird.

**Comment by hadmut** [comment]
sure.
zip with Dockerfile and testscript attached. Since it requires user interaction, the demonstration does not run at build time, but within the container

Do:

docker build --tag bundlebug  .
docker run --rm -it bundlebug /bin/bash

and within the container:
./bundlebug

When sudo asks you for a password, it is just a   p

It runs bundle three times:
- First time it installs the required gems and should ask for password vi sudo to install them into /var/lib/gems. 
  remember: password is   p

- Second time it runs without user interaction, since all required gems are installed and present.

- then exe is added, and bundle run for a third time, but now asks for a password again, since it runs  sudo true




[bundlebug_demo.zip](https://github.com/rubygems/rubygems/files/5208870/bundlebug_demo.zip)

**Comment by deivid-rodriguez** [comment]
Thanks a lot, I'll have a look at this!

**Comment by deivid-rodriguez** [comment]
Hi @hadmut. The explanation of this behavior is the following:

* When you create a new gem, a Gemfile is created that points to the local gemspec, like this:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in somegem.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"
```

This means that when you run `bundle install`, the dependencies on your gem are installed as regular gems, path the gem itself is considered a "path source" (the `gemspec` DSL you can see above). Path sources don't really get installed, they're just added to the `$LOAD_PATH` when `bundle exec` is run. However, their executables do get installed here: https://github.com/rubygems/rubygems/blob/1ccdb1f31ad002f2927af59b381fd30b3566c3d9/bundler/lib/bundler/source/path/installer.rb#L55. In this case, using sudo.

So, this is weird, but currently expected. I guess since the executables are installed every time for path gems, we could change the message from

> Using somegem 0.1.0 from source at `.`

to

> Installing somegem 0.1.0 executables and using it from source at `.`

or something.
