### ISSUE TITLE
"bundle update" doesn't update gem to latest patch version

### ISSUE THREAD

**Issue by leomao10** [rubygems/rubygems#3310]
Here is the repo I created to reproduce the issue:
https://github.com/leomao10/test_bundler

## What happen
When I use `bundle update stackdriver`, it only update its depending gem `google-cloud-logging` to latest minor version which is `1.6.0`, but not the latest patch version which is `1.6.7`. 

Run `bundle update stackdriver` again will update `google-cloud-logging` to latest patch version.

Also, remove `jbuilder` from the Gemfile and run `bundle update stackdriver`  would upgrade
`google-cloud-logging` straight to the latest patch level(`1.6.7`)

I assume `jbuilder` somehow constraining `google-cloud-logging` to upgrade to latest patch level, but I could not spot the constraint when checking `Gemfile.lock`.

## Expected Behavior
`bundle update stackdriver` would update all depending gems to latest patch level.

## Affected version:
I tested it in bundler `1.6.7`, `1.7.2` under ruby `2.5.1`  and also `2.0.2` under ruby `2.6.3`.

**Comment by deivid-rodriguez** [comment]
Hei!

So the underlying problem here is that `bundler` is not properly unlocking the `concurrent-ruby` dependency.

In the first lockfile, `concurrent-ruby` is not a dependency of the gem being updated (`stackdriver`) or any of its locked dependencies. So `bundler` is not unlocking it, and keeping the `1.0.5` version locked in the `Gemfile.lock` file instead. The newest version of `google-cloud-logging` that satisfies that is [1.6.0](https://rubygems.org/gems/google-cloud-logging/versions/1.6.0), since [1.6.1](https://rubygems.org/gems/google-cloud-logging/versions/1.6.1) depends on `concurrent-ruby ~> 1.1`. That's why bundler is stopping there.

The second time you run `bundle update`, the lockfile has been updated and now `concurrent-ruby` is a transitive dependency of `stackdriver` (because some updated dependecies of `stackdriver` started depending on it). So now `concurrent-ruby` is properly unlocked and updating all the way to `google-cloud-logging` is now possible.

The problem here is that `bundler` is only unlocking the specified gem and its _current_ dependencies (the dependencies of the currently locked version). Instead, it should unlock the specified gem and its _current and future_ dependencies (the dependencies of the current locked version and higher versions of it).

I'll try to provide a fix for this.
