### ISSUE TITLE
Warn about running version/locked version mismatch for Ruby

### ISSUE THREAD

**Issue by mvz** [rubygems/rubygems#3327]
Bundler notifies the user of any version mismatches between the currently running version of Bundler and the one in the lockfile. It would be really helpful if it did the same for the version of Ruby.

(In my case, it would have helped me understand why Heroku kept running version 2.5.3 while I was running 2.5.5.)

**Comment by jeromedalbert** [comment]
@mvz It's been 5 years since you reported this issue, can you confirm that this is still an issue? If so, can you provide an example file or pair of `Gemfile`+`Gemfile.lock` with steps to repro?

**Comment by mvz** [comment]
@jeromedalbert No problem, here is a minimal example of this issue. It uses Ruby 3.1 since that is currently the only minor Ruby version where I have two micro versions installed. Bundler is up-to-date however.

- Create a file `.ruby-version` containing `3.1.4`
- Create `Gemfile` containing:

  ```
  # frozen_string_literal: true

  ruby "~> 3.1.0"
  ```
- Run `bundle`
- `Gemfile.lock` now contains:

  ```
  GEM
    specs:

  PLATFORMS
    ruby
    x86_64-linux

  DEPENDENCIES

  RUBY VERSION
     ruby 3.1.4p223

  BUNDLED WITH
     2.5.18
  ```
- Change `.ruby-version` to `3.1.5`
- Run `bundle`, no warnings about the Ruby version appear

**Comment by jeromedalbert** [comment]
Thanks! I was able to reproduce your issue and here are my reproduction steps:

```shell
$ asdf install ruby 3.1.4
$ asdf install ruby 3.1.5

$ echo 'ruby "~> 3.1.0"' > Gemfile
$ echo '3.1.4' > .ruby-version
$ ruby --version
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin23]

$ bundle
...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ cat Gemfile.lock | grep 'ruby '
   ruby 3.1.4p223

$ echo '3.1.5' > .ruby-version
$ ruby --version
ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [arm64-darwin23]

$ bundle
...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

# Expected: the output for the last command should warn about the version mismatch
# between the Ruby in Gemfile.lock (3.1.4) and the currently running version (3.1.5)
```

---

This issue is basically a feature request to add a warning if there is a version mismatch between the Ruby in Gemfile.lock and the currently running version.

On first thought it seems like having a warning could be useful, but on second thought I am not so sure, and on third thought I think the current behavior with no warning is best.

If your `Gemfile.lock` was installed under a different ruby patch version, no matter what patch ruby version you're running, dependencies in that `Gemfile.lock` should be unaffected, so this probably shouldn't warrant a warning. In the repro steps above, the mandated ruby version is `~> 3.1.0`, so any `3.1.x` ruby should work, including `3.1.4` and `3.1.5`. Bundle concerns itself with dependencies and as far as dependencies are concerned, everything is fine as long as your Ruby has a version compatible with `~> 3.1.0`. A minor mismatch between the ruby version in `Gemfile.lock` and the currently running Ruby version is a minor implementation detail, as long as both of these versions are `3.1.x`.

And Bundler does error out if using an incompatible Ruby version. Continuing the steps to repro above:

```shell
$ cat Gemfile
ruby "~> 3.1.0"

$ cat Gemfile.lock | grep 'ruby '
   ruby 3.1.4p223

$ asdf install ruby 3.3.4
$ echo '3.3.4' > .ruby-version
$ ruby --version
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

$ bundle
Your Ruby version is 3.3.4, but your Gemfile specified ~> 3.1.0
```

As we can see Bundler errors out when using version `3.3.4`, which is incompatible with `~> 3.1.0`.

---

So I am inclined to think that this is not a Rubygems or Bundler issue. Maybe more like an issue with Heroku, if at all, since Heroku ran a version that was compatible with the tilde pessimistic operator that was provided in the Gemfile. One could argue that Heroku could parse `Gemfile.lock` to install a more appropriate Ruby version maybe.

What do you think @mvz?

**Comment by jeromedalbert** [comment]
Oh I didn't know that, if Heroku uses the version in `Gemfile.lock` then I think that's a good thing. Individual developers might have a different updated patch version but that is to be expected when the using `~>` pessimistic operator. I haven't used Heroku in a few years but personally I would go with mentioning an exact Ruby version in the `Gemfile` (like `ruby '3.3.4'`) in order to avoid any surprise.

Can you close the PR @mvz? Thanks

**Comment by mvz** [comment]
The problem with Heroku's choice is that they completely ignore the `.ruby-version` file, even if it's in the repository. So all developers use the exact same version based on the exact version in `.ruby-version`, but Heroku uses another exact version based on `Gemfile.lock`, which is their own unique mechanism that nobody else uses.

Anyway, all of this is not really Bundler's problem, so I'll close this now.

**Comment by jeromedalbert** [comment]
Oh interesting, that's unfortunate. Maybe a workaround for that Heroku limitation would be to use `ruby file: ".ruby-version"` in the `Gemfile`. Heroku would still ultimately go by the `Gemfile.lock` but if all developers use `.ruby-version` then that would be the same.

**Comment by mvz** [comment]
That's a good tip @jeromedalbert, I will try that.
