### ISSUE TITLE
binstubs support on windows

### ISSUE THREAD

**Issue by lynncyrin** [rubygems/rubygems#3381]
From: https://github.com/bundler/bundler-features/issues/92

Moving this issue from the bundler-featured repo, cc @elovelan in case you still wanted to submit a PR

**Comment by deivid-rodriguez** [comment]
Copying here the original issue text, since it's helpful:

> Unless you're running under cygwin, msys or another POSIX compatibility layer, Windows doesn't know how to interpret `#!/usr/bin/env ruby`.

> I would be happy to implement this but want to get some feedback first. I should be able to borrow most of [the code from RubyGems](https://github.com/rubygems/rubygems/blob/40e59d5619ac176cb7c0d76829f817b63fe145e1/lib/rubygems/installer.rb#L436).

Marking this as "help wanted" :)

**Comment by deivid-rodriguez** [comment]
Fixing this would also allow us to unskip most (if not all) of the Windows skips in `spec/commands/binstubs_spec.rb` and also fix the spec failures that I expected to fix in https://github.com/rubygems/rubygems/pull/3722.

**Comment by deivid-rodriguez** [comment]
Also, an alternative idea suggested by @janpio in #3353:

> Although #3381 suggested using the Rubygems implementation as a template, it was much easier to use how e.g. Cordova CLI does it: Just create a command.cmd file with content @ruby "%~dpn0" %* (for us with ruby here). Fixed the tests and has minimal code.

**Comment by deivid-rodriguez** [comment]
And yet another idea from @janpio coming from #3351:

> Indeed, a POC that adds `ruby` if the command can not be found "solves" the problem here:
> ```
>   rescue Errno::ENOENT
>      if Gem.win_platform? then
>        puts "§§§ add ruby in front of command for Windows"
>        args.unshift('ruby')
>        kernel_exec(*args)
>      end
>      Bundler.ui = ui
>```
>(line 62, exec.rb)

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

At some point, the idea was to have a 'dual purpose' binstub script that would run from either a bash shell or a Windows shell.  Ruby master (and maybe 2.7) use this, and it has an `.cmd` extension.  So, what happens is a bash shell works with `bundle.cmd`, but not `bundle`.  It's a good idea, except for cross-platform testing.

Also, Windows Ruby is almost never installed so that `#!/usr/bin/env ruby` works, so it may be modified to `#! ruby`, which seems to find ruby via `ENV['Path']`.  See https://bugs.ruby-lang.org/issues/16953, which I need to add 2.7 to, I think.

**Comment by deivid-rodriguez** [comment]
So what is your suggestion, exactly @MSP-Greg? Is it https://github.com/rubygems/rubygems/issues/3381#issuecomment-643804200? It'd be awesome to get this fixed :)

**Comment by MSP-Greg** [comment]
> So what is your suggestion

Not sure, as I'm not sure if it's a Ruby issue or a Rubygems/Bundler issue.  There may be a work-around, but right now I'm screwing around with intermittent/odd GitHub Actions behavior...

**Comment by deivid-rodriguez** [comment]
In my opinion, it is a bundler issue, since `gem install rspec` installs (I believe) a usable binstub, so that you can run `rspec` later, but `bundle install` does not.

**Comment by MSP-Greg** [comment]
That makes sense.  But also, I believe Ruby core is not building (make install) Windows Ruby with standard bash binstubs.  I guess there are two problems.

**Comment by deivid-rodriguez** [comment]
Yeah, I'd say so.

**Comment by MSP-Greg** [comment]
I installed rake using bundler (into a path), and `bundle exec rake --version` ran fine in both PowerShell and Bash, Both binstubs look fine.

If I look at (or run) spec/commands/binstubs_spec.rb, I should see the issue?

**Comment by deivid-rodriguez** [comment]
Then I was wrong and this stuff works on all Windows shells, thanks for trying it. It'd be nice to get all the stuff in `spec/commands/exec_spec.rb` passing on Windows, just to make sure.

Project binstubs are definitely not working and we should first define what the expected behavior is. I guess `bundle binstubs rspec` should generate a runnable project binstub if run from Windows.

**Comment by MSP-Greg** [comment]
One 'issue' with Windows Bash shells is that Ruby will launch sub-processes in the cmd shell, not the bash shell.

I'll have a look at that file.

> Project binstubs are definitely not working

I'm not sure what you mean.  Are you referring to tests in the specs (which have to run on a bash shell?), or in normal use?  I think several repos CI do a `bundle install` command and then use a binstub in `bundle exec`?

**Comment by deivid-rodriguez** [comment]
Thanks for the help! Having a Windows guru helping us is handy :)

A "project binstub" is the `bin/rspec` file generated when you run `bundle binstubs rspec`. This file is supposed to be runnable directly, and as far as I know, that doesn't work on Windows because these scripts rely on a shebang. Unless I'm wrong and a correct script for Windows is also generated here, that would be awesome.

**Comment by MSP-Greg** [comment]
Ok, thanks.  Using ruby master much of the time, I tend to bypass bundler, as a lot of Gemfiles may install gems that are older than what is included in Ruby master.

Anyway, now that I'm on the page you're on ('project binstub' is not the gem 'binstub')...

I ran `bundle binstubs rake`, ran the file in bash shell, and it loaded Ruby's rake, not the one installed via `bundle install`.  Looked at the code, and noticed the script was looking for a bundle binstub in the same folder. I then ran `bundle binstubs bundle`.  It worked as expected .

I then copied the rake binstub to rake.cmd, and added the following at the top:
```
@ruby -x "%~f0" %*
@exit /b %ERRORLEVEL%

```

And it ran correctly in a Windows cmd shell.  If you want to allow it to run from both shells in Windows, one needs both 'rake' and 'rake.cmd' binstubs...

**Comment by deivid-rodriguez** [comment]
Closed by #3736.

**Comment by deivid-rodriguez** [comment]
Turns out this is not actually fixed, as per https://github.com/rubygems/rubygems/pull/4077. Reopening.

**Comment by deivid-rodriguez** [comment]
Ooops, reopended the wrong issue.
