### ISSUE TITLE
add_optional_dependency

### ISSUE THREAD

**Issue by stereobooster** [rubygems/rubygems#346]
There are cases when one gem can integrate with another gem optionally. Code for this is typically looks like:

``` ruby
begin
  require 'some_gem'
  # do some stuff if gem available
rescue LoadError
  # do nothing if gem unavailable
end
```

So this method is the way to tell if there are such optional dependencies and tell if there are requirements of specific version of optional gem.

Example: [execjs](/sstephenson/execjs), can optionally integrate with `therubyracer` and `therubyrino`

**Comment by kbrock** [comment]
2 real world dependency examples: [bundler] and [html-pipeline]
(I copied this over from 1266 to consolidate)

If you note, html-pipeline has code to support 2 different versions of `gemoji`. This code could be eliminated if it were able to declare the actual dependency, rather than implementing the dependency in code.

Another example of dependencies: 

I could have sworn `metric_fu` had optional dependencies, but not able to back that up. I just remember it was a bear to install due to the version of dependencies.

[bundler]: https://github.com/bundler/bundler/blob/master/lib/bundler/cli/viz.rb#L13-L16
[html-pipeline]: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/emoji_filter.rb#L3-L7

**Comment by mathieujobin** [comment]
got onto this thread, I was looking for a nice way for a gem to support both `sinatra` and `rails`
dependency should not be enforced, but suggested

**Comment by kbrock** [comment]
@mathieujobin I linked to 2 examples up top.

There is no way to declare the version of an optional dependency, or even state the optional dependenies.
Instead, use a `begin / requires / rescue LoadError` block

You can put the version number in your dependency failure print statement.
