### ISSUE TITLE
Bundler installs unsuitable gem versions on Windows

### ISSUE THREAD

**Issue by leoarnold** [rubygems/rubygems#3519]
**Environments:** (all possible combinations were tested)
* Windows 10 or Windows Server 2012
* Ruby:
   * ruby 2.1.9p490 (2016-03-30 revision 54437) [x64-mingw32]
   * ruby 2.1.9p490 (2016-03-30 revision 54437) [i386-mingw32]
   * ruby 2.0.0p648 (2015-12-16) [x64-mingw32]
   * ruby 2.0.0p648 (2015-12-16) [i386-mingw32]
   * ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
* Gem 2.6.13
* Bundler 1.15.4
* Gemfile:

```ruby
source 'https://rubygems.org'

gem 'nokogiri'
```

**Problem:** Bundler installs a version of Nokogiri which requires `< 2.5, >= 2.2` even though Bundler is running on Ruby `< 2.2`.

```
Fetching nokogiri 1.8.0 (x64-mingw32) # respectivly (x86-mingw32)
Installing nokogiri 1.8.0 (x64-mingw32)
Gem::InstallError: nokogiri requires Ruby version < 2.5, >= 2.2.
An error occurred while installing nokogiri (1.8.0), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.0'` succeeds before bundling.
In Gemfile:
  nokogiri
Command exited with code 5
```

**Suspicion:** Bundler chooses the `mingw32` version, but uses the metadata from the mainline gem. In the case of Nokogiri 1.8.0, those differ:
* [nokogiri 1.8.0](https://rubygems.org/gems/nokogiri/versions/1.8.0) requires Ruby `>= 2.1.0`
* [nokogiri 1.8.0 (x86-mingw32)](https://rubygems.org/gems/nokogiri/versions/1.8.0-x86-mingw32) requires Ruby `< 2.5, >= 2.2 `
* [nokogiri 1.8.0 (x64-mingw32)](https://rubygems.org/gems/nokogiri/versions/1.8.0-x64-mingw32) requires Ruby `< 2.5, >= 2.2 `

**Caveat:** Using the `nokogiri` example, the bug cannot be reproduced on Ruby `>= 2.2.0`. This does *NOT* mean that the bug is not there - it's just the case where the differing Ruby version requirements currently overlap.

**Comment by deivid-rodriguez** [comment]
So, the story of this issue is that [a PR was made to rubygems.org to fix it](https://github.com/rubygems/rubygems.org/pull/1669), but it never got merged.

Then a few months ago, [it was finally fixed, but on the bundler's side](https://github.com/rubygems/bundler/pull/7554).

Hope, we've finally decided that the best place this fix this is rubygems.org, so I'm reopening this issue to track its finally resolution which involves:

* [ ] Merge and deploy of https://github.com/rubygems/rubygems.org/pull/1669.
* [ ] Revert and release the revert of https://github.com/rubygems/bundler/pull/7554.

**Comment by deivid-rodriguez** [comment]
The plan was completed with bundler-2.2.0.rc.1. Closing!
