### ISSUE TITLE
It is not possible to access runtime dependencies defined in a gemspec.

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#3588]
Considering a user may want to look at all dependencies of the current bundle, one might assume:

```ruby
runtime = Bundler.load

runtime.dependencies.each do |dependency|
  p dependency
end
```

should work.

However, if the user has the following setup (typical for gems):

#### `gems.rb`

```
source "https://rubygems.org"
gemspec
```

#### `mygem.gemspec`

```
Gem::Specification.new do |spec|
	spec.add_dependency 'a'
	spec.add_development_dependency 'b'
end
```

Only the development dependency will be listed.

This is because the `gemspec` command does not follow non-development dependencies:

https://github.com/rubygems/rubygems/blob/a753447de8fb92dad30e927656984aa2b7765f3d/bundler/lib/bundler/dsl.rb#L78-L84

Also, the `@gemspecs` is not passed into the `Definition`:

https://github.com/rubygems/rubygems/blob/a753447de8fb92dad30e927656984aa2b7765f3d/bundler/lib/bundler/dsl.rb#L232-L234

So it's not possible to work back through this trying to see throuhg the `gemspec` invocation from what I can see.

I'm not sure if there is a solution to this, but it seems logical to me that `Bundler.load.dependencies` should list runtime dependencies of a gemspec in the current directory.

If that's logical, should we consider making that possible?

**Comment by deivid-rodriguez** [comment]
Hi @ioquatix. I believe this is expected.

A Gemfile is expected to include only top level (direct) dependencies. Development dependencies excluded, the `gemspec` DSL is just a shortcut for `gem "my_gem", path: "."`, so just like adding `gem "rails"` to your Gemfile doesn't add all runtime dependencies of `rails` to the `Gemfile` definition, `gemspec` doesn't do that either.

If you want to find the runtime dependencies on `my_gem`, you'll normally load the gemspec and get them from there like: `Gem::Specification.load("my_gem.gemspec").dependencies`.

**Comment by ioquatix** [comment]
My situation is that I want to make a task that can run inside either a:

- Gem repo with a gemspec.
- Project repo with only a gemfile.

I don't feel I should have to write specific code to extract a list of top level dependencies.

In the former case, the user will pull in the appropriate gemspec in their `gems.rb` file.

In the later case there are only gems listed in the `gems.rb` file.

What you are proposing is for me to some how parse the `gems.rb` file with the expectation I can extract which of the two situations is happening above, and in the former, then try to figure out what gemspec was actually loaded, and finally, load it and traverse it's dependencies as well as those expressed in the gemfile itself.

Maybe my problem is too specific. But I don't think it's unreasonable to get a list of direct dependencies, and pulling in a gemspec *does* already do this, but only for development dependencies. I'm not sure why runtime dependencies are handled differently, but there is simply no way to access them.

Maybe the `Bundler::Definition` object can track what gemspecs have been loaded so at least it's possible to do the former approach without having to dig around trying to figure out what gemspec was actually loaded.

**Comment by deivid-rodriguez** [comment]
The current definition of the `gemspec` DSL is:

* Bring the gem defined in the gemspec as a runtime top level dependency, and
* Bring any development dependencies defined in the gemspec under a :development group also as top level `development` dependencies.

This is what it does, and I don't see a reason for changing it, honestly. And I have no idea what it would break.


I'm still unsure about _why_ you're requesting this, I'd like you to be more specific about the problem you are facing, maybe pointing us to this `rake` task for example.

I assume your task needs to behave different on a gem development context and on an application context, right? In that case, can't you detect this situation based on whether there's a `.gemspec` file in the root folder? Why do you need to parse a `gems.rb` file at all?

**Comment by ioquatix** [comment]
I want to get a list of gems that are top level runtime dependencies for both gems and web applications so I can generate documentation. As it stands, it seems like this is not possible.

`Bunder.load.dependencies` doesn't list any runtime dependencies from the gem's gemspec.

**Comment by ioquatix** [comment]
By the way, I didn't suggest changing it, because I agree we don't know what will break.

So I just suggested at least exposing that a gemspec was loaded, and providing access to it, so at least we can write something like:

```
definition = Bundler.definition

definition.dependencies + definition.gemspec.dependencies
```

Or something to that effect.

**Comment by deivid-rodriguez** [comment]
I guess we could add something like that, although it's not that simple since you can add as many `gemspec` DSL calls as you want to your `Gemfile` by specifying different names for the gemspecs, and different groups where to add its development dependencies.

But without knowing a specific use case for it, I'm definitely not willing to consider it.

Could you please point to the rake task you are trying to expose, and the specific problems you are facing when trying to make it work for both gems and applications?

**Comment by ioquatix** [comment]
> Could you please point to the rake task you are trying to expose, and the specific problems you are facing when trying to make it work for both gems and applications?

https://github.com/socketry/utopia-wiki/blob/7702346504b08efc512fad129cc9cf569f40a769/bake/utopia/wiki/code.rb#L15-L30

I gave up with the above approach and just put all gems into a documentation group but that doesn't work very well if the gems are listed twice.

**Comment by deivid-rodriguez** [comment]
I don't think we should changing `bundler` for this.

It seems that the feature request would be to add a new method to `Bundler::Runtime` to return what the OP wants, but the benefits are still unclear to me. It seems easy enough to detect whether you're in an application or library context and behave accordingly, so I'll close this request.

**Comment by ioquatix** [comment]
> It seems that the feature request would be to add a new method to Bundler::Runtime to return what the OP wants.

I don't really mind how it's implemented, just that I think it should be possible to get a list of dependencies - maybe even including transitive ones.

> but the benefits are still unclear to me.

The benefit would be accessing the metadata of the gem or application and doing something with them programatically, i.e. "Here are all the gems you directly depend on."

> It seems easy enough to detect whether you're in an application or library context and behave accordingly.

What assumptions can we make here that make it easy? I investigated this and it did not seem easy.

**Comment by deivid-rodriguez** [comment]
> The benefit would be accessing the metadata of the gem or application and doing something with them programatically, i.e. "Here are all the gems you directly depend on."

This is exactly what `Bundler.load.dependencies` does, it lists _direct_ dependencies. It doesn't list the dependencies of the dependency defined by the `gemspec` DSL because they are _indirect_ dependencies. If you want to list dependencies of that gem, you can load the `gemspec` itself and list its dependencies.

You can see the `Gemfile` inside a gem repository as an example application that uses the gem you are developing (which you point to using `gemspec`). This example application could have other direct dependencies, even other direct dependencies being developed locally (for example, with `gem "<my_other_gem>", path: "my_other_gem_subdir"`). Which are the direct dependencies of this application? That would be the list of gems defined in that `Gemfile`, it wouldn't be the list of dependencies of each of the gemspecs of the gems that you are developing, those are transitive dependencies of the application. 

The title of this issue is "It is not possible to access runtime dependencies defined in a gemspec.". This is how you would do that:

```
$ ruby -e 'puts Gem::Specification.load("utopia-wiki.gemspec").runtime_dependencies'
utopia (~> 2.14)
utopia-gallery (>= 0)
kramdown (>= 0)
kramdown-parser-gfm (>= 0)
rackula (>= 0)
falcon (>= 0)
```

I reread this whole conversation and I feel I did my best trying to explain how things work right now, and why they don't currently work the way you expect. I asked you to give me an example to help me understand what you want to do, and why we need to change `bundler` so that you can do it, but I don't think the link you gave me answered that.

My suggestion is that you monkeypatch bundler to do what you want. Once you have something working, it will be easier to justify how it's useful for more people. I agree that the line between applications and gems is quite fuzzy and there's room for improvement there. In this case, I think directly working on it would the more useful way to improve things.

**Comment by eregon** [comment]
FWIW I agree with @deivid-rodriguez.
The fact the `gemspec` dependencies are modeled as indirect dependencies seems fairly natural.
If you would consider those direct dependencies of the Gemfile, what do you do with the gem itself? Is it an direct dependency too? (inconsistent, they should not be at the same level) It is skipped magically? (cannot be, it's part of the gems included).
Changing how Bundler understands gemspec just for this use-case doesn't make sense to me.

**Comment by deivid-rodriguez** [comment]
> > It seems easy enough to detect whether you're in an application or library context and behave accordingly.

> What assumptions can we make here that make it easy? I investigated this and it did not seem easy.

I think using the presence of a `.gemspec` file at the root of the repository is a pretty good indicator of being in a library context.

**Comment by ioquatix** [comment]
All the points you make are fair and I understand them.

The problem with:

```
$ ruby -e 'puts Gem::Specification.load("utopia-wiki.gemspec").runtime_dependencies'
```

Is how do you know what the path should be?

Are you expected to parse `Gemfile` or `gems.rb` and then try to figure out what gemspec was loaded?

**Comment by deivid-rodriguez** [comment]
Bundler resolves the `Gemfile` file by searching upwards from the CWD for a file named `Gemfile`. You can do the same for `*.gemspec` files.

**Comment by ioquatix** [comment]
> Bundler resolves the Gemfile file by searching upwards from the CWD for a file named Gemfile. You can do the same for *.gemspec files.

1. I'd need to implement the same logic that bundler does to figure out whether to use `Gemfile` or `gems.rb` or some other gemfile (e.g. BUNDLER_GEMFILE was specified). This seems like leaking the implementation of bundler into any tool which wants to do this itself.
2. How do you know that `gems.rb` or `Gemfile` doesn't specify a custom `gemspec` for example a custom path or even has some convoluted logic for loading the `gemspec`. In essence, you'd need to execute this file to find it out, which requires bundler right?

So your proposed solution "find any *.gemspec in the current working directory" at least from my perspective, falls short of the actual implemented behaviour. Which is why I think Bundler at the very least could expose WHAT gemspecs have been loaded, in a systematic way, as per my original suggestion:

```
definition = Bundler.definition

# All loaded gemspecs by this bundle.
definition.gemspecs
```

Otherwise, I'm not sure anyone can correctly implement this without re-implementing a large amount of Bundler.

**Comment by deivid-rodriguez** [comment]
For 1 you can use `Bundler.root`.

For 2, I think all libraries have a gemspec file at repo root, and all repositories having a gemspec file are repo root are libraries. Anything more complex than that might actually get things wrong. Like, there may be some application that loads a dummy local gem at some subfolder just for testing. With the more complex logic you're saying it's necessary it would be interpreted as a library, because the `Gemfile` is using the `gemspec` DSL.

In any case, I think something like this might get you want you want:

```
Bundler.definition.specs.select{|s| s.source.is_a?(Bundler::Source::Gemspec) }
```

**Comment by ioquatix** [comment]
I will try it and see if I can get it to work.
