### ISSUE TITLE
Release notes for Bundler v2.1 on bundler.io

### ISSUE THREAD

**Issue by sonicdoe** [rubygems/rubygems#3599]
For Bundler v2.1, there are no release notes on bundler.io. [The latest available are for v2.0](https://bundler.io/v2.0/whats_new.html).

**Comment by deivid-rodriguez** [comment]
We decided to not create a full copy of the documentation on every minor in https://github.com/rubygems/bundler/pull/7591#discussion_r369845718. I'm not fully sold on the idea, specially since [we fully fixed the third issue](https://github.com/rubygems/bundler-site/pull/500) from the ones @indirect explained. In my opinion that was the worst issue, since it was the only real end user issue, as opposed to the others which are bundler maintainer issues.

In any case, we are lacking a "What's new page" for bundler 2.1 for sure.

**Comment by indirect** [comment]
I think release notes and full copies of every page in the docs are separate things. 😄

That said, I'm also okay with keeping complete copies of the docs for every minor version if we "archive" them out of the middleman build process once they are more than (say) 1-2 years old. Mostly it's just that I don't think we should be rebuilding the 10-year-old docs for Bundler 1.x from source every time we make a docs change. 👍🏻

**Comment by deivid-rodriguez** [comment]
You're right these are separate issues, my bad :sweat_smile:.

This one is a valid issue with our current docs site, and what I brought up is something different. I'll bring that up separately if I feel strongly about keeping full copies (and try to fix the inefficient rebuilding issue in that case).

I guess this issue should actually live in https://github.com/rubygems/bundler-site, since "release notes" are not generated from content inside this repo, but I'm not 100% sure.
