### ISSUE TITLE
`bundle install` thinks that version 0.0.0 is higher than 0.1.x

### ISSUE THREAD

**Issue by makevoid** [rubygems/rubygems#3654]
A gem author published a gem version "0.0.0" of one of his gem and I noticed that even if `gem install gemname` installed the latest version correctly, `bundle`, based on the Gemfile contents, always tried to install "0.0.0".

#### steps to reproduce:

- Publish a gem with version "0.0.0" and then bump the version (e.g. to "0.1.0") and push that version as well

- Create the following Gemfile:

```rb
source "https://rubygems.org"
gem "gemname"
```

- run:

```
bundle
```

You will notice the following message:

```
Using gemname 0.0.0
```

Perform `bundle open gemname` to double check that the code is indeed from version 0.0.0

---

I think it's a very rare edgecase but it happened to a fairly popular gem, the author unpublished v 0.0.0 to fix the problem so that no noobies are stuck with that.

---

my env:

```Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.0.3
```

**Comment by deivid-rodriguez** [comment]
Hi @makevoid! I don't seem to be able to repro this. I used the [ajp-rails](https://rubygems.org/gems/ajp-rails) gem which had given us trouble in the past and things seem good. What bundler version are you using?

**Comment by deivid-rodriguez** [comment]
Also, from your sample output, you _already_ had 0.0.0 installed, so it seems like bundler picked it up because it satisfied the requirements.

**Comment by makevoid** [comment]
try with `hanami-api`, 0.0.0 is still published

my bundle installation output:
```Fetching gem metadata from https://rubygems.org/................
Resolving dependencies...
Using bundler 2.1.4
Fetching hanami-api 0.0.0
Installing hanami-api 0.0.0
```

using this gemfile:

```rb
source "https://rubygems.org"

gem "hanami-api"
```

weird :D

---

after your comment I thought it was RVM so I tried with latest ruby, dockerized, and I get the same behaviour:

Dockerfile
```dockerfile
FROM ruby:latest

RUN gem i bundler
COPY Gemfile ./
RUN bundle
```

docker-compose.yml
```yml
version: "3"

services:
  app:
    build:
      context: .
```

command:
```
docker-compose up --build
```

**Comment by deivid-rodriguez** [comment]
I still can't repro.

My guess is that your local docker image is not using 2.7.0 (`docker pull ruby` should fix it), and you're not using ruby 2.7.0 locally either. Since version `0.0.0` of `hanami-api` is the only published version of this gem supporting rubies other than 2.7.0, it's getting correctly picked up in these cases. See the "required ruby version" section of https://rubygems.org/gems/hanami-api/versions/0.0.0 vs https://rubygems.org/gems/hanami-api/versions/0.1.0 or https://rubygems.org/gems/hanami-api/versions/0.1.1 to double check.

Let me know if this makes sense and please close the ticket in that case :)

**Comment by makevoid** [comment]
you're right! I should have noticed :)! thanks!
btw I tried checking multiple versions (instead of of `:latest` I tried the following docker tags and found that on 2.7s it works)

on these versions it works:

```
ruby:2.7.1-stretch
ruby:2.7.0
```

on these instead it picks up 0.0.0 as latest gem version:

```
ruby:2.6.6-stretch
ruby:2.5.8-stretch
ruby:2.4
ruby:2.3
```

I guess that people should just unpublish the v. 0.0.0 of their gem as it's an edge case :)

**Comment by deivid-rodriguez** [comment]
Hei @makevoid! Thanks for the feedback!

Note that this is unrelated to version "0.0.0". Bundler is just doing what it's supposed to.

Version 0.0.0 of this gem supports all rubies, while version 0.0.1 and 0.1.0 only support ruby 2.7. This is the gem author's choice. Bundler is just respecting that by choosing the latest version if you are on ruby 2.7, or 0.0.0 otherwise.

**Comment by makevoid** [comment]
ah I reread your comment and you mentioned it before, then I guess we can close the issue, no bugs ^^
