### ISSUE TITLE
Verify gem signature

### ISSUE THREAD

**Issue by p-mongo** [rubygems/rubygems#3680]
I would like to verify that a gem file is signed.

The [documentation](https://guides.rubygems.org/security/) only mentions being able to require that signatures are verified during gem installation, however I would like to verify a particular file without installing it (thus bypassing both the danger of installing a different version and the problems having to do with the gem's dependencies).

How would one verify that the particular gem file is signed?

**Comment by pjmartorell** [comment]
If you use Bundler you can check a gem (checksums and signatures) with `HighSecurity` policy running  `Bundler.rubygems.spec_from_gem('/whatever/vendor/cache/nokogiri-1.10.10.gem', 'HighSecurity')`.
It will raise a `Bundler::SecurityError` exception if there is something wrong/invalid like the following: `Bundler::SecurityError (The gem nokogiri-1.10.10 can't be installed because the security policy didn't allow it, with the message: unsigned gems are not allowed by the High Security policy)`

**Comment by deivid-rodriguez** [comment]
No further feedback here, so closing. Thanks for the tip @pjmartorell!
