### ISSUE TITLE
'RUBYOPT' still contain "-r bundler/setup" when using `unbundled_env`

### ISSUE THREAD

**Issue by Edouard-chin** [rubygems/rubygems#3705]
Hi everyone 👋 , thank you very much for the work on Rubygems/Bundler.

I found out an issue related to `bundle exec` which set the `RUBYOPT` env variables to something like: `-r/opt/rubies/2.7.1/lib/ruby/2.7.0/bundler/setup`

When using `Bundler.with_unbundled_env`, bundler is supposed is to strip out the `-r bundler/setup` part but the regex is incorrect and assume the path is relative whereas it was set as an absolute path https://github.com/rubygems/rubygems/blob/e2a4895aab3225652d5946dc34623fb4177a2678/bundler/lib/bundler.rb#L356

Concretely, this creates a bug if you try to `bundle install` programatically after running `bundle exec`.

```ruby
# Gemfile

sources 'https://rubygems.org'
gem 'activesupport'

# --------------

# Gemfile_bis

sources 'https://rubygems.org'
gem 'activerecord'

# --------------

# script.rb

Bundler.with_unbundled_env do
  system('BUNDLE_GEMFILE=Gemfile_bis bundle install')
end

# --------------

# bundle exec script.rb
# Could not find gem 'activerecord' in any of the gem sources listed in your Gemfile.
# Run `bundle install` to install missing gems.
```

Tested on Ruby 2.7.1 , Bundler 2.1.4. The bug seems present on Bundler edge.

**Comment by deivid-rodriguez** [comment]
Yes, this seems like a bug to me, thanks for reporting! I'll try to sneak the fix into the next release :+1:.

**Comment by rreinhardt9** [comment]
I've been looking farther into this one in the attached draft PR, but I've come up with several questions from the investigation.

## What I've found
 If you were to just comment out the line https://github.com/rubygems/rubygems/blob/e2a4895aab3225652d5946dc34623fb4177a2678/bundler/lib/bundler.rb#L356 

and then run the specs, this spec still passes https://github.com/rubygems/rubygems/blob/035984c789d1a793e5dffcae0a285a63558a8e7e/bundler/spec/runtime/with_unbundled_env_spec.rb#L87-L96

The reason for this is because `unbundled_env` actually starts with the `original_env` (the env before bundler was initially loaded) and then tries to further remove bundler related ENV vars https://github.com/rubygems/rubygems/blob/e2a4895aab3225652d5946dc34623fb4177a2678/bundler/lib/bundler.rb#L346-L347

So in the simple case, the code in `bundler.rb` that is trying to sub out the `bundler/setup` addition to `RUBYOPT` never gets called. Thanks to the fact that it starts with `original_env`, `RUBYOPT` has already been set back to it's pre-bundler state.

Based on that it would seem that we could actually just remove these lines entirely: https://github.com/rubygems/rubygems/blob/e2a4895aab3225652d5946dc34623fb4177a2678/bundler/lib/bundler.rb#L355-L357

So I looked back in history to see why this line is there in the first place. [Looking back at 2012](https://github.com/rubygems/bundler/issues/1604#issuecomment-3345485), it looks like intention was to solve for this use case:
> Process A does the bundler setup. Then spawns Process B (not cleaned). Process B then wants to spawn process C in a clean environment. RUBYOPT will remain dirty despite calling with_clean_env.

So, my conclusion so far is that:
- For most use cases, RUBYOPT it taken care of when we reset the to the original env and we never actually get to the line in `bundler.rb` that tries to sub out the require.
- There is possibly a more complex use case where process A spawns process B spawns process C that I need to reproduce in order to test the fix (or know if the fix is even still necessary)

## Reproduction Attempts

I first tried to reproduce it using the script above (thanks for the starting point!!). A couple of notes, I modified it a bit to try and get it to work for me, and I'm using bundler 2.1.2 to test the script (I'm running into local problems running bundler specs when I upgrade to 2.1.4 because of default gems... I still haven't figured that out). Here is the script I tested with:

```Ruby
# Gemfile
source 'https://rubygems.org'
gem 'minitest', '< 4'

# Gemfile_bis
source 'https://rubygems.org'
gem 'minitest', '>= 4'

# script.rb
Bundler.with_unbundled_env do
  system('BUNDLE_GEMFILE=Gemfile_bis bundle install')
end
```

Here is how I ran it:
<details>
<summary>Script Output</summary>

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.2
Fetching minitest 3.5.0
Installing minitest 3.5.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./vendor/bundle`

$ bundle exec ruby script.rb
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.2
Using minitest 5.14.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```
</details>

<details>
<summary>Resulting Gemfile.lock</summary>

```
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    minitest (3.5.0)

PLATFORMS
  ruby

DEPENDENCIES
  minitest (< 4)

BUNDLED WITH
   2.1.2
```
</details>
<details>
<summary>Resulting Gemfile_bis.lock</summary>

```
$ cat Gemfile_bis.lock 
GEM
  remote: https://rubygems.org/
  specs:
    minitest (5.14.1)

PLATFORMS
  ruby

DEPENDENCIES
  minitest (>= 4)

BUNDLED WITH
   2.1.2
```
</details>

I wanted an even clearer picture of the state of `RUBYOPT` here, so I added some `binding.irb` calls in the script:
```
binding.irb
Bundler.with_unbundled_env do
  binding.irb
  system('BUNDLE_GEMFILE=Gemfile_bis bundle install')
end
```
When I re ran the script, at the first break point I found that `ENV['RUBYOPT']` was present and contained an absolute path: `"RUBYOPT"=>"-r/Users/ross/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/setup"`. Additionally, the old value (nothing) was backed up `"BUNDLER_ORIG_RUBYOPT"=>"BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL"`. At the second breakpoint, `RUBYOPT` had been removed from the ENV.

I also tried with an existing `RUBYOPT` to make sure that worked as well. There at the first break point `"BUNDLER_ORIG_RUBYOPT"=>"-W2", "RUBYOPT"=>"-r/Users/ross/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/setup -W2"` and at the second `"RUBYOPT"=>"-W2"` so that seems to work as intended as well thanks to the replacement with the `original_env`.

I'm trying to create a script that would simulate the situation described in that old issue, and so far I'm not seeing any breakage there either (but it could be I'm not reproducing that situation correctly). I create the following script:

```Ruby
# Gemfile
source 'https://rubygems.org'
gem 'minitest', '< 4'

# script.sh
bundle exec ruby ./print_opts.rb

# print_opts.rb
Bundler.with_unbundled_env do
  puts "Current opts:"
  puts ENV['RUBYOPT']
end
```

I tried running it like

<details>
<summary>Script Run</summary>

```
# First, make sure script is executable
chmod +x script.sh

$ bundle exec ./script.rb
Current opts:

```
</details>

It appeared that even in the process started by the script that `RUBYOPT` had been appropriately removed.

## Next Steps

Does anyone have an idea of how we can reproduce the use case from that earlier comment to see if the issue exists and judge if the fix works?

If we can't reproduce, perhaps this code is no longer needed as the old use case is now covered by the current implementation of the restoration of the original env? In that case, we might be able to just remove the old regex and spec.

I'd love to hear any other ideas or thoughts on those potential next steps because I'm kind of stumped at the moment :-) Thanks y'all!

**Comment by rreinhardt9** [comment]
After digging a bit more in the history, it looks like line explicitly removing RUBYOPT was no longer needed after this commit adding `INTENTIONALLY_NIL` to EnvironmentPreserver https://github.com/rubygems/rubygems/commit/8e3b925413e1ed5f721e2f7d90dfe6f0e3c43af5 

It USED to work differently back in 2012 when the explicit removal was added. Then `ORIGINAL_ENV` quite literally just saved whatever was in `ENV` https://github.com/rubygems/bundler/blob/9febfef6e0699d618852d7a1a1fe5a7acffbed8c/lib/bundler.rb#L10 `ORIGINAL_ENV = ENV.to_hash`

Whenever bundler was required, it would capture the ENV present at that moment.

Fast forward, and `EnvironmentPreserver` was introduced. It began saving backups of environment variables with a special bundler prefix, but it would not save a backup if the ENV key didn't exist https://github.com/rubygems/rubygems/commit/d74920ec939fd2752a168746247f2174efe920e8 What this means practically, is if `RUBYOPT` wasn't set before bundler was loaded, there would be no record of it NOT being set. So, when "restoring" the original environment, `RUBYOPT` was just left alone because there was no backup key showing it didn't exist before bundler.

Later, a changes was added to EnviromentPreserver to make sure that it preserves ALL and ONLY bundler specific original ENV keys, even ones that were actually blank. https://github.com/rubygems/rubygems/commit/8e3b925413e1ed5f721e2f7d90dfe6f0e3c43af5#diff-83eb5e43a306cb4526be4c5e5a790479 Because of this change, now if `RUBYOPT` was blank (or had a value) before bundler was loaded it was ensured that it was restored to that value when calling `with_original_env`. 

After that change, that is when the line explicitly removing `bundler/setup` was no longer required as it will always be reverted to the original version of `RUBYOPT` or removed from the ENV if it was not present before.

Given that, I think we can quite literally just remove the line https://github.com/rubygems/rubygems/blob/e2a4895aab3225652d5946dc34623fb4177a2678/bundler/lib/bundler.rb#L355-L357 For that matter, I wonder if the explicit reverting of `RUBYLIB` and `MANPATH` in next to that line are needed anymore as well. I'll play with removing them and see if the specs still pass.

I've been unable to reproduce an issue using a script similar to the original one... I just used:
```Ruby
# Gemfile
source 'https://rubygems.org'
gem 'rspec'

# Gemfile_bis
source 'https://rubygems.org'
gem 'minitest'

# script.rb
Bundler.with_unbundled_env do
  system('BUNDLE_GEMFILE=Gemfile_bis bundle install')
end

# Commands:

# bundle install
# bundle exec ruby script.rb
```
This behaves as expected. I did have to make some changes on the original example, I had to %s/sources/sources/ in the Gemfiles, make sure to `bundle install` before running the script, and call `ruby script.rb` instead of just `script.rb`.

It's very possible I'm missing something here, please let me know if you see something I'm missing! Unfortunately, I'm not sure this helps solve your original trouble @Edouard-chin 😬 If you have any insight into how to better reproduce the issue with RUBYOPT not being removed let me know!

**Comment by deivid-rodriguez** [comment]
Hi @rreinhardt9! Thanks so much for the investigation. I agree we can kill those lines manipulating `RUBYOPT`. Are you planning to update the draft PR with those changes?

@Edouard-chin Does removing those lines help with your problem?

**Comment by rreinhardt9** [comment]
@deivid-rodriguez You bet; I'll get right on updating that PR with those changes! Thanks for the sanity check!! 🙏

**Comment by deivid-rodriguez** [comment]
@Edouard-chin Just realized that I was somewhat waiting for you to double check the attached PR, but I forgot and went ahead and merge it :sweat_smile:. Anyways, feel free to try it and let us know if you run into any issues :+1:.

**Comment by Edouard-chin** [comment]
My apologies for not answering on time :(. Thanks so much @rreinhardt9 for taking care of this ❤️ . I'll give it a try and post back if I find other issues.
