### ISSUE TITLE
`bundle install` fails when paths don't exist in optional groups.

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#3730]
I can have something like:

```ruby
group :local, optional: true do
	gem "async-rspec", path: "../async-rspec"
	gem "rspec-files", path: "../rspec-files"
end
```

Even if I don't specify `bundle install --with local` it still fails if those paths don't exist. I think they should be ignored when running `bundle install`.

**Comment by deivid-rodriguez** [comment]
The explanation for this is that, even if optional groups are used, resolving still happens considering the dependencies of your optional gems, so that only a single compatible version of each dependency is chosen. So that, say, if your Gemfile depends on `rspec` at runtime like this:

```
source "https://rubygems.org"

gem "rspec", "~> 2.9"

group :local, optional: true do
	gem "async-rspec", path: "../async-rspec"
	gem "rspec-files", path: "../rspec-files"
end
```

Bundler needs to know which dependency on `rspec` the other gems have, because if for example they depend on `rspec ~> 3.0`, they presumabiliy won't work for your Gemfile, since it depends on RSpec 2.

And in order to figure out the dependencies of your optional gems for resolving, bundler needs to read the actual source and look for gemspecs in there, and in the case of path sources, this is the local filesystem.

So that's why it fails if the paths don't exist.

I can see how it could be convenient to ignore this error, but this is very easy to fix so I don't think we should be changing anything in bundler.

So, I'll close this.
