### ISSUE TITLE
Bundle install --without shouldn't be remembered

### ISSUE THREAD

**Issue by Ana06** [rubygems/rubygems#3842]
Bundle documentation claim the following:

> Flags passed to bundle install or the Bundler runtime, such as --path foo or --without production, are not remembered between commands

However, when I run `bundle install` with the `--without` option, a `.bundle/config` which specifies `BUNDLE_WITHOUT`.

### Which command did you run?

`bundle install --without group_name`

### What were you expecting to happen?

I didn't expect a `.bundle/config` file to be created

### `bundle env`
```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
  Full Path   /home/ana/.rbenv/versions/2.6.2/bin/ruby
  Config Dir  /home/ana/.rbenv/versions/2.6.2/etc
RubyGems      3.0.3
  Gem Home    /home/ana/.rbenv/versions/2.6.2/lib64/ruby/gems/2.6.0
  Gem Path    /home/ana/.gem/ruby/2.6.0:/home/ana/.rbenv/versions/2.6.2/lib64/ruby/gems/2.6.0
  User Home   /home/ana
  User Path   /home/ana/.gem/ruby/2.6.0
  Bin Dir     /home/ana/.rbenv/versions/2.6.2/bin
Tools         
  Git         2.16.4
  RVM         not installed
  rbenv       rbenv 1.1.1
  chruby      not installed

## Bundler Build Metadata

Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Correct documentation is now live, so I'll go ahead and close this. Thanks so much for the report!

**Comment by Ana06** [comment]
@deivid-rodriguez thank you for the quick response! the new documentation clarifies this :+1: 

> BUT, you should have gotten a deprecation message in the console telling you that using the --without flag is deprecated due to this future behaviour change, and advising you to use bundle config instead. Did you get this message printed to the screen?

Yes (I hadn't seen it, but it was printed :see_no_evil:). However I was not trying to remember the flag. I want to install only a group in a GitHub Action, but I do not want this setting to be remembered (as I want to install all the groups locally). Should I be doing this in a different way?

**Comment by deivid-rodriguez** [comment]
I see.

No, you're not doing anything wrong, `bundler` is, but changing this bad legacy behaviour legacy is problematic and we need to do it on a major version. Is the configuration being saved a problem in your actions workflow? Since the workflow runners should be ephemeral doesn't sound like a big deal?

In any case, we have some hacky feature flags in place that you can setup through configuration to early opt in to the new behaviour. You can do `bundle config set forget_cli_options true` or set the `BUNDLE_FORGET_CLI_OPTIONS` environment variable. I say "hacky" because this is not really configurable behaviour, since the old behaviour will not be supported at all in the future and the setting will be removed, but it does the trick for now if you want to early opt in.

**Comment by Ana06** [comment]
@deivid-rodriguez 

> No, you're not doing anything wrong, bundler is, but changing this bad legacy behaviour is problematic and we need to do it on a major version. Is the configuration being saved a problem in your actions workflow? Since the workflow runners should be ephemeral doesn't sound like a big deal?

I modify some files and commit them back in the workflow. I had committed the bundle configuration file by accident, but I have now just excluded that file in `.gitignore`. So it is not really a big deal :sweat_smile: 

Thanks a lot for the explanation! :+1:

**Comment by deivid-rodriguez** [comment]
Any time! Thanks to you for your clear report!
