### ISSUE TITLE
Bundler local filters out all "ruby" platform gems on JRuby

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#3874]
It appears that Bundler is filtering out all gems that don't have a platform of "java" when trying to activate a local/vendored bundle.

The original issue reported by @eregon is here: https://github.com/jruby/jruby/issues/6349

I dug into this and discovered that `expand_dependencies` is filtering out all dependencies in the "ruby" platform if the `generic_local_platform` is not also "ruby". This means that only "java" platform gems get included, which clearly won't work.

https://github.com/jruby/jruby/issues/6349#issuecomment-668149352

I do not know why it breaks in this situation and not when running a bundled application normally. I suspect it has something to do with how local bundling limits gem visibility to only the gems vendored into the application.

The "ruby" platform is both a marker for C extensions and a default or fallback platform. Removing all "ruby" gems if the platform differs is not correct logic; as with normal gem resolution, a platform-specific gem should be used if available, and the default "ruby" platform gem should be used otherwise.

This should affect any implementation that ends up with a `generic_local_platform` that is not simply "ruby" but I do not know of any implementation that both supports Bundler and also has this different platform.

**Comment by headius** [comment]
I believe this would also fail to include gems that have been pre-built for specific platforms, such as for win32.

**Comment by deivid-rodriguez** [comment]
Your investigation about this issue was very helpful. Just two notes to clarify from what I found:

> I do not know why it breaks in this situation and not when running a bundled application normally. I suspect it has something to do with how local bundling limits gem visibility to only the gems vendored into the application.

The culprit was not actually related to local bundling, but to freezing. In other words, `bundle config set --local path foo` was not the culprit, but `bundle config set --local frozen true`. The reason is that on regular mode, the current platform is always added to the definition, but that does not happen in "frozen mode" where only platform information from the lockfile is used. It's this code here:

https://github.com/rubygems/rubygems/blob/74ecd2f57efde65f456c21b6bf25c33682423cb0/bundler/lib/bundler/definition.rb#L126

Because of this, the current platform would not end up being used at all in `expand_dependencies` when in frozen mode.

> The "ruby" platform is both a marker for C extensions and a default or fallback platform. Removing all "ruby" gems if the platform differs is not correct logic; as with normal gem resolution, a platform-specific gem should be used if available, and the default "ruby" platform gem should be used otherwise.

This seems correct as well, except that this fallback does not apply in frozen mode. In frozen mode, the gems and platforms used are the ones in the lockfile. So, in this case, the bug was that the "ruby" platform was not being considered even if it was the platform the lockfile was locked to. Once the bug is fixed, the "ruby" platform is the only platform being considered in this case. To get the platform specific fallback logic in place, you'd need to either run `bundle lock --add-platform java` under any platform and commit the updated lockfile, or to re-resolve under jruby and commit the updated lockfile.
