### ISSUE TITLE
Installing git gem with disable_multisource enabled doesn't work

### ISSUE THREAD

**Issue by rafaelfranca** [rubygems/rubygems#3948]
### Describe the problem as clearly as you can

Consider the following Gemfile:

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', github: 'rails/rails'
gem 'activeresource'
```

### Which command did you run?

`bundle config --local set disable_multisource true`
`bundle lock`

### What were you expecting to happen?

Lockfile generate with success

### What actually happened?

```
The gem 'activesupport' was found in multiple relevant sources.
  * https://github.com/rails/rails.git (at master@77fc1c2)
  * rubygems repository https://rubygems.org/ or installed locally
You must add this gem to the source block for the source you wish it to be installed from.
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this, @rafaelfranca! Definitely a bug.

I was just working today on [a PR to enable `disable_multisource` by default](https://github.com/rubygems/rubygems/pull/3655), so we should definitely fix this before moving that one forward.

I'll have a look soon.

**Comment by rafaelfranca** [comment]
Related to this issue but not the same problem this Gemfile doesn't raise and also search first on the rubygems.org source not in the same source as the specified gem:

```ruby
# my-gem.gemspec
# ...
gem.dependency("my-another-private-gem")

# Gemfile
source 'https://my-private-server' do
  gem 'my-private-gem'
end
```

Bundle will still install `my-another-private-gem` from rubygems.org if the gem exists there. We should probably search first in the same source as `my-private-gem` before falling back.

**Comment by deivid-rodriguez** [comment]
Interesting. That makes sense, yeah. What if rubygems.org has a "better version" (higher version that still meets requirements)? I guess you'd still want the one from your source even if it's "worse" in terms of versioning?

**Comment by deivid-rodriguez** [comment]
Maybe @indirect has more context about this. I recall some conversations about this with him and Samuel involved.

**Comment by deivid-rodriguez** [comment]
Also, what if the same dependency is explicit in the top level, but a transitive dependency of a "scoped" source? Which one should be preferred?

**Comment by rafaelfranca** [comment]
My main concern about this is security.

If a private gem is squatted on Rubygems.org bundler will install the Rubygems.org version while what we need is the private version. For security reason I'd want the "worse" version over the "better version" on rubygems.org.

In the case of the gem being explicitly define in the top level, I think the source of top level gem should have precedence.

**Comment by indirect** [comment]
This doesn't seem like a bug to me, this seems like Bundler working exactly correctly. Because of security, it is an unfixable error for you to ask for `activeresource` without telling Bundler which source you want explicitly. If you want `activeresource` from the `rails` git repo, you must say so:

```ruby
source git: "https://github.com/rails/rails" do
  gem "rails"
  gem "activeresource"
end
```

Can you clarify what you think is a bug about this?

**Comment by rafaelfranca** [comment]
`activeresource` is not in the Rails repo, so that will not work. activesupport is, and that is what is failing. I tried to enable this option in 5 applications and while I agree that it seems good in terms of security to ask users to repeat every single indirect dependency that could possibly be in two different sources in the Gemfile it doesn't seems like a good option in terms of UX.

This gemfile would work:

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', github: 'rails/rails'
gem 'activeresource'
gem 'activesupport', github: 'rails/rails'
```

But as soon you use any other gem that by some 3rd or 4th level of indirection depend on railtie now you need to add `gem railties`, github: 'rails/rails'` as well to you Gemfile. And you would be surprised why bundler failed. At this point I'm sure most users will forget about this option and just disable it.

I think we can keep things secure and with a good UX if we keep a map of all gems from different sources than the Rubygems.org and try to install first from that source and then fallback to Rubygem.org.

**Comment by indirect** [comment]
The option is going to be turned on permanently soon, because (as you note) it is insecure to have it turned off. Trying first from a source and then fallback to rubygems.org recreates the entire problem, just in reverse. If (say) the sidekiq gem server has the malicious gem on it, then Bundler would install from rubygems.org until the day that the malicious gem was added to the sidekiq server, and you would suddenly be getting the malicious gem with no warning.

The only way we could figure out to make this secure is to require an explicit server for every single gem that is present in multiple servers. Create one block for each source, put the gems you need from that source in that block. Like this:

```ruby
source "https://rubygems.org"

gem "activeresource"

source git: "https://github.com/rails/rails" do
  gem "rails"
  gem "activesupport"
end
```

**Comment by rafaelfranca** [comment]
Good point about the reverse problem. I do agree it is better to not fallback at all.

A setup like this is not raising, so maybe we should make it raise?

```
# my-private-gem.gemspec
# ...
gem.dependency("my-another-private-gem")

# Gemfile
source 'https://my-private-server' do
  gem 'my-private-gem'
end
```

This setup would install `"my-another-private-gem"` from Rubygems and not show any warning/raise. As this is a different issue from the one I original opened should I open a new issue?

**Comment by deivid-rodriguez** [comment]
I think they issue you are discussing is fixed by keeping separate sections in the lockfile for each gem server source. That's part of the behaviour `disable_multisource` enables. With that in place, once you get a resolution with a certain gem server source priority, you'll always get that same source priority, no matter which gem releases which version to which gem server source. That seems like the right thing to do to me and given that, I don't think we need to raise or warn when a gem is present in multiple sources at all?

I _do_ think there's value in implementing a more expected/usable gem server source priority as suggested in https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465, but it sounds quite tricky with a lot of edge cases as opposed to the current solution (only use block sources for gems directly under them).

**Comment by rafaelfranca** [comment]
👍 we can close this issue then. I’ll try to migrate one of our gemfiles with this new option enabled and report if I find more concrete problems. I’m happy that we are enabling it by default.

**Comment by deivid-rodriguez** [comment]
Actually, even if the issue we discussed might not be an issue with `disable_multisource`, the original problem reported here still seems like an issue, right?

**Comment by deivid-rodriguez** [comment]
> In the case of the gem being explicitly define in the top level, I think the source of top level gem should have precedence.

Ok, so I had another look at this, and I had misunderstand the report. It's actually the above case, right?

Normally, activesupport would be picked up from the `github` source, but since it's explicited in the top level, it should be picked up from rubygems.org, right?

However, I removed the "multisource check" causing this error (based on the rationale that we already get the security we want with the source pinning `disable_multisource` implemements), and it turns out that `activesupport` is picked up from the `github` source, which is totally unexpected to me.

Thoughts? Should I consider this a bug and try to fix it?

**Comment by deivid-rodriguez** [comment]
Oh, wait! I think I get it now.

As far as a I know, all the family of "rails" gems are versioned in sync, which means that if we pickup the parent gem `rails` from the `github` source, the only set of gems satisfying that dependency will be the ones also present in the `github` source, since I don't think there's `6.1.0.alpha` versions at `rubygems.org`.

So what `bundler` is doing is finding the only possible resolution? The only question is an error is fine, or we should allow the "alpha" gem to be picked up from the `:github` source. In my opinion, showing an error is fine, but the wording is not good, because this is not about the specification of sources being incorrect or ambiguous, but about bundler not being able to find a proper resolution for the current specification of sources.

**Comment by deivid-rodriguez** [comment]
Oh boy, I misread `activeresource` as `activesupport` :see_no_evil:. The error is totally unexpected then. Back to square one.

**Comment by deivid-rodriguez** [comment]
Ok, so it turns out this is behaving as expected. `activesupport` is a dependency of `activeresource`, and it's also a dependency of `rails`. So where should `bundler` pick it up from? As a feature enabled with the `disable_multisource` setting, `bundler` raises an error in this "ambiguous" case.

I'm not sure we need this though, given that we'll be locking all sources separately in the lock file (note that in this case, namely, 1 gem server source + 1 github source, this is already happening, it's just not happening if you have multiple gem server sources). If we keep the current behaviour (find the only resolution that would work, which is to pick `activesupport` from the `github` source, then that resolution will be locked in the `Gemfile.lock` file. So even if someone managed to maliciously release `activesupport 6.1.0.alpha` to rubygems.org, that wouldn't change anything for an application locked to `activesupport 6.1.0.alpha` coming from a different source.

Any thoughts appreciated, my current idea would be to remove this specific error.

**Comment by indirect** [comment]
@deivid-rodrigue I think we’re basically on the same page now. 😅 The reason for the error when a gem is available in two sources is a security thing: source 1 might have a completely different acriveresource than source 2. Locking gems to a source only works after the first install—on the first install, Bundler needs you to put the gem in a source block to know which source you intend the gem to come from. Happy to explain more if that’s not clear. 🙂

**Comment by deivid-rodriguez** [comment]
Hei! Thanks for your feedback @indirect.

First, and just to make sure we're on the same page, I think you made a typo and wrote `activeresource` where you meant to write `activesupport`. I made the same error and that confused me when looking into this issue. In other words, this ticket is not about direct dependencies (`activeresource`'s source is non ambiguous in this Gemfile), but about transitive dependencies.

Also, yes, I'm definitely aware that the concern here is security. That's my main motivation for moving #3655 forward :smiley:. That's very close to being ready by the way.

So, after getting familiarized with all this code, I think there's a few different things that will get enabled with `disable_multisource`:

1) **Separate sections for gem server sources in the lock file**. I think this is unquestionable as a security improvement. Once you have locked your application to a matrix of gem sources and gem versions from those sources, that can never change. No matter if a different source releases the same version of a gem you're currently locked to.

2) **Warning for multiple global sources**.  This seems also nice, because `Gemfile`'s with multiple top level sources are clearly ambiguous about which gems they want from each source. I'm also :100: on deprecating this, but I don't consider as bad as not having 1). After all, if someone manages to push a malicious version of gem X to source 1, you don't need both source 1 and source 2 as global sources in your Gemfile to potentially get the malicious gem, you only need source 1. What I mean is that the real fix here is to test your dependencies, make sure they are correct, and lock to them, before you ever push them to production.

3) **Hard error for same transitive dependency from two different sources**. This is what's happening in this issue, and the way I see it, it's quite similar to 2). The differences are:
    * Since it's about transitive dependencies, and some dependencies are shared by many different gems, I feel it might get quite annoying and verbose to adjust Gemfiles to this. This would be the UX issue @rafaelfranca mentioned in https://github.com/rubygems/rubygems/issues/3948#issuecomment-693028358.
    * It's a hard error, so no chance of getting ready for it or see the impact beforehand.
    * It will get in the middle in common cases. In the case of this issue, it's clear that you want `activesupport` from the `github` source, since it's the only source that has matching "beta" versions of the dependent gems. Of course, if someone pushes a malicious `6.1.0.alpha` version of `activesupport` to `rubygems.org`, then you could end up with a different "dangerous" resolution, but in that case, everyone depending on `activesupport` from `rubygems.org` and not committing a lockfile would be vulnerable, not only those using two different gemfile sources including `activesupport`. So, again, real fix is to make sure you lock your dependencies and properly audit changes.

So, in conclusion, totally :+1: on 1) and 2), but I have some hesitations on 3), and if we decide to do it, I'd like to deprecate it first.

**Comment by indirect** [comment]
@deivid-rodriguez you make an excellent point. If we want to roll out 3), we probably need to ship it as a warning first, with a config setting to disable the warning. Then we can propose making it a hard error, see what community feedback on that is based on the warning, and go from there.

**Comment by deivid-rodriguez** [comment]
Ok, just to unlock 1) and 2), I plan to remove the hard error in 3) temporarily from #3655, and then open a separate issue to discuss how to move that one forward.

**Comment by casperisfine** [comment]
Sorry to jump in this conversation, but this whole situation is creating a huge toll on our org, and I'm really not certain the proposed solutions would help that much.

Locking gems to a source help existing apps, but leave new apps, or apps adding that gem later vulnerable. 

> What I mean is that the real fix here is to test your dependencies, make sure they are correct, and lock to them, before you ever push them to production.

Sure, but:

  - An attacker can already do quite considerable damage by having a compromised gem installed on developers machines or CI. It's kind of too late already.
  - In term of UX, the proposed solutions are really not so good. We have a lot of not so confirmed developers, and they're having a real hard time fixing their `Gemfile`.

The main thing that cause us problem today is transitive dependencies, e.g.

  - `foo` is on our private gem server
  - `bar` is on rubygems.org
  - `plop` is private as well.
  - `foo` depends on `bar` and `plop`. 

This force to have to declare `plop` at the top level of the Gemfile.

Ultimately I believe that the source priority solution initially proposed is the best, e.g. allow to set sources so that bundler will never look for a gem on `rubygems.org` if that name exist on `private-server.com`.

> Trying first from a source and then fallback to rubygems.org recreates the entire problem, just in reverse. If (say) the sidekiq gem server has the malicious gem on it, then Bundler would install from rubygems.org until the day that the malicious gem was added to the sidekiq server, and you would suddenly be getting the malicious gem with no warning.

I understand your point of view, and it make sense for a 3rd party private server such as sidekiq's, best practice would be to use a `source` block or param for such a gem.

However for an organization like ours with a private server containing many gems, being able to very simply configure that server has having priority over the public one would lead to a much better UX, and would avoid countless mistakes and wasted hours for our developers. It would be also very easy to statically enforce with linters, making that entire class attack moot.

**Comment by deivid-rodriguez** [comment]
I don't think 1) + 2) will create any UX problem, right? If we do the current plan, the `Gemfile` in this issue will just work exactly as it works today.

**Comment by deivid-rodriguez** [comment]
I assume your whole argument is that we shouldn't do 3) at all?

**Comment by deivid-rodriguez** [comment]
The whole source priority thing needs a review, and I understand your point that also fresh apps and developers machines should be considered, I'm just trying to get these improvements in first.

**Comment by casperisfine** [comment]
> I don't think 1) + 2) will create any UX problem, right?

1) is fine yes. UX wise it shouldn't cause any new concerns to users.

2) is ok today I guess, but if we're talking source priorities, then it might no longer make sense.

e.g. ideally I'd like to just be able to do:

```ruby
source 'https://private-gems.example.com' # number 1 priority
source 'https://rubygems.org' # fallback
```

Of course as you mention it's a bit ambiguous wether priority is from first declared to last, or the other way around.

> I assume your whole argument is that we shouldn't do 3) at all?

I mean, it's one solution. But for context our security team has been temporarily name squatting all our private gems on `rubygems.org` with version `9000.1`, as a way to prevent attacks until we figure a good way to ensure this kind of mistake no longer happen.

So I've been pinged on many internal issues and PR by developers having lots of trouble configuring their Gemfile properly, hence why I'm concerned about UX. A hard error is better than nothing, but it doesn't help non-experts from fixing the situation, especially for gems that are dependencies of dependencies.

So to answer your question directly, I'm not saying you shouldn't do any of 1) 2) 3), some of it might be helpful for sure. I'm just concerned by usability.

 > The whole source priority thing needs a review

**Comment by casperisfine** [comment]
> The whole source priority thing needs a review

Not sure I understand that part. A review of what? by whom?

**Comment by deivid-rodriguez** [comment]
That I'm still new to `bundler`'s source priority, so I'd like to test some more cases and make sure they work as I expect.

So, essentially, the alternative to 3) would be to always choose the block source over the global source if an indirect dependency is present in two different sources? What if the indirect dependency is present in two different block sources? Then _do_ raise in that case?

I had never considered an "order priority" like the one you mention. I wouldn't expect `bundler` to resolve differently depending on the order in which you specify things. I think it's better to fail if the specification is ambiguous.

**Comment by deivid-rodriguez** [comment]
Maybe we could also extend the `DSL` to something like `source "foo", fallbacks: ["bar", "baz"]` or something.

**Comment by casperisfine** [comment]
> would be to always choose the block source over the global source if an indirect dependency is present in two different sources?

I think it should yes, but of course it has the problem mentioned before of: what if that indirect dependency is pulled form two distinct sources. e.g.:

```
foo (rubygems.org) => dep
bar (private.org) => dep
```

```
source 'https://rubygems.org'

gem 'foo'

source 'https://private.org' do
  gem 'bar'
end
```

Assuming `dep` is present on both servers, then it's ambiguous where `dep` should be fetched from.

Whereas if you define sources with priorities, this issue goes away.

> I had never considered an "order priority" like the one you mention. I wouldn't expect bundler to behave differently depending on the order in which you specify things in the Gemfile. 

Yes, I'm not suggesting to use that syntax, the ordering could be made explicit via another syntax. But in a way this concept already exist, when you do:

```
source 'https://private' do
   gem 'bar'
end
```

You kinda "prepend" the private gem server in the resolution list.

> Maybe we could also extend the DSL to something like source "foo", fallbacks: ["bar", "baz"] or something.

Maybe yes. I feel like absolute priorities is the solution, but I admit I'm really unsure what the best syntax for it would be.

**Comment by deivid-rodriguez** [comment]
So, what I'm seeing is basically we agree: block sources take priority over the global source. But what about:

```ruby
source 'https://rubygems.org' do
  gem 'foo'
end

source 'https://private.org' do
  gem 'bar'
end
```

I guess we should raise in that case.

**Comment by casperisfine** [comment]
> I guess we should raise in that case.

Yes, that what I was saying as well. Your snippet like just like mine is asking bundler to fetch the same gem from two different sources, that's a conflict, it should raise for sure.

**Comment by deivid-rodriguez** [comment]
Wait, so you're saying that

```ruby
source 'https://rubygems.org'

gem 'foo'

source 'https://private.org' do
  gem 'bar'
end
```

should also raise? But that's exactly what 3) would do, and why the Gemfile in this issue doesn't work with `disable_multisource`.

**Comment by casperisfine** [comment]
> But that's exactly what 3) would do, and why the Gemfile in this issue doesn't work with

Oh 🤦 my bad...

Then yeah I suppose that if we want decent UX, an "explicit source" (e.g. `source do` or `source:`) must be able to "win" over a "default source" (set at top level with `source "url"`).

So that in you last example:

```ruby
source 'https://rubygems.org'

gem 'foo'

source 'https://private.org' do
  gem 'bar'
end
```

`gem 'foo'` would initially pull `dep` from `rubygems.org`, but `source 'https://private.org' { gem 'bar' }` should be able to override that.

Would that make sense to you?

**Comment by deivid-rodriguez** [comment]
Yeah, to me that'd be a reasonable source priority. I'd like to hear @indirect's thoughts though.

What I'm not sure of, and that's why I said that this thing requires a review, is whether that's how bundler works today, or whether bundler looks for any valid resolution among all possible sources. In other words, if it choses `activesupport` from `github` in the sample `Gemfile` given in this issue because it ended up preferring the "more explicit source", or because it's the only possible resolution among all sources.

**Comment by indirect** [comment]
It's probably worth pointing out that we ended up with the behavior that we have today because it's impossible to know what a user intends. Do they "obviously" want dependencies to only come from the source of the parent? Or do they "obviously" want child dependencies to be satisfied by any source?

Merely prioritizing one source ahead of another produces _extremely_ confusing results: for example, "Bundler is broken" because it will not upgrade to the newer version, changing sources. Or "Bundler is broken" because it _will_ upgrade to a newer version in another source.

This is why our final conclusion was that there can only be _one_ default source, never a prioritized list. Any gem that is present in more than one source _must_ be disambiguated with a source block.

```ruby
source "private.org"
gem "private_gem" # depends on `private_child`

source "rubygems.org" do
  gem "public_gem" # depends on `public_child`
end
```

Let's say both private.org and rubygems.org have versions of `private_child` and `public_child`. How do we know which child gems the application developer intends to use? My understanding is that Bundler would use `private_child` from `private.org` (the default source), and raise an error about `public_child` because it is in both sources.

I _think_ I would be okay with automatically choosing one as long as a warning is printed every time, telling the user that Bundler had to choose and might have chosen wrong.

**Comment by casperisfine** [comment]
> I _think_ I would be okay with automatically choosing one as long as a warning is printed every time

A warning certainly wouldn't hurt.

**Comment by deivid-rodriguez** [comment]
I totally see your point @indirect.

I have the feeling that normally people use block rubygems sources for private sources, and a global rubygems.org source as a fallback, and when they do that, they want dependencies for gems under the private source block from the private source too, rather than any available resolution using both sources. But this is just a gut-based guess without any real evidence, so let's just ignore it.

Let's go with 1) and 2), and for 3) let's start with a warning and see how it goes from there.

**Comment by casperisfine** [comment]
>  they want dependencies for gems under the private source block from the private source too, rather than any available resolution using both sources. But this is just a gut-based guess without any real evidence

I can confirm that this is exactly the expectation our developers have.

**Comment by indirect** [comment]
Yep, that matches my experience as well—with the catch that private gems often include public gems as dependencies. At that point, you're stuck in the opposite direction, with a private gem in a private source block that can't work until you list all the public dependencies at the top level. 😅

**Comment by deivid-rodriguez** [comment]
Yeah, still _guessing_ how people use this, but I imagine that what's usually done is continuously audit and upload all versions of those indirect dependencies released to rubygems.org to the private source?

**Comment by casperisfine** [comment]
>  At that point, you're stuck in the opposite direction

That's why I'm suggesting it should fallback to the top-level `source`.

>  I imagine that what's usually done is continuously audit and upload all versions of those indirect dependencies released to rubygems.org to the private source?

No what's usually done is that there's generally no conflict between private and public name, so it kinda just works.

**Comment by indirect** [comment]
> I imagine that what's usually done is continuously audit and upload all versions of those indirect dependencies released to rubygems.org to the private source

Hopefully! 😅 In my past experience, that doesn't always happen, and people get angry when those public dependencies don't "just work".

But to be clear, I agree with your plan of doing 1+2, and converting 3 to a warning, and then seeing how things go. 👍🏻

> That's why I'm suggesting it should fallback to the top-level source.

My understanding is that it already does this, today, if a child gem is only present in the default source, and not in the source block of the parent.

**Comment by casperisfine** [comment]
> My understanding is that it already does this, today

No, as explained by Rafael in https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465 it doesn't, and that's the core of our current issue.

**Comment by deivid-rodriguez** [comment]
Right. Ok. I propose we stick to the plan of doing 1+2 and making 3 a warning, and also open a separate ticket about https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465, since I acknowledged that as an issue but had already forgotten about it :sweat_smile:.

**Comment by deivid-rodriguez** [comment]
Just to confirm, the problem in https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465 doesn't work as expect today, and doesn't work with `disable_multisource` either, right?

**Comment by casperisfine** [comment]
> the problem in [#3948 (comment)](https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465) doesn't work as expect today, and doesn't work with `disable_multisource` either, right?

Yes and Yes.
