### ISSUE TITLE
Extraction of the rubygems tar archive fails in a rootless container

### ISSUE THREAD

**Issue by beyhan** [rubygems/rubygems#3977]
Extraction of the rubygems tar archive fails on a rootless container.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other (extracting the rubygems tar)

Here are my current environment details: I tried this with rubygems 3.1.2 and 3.1.4.

Steps to reproduce:
```
// install rootless docker as described in https://docs.docker.com/engine/security/rootless/#install
mkdir /tmp/rubygems-rootless-issue
cd /tmp/rubygems-rootless-issue
wget https://rubygems.org/rubygems/rubygems-3.1.4.tgz
docker run -ti -v "/tmp/rubygems-rootless-issue":"/tmp/rubygems-rootless-issue" ubuntu:bionic /bin/bash
cd /tmp/rubygems-rootless-issue
tar zxvf rubygems-3.1.4.tgz
```
you will get errors like:
```
...
tar: rubygems-3.1.4/bundler/man/bundle-gem.1.txt: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-open.1
tar: rubygems-3.1.4/bundler/man/bundle-open.1: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-remove.1.txt
tar: rubygems-3.1.4/bundler/man/bundle-remove.1.txt: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-add.ronn
tar: rubygems-3.1.4/bundler/man/bundle-add.ronn: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-lock.1.txt
tar: rubygems-3.1.4/bundler/man/bundle-lock.1.txt: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-open.ronn
tar: rubygems-3.1.4/bundler/man/bundle-open.ronn: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-lock.1
tar: rubygems-3.1.4/bundler/man/bundle-lock.1: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-exec.ronn
tar: rubygems-3.1.4/bundler/man/bundle-exec.ronn: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-check.ronn
tar: rubygems-3.1.4/bundler/man/bundle-check.ronn: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
rubygems-3.1.4/bundler/man/bundle-info.1.txt
tar: rubygems-3.1.4/bundler/man/bundle-info.1.txt: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
...
```

Current workaround is to extract the rubygems tar in a rootless container like:
```
tar zxvf rubygems-3.1.4.tgz --no-same-owner
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thanks for the ticket!

Could you replace "start a rootless container" with real steps that anyone can run to start a dummy rootless cointainer?

**Comment by deivid-rodriguez** [comment]
@beyhan Thanks for editing the issue description, looks much better now. I'll try to have a look at this at some point.

**Comment by friegger** [comment]
@deivid-rodriguez Did you have time to look into this? Other archives like the tar of ruby itself don't have this issue, so it seems that adjustments in creating the archive would solve this.

**Comment by deivid-rodriguez** [comment]
Hi! I just looked at it now.

On a "rootless docker" context, `tar` thinks it's being run as root. When that happens, `tar` looks at the original owner & group of each file, and try to give a compatible owner & group to the extracted file.

Let's take a file in the "ruby" package as an example:

```
root@51a65eabc2cc:/tmp/rubygems-rootless-issue $ tar --list --verbose --file ruby-2.7.2.tar ruby-2.7.2/win32/winmain.c
-rw-r--r-- ruby/ruby       184 2020-10-01 14:15 ruby-2.7.2/win32/winmain.c
```

tar knows the original file was owned by a user named "ruby" belonging to a group named "ruby".

With the `--numeric-owner` flag, we can see the original ids of the user and group.

```
root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --list --numeric-owner --verbose --file ruby-2.7.2.tar ruby-2.7.2/win32/winmain.c
-rw-r--r-- 0/0             184 2020-10-01 12:15 ruby-2.7.2/win32/winmain.c
```

That's the standard "root uid", that's why extracting the file gets a root owner & group.

```
root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --extract --file ruby-2.7.2.tar ruby-2.7.2/win32/winmain.c && ls -la ruby-2.7.2/win32/winmain.c
-rw-r--r-- 1 root root 184 Oct  1 12:15 ruby-2.7.2/win32/winmain.c
```

Ok, now with a rubygems package I manually built on my system.

```
root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --list --verbose --file rubygems-3.2.0.rc.2.tar rubygems-3.2.0.rc.2/rubygems-update.gemspec
-rw-rw-r-- deivid/deivid  1822 2020-10-29 11:03 rubygems-3.2.0.rc.2/rubygems-update.gemspec

root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --list --numeric-owner --verbose --file rubygems-3.2.0.rc.2.tar rubygems-3.2.0.rc.2/rubygems-update.gemspec
-rw-rw-r-- 1000/1000      1822 2020-10-29 11:03 rubygems-3.2.0.rc.2/rubygems-update.gemspec

root@51a65eabc2cc:/tmp/rubygems-rootless-issue# ls -la rubygems-3.2.0.rc.2/rubygems-update.gemspec
-rw-rw-r-- 1 1000 1000 1822 Oct 29 11:03 rubygems-3.2.0.rc.2/rubygems-update.gemspec
```

That makes sense. tar assigned the original ownership information to the extracted file, but since there's no user with UID 1000 or group with GUID 1000 in the rootless container, `ls` shows the raw uid/gid.

Now let's look at the official rubygems package

```
# tar --list --verbose --file rubygems-3.1.4.tar rubygems-3.1.4/rubygems-update.gemspec
-rw-r--r-- hsbt/2033490572 1847 2020-06-03 03:39 rubygems-3.1.4/rubygems-update.gemspec

root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --list --numeric-owner --verbose --file rubygems-3.1.4.tar rubygems-3.1.4/rubygems-update.gemspec
-rw-r--r-- 218038053/2033490572 1847 2020-06-03 03:39 rubygems-3.1.4/rubygems-update.gemspec

root@51a65eabc2cc:/tmp/rubygems-rootless-issue# tar --extract --verbose --file rubygems-3.1.4.tar rubygems-3.1.4/rubygems-update.gemspec
rubygems-3.1.4/rubygems-update.gemspec
tar: rubygems-3.1.4/rubygems-update.gemspec: Cannot change ownership to uid 218038053, gid 2033490572: Invalid argument
tar: Exiting with failure status due to previous errors
```

Apparently the system where the package was created had some very high UID/GID values that `tar` doesn't support.

According to [wikipedia](https://en.wikipedia.org/wiki/Group_identifier#Conventions).

> ### Type
> Originally, a signed 16-bit integer was used. Since the sign was not necessary – negative numbers do not make valid group IDs – an unsigned integer is now used instead, allowing group IDs between 0 and 65,535. Modern operating systems usually use unsigned 32-bit integers, which allow for group IDs between 0 and 4,294,967,295. 
> 
> ### Reserved Ranges
>
> (...)
>
> ### Special Values
>   * 0 (...)
>   * -1 (...)
>   * 65,534: The Linux kernel defaults to 216−2 = 65,534 (which many Linux distributions map to the group name "nogroup") when a 32-bit GID does not fit into the return value of a 16-bit system call.[4] The value is also returned by idmapd if a group name in an incoming NFSv4 packet does not match any known group on the system.

Which suggests that @hsbt is using a "Modern non-linux OS" :smile:

As per how to solve this, after reading related info in `man tar`, I think we could probably add `--owner=1000 --group=1000` to our `tar` commands that build the rubygems package to make it more independent from where it's created.

And to workaround, I think you can add `--no-same-owner` to make `tar` skip trying to port the original ownerswhip information to the extracted files.

**Comment by deivid-rodriguez** [comment]
Oh, I see that you already found the `--no-same-user` workaround, I missed that!

Also, regarding changes on our side, I guess setting `--owner=rubygems:0 --group=rubygems:0` might be better since it's what the ruby package includes and it seems to work fine. By the way, `ruby` seems to be generating its `tar.gz` package using `7z` by default.

**Comment by voelzmo** [comment]
Thanks for the detailed analysis, @deivid-rodriguez, this explanation was a pleasure to read!

**Comment by deivid-rodriguez** [comment]
Something else I noticed is that this is rootless docker specific, and doesn't happen if you extract the package as regular root. I guess it's related to the user & group being reported as root inside the container but not being really root in the host file system's eyes :man_shrugging:.

**Comment by beyhan** [comment]
@deivid-rodriguez you are right. This is rootless specific. Here is one explanation, which I think describes the issue very well: https://github.com/containers/buildah/issues/1702#issuecomment-508061453

**Comment by deivid-rodriguez** [comment]
Thanks @beyhan, that's very interesting info indeed :+1:.

**Comment by beyhan** [comment]
Hi @deivid-rodriguez,

what are the plans for this issue? I see that the linked pr is approved yet.

**Comment by deivid-rodriguez** [comment]
I'll merge it now, we might want to do a final rc3 release just to make sure there are no issue with the new package.

**Comment by beyhan** [comment]
ok, thanks!
