### ISSUE TITLE
BUNDLER_VERSION env variable is not documented

### ISSUE THREAD

**Issue by skalee** [rubygems/rubygems#3978]
### Describe the problem as clearly as you can

It appears that `BUNDLER_VERSION` environment variable can be used to force a specific Bundler version, for example:

```bash
$ bundle -v
# => Bundler version 2.1.4
$ env BUNDLER_VERSION=1.17.3 bundle -v
# => Bundler version 1.17.3
```

However, this feature is not described on `bundle-config` page of documentation (see: https://bundler.io/v2.1/bundle_config.html), neither it is mentioned anywhere else AFAIK.

The `BUNDLER_VERSION` environment variable is useful in some niche cases. I use it to switch to Bundler 1.7 in CI when I test my gem against Rails 4.x, which depends on Bundler < 2. (In my case I can probably set `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS` instead, but `BUNDLER_VERSION` sounds like a cleaner idea.)

### Post system independent steps to reproduce the problem

(not relevant)

### Which command did you run?

(not relevant)

### What were you expecting to happen?

(not relevant)

### What actually happened?

(not relevant)

### If not included with the output of your command, run `bundle env` and paste the output below

(not relevant)

**Comment by deivid-rodriguez** [comment]
Hi @skalee. Actually this feature might go away in the near future, so we want to keep it undocument for now. As an alternative, you can use a rubygems feature that does the same thing:

```bash
bundle _1.17.3_ -v
```

Namely, if you specify the version that you want to use surrounded by underscores right after the rubygems binstub that you want to execute, `rubygems` will select that exact version.

I _think_ this feature is undocumented too, but it'd be great to get it documented if it's not.

**Comment by skalee** [comment]
Thank you!

I've opted an environment variable because IMO it's easy to read and straightforward, contrary to variable interpolation in Bash, for example:

```
bundle ${VERSION+_${VERSION}_}
```

which runs Bundler version specified in `VERSION` or, if `VERSION` is unset, the latest Bundler.

That said, I've just noticed that for some reason `BUNDLER_VERSION` has no effect when running Bundler 2.1.4 on Ruby 2.4. Of course Ruby 2.4 reached its end of life, so this is unlikely a big deal. However it makes `BUNDLER_VERSION` less useful than I initially thought, because people who want to force old Bundler versions are likely to do it on some old Rubies.

Regarding my particular case, I've eventually went with `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS`, which works great and requires no Bash tricks.

Please feel free to close this issue if you're not going to document `BUNDLER_VERSION`.

**Comment by deivid-rodriguez** [comment]
No problem!

Actually, even if `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS` is currently documented, I was thinking of removing it because it seems like calling for trouble to me. What the setting does is ignoring some incompatible `bundler` requirement some of the gems you use have set. While it might be an error on that gem's side, it might also be intentional to signal that their dependency doesn't work under some bundler versions (for example, they could be using some bundler APIs programatically or whatever). So, I'm not really comfortable with doing something like that.

So if you can use the `_` trick, I really recommend it. You could for example create a small script that runs the proper version using `_`, keep it in your repository, and always use that to run bundler. Or some similar trick.

**Comment by deivid-rodriguez** [comment]
@skalee For now we won't be documenting `BUNDLER_VERSION`, but I hope you found the alternatives given acceptable :+1:. I'll close this now.

**Comment by skalee** [comment]
Thanks! For now I stick to `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS` which works very well in my particular case. Given my dependency set, I don't expect intended version constraints on Bundler, though in general I agree with your reservations about this variable. If you remove it, I'll just migrate to `_` trick without much hassle.

**Comment by Alexand** [comment]
@deivid-rodriguez 👋 

Is it still the recommendation to not use `BUNDLE_VERSION` to force the bundle version to be used?

I think this environment variable has an advantage against `bundle _VERSION_ -v`, that it's applied globally. Otherwise, I think I'd have to create an alias like `alias bundle="bundle _VERSION_"` to apply to all the commands, right? 🤔 

Or is there yet another recommended approach to guarantee bundle commands will be locked to a certain version?

Thanks in advance for your guidance. 🙇

**Comment by deivid-rodriguez** [comment]
Since this issue was opened, we added a `version` setting that can be set with `bundle config version <system|lockfile|x.y.z>`. Like other settings, this setting is documented and can be set with `BUNDLE_VERSION`. So that should be the recommended way now, and `BUNDLER_VERSION` should probably be deprecated.

Except that I just did some testing and... it's not working 😅. I'll look into that.

**Comment by Alexand** [comment]
> Since this issue was opened, we added a `version` setting that can be set with `bundle config version <system|lockfile|x.y.z>`. Like other settings, this setting is documented and can be set with `BUNDLE_VERSION`. So that should be the recommended way now, and `BUNDLER_VERSION` should probably be deprecated.
> 
> Except that I just did some testing and... it's not working 😅. I'll look into that.

This option looks neat!

`bundle config version system` would fit well for our use case. 👍

**Comment by Alexand** [comment]
@deivid-rodriguez FYI, it seems to be working on my mac. I'll attempt on our CI.

Testing locally:

```sh
$ bundle -v
Bundler version 2.5.17
$ bundle install
Bundler 2.5.17 is running, but your lockfile was generated with 2.5.11. Installing Bundler 2.5.11 and restarting using that version.
^C%
$ bundle config version system
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
```

My local env:

<details><summary>gem env</summary>

```sh
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.19
  - RUBY VERSION: 3.2.4 (2024-04-23 patchlevel 170) [arm64-darwin23]
  - INSTALLATION DIRECTORY: $HOME.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0
  - USER INSTALLATION DIRECTORY: $HOME.gem/ruby/3.2.0
  - RUBY EXECUTABLE: $HOME.asdf/installs/ruby/3.2.4/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: $HOME.asdf/installs/ruby/3.2.4/bin
  - SPEC CACHE DIRECTORY: $HOME.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: $HOME.asdf/installs/ruby/3.2.4/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-23
  - GEM PATHS:
     - $HOME.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0
     - $HOME.gem/ruby/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - $HOME.asdf/installs/ruby/3.2.4/bin
     - $HOME.nvm/versions/node/v20.16.0/bin
     - $HOME.rd/bin
     - $HOMEgoogle-cloud-sdk/bin
     - $HOME.asdf/shims
     - $HOME.asdf/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
 ```
 
 </details>

**Comment by deivid-rodriguez** [comment]
It sounds like I hit some edge case then! Will look into it, but glad to see it's working in general!

**Comment by Whirlwind** [comment]
I test the `BUNDLER_VERSION` in the Bundler version 2.4.x, it not works! But it works in the Bundler version 2.3.x.

I use ruby 2.6, so I can not test the bundler 2.5 and 2.6.
