### ISSUE TITLE
EditorConfig creation option for `bundle gem` command

### ISSUE THREAD

**Issue by ismailarilik** [rubygems/rubygems#4013]
Hi. I am wondering if `bundle gem` command can ask for the creation of an EditorConfig file and creates if the answer is positive. As you know, [EditorConfig](https://editorconfig.org/) is for some common editor configuration and by the time most editors respect it with or without a plugin. As I see, its usage is common and increasing by time. So `bundle init` command may have an option for it. I have researched how to implement it; writing plugin is not an option I think (for this structure, at least). So necessary changes should be in this repo. If you think positive about this change, I can implement it and send you a PR to be reviewed. Thanks, stay healthy!

**Comment by deivid-rodriguez** [comment]
Hi @ismailarilik!

I'm not sure how many people will be interested in an option like this, specially since there's very little code being generated with a new gem skeleton. Also, I haven't seen any adoption of this configuration file in gems out there. I'd rather see some adoption first before adding it to the gem generator. Could you point to me to some gems using this? Also, what rules would you be interested in as defaults?

All that said, I have to say I love `EditorConfig` :)

**Comment by deivid-rodriguez** [comment]
I'll close this now since there was no further feedback and in principle I think this is too much for a `bundle gem` option. But I'm happy to keep discussing on the closed ticket and eventually change my mind :)

**Comment by hsbt** [comment]
> I think this is too much for a `bundle gem` option.

I also use EditorConfig. But I agreed this.
