### ISSUE TITLE
How can I specify the same gem twice in Gemfile?

### ISSUE THREAD

**Issue by marcandre** [rubygems/rubygems#4014]
I specified:
```ruby
# Gemfile:
gem 'rubocop-rspec', '~> 1.0'

# Gemfile.local (loaded by my Gemfile):
gem 'rubocop-rspec', path: '...'
```
But
```sh
$ bundle update

[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile.local`: You cannot specify the same gem twice with different version requirements.
You specified: rubocop-rspec (~> 1.0) and rubocop-rspec (>= 0). Bundler cannot continue.
```

I see no incompatibility here, and I didn't exactly specify a difference version requirements, I specified only one version requirement.

I can get rid of that by repeating `'~> 1.0'` in my `Gemfile.local`, but then I get:

```
There was an error parsing `Gemfile.local`: You cannot specify the same gem twice coming from different sources.
You specified that rubocop-rspec (~> 1.0) should come from an unspecified source and source at `/Users/mal/rubocop-rspec`
```

Again, why would an "unspecified source" and source at `/Users/mal/rubocop-rspec` be considered "different"?

Finally, I know that `bundler` has the capacity to have multiple requirements, because if I move the `gem` statement from the `Gemfile` to the `gemspec` as a `spec.add_development_dependency('rubocop-rspec', '~> 1.0')`, then I don't get any error message.

What am I missing?

(Bundler version 2.1.4)

**Comment by simi** [comment]
This is not possible since there will be no way to provide predictable lockfile AFAIK. I do recommend to modify Gemfile temporarily to use local git path for development. Also there is option to override git remote in local setup, but if I understand it well, it doesn't work with non-git soruces. https://bundler.io/v2.4/man/bundle-config.1.html#LOCAL-GIT-REPOS

The exception you have mentioned is implemented at: https://github.com/rubygems/rubygems/blob/98dbafa827ad9028a6f8aa0951abe5e8744f7bfc/bundler/lib/bundler/dsl.rb#L103-L105.

Considering the outcome and also non-activity for long time in this issue, I'm going to close this. Feel free to ping back to reopen if you think it still makes sense.

**Comment by simi** [comment]
@HoneyryderChuck I think for your usecase you should off-board rails to individual sub-gemfiles or use some advanced tool like Appraisal.
