### ISSUE TITLE
Bundle run within rake in subdirectory calculating relative path from directory where rake is called.

### ISSUE THREAD

**Issue by justin808** [rubygems/rubygems#4074]
### Describe the problem as clearly as you can

There seems to be a problem with rake setting some global variable that is picked up by the bundle command.

Is there any such global for the bundle command? Can it be changed temporarily and then reset?

I'm using a relative path for the gem, per example at https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/Gemfile#L7

in spec/dummy/Gemfile:
```ruby
gem "react_on_rails", path: "../.."
```

When I release a new version, I want to make sure that `bundle` has run in directory spec/dummy so that the Gemfile.lock reflects the new version. I don't want running bundle in that directory to cause the Gemfile.lock to change just because of a new release.

However, all my attempts to run bundle from with rake result in the Gemfile.lock not changing. But when I run bundle directly in the shell, the Gemfile.lock changes.

Within rake task, this command runs:
```
 cd /Users/justin/shakacode/react-on-rails/react_on_rails_pro/spec/loadable && bundle install
```
And this is logged:
```
Using react_on_rails_pro 1.5.6.beta.9 from source at `.`
```

Running from shell:

```
cd /Users/justin/shakacode/react-on-rails/react_on_rails_pro/spec/loadable && bundle install
```

Then this is logged:
```
Using react_on_rails_pro 1.5.6.beta.9 (was 1.5.6.beta.8) from source at `../..`
```

Notice that the shell running seems to recognize the property relative path.

When run from rake, the relative path is calculated relative the path that rake is run **and not the path relative when cd'ing in the shell command**

See the release.rake file changes:

https://github.com/shakacode/react_on_rails/pull/1341/files#diff-1e28be9fbab9e305fe4d9e1bbdfeca0bbe325cb72a926b17f464f745dc8d8cc4R57
 
My only fix is to log what should be run at the command line.

```ruby
  msg = <<~MSG
    Once you have successfully published, run these two commands to update the spec apps:
    cd #{dummy_app_dir}; bundle update react_on_rails
    cd #{gem_root}#{' '}
    git commit -a -m 'Update Gemfile.lock for spec app'
    git push
  MSG
  puts msg
```

### Post steps to reproduce the problem

I tried many different approaches to work around the issue. None worked.

### Which command did you run?

`bundle`
`bundle update react_on_rails`

Both had the same effect.

### What were you expecting to happen?

Running from the shell vs running from a rake task two directories up should result in the same effect.

### What actually happened?

Bundler is confused regarding the path.

### If not included with the output of your command, run `bundle env` and paste the output below

```
# Environment

```
Bundler             2.1.4
  Platforms         ruby, x86_64-darwin-19
Ruby                2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin19]
  Full Path         /Users/justin/.rvm/rubies/ruby-2.7.2/bin/ruby
  Config Dir        /Users/justin/.rvm/rubies/ruby-2.7.2/etc
RubyGems            3.1.4
  Gem Home          /Users/justin/.rvm/gems/ruby-2.7.2@rails6
  Gem Path          /Users/justin/.rvm/gems/ruby-2.7.2@rails6:/Users/justin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home         /Users/justin
  User Path         /Users/justin/.gem/ruby/2.7.0
  Bin Dir           /Users/justin/.rvm/gems/ruby-2.7.2@rails6/bin
Tools
  Git               2.29.2
  RVM               1.29.10 (latest)
  rbenv             not installed
  chruby            Loading .zshrc
  rubygems-bundler  (1.4.5)
```

**Comment by justin808** [comment]
If the relative path is used, why does the Gemfile.lock store the version number? How is that relevant?

**Comment by deivid-rodriguez** [comment]
Hi @justin808!

I assume you're running your release tasks in a bundler context (with `bundle exec`) and from the root directory of your repository, correct? And then inside the `rake` task you invoke all those `cd` and subcommands.

If this is the case, I believe you need to wrap your commands with a `Bundle.with_original_env` block. By default `bundler` saves its own environment in environment variables, and we you shell out from inside a `bundle exec` context, the previous environment is inherited by the new process. So, the external `bundle exec` command will save the root `Gemfile` in the `BUNDLE_GEMFILE` environment variable, and when your internal ` cd /Users/justin/shakacode/react-on-rails/react_on_rails_pro/spec/loadable && bundle install` command runs, it picks up the Gemfile from the `BUNDLE_GEMFILE` environment variable previously saved instead of resolving it from the CWD.

This is some historical behaviour that we can't really change, at least not in a minor version, but I always have the feeling that this "environment inheritance" thing should be opt-in, not opt-out, because it causes more confusion than benefits.

Anyways, I hope this helps you.

**Comment by deivid-rodriguez** [comment]
I'll close this since there hasn't been any recent feedback here, but let me know if you run into issues when you get to it.
