### ISSUE TITLE
Deployment to AWS Lambda - clarifications and recommendations

### ISSUE THREAD

**Issue by brandonhilkert** [rubygems/rubygems#4176]
First off, thank you for `bundler` and thank you for aiding the terrific ecosystem it helps make a Ruby a joy to work with.

We have a handful of functions deployed to AWS Lambda. We deploy to them using the serverless framework (not super important, but it's the thing doing the zipping of all the packages and uploading to S3). Because Lambda doesn't have a "build" step, everything has to be ready to go when the function runs. 

We use CircleCI for CI/CD and our deployment step does the following:

```
bundle install --path vendor/bundle
```

In our function, we then require dependencies at the top and everything works great:

```ruby
require 'json'
require 'base64'
require 'singleton'

require 'aws-sdk-dynamodb'
```

One of our functions now depends on a private gem in our Github org named `muzzle` that's referenced via the following line in `Gemfile:
```
gem "muzzle", git: "git@github.com:[GH ORG]/muzzle.git"
```

The CI user can bundle it, but when I look at the `vendor/bundle`, I see the following tree (I've removed the unexciting bits):

```
vendor/
└── bundle
    └── ruby
        └── 2.7.0
            ├── bin
            │   ├── dotenv
            │   ├── httparty
            │   ├── rackup
            │   ├── rake
            │   ├── sidekiq
            │   └── sidekiqmon
            ├── build_info
            ├── bundler
            │   └── gems
            │       └── muzzle-325f470ea758
            │           ├── [gem contents]
            ├── cache
            │   ├── activesupport-6.0.3.4.gem
            │   ├── addressable-2.7.0.gem
            │   ├── aws-eventstream-1.0.3.gem
            │   ├── aws-partitions-1.278.0.gem
            │   ├── aws-sdk-core-3.90.1.gem
            │   ├── aws-sdk-dynamodb-1.43.0.gem
            │   ├── aws-sdk-firehose-1.25.0.gem
            │   ├── aws-sdk-kinesis-1.20.0.gem
            │   ├── aws-sdk-kms-1.30.0.gem
            │   ├── aws-sdk-s3-1.61.1.gem
            │   ├── aws-sdk-sqs-1.26.0.gem
            │   ├── aws-sigv4-1.1.1.gem
            │   ├── bundler
            │   │   └── git
            │   │       └── muzzle-428facdd2dddb1bb68f1b5e36e09232e3d124f96
            │   │           ├── HEAD
            │   │           ├── config
            │   │           ├── description
            │   │           ├── hooks
            │   │           ├── info
            │   │           │   └── exclude
            │   │           ├── objects
            │   │           │   ├── info
            │   │           │   └── pack
            │   │           │       ├── pack-63c2bc0e4ffcdfc7c7a4e14837fdb171f29a9496.idx
            │   │           │       └── pack-63c2bc0e4ffcdfc7c7a4e14837fdb171f29a9496.pack
            │   │           ├── packed-refs
            │   │           └── refs
            │   │               ├── heads
            │   │               └── tags
            │   ├── concurrent-ruby-1.1.7.gem
            │   ├── connection_pool-2.2.3.gem
            │   ├── dotenv-2.7.5.gem
            │   ├── httparty-0.18.0.gem
            │   ├── i18n-1.8.5.gem
            │   ├── jmespath-1.4.0.gem
            │   ├── jwt-2.2.2.gem
            │   ├── mime-types-3.3.1.gem
            │   ├── mime-types-data-3.2019.1009.gem
            │   ├── minitest-5.14.2.gem
            │   ├── multi_xml-0.6.0.gem
            │   ├── public_suffix-4.0.6.gem
            │   ├── rack-2.2.2.gem
            │   ├── rack-protection-2.0.8.1.gem
            │   ├── rake-13.0.1.gem
            │   ├── redis-4.2.2.gem
            │   ├── sidekiq-6.0.6.gem
            │   ├── statsd-ruby-1.4.0.gem
            │   ├── thread_safe-0.3.6.gem
            │   ├── tod-2.2.0.gem
            │   ├── tzinfo-1.2.8.gem
            │   └── zeitwerk-2.4.1.gem
```

In the function that needs `muzzle`, I try to `require 'muzzle'` and it blows up during execution b/c it can't find `muzzle`:

```

@ingestionTime | 1608404535612
-- | --
@log | 520245715689:/aws/lambda/bark-screentime-sls-prod-domainCategorize
@logStream | 2020/12/19/[$LATEST]6dd33f191eec474e8acf8e8137ddec10
@message | {  "errorMessage": "cannot load such file -- muzzle",  "errorType": "Init<LoadError>",  "stackTrace": [    "/var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'",    "/var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'",    "/var/task/domain_categorize.rb:7:in `<top (required)>'",    "/var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'",    "/var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'"  ]}
@timestamp | 1608404535429
errorMessage | cannot load such file -- muzzle
errorType | Init<LoadError>
stackTrace.0 | /var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
stackTrace.1 | /var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
stackTrace.2 | /var/task/domain_categorize.rb:7:in `<top (required)>'
stackTrace.3 | /var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
stackTrace.4 | /var/lang/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

After some experimentation, I settled on doing the following prior to requiring anything:

```ruby
require "rubygems"
require "bundler/setup"
```

That seemed to fix the loading of `muzzle` for that function so then I moved on.

A few nights ago, this function started throwing a bunch of errors (after running successfully for months) on one container (out of maybe 20). As I dug in, I found the following error:

```

@ingestionTime | 1608269949926
-- | --
@log | 520245715689:/aws/lambda/bark-urls-sls-prod-urls
@logStream | 2020/12/18/[$LATEST]a7000a1473274e08be7b9544f1cf8c6a
@message | {   "errorMessage": "There was an error accessing  `/var/task/Gemfile.lock`.\nThe underlying system error is Errno::EROFS:  Read-only file system @ rb_sysopen - /var/task/Gemfile.lock",  "errorType": "Init<Bundler::GenericSystemCallError>",  "stackTrace": [    "/var/runtime/gems/bundler-2.2.0/lib/bundler/shared_helpers.rb:117:in `rescue in filesystem_access'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/shared_helpers.rb:102:in `filesystem_access'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/definition.rb:363:in `lock'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/runtime.rb:104:in `lock'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/runtime.rb:41:in `setup'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler.rb:149:in `setup'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `block in <top (required)>'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:136:in `with_level'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:88:in `silence'",    "/var/runtime/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `<top (required)>'",    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",    "/var/task/urls.rb:2:in `<top (required)>'",    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"  ]}
@timestamp | 1608269949856
errorMessage | There was an error accessing `/var/task/Gemfile.lock`.The underlying system error is Errno::EROFS: Read-only file system @ rb_sysopen - /var/task/Gemfile.lock
errorType | Init<Bundler::GenericSystemCallError>
stackTrace.0 | /var/runtime/gems/bundler-2.2.0/lib/bundler/shared_helpers.rb:117:in `rescue in filesystem_access'
stackTrace.1 | /var/runtime/gems/bundler-2.2.0/lib/bundler/shared_helpers.rb:102:in `filesystem_access'
stackTrace.2 | /var/runtime/gems/bundler-2.2.0/lib/bundler/definition.rb:363:in `lock'
stackTrace.3 | /var/runtime/gems/bundler-2.2.0/lib/bundler/runtime.rb:104:in `lock'
stackTrace.4 | /var/runtime/gems/bundler-2.2.0/lib/bundler/runtime.rb:41:in `setup'
stackTrace.5 | /var/runtime/gems/bundler-2.2.0/lib/bundler.rb:149:in `setup'
stackTrace.6 | /var/runtime/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `block in <top (required)>'
stackTrace.7 | /var/runtime/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:136:in `with_level'
stackTrace.8 | /var/runtime/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:88:in `silence'
stackTrace.9 | /var/runtime/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `<top (required)>'
stackTrace.10 | /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
stackTrace.11 | /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
stackTrace.12 | /var/task/urls.rb:2:in `<top (required)>'
stackTrace.13 | /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
stackTrace.14 | /var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
```

The important part being:
> There was an error accessing  `/var/task/Gemfile.lock`.\nThe underlying system error is Errno::EROFS:  Read-only file system @ rb_sysopen - /var/task/Gemfile.lock

This threw me off. First off, it's read-only, which seems reasonable that it'd be allowed to read it, but I don't know the details of the containers file system to make anything more than assumptions. Since this occurred on a small percentage of requests (~2%), not 100% it felt like an infrastructure thing, so I submitted a support case and recently got the following response after it was escalated:

```
Looks like if the ruby code has "require 'bundler/setup'" then this will try to open "/var/task/Gemfile.lock" file and as you already know /var/task is a read-only directory.

Please note that "require 'bundler/setup" is not required while running your ruby code in the Lambda environment and it's necessary only when you are running this on a local machine.

Further, during a test replication when the require 'bundler/setup was removed from the ruby code and run in the Lambda environment, it did not create any file under "/var/task" and the execution was completed as expected.
```

Seemed like an easy fix, but then I remembered the issue around requiring a private gem that doesn't get cached similarly while using the `--path` argument during `bundle install`.

So a few questions...

1. Is there any scenario that you can think of that would cause `require 'bundler/setup'` to attempt to write a Gemfile.lock? Because only a small percentage of requests were failing, I want to better understand if this was the real reason or there was another underlying infrastructure issue that's a better explanation.

2. It seems using the `--path` argument (or equivalent config) doesn't include private gems in the load path like it does with public gems. Is there a non-manual way to do this without adding specific `require` lines for the directory cached in `vendor/bundle`?

3. Can you recommend a way to include private gems in a simple function for deployment to AWS that might not need `require 'bundler/setup'` if it's not above?

Thanks again for all the great work and the potential help!

**Comment by deivid-rodriguez** [comment]
Hi @brandonhilkert, thanks for the ticket, and sorry for the issues :pray:.

I think this is similar to other issues the recent 2.2.0 release has caused. I'm currently working on smoothing out those issues, so this might get fixed in the next patch level releases. In any case, I'll try to answer your questions so you can get this fixed now on your side.

> Is there any scenario that you can think of that would cause require 'bundler/setup' to attempt to write a Gemfile.lock? Because only a small percentage of requests were failing, I want to better understand if this was the real reason or there was another underlying infrastructure issue that's a better explanation.

Yes, the reason for your problem is most likely the new version of bundler generating slight changes in the `Gemfile.lock` file and rewriting it. This is something `bundler/setup` does, yeah. Normally if the bundle is valid, the lockfile won't change and requiring `bundler/setup` won't change the lockfile. However, in this version we shipped a change where a small difference will be written to the lockfile, causing your issue. Regardless of any changes we make that might help with this, the permanent fix for your issue would be to regenerate the lockfile and commit the slight change in the lockfile, so that requiring `bundler/setup` won't generate any changes.

Something I don't quite understand is that these differences in the lockfile should have been created by `bundle install` already by the `bundle install` deployment step, not at boot time. I guess it's related to the way you deploy the code (you deploy you app's code _before_ `bundle install_`), and explains why you only get it on some containers.

> It seems using the --path argument (or equivalent config) doesn't include private gems in the load path like it does with public gems. Is there a non-manual way to do this without adding specific require lines for the directory cached in vendor/bundle?

I'm not aware of any problems related to this, it might be a problem in bundler I'm not aware of :man_shrugging:. Note that to make your dependencies available, requiring `bundler/setup` is always needed. You might need to do it by hand like in your case, although running a command through `bundle exec` will do it automatically. Oh, and also note that `bundle install --path vendor/bundle` is deprecated. You should configure the path first, with `bundle config set --local path vendor/bundle`, and then run `bundle install` without any flags. Not sure if this is something you're running in your configuration or something `CircleCI` does under the hood?

> Can you recommend a way to include private gems in a simple function for deployment to AWS that might not need require 'bundler/setup' if it's not above?

I think requring `bundler/setup` is correct that make your dependencies available like a explained above.

So, to sum up, try the workaround of regenerating the lockfile and committing the result back. Note that you need to regenerate it in the same platform CircleCI is running. If you don't have local access to such platform, say you're running MacOS locally and Linux on CircleCI, you can also run `bundle lock --add-platform x86_64-linux` from your local machine. Actually, since you might have no idea of the exact platform CircleCI is running, you can print the lockfile inside the CircleCI deployment step, right after `bundle install`, and you should see the specific platform:

```
- bundle install --path vendor/bundle
- cat Gemfile.lock
```

That should print the platform you need to add to your lockfile.

Anyways, let me know how it goes, I'll also keep you posted of any changes we make in our side to alleviate this.

**Comment by brandonhilkert** [comment]
Hey @deivid-rodriguez. Thanks so much for the thoughtful, I appreciate it.

I dug in a little more today and here is some more information and things I've learned. We use CircleCI's ruby 2.7 image. Since it's public, we can inspect the bundler version there:

```
$ docker run -it --rm circleci/ruby:2.7 bash
circleci@0a97702bccf0:/$ bundler -v
Bundler version 2.1.4
```

This matches our working version locally. What I'm not sure of is the bundler version in the container runtime of AWS Lambda.

I think what gets me is this error was only on 2% of the requests. That makes me feel like it's related to the infrastructure and not with the code. I don't know the details of their underlying platform, so it's really hard to say if we caught an in between on some changes they were making. I haven't seen the error since then.

I tested a new function and tried to better understand what was needed if we didn't include `require 'bundler/setup'`. After some experimenting, I found that I could avoid the inclusion of that requirement if I:

1. Copied the source code of the bundled gem from github from `vendor/bundle/ruby/2.7.0/bundler/gems/muzzle-325f470ea758` to `vendor/bundle/ruby/2.7.0/gems/muzzle-0.2.5/`
2. Copied the `gemspec` from `vendor/bundle/ruby/2.7.0/bundler/gems/muzzle-325f470ea758/muzzle.gemspec` to `vendor/bundle/ruby/2.7.0/specifications/muzzle-0.2.5.gemspec`

Those steps allowed me to remove `require 'bundler/setup`` and let `require 'muzzle'` work without any other modifications.

All other publicly available gems worked just fine without `require 'bundler/setup'`. It seems to me this more an issue about bundling gems straight from github rather than a gzipped package from rubygems.

Do I have all that right?

**Comment by deivid-rodriguez** [comment]
Regarding your errors about writing to the lockfile, they should be gone after we release #4179 and the container runtime of AWS lambda upgrades. It seems that you're no longer seeing them, but just in case.

Regarding your findings about the need of `bundler/setup`, well that explains things indeed. It sounds like the `GEM_PATH` environment variable in your container might be set to `<whatever_the_beggining_of_the_path_is>/vendor/bundle/ruby/2.7.0/`. That means that plain `rubygems` (without bundler) is able to find your gems when you require them automatically as long as they live in that path. Rubygems doesn't know about gems from git sources, that's why you need to do that hacky copying to avoid requiring `bundler/setup`.

In any case, my recommendation would be that you stick to requiring `bundler/setup`, since it's what's officially supported when you use a `Gemfile`.

**Comment by brandonhilkert** [comment]
Got it. Thanks for the info. I learned something today 👍
