### ISSUE TITLE
multiple default bundler

### ISSUE THREAD

**Issue by jzhao2004** [rubygems/rubygems#4227]
Hello All:
i have issue for default bundler

gem list | grep "bundle"

bundler (default: 2.1.4, default: 2.1.2, default: 1.17.3)

Thank you

Joseph

**Comment by deivid-rodriguez** [comment]
Hi @jzhao2004!

I'm not sure the specific issues this is causing for you, although I agree it's weird.

It sounds like you used the `--default` flag of `gem install` at some point, which messed things up.

We should probably get rid of this flag without deprecation, since it doesn't really work as expected. It only installs a default gemspec in the default gemspecs folder, but it doesn't install any actual code! :grimacing:

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
