### ISSUE TITLE
Template for github actions recommendations

### ISSUE THREAD

**Issue by marcandre** [rubygems/rubygems#4230]
1)
```
with:
        ruby-version: 3.0.0
```

Should be using a matrix, even if you only want a single version, as it makes it easier to add versions.
Morevover, I feel that just the current stable ruby version is not the best default. My recommendation would be current and two preceding, but I leave that up to the maintainers.
More importantly, I believe that `ruby-head` should be there by default. This encourages people to report issues they might encounter with Ruby as it gets developed, provide valuable feedback on an upcoming incompatibilities, or simply prepare their code for the next version.

2)
```
# replace
on: [push,pull_request]
# with
on:
  push:
    branches:
    - master
  pull_request:
```

Otherwise, CI runs twice, once when the branch is pushed, and once when the PR is created. `master` should be replaced by whatever the default main branch in the git config.

See https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662

**Comment by deivid-rodriguez** [comment]
Improvements suggested where mostly implemented as #4619, except for adding `ruby-head` and a matrix of supported rubies in general.

That change, while it fits the workflow of some gem creators, I don't think it will be an improvement for everyone. Someone creating a small gem to learn ruby, or a quick proof of concept for some idea might want to have a CI that gives quick feedback, but won't necessarily want a full matrix of supported rubies plus having to deal with `ruby-head`. And even those who want to support  several rubies might want to support different things, like current and previous ruby, all non-EOL'd rubies, or other combinations.

So, I think it would be best to make this configurable, so that gem authors can choose the range of rubies they want to support in their new gems. For example, as `bundler config gem.supported_rubies 2.7:3.0:head` or something like that.
