### ISSUE TITLE
I got this error after this command: rails new railstest. 

### ISSUE THREAD

**Issue by theblindguidedog** [rubygems/rubygems#4369]
The system asked me to start a new issue.
[error_report.txt](https://github.com/rubygems/rubygems/files/5963304/error_report.txt)

**Comment by deivid-rodriguez** [comment]
Hi @theblindguidedog, sorry for the delay.

We have fixed some race conditions lately in `bundle install`. Please upgrade bundler to the latest version and if you can still reproduce this, open another ticket. Make sure you copy the error directly into the report instead of attaching a file, it's easier for us.

Thanks!
