### ISSUE TITLE
Adding `bin/console` binstub for existing gems

### ISSUE THREAD

**Issue by jacobat** [rubygems/rubygems#4402]
I am the maintainer of a gem. When I run `bundle console` I get a deprecation warning:
```
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
```

Given that this is an existing gem I have no easy way to run this command for the gem. It would be nice to have something like the `bundle binstubs` command to generate the console command for an existing command.

**Comment by duckinator** [comment]
I agree, it'd be nice to have a command to (re)generate binstubs. I've had a few cases where I basically 

I'm not sure what the best approach would be for the command syntax itself, but I figured I'd get together some relevant information.

**Relevant parts of the codebase:**

It looks like, atm, all of the code related to binstubs is in [`bundler/lib/bundler/cli/gem.rb`](https://github.com/rubygems/rubygems/blob/81ea035/bundler/lib/bundler/cli/gem.rb). That code is for the `bundle gem` command.

The templates for binstubs are in [`bundler/lib/bundler/templates/newgem/bin/`](https://github.com/rubygems/rubygems/tree/81ea035/bundler/lib/bundler/templates/newgem/bin).

**Workaround:**

The existing template for `bin/console` can be found in [`bundler/lib/bundler/templates/newgem/bin/console.tt`](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/templates/newgem/bin/console.tt).

Until a command to automate this exists, you can copy that file to `bin/console` and replace `require "<%= config[:namespaced_path] %>"` with the code needed to load your gem.

**Comment by deivid-rodriguez** [comment]
You can't right now, we're proposing to make `bundle binstubs` capable of doing that. Maybe with an additional flag? `bundle binstubs --console`?

**Comment by jacobat** [comment]
From the help page for binstubs:

> Binstubs are a shortcut-or alternative- to always using bundle exec.

So console doesn’t appear to fit as a binstub. Options could be:

- "bundle gem —binaries” as bin/console is already generated by that
command.
- “bundle console —generate”. I’m not sure what the reasoning was for
removing "bundle console” so don’t know if this is even an option.

This is really an edge case so it probably doesn’t matter too much which
option is chosen.

**Comment by olivierlacan** [comment]
What's strange to me about this deprecation is that `bundle console` is something I use to load bundle gems in a local console for a Ruby app without having to require Gemfile gems manually. Having to generate a bin/console for this is a bit odd and not a very good experience for Ruby newcomers. 

In other words, this deprecation makes no sense to me. And I don't see how it's helpful to folks building Ruby apps using Bundler, not not building gems themselves. 

I don't think asking people to generate binstubs is a reasonable expectation.

@deivid-rodriguez was the deprecation done because of issues/concerns about having an specific version of Bundler installed which would somehow collide with Gemfile-resolved gems?

**Comment by deivid-rodriguez** [comment]
As I said in my message just before, my recollection is that the deprecation happened because people kept asking for new features to be added to `bundle console`, and the Bundler team did not want to maintain that. I think if you search issues/commit history in [the old repo](https://github.com/rubygems/bundler) you may find something more specific.

**Comment by simi** [comment]
:thinking: I'm big fan of simple `bundle console` as well for cases where `bin/console` doesn't make sense.

**Comment by deivid-rodriguez** [comment]
To be clear, I didn't say that I'm against removing this deprecation, I'm just trying to explain what's my recollection about the reasons for deprecating it at the time, which again happened a long time ago before I was even a maintainer and may not be relevant anymore, or not good reasons for deprecating `bundle console`. Someone needs to check.

**Comment by jeromedalbert** [comment]
🕵️ I dug up the history:

- Initial issue in the old repo: https://github.com/rubygems/bundler/issues/4025. Also relevant: commit https://github.com/rubygems/bundler/commit/748d8ec27db1722e0880c9c4aed50c4bca78a77f.
- Commit that introduced the deprecation message: https://github.com/rubygems/bundler/pull/4028
- PR that moved the console command behind a `console_command?` feature flag: https://github.com/rubygems/bundler/pull/5793
- Commit that used the `bundler_3_mode?` feature flag instead of `console_command?`: https://github.com/rubygems/rubygems/commit/9f52ebfc9

To summarize, the reason for deprecation was laid out by @indirect in this [comment](https://github.com/rubygems/bundler/issues/4025#issuecomment-144857503):

> The console command has gotten many, many pull requests for different kinds of customization and so we eventually realized that an editable bin/console is the only way to provide that level of customization.

and this [commit message](https://github.com/rubygems/bundler/commit/748d8ec27db1722e0880c9c4aed50c4bca78a77f):

> Rather than adding .consolerc and seeing the surface area of things that Bundler supports continue to grow endlessly, Bundler 2.0 will deprecate the `bundle console` command, and instead add a script to each generated gem that loads `bundler/setup` and then loads the gem. Anyone can then edit that file to run the REPL they want, load the fixtures they want, and everything else, without anything specific to Bundler at all.

**Comment by jeromedalbert** [comment]
@indirect Can you confirm this deprecation is still relevant?

I don't have a dog in this fight as I didn't know until `bundle console` until I read this issue 🙈, but it seems that olivierlacan and simi have highlighted a use case where `bundle console` could still be useful.

Namely when you need quick access to the console for some random gem that doesn't have `bin/console` — maybe it's not even your gem — and you don't want to bother (or you don't even know about) doing `bundle exec irb` followed by `Bundler.require`.

**Comment by indirect** [comment]
I'm not totally sure what the advantage of keeping `bundle console` is vs running `bundle exec irb`, but I'm fine with leaving it if it's useful for some users.

**Comment by deivid-rodriguez** [comment]
I agree with @indirect that `bundle console` does not bring anything over `bundle exec irb` other than saving a few characters.

That said, I think `bundle console` provides a nice home for a new flag to generate a `bin/console` file for further customization, so I'd propose to:

* Cancel `bundle console` deprecation.
* Add `bundle console --generate` or `bundle console --customize` or something like that to add a `bin/console` file to an existing gem.

**Comment by jeromedalbert** [comment]
When you mention saving a few characters, are you talking about saving the 15 characters needed to type `Bundler.require` once you've typed `bundle exec irb`?

If so, it is indeed only a few a few characters which doesn't seem that important, but users might not be aware that they need to type `Bundler.require` to have full access to gems from the Gemfile, whereas `bundle console` does that for you. Or is that convenience not considered that important?

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez When you mention saving a few characters, are you talking about saving the 15 characters needed to type Bundler.require once you've typed bundle exec irb?

Nope, I missed that `bundle console` also runs `Bundler.require` under the hood. I assume it didn't because `bin/console` only setup the `$LOAD_PATH`, requires the gem, and starts `irb`. So that means `bin/console` is not really a replacement of `bundle console`.

Given that, I think it's enough to cancel the deprecation of `bundle console` and move on.

**Comment by simi** [comment]
> Given that, I think it's enough to cancel the deprecation of bundle console and move on.

Yeeeeees! 🙏

**Comment by Earlopain** [comment]
How does this play into ruby wanting to make irb a bundled gem with 3.5? https://bugs.ruby-lang.org/issues/20309
Will rubygems vendor irb, or will I be expected to add `irb` to all my gemfiles. I am already getting a warning on 3.4-dev about this.

```sh
$ bundle console
irb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add irb to your Gemfile or gemspec to silence this warning.
rdoc was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add rdoc to your Gemfile or gemspec to silence this warning.
```

**Comment by deivid-rodriguez** [comment]
Good point.

I thought @hsbt had added some hacks so that the warning does not trigger for irb, and so that `irb` it's still loaded from system gems even if not in the Gemfile. But apparently that's not working, or I misunderstood?

I personally think `irb` should not be moved to a bundled gem without a better solution for this.

**Comment by deivid-rodriguez** [comment]
@hsbt I just saw that you reverted the hack for irb at https://github.com/ruby/ruby/commit/38b07a7feee2afb229882f270af1947273f13a2f. Would it be possible to delay irb extraction to a bundled gem to Ruby 3.5. That would give us time to implement proper features in Bundler to satisfy the requirements (irb can be removed from your Ruby installation, irb can be upgraded as a gem, `binding.irb` can be used normally just by having `irb` globally installed, without having it included in your Gemfile).

**Comment by hsbt** [comment]
>Would it be possible to delay irb extraction to a bundled gem to Ruby 3.5

My existence plan is that.

* Ruby 3.4: Warning for irb extraction.
* Ruby 3.5: Extract irb as bundled gems.

We can consider that in next year.

**Comment by deivid-rodriguez** [comment]
Yeah, sorry, I was asking if it would be possible to delay the warning to 3.5? My concern is that people is going to be annoyed by having to add `irb` to their `Gemfile`, and we should prevent that particularly if the future plan is to make that not necessary.

**Comment by deivid-rodriguez** [comment]
Thanks for sharing the conclusion.

My opinion is that it's quite confusing to ask people in Ruby 3.4 to add `irb` to their Gemfiles, and then make that unnecessary in Ruby 3.5.

A warning should make users aware of future breakage, and recommend a better, preferred practice. But my understanding is that ruby-core team has no breakage in mind, nor thinks it's a best practice to add `irb` to your Gemfile if you just want to use `binding.irb` sometimes. So why the warning?

I understand that the decision is made, but wanted to share my thoughts around this anyways.

**Comment by Earlopain** [comment]
What about `bundle console` or `bundle exec irb`? I find it excessive to be asked to add irb to my gemfile when all I want is a console with the loadpath correctly set up. Per this comment, this is what I am supposed do https://github.com/ruby/irb/pull/999#issuecomment-2331308387

**Comment by deivid-rodriguez** [comment]
This warning triggers when `irb` is used in a Bundler context but `irb` is not part of the Gemfile, and both `bundle console` and `bundle exec irb` are bundler contexts. I agree this is excessive in the current situation, and I'd like more time to properly figure out how to support it in Bundler. But this decision was made by ruby-core, and @hsbt is also a Bundler maintainer, so I don't there's much that we can do about it. What is it exactly that you are asking for?

**Comment by deivid-rodriguez** [comment]
It sounds pretty tricky though since we have never vendored a gem with executables, and I'm unsure how it would work. I don't think there's time to explore that before Ruby 3.4.
