### ISSUE TITLE
Redact private data from `bundle env` output

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4414]
### Describe the problem as clearly as you can

As per https://github.com/rubygems/rubygems/pull/4359, Our issue templates tells users to copy the output of `bundle env` without remembering them to anonymize any private data before doing so.

Ideally we should anonymize any private data included in `bundle env` output by default, but since that might be tricky, we should at least add a note about it to the template.

**Comment by aaronjensen** [comment]
Just a note: even if you succeed in redacting data (which, I would think would just be a matter of only emitting bundle configuration for named/hard-coded configuration options, which should not include credentials), you should still encourage anonymizing the data because you cannot force people to upgrade and there are already old versions in the wild that emit private data.

**Comment by deivid-rodriguez** [comment]
Sure, I just added a note about this at #4416.

**Comment by deivid-rodriguez** [comment]
#4566 should fix this!
