### ISSUE TITLE
Unable to install from multi-source lock file generated by 2.2.14

### ISSUE THREAD

**Issue by stevenharman** [rubygems/rubygems#4452]
Thank you all for the endless hours and effort you put into Bundler and RubyGems! ❤️ 

### Describe the problem as clearly as you can

We have multiple `source`s in our `Gemfile` - rubygems and a private gem server. When generating with Bundler 2.2.14 the `Gemfile.lock` has multiple `GEM` sections, one for each of the two `source` declared in the `Gemfile`. This is as expected.

However, when trying to `bundle install` for deployment with an older Bundler (`2.2.11`, for example), an error is raised. This happens in practice when deploying to Heroku, for example, because the `heroku/ruby` build pack uses Bundler 2.2.11.

### Post steps to reproduce the problem

Here is a minimal example to reproduce. For this, I've set up an empty Gem named [`sekret_lib` as a public package on Gem Fury](https://gemfury.com/stevenharman/ruby:sekret_lib). 

1. Be sure you have Bundler 2.2.11 and 2.2.14:

```console
gem install bundler --version 2.2.11
gem install bundler --version 2.2.14
```

2. Starting with the following `Gemfile`:

```ruby
source "https://rubygems.org"

ruby "2.7.2"

gem "dumb_delegator"

source "https://gem.fury.io/stevenharman/" do
  gem "sekret_lib"
end
```

3. Then generate the `Gemfile.lock` with 2.2.14

```console
bundle _2.2.14_ install
```

4. At which point the `Gemfile.lock` looks like this:

```ruby
GEM
  remote: https://gem.fury.io/stevenharman/
  specs:
    sekret_lib (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    dumb_delegator (1.0.0)

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  dumb_delegator
  sekret_lib!

RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.2.14
```

### Which command did you run?

Try to install the gems for deployment using Bundler 2.2.11.

```console
BUNDLE_DEPLOYMENT=1 bundle _2.2.11_ install
```

### What were you expecting to happen?

I expected this to install the gems into `vendor/bundle`. Installing with 2.2.14 does just that, as expected.

### What actually happened?

Bundler reported a warning (as expected) and an error to the console:

```
Warning: the running version of Bundler (2.2.11) is older than the version that created the lockfile (2.2.14). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.14`.
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /Users/sharman/code/stevenharman/bundler_issue/Gemfile freeze
by running ``.

The list of sources changed
```

Again, thank you. And please let me know how I might be of help on this one!

**Comment by deivid-rodriguez** [comment]
Hi @stevenharman, thanks so much for the kind words.

This issue keeps coming up so I should get to it as soon as possible.

Currently bundler is very picky specially when run in frozen mode. Ensuring forward compatibility of old versions with all future lockfiles is virtually impossible for us, handling backwards compatibility is already hard enough :sweat_smile:.

The only way to 100% guarantee that `bundle install` will work with a specific lockfle, is to use the bundler version that generated it, since we already know that works fine.

The way we plan to implement that is to add logic to bundler that, when `bundle install` is run, it first parses the `BUNDLED WITH` section in the lockfile, then installs that exact version of bundler if not already installed, and then reexec's `bundle install` using the locked version.

In addition to fixing this issue, this will have additional benefits:

* It will ensure that the `BUNDLED WITH` version is always available after `bundle install`. Rubygems already includes logic to always prefer this version if available, so basically we'll be sure that `bundler-x.y.z` will always be used with lockfiles generated with `bundler-x.y.z`.

* This should allow heroku to remove all bundler-related logic, and heroku users to choose their preferred bundler version, by using a lockfile generated by that particular version.

**Comment by schneems** [comment]
> then installs that exact version of bundler if not already installed

I spoke to Andre and Colby at length about this in Nashville at RubyConf pre-pandemic. I'm happy to talk about this more with you either sync or async. I would be happy to talk with you. Since we cannot see each other in person maybe we can set up a call and I can virtually buy you a coffee/pizza/thing (send a Venmo payment for the rough amount of food delivery in your area). 

> This should allow heroku to remove all bundler-related logic

Bundler is DEEPLY embedded in the core of the Ruby buildpack. We have to have a version of bundler already built and available on S3 before we can invoke the customer's code. We use bundler to determine what version of Ruby is used, so that means we have to:

- Bootstrap a version of Ruby for the buildpack
- Detect approximate bundler version via Gemfile.lock (we currently only look at major and minor versions)
- Download that pre-packaged version of bundler from S3 and put it in a very specific place.
- Execute that bootstrapped version of bundler to call `bundle platform --ruby` 
- Only at this point do we know what version of Ruby to download and install for the customer

After that, we delete the `BUNDLED WITH` as there are no other supported "escape valves" for the errors that are shipped with bundler and rubygems that were in part triggered by the last attempt to auto-download and exec ruby versions (context https://github.com/rubygems/rubygems/issues/2666#issuecomment-468767513).

Once we have the customer's Ruby version bootstrapped, we then load the bundler version's lockfile parser we just loaded into the buildpack's bootstrapped Ruby process so we can do things like detecting what exact version of Rails they're requesting. (This is a re-write but the same basic idea https://github.com/heroku/heroku-buildpack-ruby-experimental/blob/46880cd7b4342d8b854687fb433a0869fb6a2b99/lib/heroku_buildpack_ruby/bundler_lockfile_parser.rb#L25-L27).

We've explicitly worked to be able to curate the Bundler version. One major benefit of this curation is it means we're able to track, document, and mitigate edge cases in specific bundler versions. Historically changing bundler versions results in increased support ticket load so we tend to prefer stability over being on the bleeding edge. The way we package and deliver bundler also would make it very difficult to support arbitrary versions.

Anywhoo. That's a lot for one comment. Before the work is done to implement this version switching code. I would very much like to talk if possible.

**Comment by deivid-rodriguez** [comment]
Sure @schneems, I'll loop back to you before I get to this feature. It might be a while, but I'll get to you :+1:.

> After that, we delete the BUNDLED WITH as there are no other supported "escape valves" for the errors that are shipped with bundler and rubygems that were in part triggered by the last attempt to auto-download and exec ruby versions (context #2666 (comment)).

As far I know, auto-downloading was never enabled by default, only auto-switching, and that's what caused most issues: rubygems would try to forcefufully use a version that was never made available by `bundle install`. The way I see it, it's completely natural that `bundle install` downloads and iinstalls the bundler version locked in the `Gemfile.lock` file. `bundle install` already downloads and installs gems, I don't think it will surprise anyone that it also installs an appropriate bundler version.

> We've explicitly worked to be able to curate the Bundler version. One major benefit of this curation is it means we're able to track, document, and mitigate edge cases in specific bundler versions. Historically changing bundler versions results in increased support ticket load so we tend to prefer stability over being on the bleeding edge.

Anything not properly working in bundler should be fixed upstream, and a newer version should be more stable than an older version, in general. Of course, regressions happen, but that's exactly the point of users being able to lock their version of bundler, choose when to upgrade, and use a consistent version between development and other environments. I guess there's a tension between increased support ticket for heroku and for bundler, because the main motivation for me to implement this feature is to decrease our support load. I've been maintaining bundler for a few years now, and at this point I'm pretty sure this will be a good move for us maintenance-wise (for example, this issue won't exist once this feature is implemented).

**Comment by schneems** [comment]
Sorry for the long response. I've tried to break it out into smaller sections.

This feature proposal brings up some historical examples that I think we can pull from to estimate a certain amount of instability.

## Prior Example: Bootstrapping Heroku Ruby

When I started at Heroku, the Ruby buildpack used the system Ruby. I did the work to move it over to boostrapping a ruby version instead. It took the Heroku Ruby Buildpack about 2 years worth of very difficult-to-find bugs to get rid of the majority of edge cases. It actually increased my support load over that time. (It's also worth pointing out that I did this out of necessity, not due to reducing tickets).

## Prior Example: Bundler raising errors on binstubs

When bundler moved to raising errors it brought out bugs that existed in rubygems for years that were yet to be found. I don't doubt that if this feature worked flawlessly that it would reduce support burden on your side. However the edge cases are many and the road to find and fix them all is long.

It's worth mentioning that whatever download code you write will have to be bug free in all the versions shipped of bundler and that once they're out in the wild they can't be modified or updated. They'll also have to work with a matrix of rubygems versions. 

Regarding bundler erroring out when it finds a different BUNDLE WITH declartion: The best decision I've made for my support volume at Heroku was to programmatically edit customer's `Gemfile.lock` to remove the `BUNDLE WITH` declaration. It's not ideal, but it's been very effective.

## Prior Example: Binstubs from Rails

To this day I'm still finding edge cases with Rails' decision to ship binsubs to auto exec bundler so `bundle exec` isn't needed. If I could go back in time I would advocate against binstubs in Rails, it's one of the most common causes of breakages for my customers. It's a layer of indirection that when things go wrong...it's difficult to spot and difficult to debug. It might be a cheap win for usability, but it comes at the cost of making the ecosystem more opaque and hostile to developers when things go wrong.

I'm on the fence if this one was "worth it" or not. I think I would have proposed we reach out to the author of the `b` gem to see if we can own it and claim that as a CLI command since the primary issue was "cli commands are too long when you have to type out 'bundle exec'". Though that ship has sailed many years ago.

## Prior Example:  Default bundler in Ruby

Even including bundler as a default gem, which seems like a very easy win was not smooth to implement. I support this feature and I'm glad we went through those growing pains, but I believe what you're describing is much involved and will at minimum have a similar amount of issues.

I believe having bundler be responsible for downloading and re-exec-ing itself will be a dramatic expansion of its surface area. I would ask if you end up shipping this feature you also have a flag to disable it. 

## Prior Art: Other package managers

I was looking around and I don't think I know of any dependency manager that does nstalls a newer version of itself. All the other package managers tell the user to do it.

The alternative we discussed in Nashville would be to version the lockfile parser and ship multiple parsers. Instead of versioning bundler in the `Gemfile.lock`, the lockfile could store it's own version i.e. v1, v2, v3 etc. It would be expected that recently released bundlers would be able to parse lockfiles generated from older versions.

## Re: Using arbitrary bundler

> a newer version should be more stable than an older version

That's not been my experience, unfortunately. Bundler has an extremely wide footprint (as you know). I tried to upgrade Heroku to 2.2.12 and was unable due to a regression. We're currently locked on 2.2.11 which seems to have no major issues across the platform. I was hit with mimemagic before being able to look into rolling out the 2.2.15.

When someone's deploy doesn't work on Heroku, regardless of the underlying reason, people's first reaction is to blame the platform. Especially if it works for them locally but not at deploy time. This is common with bundler since we're using flags (such as `--deployment` and BUNDLE_WITHOUT) that they're not using locally.

Just about every time someone's bundler version changes (to an older version) our ticket volume goes up.

> Anything not properly working in bundler should be fixed upstream

I try to document everything that I find via issues and work with customers to either find workarounds or propper fixes. I also document known issues on our docs site and tutorials, and in some cases I bake in fixes and warnings directly into the buildpack itself. For example warning and fixing a `BUNDLE_WITHOUT` env var that accidentally has a space in it is common because it was a typo on the bundler example docs at one point https://github.com/heroku/heroku-buildpack-ruby/blob/e5a8482fb961b4812c31632a3bff16ea30de5f6e/lib/language_pack/ruby.rb#L352-L357.

I'm not as active in contributing code with bundler as I would like, but I'm frankly spread thin between puma, rails, sprockets, and a whole host of random issues in other gems (like mimemagic for example). I understand you're also under a high support load as well and I appreciate your time.

**Comment by deivid-rodriguez** [comment]
> Prior Example: Bundler raising errors on binstubs

This was a bad move on bundler's side because it started being picky about the locked version without making it available first at `bundle install` time. My proposal is a way to achive the same goal of making sure that bundler x.y.z always runs lockfiles generated with bundler x.y.z, because `bundle install` already needs to be run before `bundle exec` is run.

> Prior Example: Binstubs from Rails

Honestly, I LOVE this feature. I just think it should live inside bundler/rubygems and be the default behaviour for all gem executables. If in a Gemfile.lock context, the locked version should be run, not the latest version in your system. Just like rails does. This is also in the roadmap.

> Prior Example: Default bundler in Ruby

Happy we agree this was a good move, and I also agree that this caused issues that we managed to solve. I disagree that this feature will cause the same amount of issues.

> Prior Art: Other package managers

Thanks for the context, I don't consider this much of a problem, each package manager has its own issues and needs. I think it's good to look around a grab ideas, but that's all.

> When someone's deploy doesn't work on Heroku, regardless of the underlying reason, people's first reaction is to blame the platform. Especially if it works for them locally but not at deploy time. This is common with bundler since we're using flags (such as --deployment and BUNDLE_WITHOUT) that they're not using locally.

Exactly. And these problems usually happen because people upgrade bundler locally, but can't upgrade bundler in heroku. Most issues wouldn't happen if they could also choose their version in heroku. Well, not really "choose", just use the right version that it's known to work 100% with their particular lockfile because it's the one that generated it locally.

> I try to document everything that I find via issues and work with customers to either find workarounds or propper fixes. I also document known issues on our docs site and tutorials, and in some cases I bake in fixes and warnings directly into the buildpack itself. For example warning and fixing a BUNDLE_WITHOUT env var that accidentally has a space in it is common because it was a typo on the bundler example docs at one point https://github.com/heroku/heroku-buildpack-ruby/blob/e5a8482fb961b4812c31632a3bff16ea30de5f6e/lib/language_pack/ruby.rb#L352-L357.

Yes, sorry, I didn't mean to imply that you're not "a good citizen", I just mean that we are happy to get issues reported and try to fix them.

> I'm not as active in contributing code with bundler as I would like, but I'm frankly spread thin between puma, rails, sprockets, and a whole host of random issues in other gems (like mimemagic for example). I understand you're also under a high support load as well and I appreciate your time.

Same here, I really appreciate your work in all those tools which I use myself.

**Comment by deivid-rodriguez** [comment]
I'm going to close this, since I don't think we can do much about this now. The separation of sources with multiple remotes in the lockfile was a one time thing to fix a security issue. Old versions of bundler in frozen mode cannot understand the multi source format, indeed, and there's no much that can be done about it.

We don't plan to introduce changes in the lockfile format like this in the near future, and we will try to do it in a graceful manner if we need to do it.
