### ISSUE TITLE
`bundle clean` isn't handling `with` config

### ISSUE THREAD

**Issue by ojab** [rubygems/rubygems#4480]
### Describe the problem as clearly as you can

Documentation says `This command will remove all unused gems in your bundler directory. This is useful when you have made many changes to your gem dependencies.` and it's not clear what exactly should be done, but my expectation is that after
```sh
bundle config set --local with production
bundle config set --local clean true
bundle install
bundle clean
```  
there wouldn't be development/test gems installed, since they're unused by the current configuration.

### Post steps to reproduce the problem

```dockerfile
# syntax=docker/dockerfile:1.2

FROM ruby:3.0.0-slim

RUN mkdir -p /tmp/bundler_test

WORKDIR /tmp/bundler_test

RUN bundle init
RUN bundle clean --force
RUN bundle add dry-core
RUN bundle add -g test rspec
RUN bundle config set --local with production
RUN bundle install
RUN bundle clean --dry-run
```

`bundle clean --dry-run` says that nothing to remove here.

**Comment by deivid-rodriguez** [comment]
I think this might be a more general request for change about how `bundle install` works with groups.

I believe `bundle install` currently installs all groups and `with`/`without` settings are only applied on `bundle exec`. Not sure whether there's a good reason for this, I guess we'd need to investigate.

**Comment by deivid-rodriguez** [comment]
I think the problem is `bundler installs` all groups by default. If you set `bundle config without test`, the `bundle clean` should clean things as expected.

**Comment by ojab** [comment]
kinda, `install` part is already covered by https://github.com/rubygems/rubygems/issues/4048, so it's the additional issue for `bundle clean` which may be solved without #4048.
Anyway IMHO `bundle clean` should handle `with` even when `bundle install` is run without `with` set.

**Comment by deivid-rodriguez** [comment]
Ok, then I can confirm that I'm not sure what the issue is, and how it relates to #4048.

Let me explain how I think groups currently work, so that we can hopefully get to the same page and figure out whether there's an issue here or not.

* By default, `bundle install` installs all groups, except for group definitions including `optional: true`.
* With `without`, you can opt-out of installing specific groups.
* With `with`, you can opt-in to installing specific optional groups, and if the group is not optional, it doesn't really have an additional effect.

Bundle clean should respect your `with`/`without` configuration, and removing any unused gems.

I tried the example you gave and some other combinations, and I didn't get any unexpected results, assuming the behaviour I explained above is expected.

**Comment by ojab** [comment]
Thanks! Looks like I understood `with` incorrectly. I thought that `--with production` should install only `default production` groups (like `--only` from #4048), looks like I should go with `--without`.
Closing for now, will recheck and reopen if any issues will be found later.
