### ISSUE TITLE
Difficulty tracing dependency tree for yanked packages

### ISSUE THREAD

**Issue by mcandre** [rubygems/rubygems#4490]
I'm having a problem or would like to suggest a feature.

My current problem is once a package is yanked from RubyGems.org, then it becomes difficult to identify the higher level package in a Ruby project that is trying to pull in the deprecated package. Both `bundle install` and `gem dependency` terminate too early, providing very little helpful information.

In my case, even `Gemfile.lock` and `Gemfile` hide this information, so I am not sure what recourse to take.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.9
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by rubyFeedback** [comment]
If I understand it correctly then you want to see prior dependencies of yanked gems?

If so then I think this may be useful indeed. I personally tend to yank old gems a lot
because I don't want to maintain outdated projects, but I am also fine with other
people using these old versions and such - I just don't want to have to bother with
them since I focus on the versions I still maintain. So if that was your idea, to give
users the possibility to show information pertaining to yanked gems, such as
your example of showing all dependencies, then yes.

I guess what you could add is how you may consider implementing this best,
ideally in a simple manner. I assume since the information is already there,
we don't need that much new code; just the ability for users to inspect this
information for yanked gems as well. (I believe at the least some yanked gems
will still be available on rubygems.org yes?).

Would you suggest a commandline flag or some other solution? Or just
an identifier on the homepage of a gem? It may be useful to recommend
to the folks who are active on the issue tracker how this could ideally
be implemented in a simple manner. I assume nobody would have a
big reason against it but it may depend on the feature limitation as
well.

**Comment by deivid-rodriguez** [comment]
I think you're asking for:

* Being able to list reverse dependencies of a gem: https://github.com/rubygems/rubygems/issues/3336.
* Being able to parse lockfile information without actually installing gems (even more necessary here since the gem can't be installed): https://github.com/rubygems/rubygems/issues/3342.

Correct?

**Comment by deivid-rodriguez** [comment]
Since there's two other tickets already tracking this, and I got no further feedback, I'm closing this.
