### ISSUE TITLE
Getting a strange lockfile with a single source block

### ISSUE THREAD

**Issue by theflow** [rubygems/rubygems#4570]
### Describe the problem as clearly as you can

I've noticed that this way of using sources results in a strange lockfile. Everything does seem to work in general, but it still doesn't seem right to me 😊

### Post steps to reproduce the problem

Running `bundle install` on this Gemfile, results in that empty `GEM` block.

### Gemfile

```ruby
source 'https://rubygems.org' do
  gem 'rake'
end
```

### Gemfile.lock

```
GEM
  specs:

GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.3)

PLATFORMS
  x86_64-darwin-18

DEPENDENCIES
  rake!

BUNDLED WITH
   2.2.16
```

## Environment

```
Bundler       2.2.16
  Platforms   ruby, x86_64-darwin-18
Ruby          2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
  Full Path   /Users/flo/.rbenv/versions/2.6.5/bin/ruby
  Config Dir  /Users/flo/.rbenv/versions/2.6.5/etc
RubyGems      3.0.3
  Gem Home    /Users/flo/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  Gem Path    /Users/flo/.gem/ruby/2.6.0:/Users/flo/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  User Home   /Users/flo
  User Path   /Users/flo/.gem/ruby/2.6.0
  Bin Dir     /Users/flo/.rbenv/versions/2.6.5/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
Yes, I noticed it too!

It's because the default source also considers locally installed specifications, and if there's no explicit default source, this "local fallback" is still there. So, this Gemfile works just fine as long as you have `rake` installed locally, and the `rake` gem gets locked under this empty GEM source section.

 ```
gem "rake"
```

In your example, the empty section would mean "No specs should be picked up from the default local source".

**Comment by theflow** [comment]
Ok, makes sense, I guess 😊 Thanks for explaining and feel free to close this.

**Comment by deivid-rodriguez** [comment]
No problem, I admit it's a bit weird but since it doesn't seem to cause any issues, I'll close this!
