### ISSUE TITLE
gemrc values are ignored

### ISSUE THREAD

**Issue by konsolebox** [rubygems/rubygems#4594]
In Gem::ConfigFile#initialize, keys of loaded YAML values are checked as symbols, but keys are loaded as strings so lines like these make them ignored:

@verbose                     = @hash[:verbose]                     if @hash.key? :verbose

This however would work:

@verbose                     = @hash["verbose"]                     if @hash.key? "verbose"

To reproduce, create /etc/gemrc with `verbose: "really verbose"` as content, and then perhaps a debug command next to one of the lines above which displays/logs the 'inspect' value of @hash and @verbose.

Tested on Rubygems version 3.2.14 with Ruby version 2.7.2p137.

**Comment by deivid-rodriguez** [comment]
If you have a look at [gemrc tests](https://github.com/rubygems/rubygems/blob/28621d1d0844a05a778791c3e4aef6b26f0b4da2/test/rubygems/test_gem_config_file.rb), it seems intentional that the configuration keys need to be specified as symbols. I guess we could also accept strings, or at least document better that symbols are needed.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by konsolebox** [comment]
Thanks for the reply by the way.  It helped.  I agree with the keys being made adaptable, probably through .to_sym.
