### ISSUE TITLE
`bundle install` broken in 3.2.18

### ISSUE THREAD

**Issue by alanbrent** [rubygems/rubygems#4620]
It looks like `rubygems-update` 3.2.18 has introduced a bug with resolving and/or finding dependencies. Please see the output in below for a demonstration of the problem behavior showing up in 3.2.18.

This issue is related to:

  - [x] Installing a library
  - [x] The command line `gem`
  - [x] `bundler`

From a fresh official Ruby container:

```
root@ruby-3:/# ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
root@ruby-3:/# gem update -N --system=3.2.18 # Output snipped. It succeeds.
root@ruby-3:/# gem --version
3.2.18
root@ruby-3:/# mkdir /scratch && cd /scratch
root@ruby-3:/scratch# cat <<EOF > Gemfile
source 'https://rubygems.org'

gem 'rails'

EOF
root@ruby-3:/# bundle package # Output snipped. It succeeds.
root@ruby-3:/# bundle install --path=vendor/bundle --local
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
Some gems seem to be missing from your vendor/cache directory.
Could not find racc-1.5.2 in any of the sources
root@ruby-3:/# gem update -N --system=3.2.17 # Output snipped. It succeeds.
root@ruby-3:/# gem --version
3.2.17
root@ruby-3:/# bundle install --path=vendor/bundle --local # Output snipped. It succeeds.
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thank you! I can reproduce this, but I have no idea what's going on. Looking at it now.

**Comment by deivid-rodriguez** [comment]
It's due to backporting https://github.com/rubygems/rubygems/pull/4260 with rubygems 3.2.18, which I did because I was getting some conflicts in the release branch which backporting the PR fixed, and I expected it to not have any user facing changes anyways. Fix coming, please stick to 3.2.17 until 3.2.19 is out.

**Comment by dmcinnes** [comment]
Thanks for the fix! Any ETA on 3.2.19? This is breaking some of our CI and other tooling.

**Comment by deivid-rodriguez** [comment]
I'll release this on Monday :+1:.

**Comment by deivid-rodriguez** [comment]
Just to correct my previous message. In the end, my diagnosis was that this change in rubygems actually made a problem in bundler surface, so the fix will be released with bundler `2.2.19` and you'll need to upgrade `bundler` to get this working again.

**Comment by dmcinnes** [comment]
Thanks @deivid-rodriguez !

**Comment by alanbrent** [comment]
While I can appreciate that this revealed a bug in Bundler, the requirement to run the latest version of bundler is going to be break _a lot_ of builds out there for an indeterminate amount of time. Not everyone has made the jump to Bundler 2.x for every one of their Ruby applications. AFAICT those using environments that automatically provide the latest Rubygems (_side-eye_ @ Travis) are now stuck with forceably downgrading to Rubygems 3.2.17 until such time as they can update their application to use Bundler 2.x.

I'm not asking for a different fix; I get that you're fixing bugs in ways that seem most appropriate to you. I just want to point out that the (unintended) consequences of this change are quite broad. At the end of the day I'm far more annoyed w/ our CI vendor for "helpfully" updating us to the very latest Rubygems on every build.

**Comment by deivid-rodriguez** [comment]
@alanbrent hanks for your feedback. I guess we could revert the change in rubygems in we consider it too disrupting. @simi thoughts? IMO the workaround of dowgrading rubygems is easy enough and the problem is quite specific (new rubygems + old bundler which can't be upgraded + bundler caching enabled + using extension gems). And locking your CI dependencies is a good practice anyways so the way I see it it's something you should do regardless.

By the way, can you elaborate on the issues preventing you from upgrading bundler, I keep hearing that some people are not ready for bundler 2.x, but I can't figure out why. Is it because of supporting old rubies?
