### ISSUE TITLE
Allow some "backdoor" gems available under 'bundle exec` regardless of Gemfile

### ISSUE THREAD

**Issue by mame** [rubygems/rubygems#4649]
How about providing a "backdoor" way to make some special gems available even if they are not written in Gemfile?

I frequently use the `stackprof` gem to profile Ruby apps and gems. However, to use `stackprof` under `bundle exec`, I need to modify Gemfile to add `gem 'stackprof'` every time. After profiling and performance improvement, I need to be careful to revert the modification before commit. This repeated process is, honestly, annoying and error-prone to me. (If there is already a way to temporarily make some special gems available without Gemfile modification, sorry but let me know.)

My current motivation is `stackprof`, but this is not limited to the gem. There are some gems that we want to use only during development. Currently, @ko1 is creating a new `debug` gem, which we will want to use with no code modification. Also, this is related to https://bugs.ruby-lang.org/issues/16778; if it is easy and useful enough to make a gem "special", we may promote some default gems (for example, irb) to bundle gems.

My naive idea to use an environment variable. For example, `bundle exec` can make gems listed in `BUNDLER_BACKDOOR_GEMS`.

```
export BUNDLER_BACKDOOR_GEMS=stackprof,debug,irb
```

Another idea is `~/.bundle/config`, or something.

I know that my proposal reduces the environment reproducibility which is the main motivation of Bundler. Some users may use this backdoor in development environment, unintentionally write code that depends on the gems, commit and deploy the code, but the code does not work in production. So, this is a trade-off between development usability and production robustness. Thus, I call my proposal as "backdoor" to notice users that this feature is somewhat dangerous.

However, in recent practice, this kind of issues (unintentionally deploying code) will be typically visible in CI environment. Rather, in this regard, unintentionally committing a temporal modification of Gemfile to add `gem "stackprof"` or `gem "debug"` or something is much worse because it may pass the CI test and bring big performance overhead in production.

What do you think?

**Comment by duckinator** [comment]
The entire purpose of `bundle exec` is to create an isolated environment. From `man bundle-exec`:

> **bundle exec** makes a number of changes to the shell environment, then
> executes the command you specify in full.
>
> [...]
>
>  It also modifies Rubygems:
>  •   disallow loading additional gems not in the bundle
> [...]

Interestingly, you can do `bundle exec gem install stackprof` and it still hides it during `bundle exec`. But the files are all there, meaning it is theoretically possible to allow access to it.

I'm not sure whether I'm in favor of this kind of feature or not but, if this is added, perhaps instead of an environment variable it could be a command-line argument? E.g., `bundle exec --allow-gems=stackprof,debug,irb your-command-here`?

The reason I suggest that as an alternative is because it allows you to pass through whatever you want, while avoiding the problem of accidentally relying on things you shouldn't (it's in the command you run, as opposed to hidden in an environment variable).

If you found you used it often, you could make a shell alias or script to accommodate it (maybe called `bundle-debug` or similar, in your specific context).

**Comment by mame** [comment]
@duckinator Thank you for your comment. 

> `bundle exec --allow-gems=stackprof,debug,irb your-command-here`?

It makes great sense! It is definitely better than my idea.

**Comment by mame** [comment]
Oops, I've posted my previous comment in the middle of writing it.

As far as I understand, `bundle exec` just invokes the external command with some environment variables like RUBYOPT, so I think in any way we have to introduce a new environment variable like `BUNDLER_BACKDOOR_GEMS` to convey the information what gems should be specially allowed. However, the command-line options are a better UI to specify the gem list because it is very explicit and less misleading users to a potentially dangerous configuration like `export BUNDLER_BACKDOOR_GEMS=stackprof` in `.bashrc`.

**Comment by simi** [comment]
The problem is usually with dependencies. Lockfile has dependency A locked in version `2`, but your "backdoor" gem has dependency A and requirement to have version `<2`. What to do?

What you can do today is to use "Gemfile" wrapper and use `BUNDLE_GEMFILE` to use your wrapped Gemfile instead.

```ruby
# Gemfile.local
eval File.read('Gemfile')

gem 'stackprof'
```

```
BUNDLE_GEMFILE=Gemfile.local bundle
```

```
BUNDLE_GEMFILE=Gemfile.local bin/rails c

irb(main):001:0> defined? StackProf
=> "constant"
```

You can add `Gemfile.local` and `Gemfile.local.lock` to your global gitignore. `BUNDLE_GEMFILE` could be set in various ways. You can use `.bundle/config` if not already present in your git, you can set it based on file presence in bash, ...

**Comment by mame** [comment]
@simi Thank you for your comment.

> Lockfile has dependency A locked in version `2`, but your "backdoor" gem has dependency A and requirement to have version `<2`. What to do?

For my use case, there is no version requirement for backdoor gems. I don't think that the backdoor mechanism should provide such a rich feature.

So my expectation is:

* If Gemfile.lock has dependency, the version that the lock file specifies is activated. (Actually, `--allow-gems` option can be ignored because Gemfile.lock already specifies the gem that I want to use.)
* If Gemfile.lock has no dependency, the latest installed version is activated (like what the rubygems does).


> What you can do today is to use "Gemfile" wrapper and use `BUNDLE_GEMFILE` to use your wrapped Gemfile instead.

In fact, that is what I tried first :-) Unfortunately, the hack does not work so great. There is a file named `~/default.gemfile` in my machine.

```
source "https://rubygems.org"

gem "stackprof"

ENV.delete("BUNDLE_GEMFILE")
eval(Bundler::SharedHelpers.default_gemfile.read)
```

Assume that we want to use the hack for a sample repository that uses psych.

``` 
$ cat Gemfile
source "https://rubygems.org"

gem "psych"

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    psych (3.3.2)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  psych

BUNDLED WITH
   2.2.15

$ bundle exec ruby -e 'require "psych"; p Psych::VERSION'
"3.3.2"
```

Note that Gemfile.lock specifies psych 3.3.2. However, `BUNDLE_GEMFILE=~/default.gemfile bundle exec ruby` activates psych 4.0.1, which is the latest installed version in my environment.

```
$ BUNDLE_GEMFILE=~/default.gemfile bundle exec ruby -e 'require "psych"; p Psych::VERSION'
"4.0.1"
```

Even worse, Gemfile.lock is silently updated.

```
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    psych (4.0.1)
    stackprof (0.2.17)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  psych
  stackprof

BUNDLED WITH
   2.2.15
```

Note that now Gemfile.lock has two modifications: psych version is updated, and stackprof is added. By copying Gemfile.lock in the repository to `~/default.gemfile.lock` before calling `BUNDLE_GEMFILE=~/default.gemfile bundle exec`, I can avoid the first modification (i.e., psych version is not updated) but still the second modification is performed to Gemfile.lock. Anyway this process is super error-prune.

**Comment by deivid-rodriguez** [comment]
Hello @mame.

I understand your motivation, but I'd like to suggest an alternative that doesn't imply adding yet a new feature to bundler, and thus adding maintenance overhead for us. Bundler has way too many features already in my opinion.

Your main problem is "I have to add 'stackprof' to the Gemfile everytime", yeah? Ok, so why not adding it to the Gemfile permanently? That way you get one of the benefits of bundler: a consistent version for every user of the Gemfile/Lockfile. You said this is risky, because it may bring performance overhead in production, but bundler has a feature for this: Gemfile groups. You can add this to your Gemfile:

```ruby
source "https://rubygems.org"

gem "rake"

group :profiling, optional: true do
  gem "stackprof"
end
```

This means that `stackprof` won't be used by default, unless you explicitly enable the optional group. So if say you have a `rake` task that does:

```ruby
task :foo
  require "stackprof"
  puts "OK"
end
```

By default, you get:

```
$ bundle exec rake foo
rake aborted!
LoadError: cannot load such file -- stackprof
```

But you can optionally enable it with:

```
$ BUNDLE_WITH=profiling bundle exec rake foo
OK
```

What do you think? I believe it's basically what you are proposing, but with a Gemfile group instead of a manual list of gems.

**Comment by mame** [comment]
@deivid-rodriguez Thank you for your comment.

> Ok, so why not adding it to the Gemfile permanently? 

I believe it is a good practice to keep Gemfile as simple as possible.

Honestly I don't want to add a dependency that is needed just temporarily. Putting my preference aside, I actually add stackprof to Gemfile of my own project.

However, it is much tough to modify Gemfile of other projects. It is very difficult to persuade the main author to add a gem dependency that is never used by themselves, and that is needed just temporarily even for me. In fact I have some experience that such a proposal is rejected.

**Comment by deivid-rodriguez** [comment]
Ok. Let me propose an alternative then. Bundler will respect gems already loaded before `bundler/setup` is required. So, how about doing this:

```
$ ruby -rstackprof -rbundler/setup -e 'puts StackProf::VERSION; require "psych"; puts Psych::VERSION'
0.2.17
3.3.2
```

**Comment by mame** [comment]
Ohhh, why didn't I come up with? It looks a perfect solution. I'll try to use it. If I face any problem, I'll reopen this or create another ticket. Thank you very much!
