### ISSUE TITLE
Incorrect gem lookup when using multiple sources after v2.2.21

### ISSUE THREAD

**Issue by itay-grudev** [rubygems/rubygems#4875]
### Describe the problem as clearly as you can

I just did a complete reinstall and installed the latest `bundler:2.2.26` and after running `bundle` on my project I received:

```txt
Fetching source index from https://gems.graphql.pro/
Fetching gem metadata from https://rubygems.org/.......
Fetching source index from https://rubygems.org/
Resolving dependencies..........
Your bundle is locked to rails (6.1.4.1) from rubygems repository https://gems.graphql.pro/ or installed locally, but that version can no longer be found in that source. That means the author of rails (6.1.4.1)
has removed it. You'll need to update your bundle to a version other than rails (6.1.4.1) that hasn't been removed in order to install.
```
Afterwards to verify that the Gemfile and Gemfile.lock are correct I downgraded to our project's original `bundler:2.1.4` and everything worked normally.

Then I started installing and uninstalling versions to see when the problem first popped up. From what I can see, this issue first popped up on **`bundler:2.2.21`**, as `bundler:2.2.20` works just fine.

There seems to be some kind of issue with gem lookup introduced in `bundler:2.2.21` when using another repository.

My `Gemfile` structure is like so:

```ruby
source 'https://rubygems.org'

ruby '2.7.1'

gem 'rails', '~> 6.1', require: false
gem 'graphql-pro', source: 'https://gems.graphql.pro/'
```

And my `Gemfile.lock`:
```
GEM
  remote: https://rubygems.org/
  remote: https://gems.graphql.pro/
  specs:
    ...

RUBY VERSION
   ruby 2.7.1p83

BUNDLED WITH
   2.1.4
```

**Comment by sambostock** [comment]
We had something similar happen, so I'll comment here rather than open a new issue, as it might be the same root cause. I only have the commit diffs to go by, but it looks like this is what happened:

1. Our project depended on various gems, from both Rubygems and a private gem server.
2. Two of the private gems depended on the [`semian` gem](https://github.com/Shopify/semian)
3. `Gemfile.lock` correctly showed those two gems as coming from the private source, and `semian` as coming from Rubygems
4. The `semian` gem was added as an **explicit** dependency, **and erroneously put into the wrong `source` block in `Gemfile`** (human error)
5. **Bundler did not catch that the `semian` gem is not available in that private source** (presumably because the correct version was already installed locally on the dev's machine) and updated `Gemfile.lock`, moving `semian` out of the Rubygems section and into the private source section.
7. The change was pushed to GitHub and several days later, I pulled the repo and Bundler blew up when trying to install the `semian` gem from the private source with the same error message as described above:

> ```
> Your bundle is locked to semian (0.11.4) from rubygems repository <PRIVATE SOURCE> or installed locally, but that version can no longer be found in that source. That means the author of semian (0.11.4) has removed it. You'll need to update your bundle to a version other than semian (0.11.4) that hasn't been removed in order to install.
> ```

**Comment by deivid-rodriguez** [comment]
If you can share a sample repository where the steps that you followed can be replicated, that'd be :100:.

**Comment by simi** [comment]
also https://github.com/geminabox/geminabox could be handy

**Comment by xxx** [comment]
We're seeing the same. 

What, _exactly, step by step_, are we supposed to do when we one gem from a private repo, and allllllllll of the rest from rubygems.org. So far, it seems to be random as to which source our gems come from.

**Comment by itay-grudev** [comment]
Just to clarify this for other users who encounter the issue, it is solved by wrapping your gem in a `source` block like this:

```ruby
source 'https://gems.graphql.pro/' do
  gem 'graphql-pro'
end
```

This wound instead generate separate `GEM` secition in `Gemfile.lock` which is the correct behaviour and doesn't cause the issue:

```Gemfile.lock
GEM
  remote: https://gems.graphql.pro/
  specs:
    graphql-pro (1.19.2)
      graphql (>= 1.7.5)
```

**Comment by itay-grudev** [comment]
I still believe this is a bug, as definition with an inline source specification did not work.

**Comment by deivid-rodriguez** [comment]
I'm going to close the issue though since I was never able to reproduce it. If you can provide a test application that reproduces it, feel free to reopen! Thanks!

**Comment by itay-grudev** [comment]
@deivid-rodriguez I'm not sure if I have the time to set a demo up, especially setting up a third-party repo, but I can send you my `Gemfile` and `Gemfile.lock`, although in confidence, over email.

**Comment by sambostock** [comment]
@deivid-rodriguez, @itay-grudev I've set up[^1] a [demo repository](https://github.com/sambostock/rubygems-rubygems-4875-demo) which should allow you to replicate the issue (see the README). I don't have access to re-open this issue though.

Keep in mind, the reproduction I provided matches [my original comment's scenario](https://github.com/rubygems/rubygems/issues/4875#issuecomment-910414293), which may not be the exact circumstances causing @itay-grudev's issue. I'm not sure.

[^1]: Sorry it took so long! Even once I made the time, I'd never actually pushed or hosted a gem manually before and ran into a bunch of issues getting Geminabox working properly... 😅  Something to do with having tried to use an IPv6 address or something causing weird Rack Lint errors claiming `SERVER_NAME` or `SERVER_PORT` weren't right...

**Comment by deivid-rodriguez** [comment]
@sambostock Thanks! So the issue in your case is that `bundler` should detect the human error and never generate that incorrect lockfile, right?

**Comment by itay-grudev** [comment]
@deivid-rodriguez My problem I believe is similar. Incorrectly generated lockfile. Two `remote` specifications:

> ```txt
> GEM
>   remote: https://rubygems.org/
>   remote: https://gems.graphql.pro/
>   specs:
>     ...
> 
> RUBY VERSION
>    ruby 2.7.1p83
> 
> BUNDLED WITH
>    2.1.4
> ```

**Comment by deivid-rodriguez** [comment]
@itay-grudev I don't think so. If I understand correctly, in your case bundler should be able to deal with that format (merged sources) and automatically update it to the new format (separate sources), so your issue remains non reproducible I think 😬. @sambostock's case is different because `bundler` is generating a lockfile in the new format (separate sources), but an incorrect one (because is putting a gem under a source not including that gem).

**Comment by sambostock** [comment]
Yeah, I'm not sure about how @itay-grudev's `Gemfile` got in its state. Perhaps a related thing where Bundler erroneously thought `rails` should come from the same private source, because `graphql-pro` depends on it and is itself from a private source?

In any case, as far as my reproduction case, I think the bugs are as follows:
- Bundler should probably **not be able to create an invalid `Gemfile.lock`** (incorrect source) just because a gem is cached locally.
  Perhaps the cache should include information about which source the gem was fetched from?
- The **error message could be updated** to mention double checking sources.
- The **recoverability is poor** if this scenario is encountered, because of Bundler's behaviour of "propagating" sources to dependencies when they haven't been specified explicitly.
  Either this should be improved, or the error should mention intermediately forcing the source.

---

It might be useful if Bundler was able to tell you where gems are available, and might even be useful if it recommended (or forced?) an explicit source when a gem is available through multiple sources (meaning there is some ambiguity on where to fetch it from).

This kind of functionality would probably make it possible to provide a "Did you mean" style error message on gem sources.

That said, it would mean we'd have to check all sources in the Gemfile for all gems, which might be undesirable. Not sure.

Curious what you think @deivid-rodriguez!

**Comment by deivid-rodriguez** [comment]
We agree that the first bullet point is a bug :) I investigated it and found the culprit. The problem is not that the gem is already installed (bundler already handles this fine, excluding installed gems if we need to resolve from scratch), but that the gem is cached, and the current cache saves every `.gem` gem file together, not splitting by sources. I'll try to fix it although it seems tricky.

Regarding the second, I think the error message is pretty good, specially once we fix this bug and bundler no longer generates incorrect lockfiles like in this case. But I would probably tweak it to

> Your bundle is locked to rails (6.1.4.1) from rubygems repository https://gems.graphql.pro/, but that version cannot be found in that source. That means the author of rails (6.1.4.1) has removed it. You'll need to update your bundle to a version other than rails (6.1.4.1) that hasn't been removed in order to install.

It could still end up being an incorrect message if the user manually edits the lockfile to put a gem under a source where it doesn't exist. But I feel a bad error message is a fair punishment for doing that 😆.

Regarding the third issue, yeah, recoverability by changing the `Gemfile` is poor, because the problem does not lie in the `Gemfile` but in the `Gemfile.lock` file. But again, if we fix the first issue, the only way you can get into this trap is if you mess up with the lockfile directly so it doesn't seem worth improving.

Also, as a general comment, bundler behavior of propagating sources to dependencies when they haven't been specified directly is a relatively new behavior to fix a security issue, namely, https://nvd.nist.gov/vuln/detail/CVE-2020-36327.

**Comment by deivid-rodriguez** [comment]
I opened a fresh ticket to track this bug: https://github.com/rubygems/rubygems/issues/5067.

**Comment by itay-grudev** [comment]
@deivid-rodriguez Reproduced it using @sambostock's demo project. Here are the steps:

1. Run his `geminabox` and build his gem.
2. `mkdir app2 && cd app2`
3. `nano Gemfile`
```Gemfile
source 'https://rubygems.org'

gem 'example'
gem 'some_private_gem', source: 'http://localhost:9292'
```
4. `gem install bundler:2.1.4`
5. `bundle _2.1.4_ install`
6. Examine the `Gemfile.lock` which will look like this:
```
GEM
  remote: https://rubygems.org/
  remote: http://localhost:9292/
  specs:
    example (1.0.2)
    some_private_gem (0.1.0)
      example (~> 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  example
  some_private_gem!

BUNDLED WITH
   2.1.4
```

That was how bundler used to generate lock files. I didn't edit it. It's really "valid".

**Comment by deivid-rodriguez** [comment]
I didn't mean to suggest you edited it, sorry if I implied that. I'm willing to be able to reproduce your issue too so I can help you.

The lockfile bundler 2.1.4 generated is insecure but as I said, current bundler should be able to deal with it.

If you run `gem install bundler & bundle _2.2.31_ install`, it should work properly and automatically update the lockfile to the secure format, namely:

```
GEM
  remote: http://localhost:9292/
  specs:
    some_private_gem (0.1.0)
      example (~> 1.0)

GEM
  remote: https://rubygems.org/
  specs:
    example (1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  example
  some_private_gem!

BUNDLED WITH
   2.2.31
```

Neither the lockfile generated with bundler 2.1.4 nor the updated lockfile have the issue of @sambostock where a `GEM` section includes a gem not present in any of the remotes of that `GEM` section.
