### ISSUE TITLE
2.2.27 Could not find gem when the gem set the `:path`

### ISSUE THREAD

**Issue by Whirlwind** [rubygems/rubygems#4914]
### Post steps to reproduce the problem

Remove all gem in bundler gem directory:

```bash
rm -rf ~/.bundle/vendor/ruby/2.6.0
```

Remove the Gemfile.lock in working directory:

```bash
rm -rf Gemfile.lock
```

The Gemfile:

```
source 'https://rubygems.org' do
    gem 'cocoapods', :path => '~/Documents/Developer/CocoaPods'
end
```

Then install gems:

```
❯ bundle install
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Fetching gem metadata from https://rubygems.byted.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "cocoapods-core":
  In Gemfile:
    cocoapods was resolved to 1.7.5, which depends on
      cocoapods-core (= 1.7.5)

Could not find gem 'cocoapods-core (= 1.7.5)', which is required by gem 'cocoapods', in locally installed gems.
```

I test the version v2.2.8, everything is OK. after upgrade to v2.2.27, the bundler will not work.

If remove the `:path`, the bundler will work.

**Comment by Whirlwind** [comment]
I check the comment: https://github.com/rubygems/rubygems/issues/4632#issuecomment-851517160
> By using scoped sources, you tell bundler "I want the gems specified under this source, and also their dependencies, to be fetched from this source".

The `cocoapods-core` should use the `https://rubygems.org` source, right?

**Comment by deivid-rodriguez** [comment]
@Whirlwind Unfortunately, no. `cocoapods` and its dependencies (I assume `cocoapods-core` is a dependency) will use the `path` sources. This is common behaviour, for example, when you run from a clone of rails using `gem "rails", path: "/path/to/rails"`: all rails gems, `activesupport`, `activerecord` and so on, will be picked up from the `path` source.

Ideally, `bundler` would have a better priority and if some dependency is not found in the innermost source, it would look in the other nested sources, like `rubygems.org` in this case. However, we don't have such logic right now, and the only fallback bundler has is to default to the global source.

Before fixing dependency confusion vulnerabilities, this used to work because when the source from a dependency was not specified directly, bundler would randomly choose any source in the Gemfile including it. But this behaviour was removed due to being insecure.

I'll close this since the improvement of the fallback behaviour is tracked at #4817, but let me know if you have any questions!
