### ISSUE TITLE
Bundle config docs don't mention that you can set without using set

### ISSUE THREAD

**Issue by masukomi** [rubygems/rubygems#4924]
### Describe the problem as clearly as you can

The `bundle config` docs [here](https://bundler.io/man/bundle-config.1.html) suggest that the options to bundle config are 

```
bundle config [list|get|set|unset] [name [value]]
```

They fail to document the fact that you can run `bundle config name value` and have it perform the same behavior as `bundle config set name value`.

It is unclear if this is a bug in the behavior of `config` or a bug in documentation. I'm assuming documentation. 

### Reproduction 

1. run `bundle config foo bar` 
2. run `bundle config get foo` 
3. confirm that "bar" is returned 
4. note that this is an unexpected result, as this is undocumented behavior

### `bundle env` output: 

I think the only relevant bit here is that I'm using bundler 2.2.27

### commentary: 
Personally, I'd prefer it if config returned an error if you tried to use it without providing one of the supported verbs. Ambiguous behavior is rarely a good thing.

**Comment by deivid-rodriguez** [comment]
Actually the help seems right. Brackets indicate that the argument is optional, no?

**Comment by rubyFeedback** [comment]
Hmm. Although that may be the explanation, isn't it then not strange that the [] parens are grouped?
E. g.

    bundle config [list|get|set|unset] [name [value]]

Would that not mean that we could omit value, but provide name, due to it also being in []?

**Comment by rubyFeedback** [comment]
Or perhaps worded differently, can we just use "name" without trailing value ever? In that case perhaps it should be [name value] rather than [name [value]], but I may not have thought this through entirely. I can see why that looks a bit confusing.

**Comment by deivid-rodriguez** [comment]
`bundle config foo` is also valid and equivalent to `bundle config get foo`, so yeah, it's possible to pass name and no value.

Maybe we can change the synopsis to the following to make it more accurate:
 
```
bundle config[ list]
bundle config[ get] <name>
bundle config[ set] <name> <value>
bundle config unset <name>
```

**Comment by deivid-rodriguez** [comment]
I'm not saying we shouldn't deprecate `bundle config <key> <value>` without explicit `set`. As a matter of fact, there is a plan to deprecate it (although the reason if I recall correctly was to fix some ambiguous edge cases, not the one about destructiveness you're mentioning here). I just decided to postpone it for now to focus on other things first, because I thought requiring explicit verbs might be too verbose for little benefit and could annoy some folks (and some people agreed with me).

I'm curious about your argument about `bundle config <foo> <bar>` being unexpected because of its destructiveness. No one has ever complained about it, people seem to unambiguously understand that `bundle config` with two arguments means setting the config key passed as first argument to the value passed as second argument. It always seemed natural to me too, maybe because that's also how `git config` works? :shrugh:. As a matter of fact, `bundler` is even more helpful than `git` in this regard because it tells you the previous value if you're overwriting it.

```
$ bundle config foo bar
$ bundle config foo baz
You are replacing the current global value of foo, which is currently "bar"
```

**Comment by deivid-rodriguez** [comment]
> I'm cool with everything there, and think it's a reasonable improvement except implied "set". I don't think we should ever be able to perform a destructive operation without being explicit about it.

Great, I'll propose that improvement to the command synopsis. Note that implied `set` is how `bundler`already works, this change would be just better documenting that. But if you want to open a separate ticket to propose changing it, +1:.
