### ISSUE TITLE
Bundler version 2.2.22 contains an undocumented breaking change on `--source`

### ISSUE THREAD

**Issue by tom-lord** [rubygems/rubygems#4995]
### Describe the problem as clearly as you can

See this PR: https://github.com/rubygems/rubygems/pull/4692

And see these notes in the `CHANGELOG.md`: https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2222-july-6-2021

There is no mention of the fact that `bundle update --source <gemname>` no longer mimics the behaviour of `bundle update --conservative <gemname>`.

Whilst I agree with the change, it's undocumented and breaking. I don't think this should have been a patch release, and it should at least be mentioned in the CHANGELOG.

See also, [this original issue which describes the (surprising) behaviour](https://github.com/rubygems/bundler/issues/3759).

**Comment by deivid-rodriguez** [comment]
Hello @tom-lord.

As you can read in the issue you linked to, that behavior was not documented anywhere and the fact that it actually worked like that was just pure chance. The option is even documented with a different meaning, and after reading the code and fixing the proper flag to update conservatively, `--conservative`, I verified that the fact that it worked like that was just a bug.

So, in my opinion, it was perfectly fine to drop that behavior any time and it shouldn't be mentioned in the changelog because the option was never supposed to work like that in the first place. I did mention that the `--conservative` flag now works as expected, since that was a bug fixed in the release.

Hope it's ok!

**Comment by tom-lord** [comment]
@deivid-rodriguez You're right that it was undocumented (as far as I can tell). It's also _unclear_ whether this feature was originally added intentionally or by chance. However:

* [Support for this behaviour of `--source` was added into the bundler specs.](https://github.com/rubygems/bundler/pull/3763/files)
* Prior to `bundler v1.14`, this was the **only** way to "conservatively" update a gem. Therefore this change will have silently broken anyone's setup who was relying on it.
* For example, anyone who googled something along the lines of ["update one gem with bundler" would have found adding `--source` as the best available option](https://stackoverflow.com/q/11263150/1954610).

As I said, at the very least I think this is worth a mention in the CHANGELOG. There are bound to be thousands of developers still expecting `--source` to behave in this manner.
