### ISSUE TITLE
bundler exits with code 16 after latest update on GitHub Actions

### ISSUE THREAD

**Issue by luizkowalski** [rubygems/rubygems#5064]
### Describe the problem as clearly as you can

I have a github action that was using the latest version of Bundler. Since today, it started to fail with this message:

```
  You are trying to install in deployment mode after changing
  your Gemfile. Run `bundle install` elsewhere and add the
  updated Gemfile.lock to version control.
  
  If this is a development machine, remove the
  /home/runner/work/concurrent_rails/concurrent_rails/Gemfile freeze
  by running `bundle config unset deployment`.
  
  The lockfile does not have all gems needed for the current platform
  Took   0.83 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle' failed with exit code 16

```

### Did you try upgrading rubygems & bundler?

I tried upgrade and dowgrande

### Post steps to reproduce the problem

This happens on an open-source repository: https://github.com/luizkowalski/concurrent_rails/pull/11

I believe this is enough, let me know if I should give more info

**Comment by deivid-rodriguez** [comment]
Hello @luizkowalski, I'm trying to reproduce this locally, but I can't.

I suspect you have a corrupted bundler cache on GitHub Actions, because something I did find is that on bundler 2.2.28 (previous version you were using), `bundle install`  crashes hitting [this issue](https://github.com/rubygems/rubygems/issues/4922). Can you try https://github.com/ruby/setup-ruby#dealing-with-a-corrupted-cache and see if that fixes things?

**Comment by luizkowalski** [comment]
just did that and got the same error...I noticed that different bundler versions will trigger different errors. This is the error with bundler version 2.2.29: https://github.com/luizkowalski/concurrent_rails/runs/4151349462?check_suite_focus=true

**Comment by deivid-rodriguez** [comment]
Yes, that's what I meant when I said you were previously running into https://github.com/rubygems/rubygems/issues/4922. That one was fixed by bundler 2.2.30, so it's expected that you no longer get that error. What's not expected is that you get another error 😅.

I tried to repro this on my OSX laptop, so maybe that's why I cannot reproduce. Let me try on Linux.

**Comment by deivid-rodriguez** [comment]
Hi @luizkowalski, I didn't get to my linux machine yet but I looked at the lockfile and found the issue. Bundler error message could be more informative but does explain the culprit, in particular,

>   The lockfile does not have all gems needed for the current platform

There's two platforms in your lockfile, `x86_64-darwin-20` and `ruby` (which is the "generic" platform that resolves only to not platform specific versions of gems). Since your CI runs on Linux and in frozen mode (only information from the lockfile can be used), bundler chooses `ruby` as the only possible compatible platform, but the lockfile is incomplete for `ruby`. In particular, the only version of `nokogiri` included in the lockfile is `nokogiri (1.12.5-x86_64-darwin)`, which is not compatible with Linux.

The issue was introduced by https://github.com/luizkowalski/concurrent_rails/commit/66c07c6d309806c43ebab77f23ec93c7c0d4b75c, see how that commit removes the pure ruby variant of `nokogiri` from the lockfile: https://github.com/luizkowalski/concurrent_rails/commit/66c07c6d309806c43ebab77f23ec93c7c0d4b75c#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL95-L97.

So, the question is why/how that lockfile was generated. Unfortunately I tried all versions from bundler 2.1.4 and up over the tip of your main branch with the lockfile changes reverted, and none of them removed the pure ruby version of `nokogiri`. My current platform is `arm64-darwin20` not `x86_64-darwin-20`, not sure if that could be related. So can try under `x86_64-darwin-20` to make sure.

Anywyays, you can fix the issue by restoring the pure ruby version to the lockfile using `bundle lock --add-platform ruby` and commit back the result.

**Comment by luizkowalski** [comment]
wow, good catch! I totally missed that. 
`ruby` was there already, so I had to remove the line from the lockfile and run `bundle lock --add-platform ruby` again it worked!

yeah, my dev env is a mess, I test on linux but I code sometimes on an intel mac and sometimes on an m1 so things get lost in translations sometimes

Thanks a lot! I'm closing this now

**Comment by deivid-rodriguez** [comment]
Glad it's fixed, I'll try to improve this error message to make this issue easier to figure out.

> ruby was there already, so I had to remove the line from the lockfile and run `bundle lock --add-platform ruby` again it worked!

I think `bundle lock --add-platform ruby` should just work and add back `Nokogiri` without removing `ruby` from the lockfile. In general, don't edit the lockfile directly, this ticket is a good example of why 😅.
