### ISSUE TITLE
bundle install --local with no Gemfile.lock does not obey "without" config

### ISSUE THREAD

**Issue by prahal** [rubygems/rubygems#5072]
Running bundle install --local when no Gemfile.lock is there or if it was removed
does not honor the bundle config "without".

repro script is [repro-1501.sh](https://gist.github.com/prahal/19635540d299bd9ad24369c2269ee10c)

## Environment

```
Bundler       2.2.5
  Platforms   ruby, x86_64-linux
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc
RubyGems      3.2.5
  Gem Home    /var/lib/gems/2.7.0
  Gem Path    /home/prahal/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /home/prahal
  User Path   /home/prahal/.local/share/gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/bin/ruby2.7
bundle #!     /usr/bin/ruby

```

## Bundler Build Metadata

```
Built At          2021-11-13
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
without
  Set for your local app (/tmp/repro-1501/.bundle/config): [:development]
```

That is without a Gmefile.lock and a Gemfile containing only a development gem, runnning
`bundle config set --local without 'development'`
has no effect and:
`bundle install --local`
still attempts to install development gems.

Is it expected ? That is is a Gemfile.lock required when calling install with --local ?

**Comment by deivid-rodriguez** [comment]
Hello! This is expected, let me explain why it works like this.

There's two steps on a `bundle install --local` run without a `Gemfile.lock` file. First `bundler` needs to resolve dependencies so that it knows what it needs to install, let's call this "dependency resolution" step. Then it needs to install them, let's call this "install" step. For both steps, when `--local` is used, bundler should perform them offline, resolving from cached and installed gemspec information and installing from cached gem packages.

Now, about the `without` configuration, and I think we need to better document this since it has come up a few times, this setting only applies to the "install" step. The "dependency resolution" step does not consider the `without` setting, instead, dependencies must be always resolved for a `Gemfile` as a whole. This is why `bundle install --local` gives an error about breakman being missing in this case, because brakeman dependency information is needed for `bundler` to resolve (regardless of the `without` setting) and that's not present locally.

The reason why `bundler` does not consider `with` / `without` settings for resolution is that the application should always use the same exact dependency regardless of the groups you are activating. So, say you have the following `Gemfile`, where gem `depends_on_activesupport_1` depends on `activesupport >= 1.0, < 2.0`, while gem `depends_on_activesupport_2` depends on `activesupport >= 2.0`

```ruby
gem "depends_on_activesupport_1"

group :development do
  gem "depends_on_activesupport_2"
end
```

If `bundler` considered `without` groups for resolving, your application would be using activesupport 1.x in your production environment but activesupport 2.x in your development environment and that would be a mess.

In other ecosystems, for example `npm`, this is not an issue, because due to how you load code in `javascript`, `depends_on_activesupport_1` could use its own namespaced version of `activesupport 1.x` while `depends_on_activesupport_2` could use it own namespaced version of `activesupport 2.x` at the same time. But in `ruby` this is not so flexible, so we need to be more strict.

I'm going to close this issue since I don't think we should be changing anything here, but feel free to contribute us a PR to make the documentation about this more clear.

Thanks!!

**Comment by prahal** [comment]
Thanks a lot for the reply. I still do not understand, though I believe I am close.

First, do you mean the two steps (resolve dependencies and install) are specific to the "bundle install --local" without a Gemfile.
Ie, such that if the Gemfile.lock is there, the resolve dependency step is taken as already done.

Finally, why is that "the application should always use the same exact dependency regardless of the groups you are activating" is needed for "bundle install -local" but not "bundle install". Ie both without a Gemfile.lock , the "--local" call will take into account activesupport_1 and activesupport_2 while the bundle install call without "--local" will only take into account activesupport_1. Why is it mandatory only for the "--local" call. Or do you mean that somewhat the call without "--local" when do also take into account activesupport_2 ?

Thanks!

**Comment by deivid-rodriguez** [comment]
Yes, sorry for the lack of clarity. Some of the things I explained above are applicable in general to `bundle install`, not particular to `bundle install --local`.

> First, do you mean the two steps (resolve dependencies and install) are specific to the "bundle install --local" without a Gemfile.
Ie, such that if the Gemfile.lock is there, the resolve dependency step is taken as already done.

Correct, if a `Gemfile.lock` is there, sometimes `bundler` is able to completely skip the resolution step and use exclusively the resolution already recorded in the `Gemfile.lock` file.

> Finally, why is that "the application should always use the same exact dependency regardless of the groups you are activating" is needed for "bundle install -local" but not "bundle install". Ie both without a Gemfile.lock , the "--local" call will take into account activesupport_1 and activesupport_2 while the bundle install call without "--local" will only take into account activesupport_1. Why is it mandatory only for the "--local" call. Or do you mean that somewhat the call without "--local" when do also take into account activesupport_2 ?

That is applicable for both `bundle install` and `bundle install --local`. Before even trying to install anything bundle needs to know which version it needs to install, and to figure out which version it needs to install it needs to resolve (or use a resolution pre-recorded in the `Gemfile.lock` file) using all groups, so that the version that gets chosen does not depend on the specific groups that are configured for the current environment. The only difference between `bundle install` and `bundle install --local` is that with `--local`, only dependency information and packages available offline are used.

**Comment by prahal** [comment]
> > Finally, why is that "the application should always use the same exact dependency regardless of the groups you are activating" is needed for "bundle install -local" but not "bundle install". Ie both without a Gemfile.lock , the "--local" call will take into account activesupport_1 and activesupport_2 while the bundle install call without "--local" will only take into account activesupport_1. Why is it mandatory only for the "--local" call. Or do you mean that somewhat the call without "--local" when do also take into account activesupport_2 ?
> 
> That is applicable for both `bundle install` and `bundle install --local`. Before even trying to install anything bundle needs to know which version it needs to install, and to figure out which version it needs to install it needs to resolve (or use a resolution pre-recorded in the `Gemfile.lock` file) using all groups, so that the version that gets chosen does not depend on the specific groups that are configured for the current environment. The only difference between `bundle install` and `bundle install --local` is that with `--local`, only dependency information and packages available offline are used.

Then I am puzzled. That explain why "bundle install --local" fails without a Gemfile.lock but suceed with one.
But both "bundle install" and "bundle install --local" without a Gemfile.lock should resolve dependencies alike and the install step in both cases should take into account the "without" config setting.
Thus I do not understand, from the above rationale, why "bundle install" without a Gemfile.lock does not error out but "bundle install --local" without a Gemfile.lock do error out :-/
This as both resolve without the "without" setting and the error is told to be at the resolve step (as it cannot be at the install step as this step is told to take "without" into account). Ie I do not understand why the plain "bundle install" succeed.

Sorry for me being slow to grasp the concept.
Do you mean that both uses all group to resolve dependencies without a Gemfile.lock (per with a Gemfile.lock this step is bypassed), but that the call with the "--local" flag has an extra resolve dependency step that makes it fail ?

I mean to tell is that plain "bundle install"  does not download bakeman which is in the development group. Why "bundle install --local" fails on bakeman. The fact that it depends on it but it is not available offline ? That would be my extra "--local resolve step.
Or otherwise, is the fact that plain "bundle install" without a Gemfile.lock works because it also resolve bakeman but the search for the bakeman package - this time online - is also a resolve step and that it succeed to find bakeman online and all is thus good ?

As it shows I am still a tiny confused.
Thanks for your patience.

**Comment by deivid-rodriguez** [comment]
> But both "bundle install" and "bundle install --local" without a Gemfile.lock should resolve dependencies alike and the install step in both cases should take into account the "without" config setting.

Correct.

> Thus I do not understand, from the above rationale, why "bundle install" without a Gemfile.lock does not error out but "bundle install --local" without a Gemfile.lock do error out :-/
This as both resolve without the "without" setting and the error is told to be at the resolve step (as it cannot be at the install step as this step is told to take "without" into account). Ie I do not understand why the plain "bundle install" succeed.

The reason is that for resolving, `bundler` needs to know the dependency constraints of all gems in the `Gemfile`, so that it can find a set of versions that satisfy all requirements. In absence of a `Gemfile.lock` file, `bundler` can find this information through the following:
* Installed gem specifications.
* A remote dependency API provided by each gem source.  For example, https://rubygems.org/info/brakeman.

If `bundle install --local` is used, only installed gem specifications are considered. But since `brakeman` is not installed on your system, and `bundler` cannot use a remote dependency API since the command must run offline, it has no way of figuring out which dependencies `brakeman` has on other gems.

> I mean to tell is that plain "bundle install" does not download bakeman which is in the development group. Why "bundle install --local" fails on bakeman. The fact that it depends on it but it is not available offline ? That would be my extra "--local resolve step.

Plain `bundle install` does not download and install the brakeman `.gem` package, but it does download dependency information about brakeman.

Hope this makes it more clear!

**Comment by prahal** [comment]
Thanks a lot; That extra resolve from remote dependency API step not shared between "--local" and non "--local" made it clear. They do not resolve the same way thus why one fail while the other does not.

The whole point was to sort out if deleting the Gemfile.lock and calling bundle install --local to check dependency was sensible as that is what debian redmine packaging does in its [postinst](https://sources.debian.org/src/redmine/4.0.7-1/debian/postinst/) .
With this new understanding of bundle install --local, this call looks fragile.

Though I have a note that I had to do the same rm Gemfile.lock, bundle install --local dance in 2016 to cope with the Gemfile.lock pointing to an old ruby-heredis system gem that was since upgrade system wide to a new release.

And my belief is that postinst script ought not to require network (to allow preseeding probably). Though I may be wrong on this one. So no plain bundle install.

Thus the whole concept of checking the dependencies in a postinst script might be unreachable per this new understanding.

So now the point is clear. One cannot expect bundle install --local to succeed (checking the dependencies) if all the gems (including development, test, etc) are not available offline.

Best wishes
