### ISSUE TITLE
Add a lock to use ruby builtin gem exclusivity in bundler if one gem is ruby builtin.

### ISSUE THREAD

**Issue by zw963** [rubygems/rubygems#5077]
### Describe the problem as clearly as you can

Here we describe a real use case.

I am working on a project, which use ruby 3.0.2, because i prefer use less gem as the first consideration, so i want to use
ruby builtin rake, minitest for write test.

it works after add a Rakefile. i can run test with `rake` or `rake TEST='test/some_test.rb`, without need change anything to Gemfile.

But, this solution lack some feature, e.g. run test suite which around the line specified by the line number, like following on rspec.

```sh
rspec spec/some_spec.rb:120
```

So, i introduce a new gem, name `m` now i can run test like this

```sh
m test/some_test.rb:120
```

But i get error message like this:

![image](https://user-images.githubusercontent.com/549126/142230632-ec5b5958-8c5f-4ba7-92e4-46d7e08b729c.png)

AFAIK, the only way to solve this issue is, add `gem 'minitest'` into Gemfile. it works!

But, it install a more newer version of "minitest" instead of builtin, that not what i want.

### What were you expecting to happen?

When add `gem "minitest"` into Gemfile, or, introduce one new option to bundler, which can always use ruby builtin gem instead of install new one.

### What actually happened?

it install a newer version minitest instead, 

For now, i have to specify minitest with a exact version. e.g.

```rb
group :test do
  gem 'minitest', '5.14.12' # 5.14.12 is the ruby 3.0.2 builtin version.
end
```

to avoid install newer, and use builtin version.

**Comment by deivid-rodriguez** [comment]
Hi!

What you call builtin gem is just a regular gem that comes preinstalled with ruby, so we don't have a way of distinguishing these builtin gems from regular gems. Also, I don't feel we need to distinguish them, since they are essentially the same thing. Depending on the packager, they might not even be there!

Besides that, bundler always prefers a higher version if available and not locked to something else, and I think that's a good thing because it picks up but fixes & security fixes by default.

If you still want to lock yourself to older versions, you should do exactly what you did: tell bundler which version you want. I don't think we need any new feature here, and as I said above, I wouldn't know how to implement it anyways.
