### ISSUE TITLE
`gem install` should fallback to ruby variants if platform specific variants don't support the current ruby version

### ISSUE THREAD

**Issue by joax01** [rubygems/rubygems#5082]
### Which command did you run?

gem install --user-install decidim  

### What were you expecting to happen?

gem installed

### What actually happened?

Problem
ERROR: Error installing decidim:
The last version of pg (~> 1.1.4, < 2) to support your Ruby & RubyGems was 1.1.4. Try installing it with `gem install pg -v 1.1.4` and then running the current command again
pg requires Ruby version >= 2.2, < 2.7.dev. The current ruby version is 2.7.4.191.

ERROR: Error installing decidim:
There are no versions of decidim-api (= 0.25.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
decidim-api requires Ruby version >= 2.7. The current ruby version is 2.6.8.205.

**Comment by deivid-rodriguez** [comment]
Thanks for trying harder to report better issues.

The problem is that, since you are on Windows, rubygems is preferring [the windows specific version of pg-1.1.4](https://rubygems.org/gems/pg/versions/1.1.4-x64-mingw32), which has a ruby requirement of `>= 2.2, < 2.7.DEV`, which does not match your current ruby version (2.7). Ideally in this case, `rubygems` should fallback to the [pure ruby version of pg-1.1.4](https://rubygems.org/gems/pg/versions/1.1.4) which works on `ruby >= 2.0.0`, and thus supports your ruby version (2.7). I don't think we currently do that, so this is a valid improvement for the `gem` CLI. Just to confirm, what's the result of `gem --version`? Does the issue also happen after running `gem update --system`?


To workaround the issue, here are a couple of ideas:

* Try `gem install decidim --platform ruby`, but this will not install platform specific gems, and I'm not sure it will work. 
* Report this to the decidim project, so that they relax or bump the dependency on `pg` to allow newer versions that support 2.7 on Windows.

**Comment by deivid-rodriguez** [comment]
Actually I tried this using the latest rubygems version and it works fine, so we must have fixed it at some point. Upgrade rubygems using `gem update --system` and it should work fine 👍.
