### ISSUE TITLE
Support gemification of `set`

### ISSUE THREAD

**Issue by casperisfine** [rubygems/rubygems#5127]
Right now on Ruby 3.0, if you run:

```ruby
$ gem install set
$ bundle exec some/script/using/set.rb
```

You'll get the following double load warning:

```ruby
/opt/rubies/3.0.3/lib/ruby/3.0.0/set.rb:648: warning: already initialized constant Set::InspectKey
~/.gem/ruby/3.0.3/gems/set-1.0.2/lib/set.rb:815: warning: previous definition of InspectKey was here
```

Based on previous similar issues I suppose `set` has to be vendored as well? Or PR simply not used anymore (it's mostly a Hash decorator in the end).

**Comment by deivid-rodriguez** [comment]
I guess yeah. Which rubygems version are you using? According to the test suite, this should've been fixed since rubygems 3.2.6

https://github.com/rubygems/rubygems/blob/a5a1c7f0828ab3c52e75ebbbc88e92a4740b9208/bundler/spec/runtime/setup_spec.rb#L1327

But there may be some situation where `set` is still loaded internally?

**Comment by casperisfine** [comment]
```
$ gem --version
3.2.32
```

That's the version that ships with a fresh ruby 3.0.3

**Comment by casperisfine** [comment]
Apologies, after digging a bit more, this is a `spring` problem. I'll fix it there.

Thank your for such a timely response.

**Comment by deivid-rodriguez** [comment]
Awesome, no problem! Thanks for your work.
