### ISSUE TITLE
NoMethodError: undefined method `metadata' for nil:NilClass since bundler 2.2.32

### ISSUE THREAD

**Issue by willnet** [rubygems/rubygems#5183]
### Describe the problem as clearly as you can

```ruby
source 'https://rubygems.org'

platforms :jruby do
  gem 'railties'
end

gem 'railties'
```

with `bundle` raise an error. 

#5113 was resolved by 2.2.33, but the Gemfile still raise an error with 2.2.33.

### Did you try upgrading rubygems & bundler?

I tried it with the following tools. 

- ruby 3.0.3
- bundler 2.2.33
- gem 3.2.33

bundler 2.2.31 doesn't raise an error, but 2.2.32, 2.2.33 does.

### Post steps to reproduce the problem

```sh
git clone https://gist.github.com/willnet/f3db323451042b724dd0501f458c378a
cd f3db323451042b724dd0501f458c378a
bundle
bundle
```

### What were you expecting to happen?

Both bundle finishes successfully.

### What actually happened?

error occurs

https://gist.github.com/willnet/f3db323451042b724dd0501f458c378a#file-error_log-txt

**Comment by simi** [comment]
If I understand this well, second Gemfile entry is just ignored and since `jruby` platform is missing in lock, gem is not added into lock file (even resolved).

`bundle lock --add-platform jruby` should fix this. As mentioned in the warning, you should not specify one gem twice. You can add related platforms to platforms argument.

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'railties', platforms: [:jruby, :ruby]

# command to lock it initially
bundle lock --add-platform jruby
```

On the otherside, bundler should not crash no `nil` error and report someting useful.

**Comment by deivid-rodriguez** [comment]
Bisected to https://github.com/rubygems/rubygems/pull/5078/commits/afaf868b68d68aa4eb98d19a2bb520c0d69b5ed2.

**Comment by deivid-rodriguez** [comment]
#5187 should fix this!
