### ISSUE TITLE
rubygems 3.3.3 is causing issues on NFS filesystems

### ISSUE THREAD

**Issue by goalkeeper007** [rubygems/rubygems#5257]
Our docker image is constructed based off `FROM selenium/standalone-chrome`. In addition to other packages, we install rubygems and bundler at some point using `gem update --system` and `gem install bundler --force`.

After installation of rubygems, we would get an error running ANY gem/bundle commands (like gem list etc), output would have this common error string-
`from /usr/local/lib/site_ruby/2.6.0/rubygems.rb:793:in `block in open_with_flock’
/usr/local/lib/site_ruby/2.6.0/rubygems.rb:793:in `flock’: Bad file descriptor @ rb_file_flock - /var/lib/gems/2.6.0/specifications/rubygems-update-3.2.33.gemspec (Errno::EBADF)`
another string
`from /usr/local/lib/site_ruby/2.6.0/rubygems.rb:793:in `block in open_with_flock’
/usr/local/lib/site_ruby/2.6.0/rubygems.rb:793:in `flock’: Bad file descriptor @ rb_file_flock - /var/lib/gems/2.6.0/specifications/os-1.1.1.gemspec (Errno::EBADF)`

the erroronous configuration is as below:

`RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.3
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /home/seluser/.local/share/gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.6
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/seluser/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.6.0
     - /home/seluser/.local/share/gem/ruby/2.6.0
     - /usr/lib/ruby/gems/2.6.0
     - /usr/share/rubygems-integration/2.6.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin`

bundler version is 2.3.3

Installing older gem version 3.2.33 fixes the issue. So we have a workaround for now. 
I appreciate any help actually fixing the issue or linking to an existing issue. (There are a few reported but could not pinpoint to one)

**Comment by deivid-rodriguez** [comment]
😞

Can you show a complete backtrace, by running whatever command is failing with the `--verbose` flag?

**Comment by goalkeeper007** [comment]
@deivid-rodriguez Unfortunately I cant get back to installing 3.3 from scratch as it would cause service disruption. But attached are the 
1. command output if I just try to install the newer version of rubygems while 3.2.33 is installed.
[gem install error.txt](https://github.com/rubygems/rubygems/files/7810277/gem.install.error.txt)

2. error on original setup where [3.3.3] was installed on fresh install.
[gem install error original setup.txt](https://github.com/rubygems/rubygems/files/7810282/gem.install.error.original.setup.txt)

3. screenshot of similar example on original setup where 3.3 was installed on fresh install.
![image (5)](https://user-images.githubusercontent.com/19277973/148120516-3674113b-f4e6-4130-86ca-3bc83ce648a3.png)

**Comment by deivid-rodriguez** [comment]
Does this patch fix things?

```diff
diff --git a/lib/rubygems/stub_specification.rb b/lib/rubygems/stub_specification.rb
index 47fe7da695..3f0c040ce1 100644
--- a/lib/rubygems/stub_specification.rb
+++ b/lib/rubygems/stub_specification.rb
@@ -9,7 +9,7 @@ class Gem::StubSpecification < Gem::BasicSpecification
   PREFIX = "# stub: ".freeze
 
   # :nodoc:
-  OPEN_MODE = 'r:UTF-8:-'.freeze
+  OPEN_MODE = 'r+:UTF-8:-'.freeze
 
   class StubLine # :nodoc: all
     attr_reader :name, :version, :platform, :require_paths, :extensions,
```

**Comment by goalkeeper007** [comment]
Is this the only change and is the file location correct @deivid-rodriguez?
`grep OPEN_MODE /usr/lib/ruby/2.6.0/rubygems/stub_specification.rb
  OPEN_MODE = 'r+:UTF-8:-'.freeze`

`gem update --system 3.3.3 --verbose` ended up with same error as before.

**Comment by deivid-rodriguez** [comment]
Maybe some other changes are needed, my patch was meant to fix the error in 3. (the screenshot). I will review others.

**Comment by deivid-rodriguez** [comment]
I guess since I only added `flock` at these spots to fix some race conditions on Windows, we could also try this:

```diff
diff --git a/lib/rubygems.rb b/lib/rubygems.rb
index 26fb93cbfb..584612e401 100644
--- a/lib/rubygems.rb
+++ b/lib/rubygems.rb
@@ -788,7 +788,7 @@ def self.write_binary(path, data)
 
   def self.open_with_flock(path, flags, &block)
     File.open(path, flags) do |io|
-      if !java_platform? && !solaris_platform?
+      if win_platform?
         begin
           io.flock(File::LOCK_EX)
         rescue Errno::ENOSYS, Errno::ENOTSUP
```

I think this should fix your issue as well and hopefully won't cause any other problems.

**Comment by goalkeeper007** [comment]
I tried this change at rubygems.rb at a few places I found on the disk, it did not work upgrading gem version to 3.3.3. 
I think I should get an environment setup with rubygems 3.3.3 from scratch instead of trying to upgrade from 3.2. I am trying to set that up so I can test this independently.

**Comment by deivid-rodriguez** [comment]
Ok, thanks @goalkeeper007. I think this is probably because due to the way rubygems upgrades itself, you need the fix in the version you upgrade to, not in the version you upgrade from. If this is the culprit, you could try cloning the rubygems repository, apply the proposed fix manually, run `gem build rubygems-update` and `gem install rubygems-update-3.3.3.gem`. That way `gem update --system` should pick up the patched 3.3.3 version from your local system and upgrade to that.

Alternatively, if you can share a Dockerfile that reproduces the issue I can take a closer look too.

**Comment by goalkeeper007** [comment]
@deivid-rodriguez I was able to recreate the environment and confirm that the suggested [single line change] in /usr/local/lib/site_ruby/2.6.0/rubygems.rb fixed the errors with gem and bundle commands. Thanks. I will be able to do more end to end test if you have a release for the fix.

**Comment by deivid-rodriguez** [comment]
Great! Are you able to share the recreated environment so that I can reproduce the issue myself. Just for the sake of understanding more deeply how this is happening so that I'm able to create a regression test for the change. If you're not able to do that I guess we can still try the fix, given that this is how it worked previously (no flock) and it caused no issues on Linux.

**Comment by goalkeeper007** [comment]
@deivid-rodriguez That might be hard. The environment is behind corporate network and the dockerfile is combination of different in house images.

**Comment by deivid-rodriguez** [comment]
I would appreciate if you could at least try. You could start removing private layers until you have a base minimal image that you can share and still reproduces the problem.

**Comment by RandieM** [comment]
I think that the following statement _may_ be the key to the problem, if the corporate network is using NFS.

> The environment is behind corporate network

We have been having the same issue with different combinations of Linux distributions (Fedora, Debian) and NFS, but the problem seems to lie in the latter. Following the changes suggested here: https://bugs.ruby-lang.org/issues/18437?tab=history, we could solve the problem. I was thinking of opening a PR with these changes, since I could not find one submitted by the original author, but then I noticed another PR that totally removes flock for Linux and I thought that this might also do the trick (not sure, though, if the problem will persist for Windows/NFS or not).

**Comment by deivid-rodriguez** [comment]
I see, this sounds not straightforward to get tested in CI, so I'll move on with #5278 for now.
