### ISSUE TITLE
Very slow dependency resolving

### ISSUE THREAD

**Issue by cmhe** [rubygems/rubygems#5689]
### Describe the problem as clearly as you can

The step to resolve the project dependencies with bundler takes multiple hours.

### Did you try upgrading rubygems & bundler?

I tried it with 2.3.17 and a couple of other older releases of bundler:

```
$ bundle --version
Bundler version 2.3.17
```

### Post steps to reproduce the problem

With this Gemfile:

```
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

  gem "puppet-module-posix-default-r2.7", '~> 1.0', require: false
  gem "puppet-module-posix-dev-r2.7", '~> 1.0',     require: false
  gem "github_changelog_generator",                 require: false
  gem "puppet-module-posix-system-r2.7", '~> 1.0',  require: false
  gem "librarian-puppet",                           require: false
```

I also tried it inside a Docker container:

```
FROM ruby:2.7.6-slim

ADD Gemfile /root/Gemfile

RUN gem install --version '= 2.3.17' bundler && \
        bundle --version && \
        cd /root && \
        bundle config set --local path vendor/bundle && \
        bash -c 'time bundle install'
```

The build inside the Docker container fails, because of missing build dependencies, however bundler mostly spends resolving dependencies there and the final time output, after it fails to build is:

```
real    332m27.595s
user    331m56.310s
sys     0m21.727s
```

So over 5 hours.

Which is the same on my host, where the build of those dependencies succeeds.

### Which command did you run?

```
bundle config set --local path vendor/bundle
bundle install
```

With the `Gemfile` posted above in place.

### What were you expecting to happen?

Resolving dependencies in under 5 minutes.

### What actually happened?

Resolving dependencies in over 5 hours.

### If not included with the output of your command, run `bundle env` and paste the output below

I used the docker container, so the environment should be clear. I can however post it as well if required...

**Comment by indirect** [comment]
Wow, congratulations on finding such a pathological resolver case! It's been years since I've seen one this bad. 😁

I suspect it will take some time to fix this, so in the meantime, here is a workaround you can use to get a complete resolution and a working Gemfile.lock:

Start with this Gemfile:

```
source "https://rubygems.org"
```

Then run:
- `bundle add puppet-module-posix-default-r2.7`
- `bundle add puppet-module-posix-dev-r2.7`
- `bundle add puppet-module-posix-system-r2.7`
- `bundle add github_changelog_generator`
- `bundle add librarian-puppet`

Commit the resulting `Gemfile.lock`, and you should have something you can use for now.

**Comment by ansonhoyt** [comment]
The workaround helped. 🙏 

`bundle add rails --version '~> 7.0.3'` quickly showed `Bundler could not find compatible versions`:

```sh
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies.....
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 6.1.6)

  In Gemfile:
    populate was resolved to 0.1.0, which depends on
      activemodel (>= 5.2, < 6.2)

    rails (~> 7.0.3) was resolved to 7.0.3, which depends on
      activemodel (= 7.0.3)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

After I allowed Rails 7.0 in `populate`'s gemspec (my private gem), upgrading with`bundle update` worked normally/quickly. 🎉

**Comment by nvasilevski** [comment]
Hey folks, sorry for chiming in 🙇 
I was wondering if @ansonhoyt could run bundler with `--verbose` flag to see if anything specific is taking the most of the time. We are looking into some dependency resolution slowness and in our case bundler tries to fetch every available `gemspec.rz` of a particular gem, like:
<img width="147" alt="image" src="https://user-images.githubusercontent.com/5512772/178554542-eb8e4c3a-e546-4431-a3cf-7d848f6931b6.png">
Most likely called from here:
https://github.com/rubygems/rubygems/blob/46a92b2b033e1e42a780ab5559782aacca3230a4/bundler/lib/bundler/fetcher.rb#L113
It becomes better on the second run because of the cache, I assume, but still takes significant time because of the iteration over all available versions:
https://github.com/rubygems/rubygems/blob/46a92b2b033e1e42a780ab5559782aacca3230a4/bundler/lib/bundler/fetcher.rb#L110-L111

It doesn't seem to do it on `bundle _2.2.33_ update --verbose`

I'll poke around a bit more to have a clear reproduction and maybe a suggested solution 

Thanks!

**Comment by deivid-rodriguez** [comment]
I think you're running into #5385.

**Comment by jesse-shopify** [comment]
I'm using Bundler 2.3.4 until #5385 is resolved.

**Comment by deivid-rodriguez** [comment]
If you're using a gemstash based server, I recommend you check out https://github.com/geminabox/geminabox/pull/435!

**Comment by deivid-rodriguez** [comment]
Just tried this reproducer against #5960 and it now resolves in 5 seconds! 🎉
