### ISSUE TITLE
Bundler "fatal: Needed a single revision" error getting a tag

### ISSUE THREAD

**Issue by drstrangelooker** [rubygems/rubygems#5693]
I don't think this requires any fixes, but I could not find any documentation. This might be good to add to that documentation.

I ran into this issue in an internal project. We did a workaround so I can't test, but I just traced some bundler source code. It was failing in our automated test environment but not on the desktop. 

This failed:
```
gem 'my-gem', :git => "https://my-server/my-gem.git", :tag => 'v0.1.0'
```

The error looked like this...
```
Fetching https://my-server/my-gem.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify v0.1.0` in directory
```

We discovered that normally git branches are pulled by the `git clone`, but not all tags. Tags that are already part of a branch come in. Tags that are not on a branch don't always get pulled. The tag `v0.1.0` was not on a branch. To workaround we just created a branch that contained the tag in question. 

In the future it might work if you specify the reference like this...

```
gem 'my-gem', :git => "https://my-server/my-gem.git", :tag => 'refs/tags/v0.1.0'
```

If you look at the code I link, you see that triggers the value `extra_ref` to be set, which triggers an additional git fetch to get that ref specifically.

https://github.com/rubygems/rubygems/blob/6a655a698e952f897d0d014fc11bae4b608528ce/bundler/lib/bundler/source/git/git_proxy.rb#L88-L104

It does a two step process. First it does something like this... (The ./foo is a target directory. It can be anything.)
```
git clone --bare --no-hardlinks --quiet -- https://my-server/my-gem.git ./foo
```

Then it does this...
```
git --git-dir=./foo fetch --force --quiet --tags -- https://my-server/my-gem.git refs/heads/*:refs/heads/* refs/tags/v0.1.0:refs/tags/v0.1.0
```
which will explicitly get the tag in question.

This second step is done whenever the reference begins with `ref/`.

**Comment by deivid-rodriguez** [comment]
Could we replace `--tags` with `refs/tags/*:refs/tags/*` to fetch all tags?

**Comment by deivid-rodriguez** [comment]
Ideally I would like things to just work and potentially remove the explicit `refs/` trick in the future.

**Comment by deivid-rodriguez** [comment]
This has been fixed recently by several changes when dealing with git sources. Should be fine now 💪.

**Comment by sergiogomez** [comment]
Hey! 😉 

I have a question about this issue. I have a similar issue installing a gem using a tag from a private repo (using `https`), and I've checked that the initial checkout is not fetching all the tags from the git repo (I've checked the downloaded gem and the cache folder for bundler).

Is that the expected behaviour? Because I didn't have that issue using ssh (`git@`) instead of `https`, and both folders (the gem and the cache) had all the tags from the repo. I'm using the latest versions of both bundler and rubygems.

Thanks in advance!

**Comment by deivid-rodriguez** [comment]
It should work. Even if Bundler is not fetching all tags, it should be fetching the one tag you need. This is an optimization is Bundler 2.4, but it should be completely transparent to users. Users may experience faster checkout of git sources but that's all. If this is not your experience, we'd need some way to reproduce what you are seeing, so that we can help!

**Comment by sergiogomez** [comment]
Thanks for the quick answer!

Yes, you're right, and it does work. I mean, it always fetches the tagged commit, but sometimes it does not fetch the annotated tag, and our particular issue comes because we were using this hack to specify the version of the gem:

```
Gem::Specification.new do |s|
  ...
  s.version = `git describe --tags`
  ...
```

So, when the annotated tag is not fetched, the gem version doesn't match with the tag.

That's why I was asking about the expected behaviour, because I'm pretty sure that we should remove that hack.

**Comment by deivid-rodriguez** [comment]
I see. Yeah, I don´t think that works anymore, since the only thing Bundler uses to know whether to optimize cloning is information from the Gemfile.
