### ISSUE TITLE
Some JRuby specs might not be running properly in the CI

### ISSUE THREAD

**Issue by johnnyshields** [rubygems/rubygems#5891]
For example this one: https://github.com/rubygems/rubygems/runs/8116674238?check_suite_focus=true

![image](https://user-images.githubusercontent.com/27655/187727207-5f56da09-203e-456c-865d-ce2128755a77.png)

**Comment by deivid-rodriguez** [comment]
This is intended! We actually only run a few specs on JRuby, and only on Linux. On Windows, all we make sure so far is that the development environment can be actually setup (the "install dependencies" step), which somehow at least exercises a bit our code on JRuby because we use HEAD bundler to install our own dependencies.

**Comment by deivid-rodriguez** [comment]
I'll close this since the current situation is intended. Happy to accept improvements in this area!
