### ISSUE TITLE
Support for full Semantic versioning

### ISSUE THREAD

**Issue by slantview** [rubygems/rubygems#592]
While gems are encouraged to use semver, it is not fully supported.

``` bash
Invalid gemspec in [mygem.gemspec]: Malformed version number string 0.1.0+build.45
ERROR:  Error loading gemspec. Aborting.
```

According to semver.org sections 9-11, "0.1.0+build.45" is a correctly formatted semantic version, but it is not allowed currently as are "0.1.0+alpha.2" or "0.1.0+beta.2" which are all correct according to semver.org.

If you would like to see a project that is correctly using the semver.org guide, check out https://github.com/RiotGames/thor-scmversion

Here is the Regex:

``` Ruby
VERSION_FORMAT = /^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-?(?<prerelease>#{Prerelease::FORMAT})?(\+build\.)?(?<build>\d+)?$/
```

**Comment by perlun** [comment]
> Doing it properly would require changing the version numbering rules, which is a giant deal because of backwards compat.

Thanks for all your hard work with Rubygems, Evan. It would be interesting to hear more about how it would break the versioning rules? I might be too naïve in my thinking here, but isn't this (partially) about making `1.0.0.beta.1` and `1.0.0-beta.1` be considered the same version? (and allowing the prereleases to include a hyphen instead of a period, to make the version string be SemVer compliant)

There are probably scenarios which I'm not aware of at the moment. Would you have some time to explain to me and others wich the major hurdles with this are, and which scenarios that would break?

(If this has been explained thoroughly elsewhere, my apologies - I searched but couldn't find any such discussion.)
