### ISSUE TITLE
Why does bundler cache gems into local install path?

### ISSUE THREAD

**Issue by blowfishpro** [rubygems/rubygems#6102]
### Describe the problem as clearly as you can

When the `path` option is set, bundler puts a cache of all the .gem files into the local install path (e.g. `vendor/bundle`) even though they are not needed for deployment.

### Did you try upgrading rubygems & bundler?

yes (rubygems 3.3.26 and bundler 2.3.26)

### Post steps to reproduce the problem

Tested in the official Ruby 3.1.2 Docker library image (`ruby:3.1.2`)

```bash
gem update --system --no-doc
mkdir /tmp/example
cd /tmp/example
bundle init
bundle add rake
bundle config set --local path vendor/bundle
```

### Which command did you run?

```bash
bundle install
ls vendor/bundle/ruby/3.1.0/cache/
```

### What were you expecting to happen?

`vendor/bundle` contains only the installed gems, not the packaged .gem files

### What actually happened?

.gem files appear to be cached into `vendor/bundle/ruby/3.1.0/cache/`.

After removing them and running some tests they do not appear to be needed for bundler to work correctly.  While harmless in principle, they can potentially add a lot of disk usage.  This is not ideal when trying to package for deployment (e.g. in a docker container).

I tried various combinations of settings and other tricks:
- `global_gem_cache` setting
- `BUNDLE_USER_CACHE` environment variable
- `deployment` setting
- packaging and then installing in separate steps:
  ```bash
  bundle config set --local no_install true
  bundle cache
  bundle install --local
  ```
  in this case the .gem files end up both in `vendor/cache` and `vendor/bundle/ruby/3.1.0/cache/`

Is there a way to get rid of this cache other than manually deleting all the .gem files?  If bundler needs a cache for downloads that's fine, but it seems like it shouldn't be here.

#### Environment

```
Bundler       2.3.26
  Platforms   ruby, aarch64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.26
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

#### Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

#### Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
path
  Set for your local app (/usr/local/bundle/config): "vendor/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

##### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rake", "~> 13.0"
```

##### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  rake (~> 13.0)

BUNDLED WITH
   2.3.26
```

**Comment by deivid-rodriguez** [comment]
When you configure Bundler to use a path relative to your project, the `GEM_HOME` location (the location where RubyGems installs and looks forgets) changes from your global Ruby installation to your local folder. That includes specifications, cached packages, install paths and anything else RubyGems needs to work.

I guessing the cache is not as necessary with a local install path, but it's just a cache, things should just work without it.

**Comment by blowfishpro** [comment]
Right okay.  So I guess the second half of my inquiry was really this: is there a way to either:
- Explicitly clean out the cache using bundler or rubygems commands
- Control the cache location

**Comment by deivid-rodriguez** [comment]
I don't think you can do either of those right now, no.

**Comment by h3xx** [comment]
This functionality is missing and should have a sane default, regardless of where bundler is configured to install its gems.

For example, `~/.bundle/cache/gem-cache/foo-0.0.1.gem`

Since the remote files aren't likely to change across `bundle install` invocations, it should be safe to store them in a shared path.

This behavior would mimic [`composer`](https://getcomposer.org/) and [`pnpm`](https://pnpm.io/).

**Comment by indirect** [comment]
The historical reason this does not exist is because RubyGems had a single "gem path" for both .gem files and for the installed gems. (For example, as if npm used `node_modules` for both the .tgz files and the unpacked packages). That led to a "global" install path and a "local" install path, but no shared cache of .gem files between them.

That said, I agree this is a good idea, and it would save both hard drive space and time during future installs. I believe it should probably default to `~/.cache/rubygems/gems`, and should be a shared cache for all RubyGems or Bundler installs on the same machine, since the .gem files do not change between Ruby, RubyGems, or Bundler versions.

**Comment by indirect** [comment]
I have opened https://github.com/rubygems/rubygems/issues/7249 to track adding such a cache.
