### ISSUE TITLE
Bundler 2.4.0.dev causes Rake to get downgraded on rails/rails

### ISSUE THREAD

**Issue by eileencodes** [rubygems/rubygems#6129]
### Describe the problem as clearly as you can

Hi! Recently our builds on rails/rails against Ruby trunk (3.2.0.dev) started failing. I narrowed it down to the following combination:

* Ruby trunk
* Bundler 2.4.0.dev
* Causes Rake to get downgraded from 13.0.6 to 12.3.3

You can see the nature of the failures here https://buildkite.com/rails/rails/builds/91646#01850dfd-0916-4175-8216-8a62744842a7/1110-1118.

I was able to reproduce locally by first ensuring that Bundler was on 2.4.0.dev and then running `bundle update`. I checked out all gem upgrades until I was down to just bundler + rake. The issue does not occur with a lower version of bundler. It also does not occur with a `bundle update rake`.

All of the Rails dependencies for Rake are all `>= 12.0` or `>= 11.0` so there's no obvious reason for a downgrade of that particular gem.

### Did you try upgrading rubygems & bundler?

Yes this is caused by the upgrade to the newest version of bundler.

### Post steps to reproduce the problem

I don't have a simple repro because it requires using edge versions of Rails, Bundler, and Ruby. But the problem is straight forward to reproduce if you have all three. I'm also trying to get a demo app running, but it's unclear exactly how I'll reproduce outside of the Rails tests.

Our builds automatically run `bundle update` to catch issues in gems. I don't understand why a full `bundle update` downgrades Rake but `bundle update rake` does not. 

* Either clone Ruby and compile from source and install it or use the nightly docker image https://hub.docker.com/layers/library/ruby/3.2.0-rc1/images/sha256-5334a7cdfb04c6fbf9a4154bbbed44c7b27811683defebe57b0c58aa76165bbf?context=explore. 
* Clone Rails and set that up as well
* Ensure the Ruby version is the one you installed
* Ensure bundler is 2.4.0.dev
* Run bundle update
* Run one of the failing bundler tests `bundle exec ruby -Ilib:test test/application/bin_setup_test.rb` and observe failures.
* Stash all changes except bundler and observe no failures.

Fill this with a list of steps maintainers can follow to reproduce your issue. Note that while you are seeing this issue in your computer, maintainers might not see the same thing on theirs. There is a number of things that could influence this:

* How your ruby is setup (OS package, from source, using a version manager).
    * I am able to observe this on both MacOS M1 (rosetta and arm) and Ubuntu Focal. I don't think this is platform related.
    * I am able to repro with chruby and rbenv, I don't think this is version manager related.
    * Requires Ruby trunk
* How bundler & rubygems are configured.
    *   Requires Bundler 2.4.0.dev
* The version of each involved piece of software that you are using.
    * Listed above, Ruby 3.2.0.dev, Bundler 2.4.0.dev, Rails main (but likely reproducible on 7.0, we don't run 7.0 against Ruby trunk)

The more complete the steps to simulate your particular environment are, the easier it will be for maintainers to reproduce your issue on their machines.

> Ideally, we recommend you to set up the list of steps as a [Dockerfile](https://docs.docker.com/get-started/). A Dockerfile provides a neutral environment that should give the same results, no matter where it's run.

I can try but I haven't had much luck with Docker...and we aren't permitted to use it on our work machines.

### Which command did you run?

`bundle update`

### What were you expecting to happen?

For Rake to not get downgraded.

### What actually happened?

Rake was downgraded causing failures in the Rails CI.

**Comment by eileencodes** [comment]
I totally missed that this is somehow related to Sneakers version bump as well. But there still seems to be something up since this doesn't happen on 2.3.x bundler and only 2.4.0.dev.

**Comment by deivid-rodriguez** [comment]
`bundle update` prioritizes upgrading direct dependencies even if that requires downgrading indirect dependencies.

`bundle update` aims to give you a result as similar as possible as `rm Gemfile.lock; bundle install`, and sneakers 2.12 + older rake is what `bundle install` without a `Gemfile.lock` would install.

If this is undesired, you could pin sneakers in the `Gemfile`, or add `rake` as a top level dependency if you're using it directly and don't want Bundler to potentially downgrade it to be able to update other direct dependencies.

As per why 2.3 does not manifest this behavior, I think it may be because of some fix/improvement in Bundler 2.4.

Does this make sense?

**Comment by deivid-rodriguez** [comment]
Actually, I see `rake` is actually a top level dependency? In that case, this is unexpected, I'll have a closer look.

**Comment by deivid-rodriguez** [comment]
I identified the issue and typed a fix that I need to validate now. Will keep you posted!

**Comment by deivid-rodriguez** [comment]
I created https://github.com/rubygems/rubygems/issues/6129 to fix this problem.

Also, the reason why this does not happen on Bundler 2.3 is indeed the migration to the PubGrub as mentioned by @skipkayhil at https://github.com/rails/rails/pull/46725#issuecomment-1351708235. While Molinillo resolves this Gemfile to Rake 13 + Sneakers 2.11 by default, PubGrub resolves to Rake 12 + Sneakers 2.12. And due to this bug, the Gemfile.lock pin is not respected and resolution from scratch happens.

**Comment by eileencodes** [comment]
Thank you @deivid-rodriguez!
