### ISSUE TITLE
Add a new entrypoint for bundler that automatically bundle installs

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#6242]
### Describe the problem as clearly as you can

We work in a large monolith and gems get bumped all the time. This means I find myself `bundle install`ing many times a day. And oftentimes, this is done after seeing a bunch of errors because, well my bundle is out of date.

Would it make sense to introduce another entry similar to `bundler/setup`? Eg...
```ruby
# instead of...
require "bundler/setup"
# you can do...
require "bundler/prepare"
```

This would automatically install your bundle if it's out of date. We can also take `BUNDLE_DEPLOYMENT` and `BUNDLE_FROZEN` into consideration. Maybe if deployment is enabled, it wouldn't auto install, and if frozen, it'd err if lockfile changes.

Separately, maybe Rails could use this in `config/boot.rb` such that `rails s` or `rails c` would just work. Binstubs would benefit from this as well? We have githooks that use the bundle and we would switch to `bundler/prepare`.

Happy to put up PR, but wanted to get feedback first.

**Comment by indirect** [comment]
Is there a reason to build this into Bundler itself, rather set up a tool like [tpope/hookup](https://github.com/tpope/hookup), which handles more than just `bundle install`?

**Comment by deivid-rodriguez** [comment]
By the way, we actually have a `bundle config auto_install true` setting that does this, but it only applies to selected CLI commands: https://github.com/rubygems/rubygems/blob/131085f1afeea7b76ec5c9fb3b37776d0163ac0e/bundler/lib/bundler/cli.rb#L11.

That doesn't fit your use case, since you want it for direct require of `bundle/exec`, but I wanted to mention it in case it's helpful and also ask how do you feel about @indirect's suggestion.

**Comment by ngan** [comment]
Hey! Sorry for the silence. I forgot about this. Hookup and other tools like this is…okay. In our experience, githooks are generally difficult to deal with. I was hoping bundle would consider taking care of this out of the box since it’s a very easy process. People who need more functionality can reach for githook tools. But this would satisfy the needs of most projects I suspect.

**Comment by indirect** [comment]
Can you say more about how you would want to use this? As David pointed out, we do already support auto-install for bundle exec if you set the config or env var. Do you need more than that?

**Comment by ngan** [comment]
An example is I would replace all the binstubs I have in my Rails app with: `require "bundler/prepare"` so that when I run `bin/rubocop` it will automatically install my bundle. Or, in `config/boot.rb` in my Rails app, replace `require 'bundler/setup'` with `require 'bundler/prepare' so that `bin/rails` will automatically install gems that I'm missing.

**Comment by ngan** [comment]
I want to point out that I understand there's other tools that can be used to facilitate this (eg git hooks), or even just modifying the binstub and `config/boot.rb` code to do this (by shelling out or something)....but this suggestion was more in asking whether or not bundler supports this out of the box.

Recently, bundler was given the feature to automatically update itself if the version of bundler specified in the lockfile differs from the one you have installed. Can this be done manually? yes. Can this be managed by something else? sure. But it was a huge quality of life improvement when it landed.

Likewise here, if my bundle is out of date and a simple `bundle install` fixes it, maybe the bundler should offer that as an option for things using `require 'bundle/setup'`?

**Comment by indirect** [comment]
@deivid-rodriguez how do you feel about extending the AUTO_INSTALL env var to also activate on `require 'bundler/setup'`? It seems like having it trigger on `bundle exec` is pretty close to that.

**Comment by ngan** [comment]
Great suggestion, André!

**Comment by deivid-rodriguez** [comment]
Makes sense to me too 👍.

**Comment by technicalpickles** [comment]
@ngan pointed this issue out to me, and wanted to share a bit more about the end-user experience we are trying to solve.

Our Gemfile.lock changes pretty frequently due to the number of gems we have (ie dependabot updates), and how we share code internally. In practice, I run into this a few times a day where I am changing branches, integrating main, etc, and the bundle becomes out of date.

I end up hitting it when going to run specs, or rails console, or whatever. I also hit it during our pre-commit hook which has commands that use bundler (rubocop, sorbet, and others). 

git-hooks could work for some cases, but rollout and setup can be annoying, and it would be project specific. There is at least one case I can think of which it doesn't catch it: when you are the one making a change but forgot to bundle 🙃
