### ISSUE TITLE
Some executables in the bundle use the #!/bin/sh wrapper when Ruby compiled with `--enable-load-relative` which fails to locate Ruby

### ISSUE THREAD

**Issue by ziggythehamster** [rubygems/rubygems#6314]
If you have Ruby compiled with `--enable-load-relative`, gems like Rake end up with `bin/rake` scripts that start like so:

```
#!/bin/sh
# -*- ruby -*-
_=_\
=begin
bindir="${0%/*}"
exec "$bindir/ruby" "-x" "$0" "$@"
=end
#!/opt/ruby2.7/bin/ruby
#
```

This does not work in a Bundle:

```
$ bundle exec rake -T
/build/vendor/bundle/ruby/2.7.0/bin/rake: line 6: /build/vendor/bundle/ruby/2.7.0/bin/ruby: No such file or directory
```

This is even the case if you fully remove `rake` from the Ruby installation and treat it like a Bundle-supplied gem only. It appears that @nobu took a stab at fixing this in #1817 and abandoned it because nobody uses load-relative and bundler. That's fair, but should Bundler warn about that if it doesn't rewrite the executable to either point at `"#{RbConfig::CONFIG['bindir']}/ruby"` or remove the shell portion?

Also, the answer to "why do you have `--enable-load-relative` enabled?" is that this build flag is used by the build script for Ruby at `$HUGE_COMPANY` and when I refactored our build process at `$SUBSIDIARY_OF_HUGE_COMPANY`, I copied their build flags. I'm going to remove this since I don't have a good reason to keep it :).

This happens with Bundler 2.4.5 / RubyGems 3.4.5 on Ruby 2.6, 2.7, 3.0, and 3.1 on both x86_64 and aarch64. Presumably, it's always happened :).

**Comment by rubyFeedback** [comment]
This ties into larger discussions - I remember I tried to explain to some established ruby
dev that using require_relative() in a bin/ file is not good because it assumes hardcoded
paths such as /usr/. I do not use the FHS on my custom linux system, yet all my ruby 
files and ruby bin executables work fine. The ruby dev did not understand the explanation,
largely because he did not understand "deviating use cases" - so I give a thumbs up to
ziggythehmaster. To me the question is not "why do you have --enabled-load-relative"
enabled. To me the question is why it does not work. Path issues are simple to understand
the moment people stop assuming everyone uses the FHS layout. Because that layout 
makes the brain become very, very lazy ...

**Comment by deivid-rodriguez** [comment]
I'm pretty sure this is now working as expected, but please do reopen if you're running into issues!
