### ISSUE TITLE
improve gem install --default

### ISSUE THREAD

**Issue by mpapis** [rubygems/rubygems#677]
Forwarding problems with the new [rubinius](https://github.com/rubinius/rubinius) and [rubysl](https://github.com/rubysl) => https://github.com/wayneeseguin/rvm/issues/2260 ... basically it is about standard library gems not found in few cases, usually with bundler.

What I would like to see from rubygems side is to make `gem install --default` to fully install the gems in `$LOAD_PATH` and build native extensions (like [zlib](https://github.com/rubysl/rubysl-zlib/blob/2.0/ext/rubysl/zlib/extconf.rb)), most of the code is in place there would be needed an extra `if` to recognize `--default-stdlib` - which would install the files in stdlib and compile extensions - compared to current `--default` which only adds specifications.

I'm opening this more for discussion and asking if that change would be approved, I can prepare code for it.

cc @headius, @brixen.

**Comment by copiousfreetime** [comment]
Checking in on the interest people have for how `--default` works.

**Comment by voxik** [comment]
I am interested in proper solution for default gems, i.e. something like I proposed in my previous comment. I don't care about --default option, since it solves just symptoms.

**Comment by enebo** [comment]
@voxik Can you uninstall those gems on Fedora?  If you do is Ruby in a broken state?

**Comment by voxik** [comment]
The problem is not with installation or uninstallation, that is why we have dependencies, but with Bundler, which knows nothing about default gems and projects typically does not specifies dependencies on them

**Comment by enebo** [comment]
@voxik I am not making an opinion on default gems.  I am just asking a question.  If I uninstall json in Fedora completely does Ruby stop bootstrapping?

**Comment by enebo** [comment]
I meant base json ruby library not some underlying C library (I hope that was obvious but I should clarify).

**Comment by headius** [comment]
There are a few issues with making things "just gems":

1. Startup time is impacted when RubyGems has to load. Normally on MRI (before 2.3) unless you use something installed as a normal gem, RubyGems does not have to do its full setup. In 2.3 they started loading the `did_you_mean` gem at boot, which impacted 2.3 startup time.
2. As @enebo mentions, if everything is "just gems" then a user can break their Ruby by uninstalling too much. Consider also that if you install multiple versions of a library that's has a default gem, you will have to uninstall each of them individually (since uninstall all would break Ruby).
3. Code is slower to load from gems than from stdlib. This is more a RubyGems architecture problem, since it does not know where to look for a given required file, but it's a real problem. Searching for a single file to load is O(n) where n = number of gems loaded.

Now, if gem install --default basically just made a gem uninstallable, that would at least fix @enebo's issue, but it would force us to load more of RG at boot and slow down lookups for default gems that become normal gems. If RG were improved, that might be less of a concern.

@voxik: Many of the gems that are "default" in MRI are actually sourced from MRI. I wouldn't consider those cases as MRI "bundling" a library as much as MRI permitting a built-in library to be overlaid by a gem.

**Comment by headius** [comment]
Oh, and for the @copiousfreetime: I'd like to see the feature be more useful, either by making "not-uninstallable normal gems" or by doing the rest of the install and copying files to stdlib.

**Comment by voxik** [comment]
@enebo 

```
$ LANG=en_US sudo dnf remove rubygem-json
Dependencies resolved.
================================================================================
 Package                    Arch        Version             Repository     Size
================================================================================
Removing:
 ruby                       x86_64      2.2.4-47.fc24       @rawhide       69 k
 ruby-irb                   noarch      2.2.4-47.fc24       @rawhide      162 k
 rubygem-bigdecimal         x86_64      1.2.6-47.fc24       @rawhide       88 k
 rubygem-coderay            noarch      1.1.0-5.fc23        @rawhide      2.4 M
 rubygem-io-console         x86_64      0.4.3-47.fc24       @rawhide       20 k
 rubygem-json               x86_64      1.8.3-100.fc24      @rawhide      149 k
 rubygem-method_source      noarch      0.8.2-2.fc23        @rawhide       16 k
 rubygem-pry                noarch      0.10.1-2.fc23       @rawhide      382 k
 rubygem-psych              x86_64      2.0.8-47.fc24       @rawhide      120 k
 rubygem-rdoc               noarch      4.2.0-47.fc24       @rawhide      1.7 M
 rubygem-slop               noarch      3.5.0-2.fc23        @rawhide       33 k
 rubygems                   noarch      2.4.8-100.fc24      @rawhide      898 k
 rubypick                   noarch      1.1.1-4.fc24        @rawhide      4.4 k
 vim-command-t              x86_64      1.13-1.fc24         @rawhide      231 k

Transaction Summary
================================================================================
Remove  14 Packages

Installed size: 6.3 M
Is this ok [y/N]: 
```

**Comment by voxik** [comment]
@headius 

> MRI permitting a built-in library to be overlaid by a gem.

I would agree with that if the loading mechanism were the same, but it isn't.

And you mention performance etc, but apparently, people does not care that much, otherwise there would be blogs such as "to speed up, you can run you ruby such as ```$ ruby --disable-gem -I/path/to/your/gem``` but I don't see such blogs.

**Comment by copiousfreetime** [comment]
Well, it definitely looks like there is still active interest in this issue :smile:.

**Comment by enebo** [comment]
@voxik so if someone does --force the important gem to be removed it would be akin to removing any other package on fedora via forcing it to ignore deps.  In that sense you can only protect people from bad actions so much.

If someone wanted to recover from a mistake like that would you just need to reinstall ruby?  Since removing a gem would break rubygems you could not just reinstall the gem anymore.   This scenario is what I was wondering about.

**Comment by voxik** [comment]
@enebo You cannot remove system gems using "gem uninstall". So you have to use system package manager for that. To remedy that mistake, you just use the system package manager to reinstall that removed gem.

**Comment by mpapis** [comment]
@voxik rubygems shows path to use if you want uninstall gem that's not in `ruby -e 'puts Gem.paths.home'` - so you could run:
```bash
gem uninstall default_gem_name
# fails & shows:
# not installed in GEM_HOME, try: gem uninstall -i /path/to/where/the/gem/was/installed default_gem_name

# so now you can:
sudo gem uninstall -i /path/to/where/the/gem/was/installed default_gem_name
```
would that break things?

**Comment by enebo** [comment]
@voxik I see.   Thanks for the explanation.   So default gems as regular gems sort of needs to fallback to something else to get it into a recoverable state.  For linux distributions, this would be whatever system packaging manager (rpm, etc...).  For MacOS, it could be homebrew?  Windows I think would probably end up being a re-install.  I guess re-install would be the base fallback if no package management exists.

 Not sure how I feel about the idea myself, but I am glad it was described in the issue as input as an alternative to default gems.  My main negative feeling to the approach would be any confusion from someone uninstalling and then not realizing how they just broke their Ruby install.  I could see a helpful error message perhaps as making this alternative not confusing and therefore not a bad alternative.  That message would need to display a clear instruction on how to get back to a good state.

**Comment by hsbt** [comment]
rubysl-* are not active project in 2019. I'm considering to change the current behavior to https://github.com/rubygems/rubygems/pull/2166.
