### ISSUE TITLE
Replace ronn by ronn-ng

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#6941]
I have noticed that Bundler is using ronn, which is long unmaintained and using even older dependencies. However, there is ronn-ng forg, which is in better shape with active upstream. I would suggest to switch to this fork.

**Comment by simi** [comment]
Seems we can try to update at https://github.com/rubygems/rubygems/blob/bfe598609ae960e8e5d6cb9eed9c4acc126da00a/tool/bundler/dev_gems.rb#L19 and update binstub to load from ronn-ng at https://github.com/rubygems/rubygems/blob/bfe598609ae960e8e5d6cb9eed9c4acc126da00a/bin/ronn#L6C16-L6C24.

I'll try and report back if that's this simple. Thanks for suggestion.

**Comment by deivid-rodriguez** [comment]
@simi Note you'll probably need to use the latest ronn-ng prerelease since ronn-ng has not released a stable version in more than 3 years.

**Comment by deivid-rodriguez** [comment]
Yes, but no luck!

@tnir actually forked ronn-ng and released [nronn](https://rubygems.org/gems/nronn) for our docs site, but I wanted to be a good citizen and went with https://github.com/rubygems/bundler-site/pull/989 in the end.

Author said he would release a new version, but that never happened.

I actually have gone through this same loop a couple of times already. [Back in 2020](https://github.com/apjanke/ronn-ng/pull/51#issuecomment-659153133), the author already said he would release a new version "in the next couple weeks.", and didn't happen either.

For this reason, and also since the downloads numbers for ronn-ng are much smaller than I thought, I think it'd be fine in this case to move on with nronn too.

**Comment by deivid-rodriguez** [comment]
To further clarify, we've already been helping with maintenance for a while. As an example, out of 24 merged PRs in the ronn-ng repo, Dependabot opened 9, and I opened 8 myself. So we're essentially the main contributors already. But when I offered to further help with releasing the gem too, offer was rejected.
