### ISSUE TITLE
RubyGems Proxying

### ISSUE THREAD

**Issue by VetheonGames** [rubygems/rubygems#6944]
# Note: This is not a Bug or Issue, it is a Feature Request

### Problem Statement

Developers like myself who maintain both public and private gems often find themselves pushing updates to multiple repositories: the official RubyGems repository and their own custom repositories. This redundancy is inefficient and increases the margin for error.

### Proposed Solution

I propose that RubyGems implement a proxying feature similar to what Rust's Cargo offers. This feature would allow gem maintainers to specify a custom repository as the primary source for their gem. When a user attempts to install the gem, RubyGems would:

   - Check if the gem has a custom repository specified.
   - If so, fetch the latest version of the gem from the custom repository rather than the RubyGems repository.

This would not mean proxying the entire connection, but rather allowing RubyGems to pull new versions from custom repositories as needed.

### Benefits

   - Reduces redundancy for gem maintainers.
   - Allows organizations to maintain internal versions of gems without having to mirror the entire RubyGems repository.
   - Increases flexibility for gem distribution, potentially encouraging more open-source contributions.

### Similar Existing Features

This feature would be somewhat similar to how Rust's Cargo handles custom registries, providing a more flexible and efficient ecosystem for package management.

**Comment by rubyFeedback** [comment]
I have a question; perhaps I did not fully understand it.

You wrote:

" When a user attempts to install the gem, RubyGems would:

Check if the gem has a custom repository specified.
If so, fetch the latest version of the gem from the custom repository rather than the RubyGems repository."

Will this be transparent to the user, including the webpage? Or will they only know about this upon installation time? I am asking specifically (to provide some context) to query how transparent it may be for the user. For instance, I would normally assume that "gem install foobar" would fetch the foobar gem from rubygems.org. I suppose your feature request is in part (or fully?) supported by bundler as-is; at the least I think bundler pioneered that to have custom repositories. So my question has more to do with the transparency and reproducibility of managing multiple repositories outside of rubygems.org.

**Comment by martinemde** [comment]
I'm also curious if I understand correctly. I read through the cargo documentation for registries and I don't quite understand what it is they do differently than rubygems.

I re-read your ticket here and I can't decide if you intend for rubygems to locally, on your computer, use a different source, or if you're suggestion that rubygems.org track private repository urls for registered gems and reply with a redirect to that private repo. If locally, what isn't covered already by the gem sources or bundler sources?

If this is meant to be on rubygems.org, I'm having trouble picturing how that would work. Maybe like you claim the private gem name on rubygems.org and whenever it's requested (accidentally?) rubygems.org would reply that the gem name is blacked? We wouldn't want to reply with the private gem server since it's very likely not available on the public internet.

What am I missing from Cargo? Sorry I'm not totally familiar with it.

**Comment by VetheonGames** [comment]
So sorry for how long it took me to respond. Evidently I didn't get a notification from Github that anyone responded so I totally thought my idea was just silly and nobody cared!

***Anyways,***

Let me explain a bit further here.

So, I was making myself a gem the other day and thought "It would be cool if I could have my own RubyGem repo to install from. So if I wanted to make gems just for my own use, I could."

Then I thought, well hang on, this is probably already a thing, so I did some digging, and set myself up my own gem repo (this was a while ago).

Fast forward to today, and I develop across like 6 different devices (so having a private repo is *super helpful*), and have become pretty weary of platforms like Github and other paltforms owned by big businesses. So I offloaded all my code, repos, and such, onto my own server. Now however, for the few public gems I maintain I find myself having to push the gem to two different hosts. RubyGems, and my private repository. (Before pushing to both was done by a github action, and the git solution I use, Gitea, doesn't do Runners like Gitlab to the best of my knowledge.)

My idea was to basically make things easier to maintain across the board, by introducing a system of some kind where the developer (should they have their own private repository) would be able to distribute their gem through RubyGems without needing to push/pull to/from two different hosts for their gem. This could be done a variety of ways now that I apply a fresh brain to the thought, but I think having a gem be pushed normally, then on the side of the site the owner of said gem can set a proxy location that the gem can be pulled from. If there is a owner set alternate remote, simply ask the user if they'd like to use it or not. That way, a developer can continue to use RubyGems the way they always have, but there's an added feature.

Now I do want to note, I came up with this idea after being up all night (and after being frustrated at libnCurses for hours), and perhaps it wasn't as fleshed out as it ought to have been. Especially seeing as one can just make a script or any other variety of things to automate the process. If you guys genuinely think the idea has potential, I'm totally down to continue discussing it and seeing if maybe something can come of it.

But I'm also totally ok with just closing this.

**Comment by martinemde** [comment]
I agree with you that a script for pushing gems could at least solve the push side. On the pull side, I don't think rubygems should suggest non-authoritative sources or put choices in the middle.

I think the problem you're running into is real and worth solving, but I'm concerned it would increase the vulnerability surface area while not buying much in the way of features. I'm going to close this for now, but we can reopen if there's more interest in the future.

Out of curiousity, why don't you _just_ host your gems on rubygems.org? Why push them to both? Maintaining a local copy of gems is quite well supported without running a gem server. If you're pushing to both, they must not be private gems. Bundler is also a little (sometimes [a lot](https://github.com/rubygems/rubygems/issues/6828)) slower with two remote sources. What benefits do you enjoy?
