### ISSUE TITLE
$ bundle install The unmet dependencies are: * bundler (~> 1.0), dependency of rails-3.0.20, unsatisfied by bundler-2.4.20

### ISSUE THREAD

**Issue by BAYRAM0661** [rubygems/rubygems#7068]
`$ bundle install`

> Installing bcrypt-ruby 3.0.1 with native extensions
> Installing json 1.7.7 with native extensions
> Installing eventmachine 1.0.0 with native extensions

> Your lockfile doesn't include a valid resolution. 
> You can fix this by regenerating your lockfile or manually editing the bad locked gems to a version that satisfies all pendencies. 
> The unmet dependencies are:

> bundler (~> 1.0), dependency of rails-3.0.20, unsatisfied by bundler-2.4.20 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

![image](https://github.com/rubygems/rubygems/assets/90972092/219af6a1-ee04-433b-bb5e-0ee9181b3a86)

**Comment by BAYRAM0661** [comment]
I'm getting this error, can you help me please?

**Comment by BAYRAM0661** [comment]
I tried but it didn't work. Mr. Martinemde

![image](https://github.com/rubygems/rubygems/assets/90972092/72697f91-0844-44fd-b4d6-d16136dff2da)

**Comment by BAYRAM0661** [comment]
> Rails'in çok eski bir sürümünü kullanıyorsunuz, dolayısıyla paketleyicinin 1.x sürümüne ihtiyacınız olacak gibi görünüyor.
> 
> `gem install bundler -v '~> 1.0'`
> 
> Muhtemelen eski sürümü kullandığından emin olmanız gerekecektir. Kontrol edin `bundle -v`.

>I tried but it didn't work. Mr. Martinemde,
![image](https://github.com/rubygems/rubygems/assets/90972092/11f4b760-874b-4bbd-a811-177ec1cc3250)

,

**Comment by martinemde** [comment]
It is still using bundler 2.4 as it says in the error message.

I don't think this will be the only error you will encounter. This app is using a rails version that is 10 years old. It is almost certain it won't run on a modern ruby. I believe ruby 1.9 was in use at the time of rails 3.

You have some work ahead of you and I won't he able to do this all for you here through screenshots if you can't solve this on your own.

Since this is not a bug with bundler, I will close this issue. You may wish to seek help from a rails group. What you are facing is the difficulty of running a decade old app on a computer from the present era.

**Comment by BAYRAM0661** [comment]
> Hata mesajında ​​belirtildiği gibi hala paketleyici 2.4'ü kullanıyor.
> 
> Karşılaşacağınız tek hatanın bu olacağını düşünmüyorum. Bu uygulama 10 yıllık bir Rails sürümünü kullanıyor. Modern bir yakutta çalışmayacağı neredeyse kesindir. Ruby 1.9'un Rails 3 zamanında kullanıldığına inanıyorum.
> 
> Önünüzde bazı işler var ve bunu kendi başınıza çözemezseniz, ekran görüntüleri aracılığıyla tüm bunları sizin için burada yapamayacağım.
> 
> Bu paketleyiciyle ilgili bir hata olmadığından bu konuyu kapatacağım. Bir Rails grubundan yardım isteyebilirsiniz. Karşılaştığınız şey, günümüzün bir bilgisayarında on yıllık bir uygulamayı çalıştırmanın zorluğudur.

Thanks...
