### ISSUE TITLE
Add option to ignore permissions when packaging

### ISSUE THREAD

**Issue by dayglojesus** [rubygems/rubygems#707]
As per https://github.com/rubygems/rubygems/issues/272, arguments for preserving or ignoring permissions when packaging a gem are a preference, not an absolute. This is not a request to change the default behaviour, rather enhance control.

It would be really nice if one could specify the behaviour in the .gemspec.

```ruby
Gem::Specification.new { |s| s.ignore_perms = true } 
```

**Comment by coofercat** [comment]
If gems can define their own permissions for the files they drop onto systems, then this would resolve the problem where a user (esp. root) has a restrictive umask (as required by some security standards) and accidentally uses 'gem' to install a gem onto the system without resetting it (which spews unusable files all over the filesystem).

If on the other hand, "gem install" uses the more restrictive of the umask or the gem-defined permission, then gem-defined permissions are pretty useless because you'll end up with permissions you (as the gem provider) weren't expecting, with corresponding support issues etc.

**Comment by copiousfreetime** [comment]
It appears that there are a couple of things that need to be documented or clarified about how the permissions of files in a gem are calculated, both during the packaging and during the installation.

Currently, during gem packaging:
* a warning is issued if the bin files do not have execute bit set
* a warning is issued if any file is not world readable

During installation the files are extracted according to the permissions on the file in the gem tarball.

Do we need to do anything else? Do we do a installation warning similar to the packaging warning?

**Comment by copiousfreetime** [comment]
Closing as this is deprecated by #1041
