### ISSUE TITLE
Feature Request: Specify constraints for bundle add

### ISSUE THREAD

**Issue by MyklClason** [rubygems/rubygems#7147]
So, `bundle add` is pretty nice but seems a bit underutilized, and I suspect it's related to locking. Also, I've noticed many gems don't include constraints on the version in the installation instructions. It's often just what little is below, which leads to many old Gemfiles being pretty much completely almost completely unconstrained.

Add this to your Gemfile.

```
gem "gem_name"
```

------------

I'm wondering if it might be possible to specify the lock level/type so gems can be added more ideally. Right now, the standard version just goes with the patch level of "1.2.3" You can also specify a specific version constraint to go with, but that doesn't help much if things could change. I think it would be useful to be able to specify things like:

```
# Lock format is just specified to define what level the version locking should use as a short hand.
bundle add gem_name --lock-format="x.y.z" # "1.2.3"
bundle add gem_name --lock-format="x.y" # "~> 1.2.3"
bundle add gem_name --lock-format="x" # "~> 1.2"
bundle add gem_name -f="x" # "~> 1.2"

# The lock format shouldn't be case or variable specific.
bundle add gem_name --lock-format="X.Y.Z" # "1.2.3"
bundle add gem_name --lock-format="a.b.c" # "1.2.3"

# Inequality constraints could also be added.
bundle add gem_name --lock-format="x < 1.3" # "~> 1.2","< 1.3"
bundle add gem_name --lock-format="x.y < 1.3" # "~> 1.2.3","< 1.3"
bundle add gem_name --lock-format="x.y > 1.1" # "~> 1.2.3","> 1.1"
bundle add gem_name --lock-format="1.1 > x > 1.3" # "~> 1.2", "> 1.1" "< 1.3"
bundle add gem_name --lock-format="1.1 < x < 1.3" # "~> 1.2", "> 1.1" "< 1.3"
```

The downside is that the new format really would probably better included in the gem line as well:

```
#  bundle add gem_name --lock-format="x.y"
gem "gem_name", "~> 1.2.3", "x.y"

# bundle add gem_name --lock-format="1.1 < x < 1.3"
gem "gem_name", "~> 1.1", "< 1.3", "1.1 < x < 1.3"
```

This also provides the potential for a rather nice utility functions:

```
# Applies specified version lock to all gems in Gemfile if the version constraints are missing.
# Does not bundle install by default (flag required)
bundle vlock  --format "x,y" --install
bundle vlock gem_name --format "x" # gem "gem_name", "~> 1.2", "x"

# Updates the lock
# gem "gem_name", "~> 1.1", "x"
bundle vlock gem_name--update # gem "gem_name", "~> 1.2", "x"

# Updates all locks where the lock format is defined (IE: gem "gem_name", "~> 1.2", "x"; the "x" makes it defined)
bundle vlock  --update-all # Updates all 
```

**Comment by indirect** [comment]
I'm not positive, but it appears you may be operating under some misconceptions.

- The version constraints listed in your Gemfile are not "locked" versions. Locked versions are single, exact numbers, and are always stored in `Gemfile.lock`.
- The `bundle add` command _always_ sets a version constraint. RubyGems.org likewise always includes a version constraint in the recommended Gemfile line. Here's an example from https://rubygems.org/gems/rails:
    <img width="324" alt="image" src="https://github.com/rubygems/rubygems/assets/78/b3ce87b5-4b1d-4999-855d-260f0f6987f6">
- You cannot provide a format for the version constraint that `bundle add` will use in the Gemfile because it will always automatically use the format recommended by the Bundler team.
- If you run `bundle add rails`, you will get `gem "rails", "~> 7.1"`. We recommend `~> X.Y` so you get every `X` version, but do not get version `X+1` until you change the version written in the Gemfile.
- If you run `bundle add gem_name` and the gem version starts with zero, you will get `gem "gem_name", "~> 0.X.Y"`, which is also the version pattern that the Bundler team recommends.
- Neither Bundler nor RubyGems supports constraints in the format `"1.1 < x < 1.3"`, so that is not a valid way to specify version constraints.
- The gem named `pessimizer` already exists and can automatically add version constraints to a Gemfile that does not have them: https://github.com/iachettifederico/pessimizer.

I'm going to close this for now, since it seems like the problems you are describing are already solved by existing tools. If you disagree, we would be happy to hear more about what problem you are trying to solve that does not seem to be solved by the existing tools.
