### ISSUE TITLE
Add Codeberg and GitLab shorthands

### ISSUE THREAD

**Issue by jgarber623** [rubygems/rubygems#7210]
## Description

For nearly a decade, Bundler has offered [`bitbucket:`](https://bundler.io/v2.4/man/gemfile.5.html#BITBUCKET), [`github:`](https://bundler.io/v2.4/man/gemfile.5.html#GITHUB), and [`gist:`](https://bundler.io/v2.4/man/gemfile.5.html#GIST) shorthands for use in `Gemfile` when defining a gem's source.

As of RubyGems 3.4.22, those are configured in the `Bundler::Dsl` class' `#add_git_sources` method:

https://github.com/rubygems/rubygems/blob/ec2089640dbbb0de136c77190cc20d78aadada15/bundler/lib/bundler/dsl.rb#L275-L299

At one point (see 924cd58), `bitbucket:` and `gist:` were marked for deprecation, but that seems to have been removed at some point along the way. I couldn't locate anything regarding the inclusion of `bitbucket:` and `gist:` (both seem curious to me, but then, there's a lot of history in this codebase).

## Proposed Solution

If it's accurate that `bitbucket:` and `gist:` are _not_ deprecated, **I propose adding similar shorthands for two other prominent Git providers: [GitLab](https://gitlab.com) and [Codeberg](https://codeberg.org)**.

On the 👍🏻 side, this proposal would add convenience for users of those platforms (myself included!).

On the 👎🏻 side, this proposal would add more (seemingly) arbitrary shorthands to the codebase.

If this proposal is acceptable, I'd be happy to write the change and necessary tests and submit a Pull Request.

Thanks for your consideration!

**Comment by martinemde** [comment]
You make a good point and I don't feel strongly either way. The existence of each clearly points to the upside and downside of including them.

Ths dsl exists for making your own shorthand in the Gemfile, but it's not as easy as an included shortcut. I don't know where to draw the line on included ones, except to acknowledge that gitlab seems an obvious omission at this point, if that's the direction we're going.

**Comment by deivid-rodriguez** [comment]
I would not mind to completely cancel the deprecation and particularly also acknowledge that gitlab is indeed a noticeable omission, and that there's not a new platform like these created every day, so I don't think we'll get a lot of bikeshidding/please-add-my-favorite-niche-provider here.

On the other hand, I'm also not particularly attached to these shortcuts, and I see how they may feel rather arbitrary, so I'm mostly neutral here.

That said, just clarify that the plan is still to deprecate these sources at some point. We just delay the deprecation horizon to make it a smoother path to users. See https://github.com/rubygems/bundler/pull/7000.

**Comment by martinemde** [comment]
If we're all neutral, then I'd say adding ~10 lines of code to the dsl and a few tests is warranted. The argument for deprecating these was probably "are we going to have to add one for every provider?" but that doesn't seem so bad to me personally.

**Comment by simi** [comment]
If I remember well, the problem is similar to no global source or later `source :rubygems` -> source is not explicit. Also with change needed for `:github` to happen at some time due to changes in the url (github provided more secure one, but it wasn't simple as switch to migrate, since it will change lockfiles) it was decided to offboard all hardcoded not-explicit shortcuts and instead custom git source was exposed leaving this to Gemfile to specify https://bundler.io/guides/git.html#custom-git-sources. IMHO deprecation is still valid (to not repeat the same mistake).

**Comment by indirect** [comment]
Personally, I would like to keep at least GitHub as a built-in option because it is so common. The GitHub change was especially bad before we had Bundler version locking--I think that today we could make that change and it would be fine, since the lock file would change at the same time as the Bundler version changed.

I would be fine with adding GitLab, especially now that we are safe from changes between Bundler causing breakage.

If we want some kind of sense of how popular each site is, here are some stats from similarweb.com:

- [GitHub, 432M visits](https://www.similarweb.com/website/github.com/#overview)
- [GitLab, 21M visits](https://www.similarweb.com/website/gitlab.com/)
- [BitBucket, 17M visits](https://www.similarweb.com/website/bitbucket.org/#overview)
- [Codeberg.org, 3M visits](https://www.similarweb.com/website/codeberg.org/#overview)

Perhaps we could use a threshold for including a config inside Bundler itself, something like 15 million visits per month?

**Comment by martinemde** [comment]
Does providing the `:github` shortcut help ensure better security by keeping the user from using a non-encrypted protocol? Do we warn about insecure git urls?

I hadn't heard of codeberg until now. 🤷‍♂️  A heuristic would be nice, then put it in the file where these live. I'd say rank rather than traffic, like top 3 or 5 by traffic if that's easy to track. What do you all think?

**Comment by deivid-rodriguez** [comment]
If I recall correctly, since Bundler 2, we automatically use https for these shortcuts, but there's still the deprecated setting `github.https` that can be set to `false` to use a non encrypted protocol.

My plan was to completely get rid of this setting in Bundler 3, and _then_ deprecate the shortcuts. So deprecation of these shortcuts is still perfectly cancellable, since it hasn't even started yet.

**Comment by deivid-rodriguez** [comment]
Actually, what I just said is wrong. Deprecation of these sources was cancelled at https://github.com/rubygems/rubygems/pull/5147.

I'm happy with any heuristic we decide to choose for new sources, but I'm also happy to not use any criteria for now and defer that to the point where it becomes annoying that people want to add their favorite (but unpopular) provider.

**Comment by deivid-rodriguez** [comment]
I missed this because it was not in the changelog for some reason. I added it here: https://github.com/rubygems/rubygems/pull/7228.
