### ISSUE TITLE
Rubygems should not install test files

### ISSUE THREAD

**Issue by anatol** [rubygems/rubygems#735]
I see that gemspec has test_files and many gemfiles include tests. I believe it is artifact from `gem test` times. I think tests in gemfiles are OK (e.g. in case if you decide to reintroduce `gem test` back #730). But `gem install` should not install these files, gem tests are useless for users (unless I missed something).

Bottomline: `gem install` should not install files from test_files.

**Comment by davexunit** [comment]
Chiming in here on this old thread in an attempt to express my
thoughts to people with decision making power.  I have been packaging
Ruby gems for the GNU Guix System Distribution for about a year now
and I've found out that including tests in gem archives has been
discouraged[0].  I think this is a major issue for a few reasons.  Gem
archives represent source code releases, not binaries.  They include
Ruby source code and sometimes C source code that native extensions
will be built from.  Source releases for software written in other
languages typically come with their associated test suite.  For C
applications that use the GNU autotools, one can run `make check` to
verify to some degree that the software they built works on their
computer.  Python packages do something similar with `setup.py`.  It
is simply good standard practice to ship the test suite with your
source releases.  Without test suites, it becomes very difficult for
GNU/Linux distros to have confidence that their Ruby packages actually
work since the CI system cannot check automatically when building from
source.

Now, I agree that `gem install` shouldn't install test files, but that
doesn't mean that tests should be stricken from release archives.
Maybe `test_files` wasn't perfect, but I think there needs to be
something like it to distinguish files that are needed for runtime and
other files like the README, Rakefile, C extension source code, and
tests.  There of course would be no obligation that everyone's test
suite must be run in the same way like in the `gem test` days, but it
would give users the chance to run the suite to test the integration
of the gem with their unique environment.

In summary, I would like the RubyGems maintainers to reconsider and
encourage that test suites (including their dependent files such as
the Rakefile to run `rake spec`, etc.) be included in gem archives.
Thank you.

[0] https://github.com/rails/arel/issues/384

**Comment by mvz** [comment]
The problem with @davexunit's request is that many gem authors find their gems become too large if they include the full test suite.

I think it would make sense to instead have separate 'source' and 'binary' gem files available for download. (I use the term 'binary' very loosely). The 'source' version would include tests etc. needed for development, while the 'binary' would be more lightweight and suitable for installing with the `--thin` flag.

**Comment by e2** [comment]
@davexunit, @mzv - check out https://github.com/rubygems/rubygems/issues/1364 for an potential solution/alternative.

**Comment by anatol** [comment]
Hi everyone.

I work on a project related to the topic of this discussion. It is an automatic rubygem to Linux Arch package converter. One of my goals of the project is to create as thin Arch packages as possible. As pointed in this thread many rubygems install tests, all sort of development scripts, intermediate compile files, git files are unneeded at runtime to users.

Besides the fast that only part of rubygem package needed at runtime there were other requirements:
 - gems with C extensions need to specify correct native dependencies
 - some gems work only with specific version of Ruby / native dependency and need patching for other versions

To create a thin Arch package I only use bare minimum needed. For most of the packages it is just `lib/` and `bin/` gem folders and `Gemspec`. Some gems require additional directories - currently 18 packages need that.


Here is the project itself - Quarry https://github.com/anatol/quarry . The most interesting part for you will be https://github.com/anatol/quarry/tree/master/config.pkg with config files that specify gem requirements.

And its corresponding Linux Arch repository - http://pkgbuild.com/~anatolik/quarry/x86_64/ Currently it successfully handles ~450+ popular rubygems.

**Comment by Davidslv** [comment]
Any updates on this? Thank you

**Comment by kaikuchn** [comment]
What's the state on this? Should maintainers remove `test_files` from the specification? Is there a way to install gems without the test files?

**Comment by schmijos** [comment]
It's painful for me to see how more and more maintainers are removing tests from their gems and I think action is needed. Ruby is open source and gems are not binaries. Each time my IDE can find some bundled tests locally my heart fills with joy. It just happened today when I looked up Capybara's beautiful `has_current_path` specs. I love my IDE (and it's not GitHub)!

I can see that the distributed kilobytes add up for popular gems, but why did you even choose Ruby in the first place if this is your concern? Is it worth [33K](https://github.com/heartcombo/simple_form/pull/1809) to remove valuable docs from the gem for everyone?

We really need a pragmatic solution to reduce bundle size in production without sacrificing the tests per default. The default should be **all the source code**, not just transpiled, compiled, tree-shaken, minified and compressed machine-fodder!

**Comment by mroach** [comment]
It's not only about disk space. It's also about whether or not you want to be shipping unnecessary files to your production environment that can be read and executed like any other Ruby source file. For a while now I've had a release build step that deletes clearly unnecessary directories like `benchmarks`, `doc`, `examples`, `spec`, `test`. This is hardly a precision tool though and I have to make exceptions, and it doesn't get everything that it should. 

I think it's a fair point that such files have a purpose for development so developers don't have to go back to the source repo and find the version they use to look at tests and embedded documentation files.

Given what's gone on lately with the xz exploit, which was done with test files, I think this deserves some thought.

When I look at some gems I use, there's quite a range in quality of files shipped. The Rails gems for example are neat and tidy, only shipping `lib`, a license file, and `examples`. Great!

Not to pick on any gem in particular but I was going in order of necessity, `pg` ships with its `.github` dir, `.pryrc`, `Rakefile`, its own `.gemspec`, and other files clearly unnecessary for runtime.

If there's a desire to keep shipping files useful for development but not runtime, perhaps the solution is to do what we do with gem dependencies: specify runtime vs development dependencies. This would allow for automated removal of development-only files during production builds.

A revised gemspec could look something like:

```ruby
# no change here from current defaults
spec.files = Dir.chdir(File.expand_path("..", __FILE)) { %x(git ls-files -z).split("\x0") }

# new addition?
spec.runtime_files = spec.files.select { _1.start_with?("lib") }
