### ISSUE TITLE
Gem::Indexer was removed in 3.5.0 (to a gem) but was not communicated in the changelog

### ISSUE THREAD

**Issue by ziggythehamster** [rubygems/rubygems#7426]
https://github.com/rubygems/rubygems/pull/7085 removed Gem::Indexer to a gem, but this change was not communicated in the `CHANGELOG.md` as a breaking change.

**Comment by deivid-rodriguez** [comment]
I'm fine with moving this change to the breaking section in the changelog. Can you create a PR?

**Comment by deivid-rodriguez** [comment]
We went with calling this an enhacement, not a breaking change, because `gem generate_index` will automatically install the new gem as a plugin when run if not available, so no breaking change there.

Of course (like with most RubyGems internals), some people were also using the `rubygems/indexer` code directly, so that did break stuff unfortunately.

I'm not sure it's actually helpful to move the change to the "Breaking changes" section at this point though, so I'll go ahead and close this issue. f you think moving sections is helpful though, please create a PR directly and we can continue discussing there :+1:.
