### ISSUE TITLE
Bundler::GemNotFound: Could not find X with Artifactory virtual gem repo + rubygems.org remote repo

### ISSUE THREAD

**Issue by coldnebo** [rubygems/rubygems#7451]
### Describe the problem as clearly as you can

this seems to be a problem with artifactory's pass-thru cache. We use a virtual repo in artifactory that consists of our company gems and a remote-repo reference to rubygems.org.  The way this is supposed to work is requests for rubygems.org gems get handled and then cached in artifactory so that everyone installing the same gem doesn't generate a large amount of traffic to rubygems.org and get blacklisted. (we have a lot of devs and a lot of projects built daily so it would be huge).

The problem is the code path for `bundle install` does not correctly resolve sometimes, but `gem install` always does with the same repository.

After `gem install` THEN `bundle install` works until it hits the next new gem not in the cache.  So devs have to work through the entire set of uninstalled gems manually. This is a PITA.

I'd like to know why the 'gem install' code path is different fundementally from the 'bundle install' code path.

It seems like since the performance outages last year and the forced deployment of the Compact API, and the continuing drama with Artifactory over the implementation of Etags between bundler and artifactory, there have been numerous CRIPPLING outages of service for us.  

Is there anything you can advise we can do? Is there a way to automate bundle install using 'gem install' instead? is there a way to force install that will use the other codepath?

I would love to wake up and find all these problems gone, but they keep hitting us out of the blue while we are trying to get critical work done. I'm pretty frustrated.

Can you help? Is there a workaround?

### Did you try upgrading rubygems & bundler?

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ gem -v
3.5.5
$ bundler --version
Bundler version 2.4.13
```

### Post steps to reproduce the problem

run bundle install.

### Which command did you run?

```bundle install```

### What were you expecting to happen?

I expect the gems to be installed.

### What actually happened?

```
$ bundle install
...
Bundler::GemNotFound: Could not find xpath-3.2.0.gem for installation
An error occurred while installing xpath (3.2.0), and Bundler cannot continue.

$ head Gemfile
source 'http://server/artifactory/api/gems/gems-virtual-repo'

$ gem install xpath -v 3.2.0
Fetching xpath-3.2.0.gem
Successfully installed xpath-3.2.0
1 gem installed

$ gem environment
...
  - REMOTE SOURCES:
     - http://server/artifactory/api/gems/gems-virtual-repo
  - SHELL PATH:
...

```

### If not included with the output of your command, run `bundle env` and paste the output below

this is a private project, I don't feel comfortable sharing that detail.  I need some idea how that is relevant before I share that.

**Comment by deivid-rodriguez** [comment]
I guess https://github.com/rubygems/rubygems/pull/7122 could be related, and possibly other fixes that came later. Please upgrade Bundler and this should hopefully be fixed.

If it doesn't fix it, feel free to reopen, but I'm afraid we're going to need some more help from your side to be able to do something about it. Is the problem reproducible every time? Is it still reproducible after removing gems one at a time? Is there a a specific gem creating the problem? Can you create dummy gems you're comfortable sharing that simulate the same kind of problem? The fact that running `gem install` first fixes the problem is useful information, but definitely not enough.

The reason why `gem install` and `bundle install` go through different code paths is because they are completely different commands (one takes a gem or list of gems, the other installs a Gemfile) and have completely different implementations.
