### ISSUE TITLE
`bundle check` causes file modifications to `Gemfile.lock`

### ISSUE THREAD

**Issue by andyw8** [rubygems/rubygems#7587]
### Describe the problem as clearly as you can

Nothing in the [docs](https://bundler.io/v2.5/man/bundle-check.1.html) indicates that `bundle check` should modify `Gemfile.lock`, but it seems to be doing so.

### Did you try upgrading rubygems & bundler?

Yes: ruby 3.3.0, rubygems 3.5.3, bundler 2.5.9

### Post steps to reproduce the problem

Create a new `Gemfile`, e.g.:

```
source "https://rubygems.org"
```

Run `bundle` to create an almost-empty `Gemfile.lock`.

Edit the `Gemfile` and add `gem "mocha"`.

Run `bundle check`.

### What were you expecting to happen?

Unsure, but `Gemfile.lock` should not change.

### What actually happened?

`Gemfile.lock` is changed and now includes `mocha`.

cc @vinistock

**Comment by deivid-rodriguez** [comment]
The way `bundle check` works is:

* Tries to resolve your bundle using only locally installed gems.
* If it finds any gem is missing, it throws an error.
* If nothing is missing, it succeeds, and potentially "completes" the lockfile if anything was missing from it.

In other words, in your example, I think it succeeds (and fixes the lockfile) because you had mocha previously installed. If mocha had not been installed, it would've given an error.

I think the easiest way to fix this is to document the current behavior?

**Comment by andyw8** [comment]
Thanks, that matches the behaviour I'm seeing. Here's a possible update to the docs: https://github.com/rubygems/rubygems/pull/7613
