### ISSUE TITLE
Unresolved or ambiguous specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by n-rodriguez** [rubygems/rubygems#7657]
Hi there!

I got this warning in CI when running my app with TruffleRuby 24.0.1 :

```sh
$ bin/bundle install --jobs ${PARALLEL_TEST_PROCESSORS}
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.0
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Bundle complete! 204 Gemfile dependencies, 390 gems now installed.
Bundled gems are installed into `/cache/nicolas/concerto/truffleruby-wip-truffleruby`
```

I don't have it with Ruby 3.3.1.

`stringio` is declared in my `Gemfile` :

```sh
nicolas@MacBook-Pro-de-Nicolas:~/PROJECTS/CONCERTO/concerto$ grep stringio Gemfile Gemfile.lock
Gemfile:  gem 'stringio'
Gemfile.lock:      stringio
Gemfile.lock:    stringio (3.1.0)
Gemfile.lock:    stringio (3.1.0-java)
Gemfile.lock:  stringio
```

Thank you!

**Comment by n-rodriguez** [comment]
It's the default `bundler` binstub :

```rb
#!/usr/bin/env ruby
# frozen_string_literal: true

#
# This file was generated by Bundler.
#
# The application 'bundle' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require "rubygems"

m = Module.new do
  module_function

  def invoked_as_script?
    File.expand_path($0) == File.expand_path(__FILE__)
  end

  def env_var_version
    ENV["BUNDLER_VERSION"]
  end

  def cli_arg_version
    return unless invoked_as_script? # don't want to hijack other binstubs
    return unless "update".start_with?(ARGV.first || " ") # must be running `bundle update`
    bundler_version = nil
    update_index = nil
    ARGV.each_with_index do |a, i|
      if update_index && update_index.succ == i && a.match?(Gem::Version::ANCHORED_VERSION_PATTERN)
        bundler_version = a
      end
      next unless a =~ /\A--bundler(?:[= ](#{Gem::Version::VERSION_PATTERN}))?\z/
      bundler_version = $1
      update_index = i
    end
    bundler_version
  end

  def gemfile
    gemfile = ENV["BUNDLE_GEMFILE"]
    return gemfile if gemfile && !gemfile.empty?

    File.expand_path("../Gemfile", __dir__)
  end

  def lockfile
    lockfile =
      case File.basename(gemfile)
      when "gems.rb" then gemfile.sub(/\.rb$/, ".locked")
      else "#{gemfile}.lock"
      end
    File.expand_path(lockfile)
  end

  def lockfile_version
    return unless File.file?(lockfile)
    lockfile_contents = File.read(lockfile)
    return unless lockfile_contents =~ /\n\nBUNDLED WITH\n\s{2,}(#{Gem::Version::VERSION_PATTERN})\n/
    Regexp.last_match(1)
  end

  def bundler_requirement
    @bundler_requirement ||=
      env_var_version ||
      cli_arg_version ||
      bundler_requirement_for(lockfile_version)
  end

  def bundler_requirement_for(version)
    return "#{Gem::Requirement.default}.a" unless version

    bundler_gem_version = Gem::Version.new(version)

    bundler_gem_version.approximate_recommendation
  end

  def load_bundler!
    ENV["BUNDLE_GEMFILE"] ||= gemfile

    activate_bundler
  end

  def activate_bundler
    gem_error = activation_error_handling do
      gem "bundler", bundler_requirement
    end
    return if gem_error.nil?
    require_error = activation_error_handling do
      require "bundler/version"
    end
    return if require_error.nil? && Gem::Requirement.new(bundler_requirement).satisfied_by?(Gem::Version.new(Bundler::VERSION))
    warn "Activating bundler (#{bundler_requirement}) failed:\n#{gem_error.message}\n\nTo install the version of bundler this project requires, run `gem install bundler -v '#{bundler_requirement}'`"
    exit 42
  end

  def activation_error_handling
    yield
    nil
  rescue StandardError, LoadError => e
    e
  end
end

m.load_bundler!

if m.invoked_as_script?
  load Gem.bin_path("bundler", "bundle")
end
```

> Is this project public?

Unfortunately no

**Comment by n-rodriguez** [comment]
repro script to run with truffleruby 24.0.1 :

```ruby
#!/usr/bin/env ruby

# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem 'psych'
end
```

**Comment by deivid-rodriguez** [comment]
I tried upgrading/downgrading RubyGems and it seems this is no longer an issue since RubyGems 3.4.21, particularly since RubyGems started using a pure-ruby YAML parser instead of psych: https://github.com/rubygems/rubygems/pull/6615.

Please do reopen if still happening after upgrading RubyGems!

**Comment by dkav** [comment]
Like @navidemad, I am seeing this regularly when updating using bundler.

```
Installing rexml 3.3.9
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.1

```
It also occurs on the latest HEAD too.

```
Installing rake 13.2.1
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.2.dev
```

**Comment by deivid-rodriguez** [comment]
Yeah, I've seen this too, will try to have a look.

**Comment by tisba** [comment]
Is there a new issue we can subscribe too? Or can you re-open this one, @deivid-rodriguez?

**Comment by deivid-rodriguez** [comment]
Nope. Can you open a new ticket with repro steps?

**Comment by tisba** [comment]
> Nope. Can you open a new ticket with repro steps?

I just saw the issue too and was wondering if this issue is the one to follow. But I'm happy trying to build a simplified repro and file a new issue. Thanks! 🚀

**Comment by deivid-rodriguez** [comment]
Great, thank you! I did notice the issue myself at some point but I forgot to open a new ticket and I now lost track of how to repro.

**Comment by kevinoid** [comment]
For what it's worth, I've been able to reproduce the "Unresolved or ambiguous specs during Gem::Specification.reset" error on Ruby 3.2.6 with Rubygems 3.4.19 after running `gem install --user-install psych stringio`.  With Docker/Podman:

```sh
podman run --rm docker.io/ruby:3.2 \
    sh -c 'gem install --user-install psych stringio && gem --version'
```

Which produces the output

    WARNING:  You don't have /root/.local/share/gem/ruby/3.2.0/bin in your PATH,
    	  gem executables will not run.
    Building native extensions. This could take a while...
    Successfully installed psych-5.2.0
    Building native extensions. This could take a while...
    Successfully installed stringio-3.1.2
    2 gems installed
    WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
          stringio (>= 0)
          Available/installed versions of this gem:
          - 3.1.2
          - 3.0.4
    WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
    Please report a bug if this causes problems.
    3.4.19

However, the error does not occur after `gem update --system` (Rubygems 3.5.23) nor with docker.io/ruby:3.3 (Ruby 3.3.6 with Rubygems 3.5.22), so I'm uncertain whether there's value to opening a new issue.

**Comment by deivid-rodriguez** [comment]
Yeah, not for that if upgrading RubyGems fixes it, but people are also seeing this with the latest RubyGems.

**Comment by tisba** [comment]
I can confirm that this is still happening to mewith Bundler 2.5.23 and rubygems 3.5.23. But so far I was unable to reproduce it reliably :( I'll try to remember to take a FS snapshot before running `bundle install`.

**Comment by scivola** [comment]
Here is a minimal reproduction procedure:
https://github.com/rails/thor/issues/889

**Comment by tisba** [comment]
Thanks, @scivola. Unfortunately I think this is not enough to reproduce. I already tried basically the same thing:

* using `ruby:3.3.6` docker image (docker just to get a guaranteed clean environment)
* running `gem update --system` to get the latest rubygems `3.5.23`
* `Gemfile` with:

  ```ruby
  source "https://rubygems.org"
  gem "stringio"
  ```
* running `bundle install`

Works fine.

**Comment by scivola** [comment]
In my example https://github.com/rails/thor/issues/889, it is necessary to use Thor.
Could you make a file with extension `.thor` such as:

```rb
require "bundler"
Bundler.require
```

and execute below?

```terminal
% gem install thor
% thor -T
```

**Comment by deivid-rodriguez** [comment]
I can somewhat reproduce this, although not as explained in https://github.com/rails/thor/issues/889.

If `stringio` is not in the Gemfile, then I get no warnings. If `stringio` is included in the Gemfile, but the version resolved by Bundler is different from the latest version installed in the system, then I get an error reading:

```
✗ thor -T     
/Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:299:in `check_for_activated_spec!': You have already activated stringio 3.1.2, but your Gemfile requires stringio 3.1.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:25:in `block in setup'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/spec_set.rb:191:in `each'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/spec_set.rb:191:in `each'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:24:in `map'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:24:in `setup'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler.rb:164:in `setup'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/site_ruby/3.3.0/bundler.rb:212:in `require'
	from /Users/deivid/code/playground/thor/tasks.thor:2:in `load_thorfile'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/util.rb:157:in `class_eval'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/util.rb:157:in `load_thorfile'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/runner.rb:227:in `block in initialize_thorfiles'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/runner.rb:226:in `each'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/runner.rb:226:in `initialize_thorfiles'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/runner.rb:176:in `list'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/bin/thor:6:in `<top (required)>'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/bin/thor:25:in `load'
	from /Users/deivid/.asdf/installs/ruby/3.3.6/bin/thor:25:in `<main>'
```

This happens because `thor` activates `stringio` internally, but activates a different version than the one Bundler is using. I think https://github.com/rails/thor/pull/892 should fix that.

**Comment by deivid-rodriguez** [comment]
Hei!

So I was finally able to reproduce the problem reliably.

You have to:

* Make sure you have two versions of `stringio` globally installed, like 3.1.1 and 3.1.2.
* Use a script like the following, and run it making sure `rake` (or any other gem) is not pre-installed. For example, with: `gem uninstall rake --force --executables && ruby script.rb`:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rake"
end
```

Then you should get output like:

```
$ gem uninstall rake --force --executables && ruby script.rb
Removing rake
Successfully uninstalled rake-13.2.1
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.2.1
Installing rake 13.2.1
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.1
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
```

The problem is that during the same process:
* First Bundler activates `psych` in order to read YAML data in the `.gem` package it's about to install.
* When `psych` is activated, its dependencies (namely, `stringio`) are left unresolved until they are actually used. In this case, `stringio` is not actually used, so the proper version is never actually resolved.
* Then Bundler sets up the `$LOAD_PATH` for the inline Gemfile, and for that it calls `Gem::Specification.reset` to reset the set of specifications known to Bundler to those in the `$LOAD_PATH`.
* `Gem::Specification.reset` prints this warning when it finds specifications that are waiting to be actually required before being completely resolved.

This kind of warning sometimes could make sense sometimes but I don't think it shows any actual problem in this particular situation, so I proposed #8309 to skip it.

**Comment by Skulli** [comment]
Is this fixed? I have similar problems, see https://github.com/puma/puma/issues/3626

**Comment by floehopper** [comment]
@Skulli It looks as #8309 by @deivid-rodriguez fixed the problem. That fix has been [merged](https://github.com/rubygems/rubygems/commit/a63e6c5f58c771f78b27603f46bc0702ef52a79c) and [released in rubygems v3.6.0](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#360--2024-12-16) which corresponds to [bundler v2.6.0](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.0). I hope that helps.

**Comment by Skulli** [comment]
Not sure if its completely fixed

still getting

> WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
>       stringio (>= 0)
>       Available/installed versions of this gem:
>       - 3.1.7
>       - 3.1.5
>       - 3.1.1

during a `bundle update` on my rails project.
Installed is `ruby 3.3.8`, `bundler 2.6.8` and `gem 3.5.22`

**Comment by floehopper** [comment]
Maybe you need to upgrade your rubygems version - the fix is in v3.6.0 and you are using v3.5.22.

**Comment by Skulli** [comment]
ups... you are right, my fault

**Comment by texpert** [comment]
Still getting this issue with ambiguos`stringio` version on `ruby 3.3.7`, `bundler 2.6.5`, amd `gem 3.6.5`:

```
01:00 bundler:install
      01 bundle install --jobs 4 --quiet
      01 WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      01       stringio (>= 0)
      01       Available/installed versions of this gem:
      01       - 3.1.7
      01       - 3.1.1
      01 WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
      01 Please report a bug if this causes problems.
```

**Comment by tisba** [comment]
@texpert you should consider open a new issue as this one was closed almost a year ago and probably doesn't get much attention. You should reference this one though.

**Comment by deivid-rodriguez** [comment]
Indeed @texpert, I haven't seen the warning in the case you present (when an unconstrained dependency like `stringio >= 0` is left unresolved) anymore since the fix was introduced. If you can still reproduce this with the latest version of RubyGems, please do open a separate issue.

**Comment by rajeshrd123** [comment]
This issue is coming up very often.
mipl@mipl-dev-server:~/metaspoit$ gem cleanup stringio
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Cleaning up installed gems...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      erb (>= 0)
      Available/installed versions of this gem:
      - 5.0.3
      - 4.0.2
      tsort (>= 0)
      Available/installed versions of this gem:
      - 0.2.0
      - 0.1.1
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Clean up complete
mipl@mipl-dev-server:~/metaspoit$ gem cleanup tsort,erb
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Cleaning up installed gems...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      erb (>= 0)
      Available/installed versions of this gem:
      - 5.0.3
      - 4.0.2
      tsort (>= 0)
      Available/installed versions of this gem:
      - 0.2.0
      - 0.1.1
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Clean up complete
mipl@mipl-dev-server:~/metaspoit$ gem cleanup tsort
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Cleaning up installed gems...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      erb (>= 0)
      Available/installed versions of this gem:
      - 5.0.3
      - 4.0.2
      tsort (>= 0)
      Available/installed versions of this gem:
      - 0.2.0
      - 0.1.1
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Clean up complete
-------
mipl@mipl-dev-server:~/metaspoit$ /usr/share/rvm/bin/rvm list

# No rvm rubies installed yet. Try 'rvm help install'.

mipl@mipl-dev-server:~/metaspoit$ gem list
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.

*** LOCAL GEMS ***

aarch64 (2.1.0)
abbrev (0.1.2, default: 0.1.1)
actionpack (8.0.5)
actionview (8.0.5)
activemodel (8.0.5)
activerecord (8.0.5)
activesupport (8.0.5)
addressable (2.8.7)
afm (0.2.2)
allure-rspec (2.27.0)
allure-ruby-commons (2.27.0)
arel-helpers (2.16.0)
Ascii85 (2.0.1)
ast (2.4.3)
aws-eventstream (1.3.2)
aws-partitions (1.1065.0)
aws-sdk-core (3.220.1)
aws-sdk-ec2 (1.511.0)
aws-sdk-ec2instanceconnect (1.55.0)
aws-sdk-iam (1.119.0)
aws-sdk-kms (1.99.0)
aws-sdk-s3 (1.182.0)
aws-sdk-ssm (1.191.0)
aws-sigv4 (1.11.0)
base64 (0.3.0, default: 0.1.1)
bcrypt (3.1.20)
bcrypt_pbkdf (1.1.1)
benchmark (0.4.1, default: 0.2.1)
bigdecimal (3.3.1, default: 3.1.3)
bindata (2.4.15)
bootsnap (1.18.4)
bson (5.1.1)
builder (3.3.0)
bundler (4.0.19, 2.5.22, default: 2.4.19)
byebug (12.0.0)
cgi (default: 0.3.6)
chunky_png (1.4.0)
coderay (1.1.3)
concurrent-ruby (1.3.5)
connection_pool (2.5.4)
cookiejar (0.3.4)
crack (1.0.1)
crass (1.0.6)
csv (3.3.5, default: 3.2.6)
daemons (1.4.1)
date (3.4.1, default: 3.3.3)
debug (1.11.0, 1.7.1)
delegate (default: 0.3.0)
did_you_mean (default: 1.6.3)
diff-lcs (1.6.2)
digest (default: 3.1.1)
dnsruby (1.74.0)
docile (1.4.1)
domain_name (0.6.20240107)
drb (2.2.3, default: 2.1.1)
ed25519 (1.4.0)
elftools (1.3.1)
em-http-request (1.1.7)
em-socksify (0.3.3)
english (default: 0.7.2)
erb (5.0.3, default: 4.0.2)
error_highlight (default: 0.5.1)
erubi (1.13.1)
etc (default: 1.4.2)
eventmachine (1.2.7)
factory_bot (6.5.5)
factory_bot_rails (6.5.1)
faker (3.5.1)
faraday (2.7.11)
faraday-net_http (3.0.2)
faraday-retry (2.2.1)
faye-websocket (0.11.3)
fcntl (default: 1.0.2)
ffi (1.16.3)
fiddle (1.1.6, default: 1.1.1)
filesize (0.2.0)
fileutils (default: 1.7.0)
find (default: 0.1.1)
fivemat (1.3.7)
forwardable (1.3.3)
getoptlong (0.2.1, default: 0.2.0)
gssapi (1.3.1)
gyoku (1.4.0)
hashdiff (1.2.1)
hashery (2.1.2)
hrr_rb_ssh (0.4.2)
hrr_rb_ssh-ed25519 (0.4.2)
http-accept (1.7.0)
http-cookie (1.0.8)
http_parser.rb (0.8.0)
httpclient (2.9.0)
i18n (1.14.7)
io-console (0.8.1, default: 0.6.0)
io-nonblock (default: 0.2.0)
io-wait (default: 0.3.0)
ipaddr (1.2.7, default: 1.2.5)
irb (1.15.2, default: 1.6.2)
jmespath (1.6.2)
jsobfu (0.4.2)
json (2.15.1, default: 2.6.3)
json-schema (6.2.0)
language_server-protocol (3.17.0.5)
lint_roller (1.1.0)
little-plugger (1.1.4)
logger (1.7.0, default: 1.5.3)
logging (2.4.0)
loofah (2.24.1)
lru_redux (1.1.0)
matrix (0.4.2)
mcp (0.13.0)
memory_profiler (1.1.0)
metasm (1.0.6)
metasploit-concern (5.0.6)
metasploit-credential (6.0.25)
metasploit-model (5.0.5)
metasploit-payloads (2.0.247)
metasploit_data_models (6.0.18)
metasploit_payloads-mettle (1.0.48)
method_source (1.1.0)
mime-types (3.7.0)
mime-types-data (3.2025.0924)
minitest (5.25.5, 5.16.3)
mqtt (0.7.0)
msgpack (1.6.1)
multi_json (1.15.0)
mustermann (3.0.3)
mutex_m (0.3.0, default: 0.1.2)
nessus_rest (0.1.6)
net-ftp (0.2.1)
net-http (default: 0.4.1)
net-imap (0.5.6, 0.3.4.1)
net-ldap (0.20.0)
net-pop (0.1.2)
net-protocol (0.2.2, default: 0.2.1)
net-sftp (4.0.0)
net-smtp (0.5.1, 0.3.4)
net-ssh (7.3.0)
net-telnet (0.2.0)
netrc (0.11.0)
network_interface (0.0.4)
nexpose (7.3.0)
nio4r (2.7.4)
nkf (default: 0.1.2)
nokogiri (1.18.10 x86_64-linux-gnu)
nori (2.7.1)
observer (default: 0.1.1)
octokit (10.0.0)
open-uri (default: 0.3.0)
open3 (default: 0.1.2)
openssl (default: 3.1.0)
openssl-ccm (1.2.3)
openssl-cmac (2.0.2)
openvas-omp (0.0.4)
optparse (default: 0.3.1)
ostruct (0.6.1, default: 0.5.5)
packetfu (2.0.0)
parallel (1.27.0)
parser (3.3.9.0)
patch_finder (1.0.2)
pathname (default: 0.2.1)
pcaprub (0.13.3)
pdf-reader (2.14.1)
pg (1.5.9)
power_assert (2.0.3)
pp (0.6.3, default: 0.4.0)
prettyprint (0.2.0, default: 0.1.1)
prime (0.1.2)
prism (1.5.1)
pry (0.15.2)
pry-byebug (3.11.0)
pstore (default: 0.1.2)
psych (5.3.1, default: 5.0.1)
public_suffix (6.0.2)
puma (6.6.0)
racc (1.8.1, default: 1.6.2)
rack (3.1.21)
rack-protection (4.2.1)
rack-session (2.1.2)
rack-test (2.2.0)
rackup (2.3.1)
rails-dom-testing (2.3.0)
rails-html-sanitizer (1.6.2)
railties (8.0.5)
rainbow (3.1.1)
rake (13.3.0, 13.0.6)
rasn1 (0.14.0)
rb-readline (0.5.5)
rbs (2.8.2)
rdoc (6.15.0, default: 6.5.0)
readline (default: 0.0.3)
readline-ext (default: 0.1.5)
recog (3.1.14)
redcarpet (3.6.1)
regexp_parser (2.11.3)
reline (0.6.2, default: 0.3.2)
require_all (3.0.0)
resolv (default: 0.2.2)
resolv-replace (default: 0.1.1)
rest-client (2.1.0)
rex-arch (0.1.20)
rex-bin_tools (0.1.17)
rex-core (0.1.36)
rex-encoder (0.1.10)
rex-exploitation (0.1.44)
rex-java (0.1.8)
rex-mime (0.1.11)
rex-nop (0.1.4)
rex-ole (0.1.9)
rex-powershell (0.1.103)
rex-random_identifier (0.1.21)
rex-registry (0.1.6)
rex-rop_builder (0.1.6)
rex-socket (0.1.71)
rex-sslscan (0.1.13)
rex-struct2 (0.1.5)
rex-text (0.2.63)
rex-zip (0.1.6)
rexml (3.4.1, 3.2.5)
rinda (0.2.0, default: 0.1.1)
rkelly-remix (0.0.7)
rspec (3.13.1)
rspec-core (3.13.5)
rspec-expectations (3.13.5)
rspec-mocks (3.13.5)
rspec-rails (8.0.2)
rspec-rerun (1.1.0)
rspec-support (3.13.6)
rss (0.2.9)
rubocop (1.75.7)
rubocop-ast (1.47.1)
ruby-macho (4.1.0)
ruby-mysql (4.2.0)
ruby-prof (1.7.2)
ruby-progressbar (1.13.0)
ruby-rc4 (0.1.5)
ruby2_keywords (0.0.5)
ruby_smb (3.3.21)
rubygems-update (3.4.20)
rubyntlm (0.6.5)
rubyzip (3.3.0)
sawyer (0.9.2)
sdbm (1.0.0)
securerandom (0.4.1, default: 0.2.2)
set (default: 1.0.3)
shellwords (default: 0.1.0)
simplecov (0.18.2)
simplecov-html (0.13.1)
simpleidn (0.2.3)
sinatra (4.2.1)
singleton (default: 0.1.1)
sqlite3 (2.9.4 x86_64-linux-gnu)
sshkey (3.0.0)
stringio (3.1.1, default: 3.0.4)
strptime (0.2.5)
strscan (default: 3.0.5)
swagger-blocks (3.0.0)
syntax_suggest (default: 1.1.0)
syslog (0.3.0, default: 0.1.1)
tempfile (default: 0.1.3)
test-prof (1.4.4)
test-unit (3.5.7)
thin (2.0.1)
thor (1.5.0)
tilt (2.6.0)
time (default: 0.2.2)
timecop (0.9.10)
timeout (0.4.3, default: 0.3.1)
tmpdir (default: 0.1.3)
tomlrb (2.0.4)
tsort (0.2.0, default: 0.1.1)
ttfunk (1.8.0)
typeprof (0.21.3)
tzinfo (2.0.6)
tzinfo-data (1.2025.1)
un (default: 0.2.1)
unicode-display_width (3.2.0)
unicode-emoji (4.1.0)
unix-crypt (1.3.1)
uri (1.1.1, default: 0.12.2)
useragent (0.16.11)
warden (1.2.9)
weakref (default: 0.1.2)
webmock (3.26.2)
webrick (1.9.1, 1.8.1)
websocket-driver (0.7.7)
websocket-extensions (0.1.5)
win32api (0.1.0)
windows_error (0.1.6)
winrm (2.3.9)
with_env (1.1.0)
xdr (3.0.1)
xml-simple (1.1.9)
xmlrpc (0.3.3, 0.3.2)
yaml (default: 0.2.1)
yard (0.9.37)
zeitwerk (2.7.3)
zlib (default: 3.0.0)
mipl@mipl-dev-server:~/metaspoit$ ruby -v
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
mipl@mipl-dev-server:~/metaspoit$

**Comment by rajeshrd123** [comment]
why code should complain about ambiguity? it should always proceed with latest version of gem and should not complain. i think this warning message is causing unnescessary time waste of users.
