### ISSUE TITLE
`The installation path is insecure. Bundler cannot continue.` on GitHub Actions runner.

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#7983]
The rack test suite was working fine until it wasn't. Maybe about a month or two ago?

It started failing with the following error:

```
The installation path is insecure. Bundler cannot continue.
/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems is world-writable
(without sticky bit).
Bundler cannot safely replace gems in world-writeable directories due to
potential vulnerabilities.
Please change the permissions of this directory or choose a different install
path.
```

The solution I found: <https://github.com/rack/rack/pull/2244> (seems like a hack).

Prior Discussion: <https://github.com/ruby/setup-ruby/issues/624>. It doesn't appear to be an issue with `setup-ruby`.

It looks like the permissions of the install directory are incorrect OR maybe bundler is being too strict. I'm not sure why this is happening or who's "fault" it is, but I thought I'd report it here for visibility.

**Comment by eregon** [comment]
My understanding is basically GitHub Actions has always been very loose with permissions (777 for the hostedtoolcache and the home):
* https://github.com/actions/runner-images/issues/10215#issuecomment-2263152071
* https://github.com/actions/runner-images/issues/267

And it seems some change in newer Bundler recently started failing in that scenario.
Were there some changes around this permission check in Bundler recently-ish?

Failing in that condition seems too limiting, very permissive permissions (777) is fairly common in Docker containers and while I would love for GitHub Actions runners to fix this, given that https://github.com/actions/runner-images/issues/267 still hasn't been fixed (AFAIK) I have very little hope it will change. I suppose they might consider it somewhat incompatible too. And for the hostedtoolcache it might be intended for it to be writable by different users.

Maybe Bundler could warn instead of error in that case, or have some config to not error in that case?

FWIW checking whether a directory is writable and safe seems not trivial, for instance I read [this ticket](https://bugs.ruby-lang.org/issues/20693) recently which explains the so many way to control file accesses.
IMO it's just not Bundler's (or Ruby's) job to check user permissions.
It's probably OK to warn for it though, if not too many false-positives.

**Comment by deivid-rodriguez** [comment]
Thanks for the report! Some observations from my investigation:

* We did not change anything related to this recently, except for some rewording of the error message to try make it more helpful.
* It's not Bundler checking permissions here, but FileUtils. FileUtils comes with a more secure version of `rm_rf` called `remove_entry_secure` that Bundler has used for years: https://github.com/ruby/fileutils/blob/8e592bbe8474248468d12a5ad7fd28b8b41535f0/lib/fileutils.rb#L1337-L1422.
* The security issue `remove_entry_secure` is protecting from is a bit obscure for me to understand but I think it's related to someone potentially creating a malicious symlink inside the folder, and as a consequence, unintended files getting removed. Or something like that. I'm not sure we need it, or whether the issue is actually valid. The issue and fix were apparently copied from Perl. Here's a couple of links from 20 years ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=286905, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=286922. In any case, I don't want to stop protecting from it unless I fully understand it.
* This problem though, was indeed introduced by a change in Bundler. It's because of https://github.com/rubygems/rubygems/pull/7673. Since that change, Bundler will explicitly install default gems, and I believe those are the ones creating the problem here.
* I assume Rails lockfile is locked to a gem that's also a default gem on Ruby 3.2 and Ruby 3.1. Default gems in a Ruby distribution are not really installed, but an emtpy installation folder is included for them.
* Since Bundler 2.5.12 (the mentioned PR), Bundler explicitly installs these gems, and it refuses to remove this empty previous installation folder because of the insecure permissions.

So, conclusions:

* Since these folders are actually empty, there's no need to even try to remove them, so I expect https://github.com/rubygems/rubygems/pull/7985 to fix this.
* I still believe the Actions environment has broken permissions for Ruby 3.1 and Ruby 3.2, but Ruby 3.3 seems fine, so probably does not need any fixes if this problem can be workaround with #7985.

**Comment by eregon** [comment]
> but Ruby 3.3 seems fine

Most likely that's because the specific 3.3.x version if not in the hostedtoolcache.
The archives built by https://github.com/ruby/ruby-builder all have correct permissions, but everything in the initial hostedtoolcache is 777.

**Comment by eregon** [comment]
Thanks, I hope https://github.com/rubygems/rubygems/pull/7985 fixes it.
From the message above, it sounds like it's about `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems` which I would think is not empty as it would contain e.g. bundled gems (but I don't have time to verify if that's the case now).

**Comment by deivid-rodriguez** [comment]
> Most likely that's because the specific 3.3.x version is not already in the hostedtoolcache.
> The archives built by https://github.com/ruby/ruby-builder all have correct permissions (in the tarball at least), but everything in the initial hostedtoolcache is 777.

That could be it. I just checked the permissions of `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems`, and `/opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems`, but could be that `3.2.5` was preinstalled but `3.3.4` was filled by `ruby/setup-ruby` if that's what you mean.

> Thanks, I hope https://github.com/rubygems/rubygems/pull/7985 fixes it.

Yeah, I'm pretty confident since I reproduced the problem locally and understood what was going on and the patch fixed it.

> From the message above, it sounds like it's about /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems which I would think is not empty as it would contain e.g. bundled gems (but I don't have time to verify if that's the case now).

The message, even if recently improved, is still not great, because even if the problem is the permissions of `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems`, the error happens when removing a subdirectory of it. In the case of `rack/rack`, it was `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems/ruby2_keywords-0.0.5`, which was an empty folder due to being a default gem. In #7985 I tried to improve the error a bit more in addition to skipping the error when the folder is actually empty. Now it will read like this:

> Bundler cannot reinstall `ruby2_weywords-0.0.5` because there's a previous installation of it at `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems/ruby2_keywords-0.0.5` that is unsafe to remove. The parent of `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems/ruby2_keywords-0.0.5` is world-writable and does not have the sticky bit set, making it insecure to remove due to potential vulnerabilities. Please change the permissions of `/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems` or choose a different install path.

**Comment by ioquatix** [comment]
Thanks for the detailed investigation and proposed fix. Once it's released, I'll try it out.

**Comment by mensfeld** [comment]
FYI I am still seeing the same issue randomly: https://github.com/karafka/karafka-testing/actions/runs/13043840673/job/36390956123

**Comment by deivid-rodriguez** [comment]
This issue was fixed in Bundler 2.5.19 and your lockfile is using Bundler 2.5.14. Make sure to update your locked version and you should be fine.

**Comment by mensfeld** [comment]
Yeah updating as we speak. Sorry for the noise @deivid-rodriguez 🙏

**Comment by dazuma** [comment]
We started encountering this in the past few weeks on our github action. In our case, we are using a bundler with the fix described in this issue (bundler 2.5.22 which ships with Ruby 3.3.7). The fix is failing on the gem `syntax_suggest-2.0.1`, and is doing so because that gem's directory is actually *not* empty, but contains an executable. An example run and output is at https://github.com/googleapis/google-api-ruby-client/actions/runs/13481932399/job/37668232365?pr=21693. For now I've worked around the issue by modifying the directory permissions.

**Comment by G-Rath** [comment]
We've started getting this on https://github.com/ackama/rails-template using [the current latest release of the Ubuntu 24.04 runner image](https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250804.2) which caches Ruby 3.4.5:

```
/opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/3.4.0/bundler/rubygems_gem_installer.rb:160:in 'Bundler::RubyGemsGemInstaller#strict_rm_rf': Bundler cannot reinstall package_json-0.1.0 because there's a previous installation of it at /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/package_json-0.1.0 that is unsafe to remove. (Bundler::InsecureInstallPathError)
The parent of /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/package_json-0.1.0 is world-writable and does not have the sticky bit set, making it insecure to remove due to potential vulnerabilities.
Please change the permissions of /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems or choose a different install path.
```

In our case we're installing the `package_json` gem [via `bundler/inline`](https://github.com/ackama/rails-template/blob/main/template.rb#L99-L112), and the directory its complaining about does not have a previous version of the gem at all (not even an empty directory) so at the least I think the error message Bundler is given is slightly incorrect

**Comment by deivid-rodriguez** [comment]
Hei @G-Rath. This was fixed in Bundler 2.5.9, but your workflows are using Bundler 2.3.11, because that's what your lockfile specifies: https://github.com/ackama/rails-template/blob/5c9062f65d1fed65ce8679cefa586701128e37e4/Gemfile.lock#L99-L100.

If you replace the `BUNDLED WITH` version with 2.7.1 in order to use the latest version of Bundler, it should work fine.

**Comment by G-Rath** [comment]
@deivid-rodriguez thanks I'd missed that (🤦) but unfortunately it doesn't make a difference:

```
/opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/bundler-2.7.1/lib/bundler/rubygems_gem_installer.rb:160:in 'Bundler::RubyGemsGemInstaller#strict_rm_rf': Bundler cannot reinstall package_json-0.1.0 because there's a previous installation of it at /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/package_json-0.1.0 that is unsafe to remove. (Bundler::InsecureInstallPathError)
The parent of /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/package_json-0.1.0 is world-writable and does not have the sticky bit set, making it insecure to remove due to potential vulnerabilities.
Please change the permissions of /opt/hostedtoolcache/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems or choose a different install path.
```

<img width="3016" height="682" alt="Image" src="https://github.com/user-attachments/assets/68e0b65d-3d38-4320-a703-74bfa29edb91" />

(https://github.com/ackama/rails-template/pull/621)

**Comment by deivid-rodriguez** [comment]
Ouch, I'll try to figure out what's going on, then!

**Comment by deivid-rodriguez** [comment]
> In our case we're installing the package_json gem [via bundler/inline](https://github.com/ackama/rails-template/blob/main/template.rb#L99-L112), and the directory its complaining about does not have a previous version of the gem at all (not even an empty directory) so at the least I think the error message Bundler is given is slightly incorrect

I added some [debugging info](https://github.com/deivid-rodriguez/rails-template/actions/runs/16944530390/job/48022051958) the previous installation is there, with the permissions specified in the error message, so I'd say Bundler is working as intended? Not sure what's up with the permissions of the new cached ruby, I guess something changed from 3.4.4?

**Comment by G-Rath** [comment]
Thanks for digging into this further - that looks to align with my findings; seems that my logging was just too early which in hindsight makes sense - `after_bundle` does an install which includes `shakapacker` which has a dependency on `package_json` too. 

(the only reason we have `bundler/inline` is ensure we can `require` the gem in our own script as I believe bundler/ruby wasn't happy with doing that for a gem that had been installed via a system call)

**Comment by deivid-rodriguez** [comment]
Oh, I understood now, too, that probably nothing changed in GitHub Actions environment. The hostedtoolcache ruby has had broken permissions for a long time, you just happened to start using it because with the Ruby 3.4.5 upgrade it started matching the Ruby version that you are using, correct?

**Comment by G-Rath** [comment]
yeah exactly, which feels like a bug _somewhere_ (probably in the GHA image runner repo...?) but no one seems that motivated to fix it which I kind of get 😅 and also because I wasn't logging at the right time, it seemed like the message bundler was giving might have been incorrect but you've confirmed that was a me issue 🙂

**Comment by ReenigneArcher** [comment]
I'm getting this when setting up Homebrew on the ubuntu arm partner image. - https://github.com/orgs/Homebrew/discussions/6615

They have bundler set as `>= 2.2.25`, so I guess it should pick up the newest version possible.

https://github.com/Homebrew/brew/blob/b64029d4f999b8963d0dadb925d3b484207c1cee/Library/Homebrew/Gemfile.lock#L148

No issue on the non arm ubuntu image.
