### ISSUE TITLE
When installing a gem with Bundler, the highest allowed version of the gem's dependencies is not installed

### ISSUE THREAD

**Issue by timrogers** [rubygems/rubygems#8002]
### Describe the problem as clearly as you can

When installing a gem using Bundler, my understanding is that the **highest allowed version of the gem's dependencies should be installed** (perhaps this understanding is wrong!).

The gem in question (which I maintain), `restforce`, [specifies](https://github.com/restforce/restforce/blob/8fb0fc8/restforce.gemspec) that `faraday` versions are allowed that are greater than or equal to `v1.1.0`, and before `v2.11.0`:

```ruby
gem.add_dependency 'faraday', '< 2.11.0', '>= 1.1.0'
```

When installing `restforce` with Bundler, the **highest allowed version** of Faraday is installed:

```bash
$ gem install restforce
# ...
Successfully installed faraday-2.10.1
```

But when installing `restforce` with Bundler, a very old version is selected:

```bash
$ echo $'source \"https://rubygems.org\"\ngem \"restforce\"' > Gemfile && bundle
# ...
Installing faraday 2.0.0
```

### Did you try upgrading rubygems & bundler?

I am running the latest version of Bundler with `gem update bundler`.

### Post steps to reproduce the problem

Run the following command with Docker to reproduce the issue:

```bash
docker run -it ubuntu /bin/bash -c "apt-get update && apt-get install -y ruby && gem install bundler && echo $'source \"https://rubygems.org\"\ngem \"restforce\"' > Gemfile && bundle"
```

In the output, you will see an old version of `faraday` being installed:

```
Installing faraday 2.0.0
```

### Which command did you run?

`bundle install`

### What were you expecting to happen?

The latest permitted version of a gem's dependencies is installed

### What actually happened?

An old version of the gem's dependencies is installed

### If not included with the output of your command, run `bundle env` and paste the output below

```
## Environment

```
Bundler       2.5.18
  Platforms   ruby, aarch64-linux-gnu
Ruby          3.2.3p157 (2024-01-18 revision 52bb2ac0a6971d0391efa2275f7a66bff319087c) [aarch64-linux-gnu]
  Full Path   /usr/bin/ruby3.2
  Config Dir  /etc
RubyGems      3.4.20
  Gem Home    /var/lib/gems/3.2.0
  Gem Path    /root/.local/share/gem/ruby/3.2.0:/var/lib/gems/3.2.0:/usr/local/lib/ruby/gems/3.2.0:/usr/lib/ruby/gems/3.2.0:/usr/lib/aarch64-linux-gnu/ruby/gems/3.2.0:/usr/share/rubygems-integration/3.2.0:/usr/share/rubygems-integration/all:/usr/lib/aarch64-linux-gnu/rubygems-integration/3.2.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.2.0
  Bin Dir     /usr/local/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-26
Git SHA           c218aab519
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
gem "restforce"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    base64 (0.2.0)
    faraday (2.0.0)
      ruby2_keywords (>= 0.0.4)
    faraday-follow_redirects (0.3.0)
      faraday (>= 1, < 3)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (3.3.0)
      net-http
    hashie (5.0.0)
    jwt (2.8.2)
      base64
    multipart-post (2.4.1)
    net-http (0.4.1)
      uri
    restforce (7.4.0)
      faraday (>= 1.1.0, < 2.11.0)
      faraday-follow_redirects (<= 0.3.0, < 1.0.0)
      faraday-multipart (>= 1.0.0, < 2.0.0)
      faraday-net_http (< 4.0.0)
      hashie (>= 1.2.0, < 6.0)
      jwt (>= 1.5.6)
    ruby2_keywords (0.0.5)
    uri (0.13.1)

PLATFORMS
  aarch64-linux-gnu
  ruby

DEPENDENCIES
  restforce

BUNDLED WITH
   2.5.18
```

**Comment by timrogers** [comment]
I think this issue is somehow related to the fact that the latest minor version of Faraday, v2.11.0, is not supported by my Gemspec at this time.

**Comment by timrogers** [comment]
Let me know if I can provide any further details on this. I am going to release a new version of the affected gem which allows the most recent minor version of Faraday, which I _suspect_ will make this go away, but it will probably still be reproducible by explicitly telling Bundler 

> There is no guarantee that Bundler will install the newest version of a gem, only that it will install a version that is compatible. That said, this does sound like it might be a bug, and worth investigating.

If Bundler isn't guaranteed to install the latest allowed gem version, what do you see as the bug here?

**Comment by deivid-rodriguez** [comment]
Hi, thanks for reporting!

So the explanation here is that resolving versions problem does not have a unique solution, and sometimes it's not easy to decide which solution is better. Indeed it's possible to install `restforce-7.4.0` while also installing `faraday-2.10.1`. However that requires sticking to `faraday-net_http-3.1.1`, because `faraday >= 2.9.0, < 2.11.0` depends on `faraday-net_http >= 2.0, < 3.2` (while `faraday-2.11.0` relaxes that to `faraday-net_http >= 2.0, < 3.4`).

So while the solution given by RubyGems maximizes the version of the `faraday` dependency, it's not able to maximize the version of the `faraday-net_http` dependency. Conversely, Bundler's solution maximizes the version of the `faraday-net_http` dependency, but it's not able to maximize the version of the `faraday` dependency.

Normally Bundler will prefer to maximize the version of direct dependencies over indirect dependencies, but in this case both `faraday` and `faraday-net_http` are indirect dependencies (dependencies of the top level `restforce` gem), so both solutions are considered equally good, and Bundler accepts the first one it finds.

The only issue I see here is the different behavior between RubyGems and Bundler. That will get fixed once RubyGems is migrated to use PubGrub as the resolution engine, that's #6042.

I'll close this but let me know if something is not clear!
