### ISSUE TITLE
Bundler inline always installs missing gems regardless of "install" parameter

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [rubygems/rubygems#8140]
The `gemfile` method from [inline.rb](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/inline.rb) takes an `install` parameter. This parameter is documented as:

```
whether gems that aren’t already installed on the

user's system should be installed.
Defaults to `false`.
```

However in my testing the missing gems are installed regardless of this parameter. I think this is because of this clause:

https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/inline.rb#L58

**Comment by jeromedalbert** [comment]
Looks like this issue is a duplicate of https://github.com/rubygems/rubygems/issues/5364.

It was [agreed](https://github.com/rubygems/rubygems/pull/6304#issuecomment-2373566735) that the `install` parameter should be deprecated, and there is a pending [PR](https://github.com/rubygems/rubygems/pull/5844) to do that, which is waiting for feedback from the author.

**Comment by LevitatingBusinessMan** [comment]
Closing this as duplicate to keep the discussion at #5364
