### ISSUE TITLE
RSpec Tests need some cleanup

### ISSUE THREAD

**Issue by soda92** [rubygems/rubygems#8249]
RSpec tests are easily getting bad.
I'm spending far more time than I planned on https://github.com/rubygems/rubygems/pull/8224.

Please check: <https://youtu.be/KyAfyyy05y0?si=87RKH5g7mgMiQtm9>

I have expanded the tests, you will see how complex they are.

**Comment by soda92** [comment]
https://github.com/rubygems/rubygems/pull/8250

**Comment by soda92** [comment]
Also, 
# How can I debug failed RSpec tests?

since Rspec is using its own DSL,
1. ⚠️ `debugger` didn't work,
2. ⚠️ `require` didn't work,
3. ⚠️ `RUBYOPT` didn't work.

I only get by by using `puts` and `sleep`. Since when did ruby become such a clumsy language?

**Comment by simi** [comment]
`debugger`, `require`, `RUBYOPT` all works also you can put `binding.irb` into middle of spec if needed. What exactly is your problem? Usually problem is in RubyGems/Bundler testing specificalities, since by the design, those tools are not simple to setup for testing since they can't mostly use itself (as are used in most of the other projects).

> Since when did ruby become such a clumsy language?

_I would say since never._

**Comment by soda92** [comment]
> since by the design, those tools are not simple to setup for testing since they can't mostly use itself (as are used in most of the other projects).

Yeah that was exactly it. maybe I'm too aggressive.

But this repo is using simulation heavily (fake repo and etc.), and I don't see any instruction for setting up rspec debugging. with extensive test suite, it will only cause frustration.

**Comment by simi** [comment]
> > since by the design, those tools are not simple to setup for testing since they can't mostly use itself (as are used in most of the other projects).
> 
> Yeah that was exactly it. maybe I'm too aggressive.
> 
> But this repo is using simulation heavily (fake repo and etc.), and I don't see any instruction for setting up rspec debugging. with extensive test suite, it will only cause frustration.

https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/DEBUGGING.md

**Comment by soda92** [comment]
Thanks I have already checked this and dbundle is working fine. But I'd like to know how to step into `rspec` tests.

it didn't work the same as the `dbundle` setup.

**Comment by simi** [comment]
Would you mind which test and how you would like to step in ?

**Comment by soda92** [comment]
A demo would be: `rubygems\bundler> rspec spec/commands/exec_spec.rb:5`

If I put a `debugger` command there, it would not work.

**Comment by simi** [comment]
Why would you put debugger in between tests to empty space?

**Comment by soda92** [comment]
Well not limited to debugger. Binding.pry or byebug is also fine. The aim is for a general debugging setup for rspec tests in rubygems.

**Comment by duckinator** [comment]
If you run `gem install pry-rescue pry-stack_explorer`, then use `rescue rspec ...` instead of `rspec ...`, any test failure will drop you into an interactive prompt.

E.g., I added `fail` to line 5 of spec/commands/exec_spec.rb (so there would be a failure), then ran `rescue rspec spec/commands/exec_spec:5`, and this is the result:

![image](https://github.com/user-attachments/assets/19309b3a-5e70-467e-8df2-a07136e288ef)

We don't really need an issue for tracking that the tests are complicated. If you have suggestions that would make them simpler, you can open a pull request and actually explain your reasoning in the PR template.

**Comment by soda92** [comment]
Thank you
