### ISSUE TITLE
Allow excluding dependencies of dependencies

### ISSUE THREAD

**Issue by bhollis** [rubygems/rubygems#835]
Every once in a while, I want my gem to depend on another gem, but _without_ some of that other gem's dependencies (because they aren't all necessary for what I'm using). For example, `middleman` vendors Padrino because it just wants part of Padrino's helpers and we don't want to pull in all of Padrino's many dependencies. Another example is a Middleman extension I'm building that wraps a Rails extension - I want to depend on and use the classes defined in the Rails extension, but I don't want to bring along the Rails dependency from the extension gem.

I'm imagining a pattern like this:

``` ruby
s.add_dependency("ngmin-rails", ["~> 0.4.0"], :without => ["rails"])
```

**Comment by simi** [comment]
I would say just ask gem author to remove the dependency if not needed. Middleman still depends on padrino helpers, but those were extracted into padrino-helpers gem and middleman functionality related was extracted into middleman-core gem. There is no safe way to exclude transitive dependency and it is against nature of dependency management to remove needed dependencies IMHO.

**Comment by deivid-rodriguez** [comment]
I think the right solution for this always belongs in the gem you are depending on. Either it should eliminate unnecessary dependencies, or convert them to [optional dependencies](https://github.com/rubygems/rubygems/issues/1811), once that's supported. I don't think explicitly allowing excluding dependencies of dependencies from the gemspec file would be a good move, so I'd focus on related features like optional dependencies.

Since other maintainers have already expressed similar feelings, I'll close this. Thanks!
