### ISSUE TITLE
Using ruby 3.0.0 doing gem update --system attemps to install rubygems-update v 3.6.2

### ISSUE THREAD

**Issue by nathanvda** [rubygems/rubygems#8363]
### Describe the problem as clearly as you can

When using ruby 3.0.0.0 doing  

     RUN gem update --system --no-document &&     gem install -N bundler

(building a docker image) 
it attemps to install `rubygems-update-3.6.2` which requires ruby >= 3.10 and thus the docker building process fails. 

### Temporary work-around?

I was able to work around this by editing the Dockerfile and replacing 

```
# Update gems and bundler
RUN gem update --system --no-document && \
    gem install -N bundler
```

with 

```
# Update gems and bundler
RUN gem update --system 3.5.22 --no-document && \
    gem install -N bundler
```

(essentially using a specific version).

**Comment by deivid-rodriguez** [comment]
Hi! This was fixed by https://github.com/rubygems/rubygems/pull/7334, released as RubyGems 3.5.4. Unfortunately old versions of Ruby still ship with a RubyGems version without that fix, hence the issue.

So, you'll need to keep the workaround until you upgrade to at least Ruby 3.3.1 (which ships with RubyGems 3.5.9, including the fix). See https://stdgems.org/rubygems/ to check which RubyGems version is shipped with each Ruby.

Closing since this is already fixed.
