### ISSUE TITLE
Why duplicate xxx.so file to `extensions` directory?

### ISSUE THREAD

**Issue by windwiny** [rubygems/rubygems#926]
I create a gem with c-extension named `abc`, and install it `gem install -l abc-0.0.1.gem`

then rubygem directory has 3 `abc.so` file.

```
<gem>/extensions/<arch>/2.0.0/abc-0.0.1/abc.so
<gem>/gems/abc-0.0.1/ext/abc/abc.so
<gem>/gems/abc-0.0.1/lib/abc.so
```

Why duplicate xxx.so file to `extensions` directory?

Delete `<gem>/extensions/<arch>/2.0.0/abc-0.0.1` directory, and run `require 'abc'` , then `rubygem` will re-compile the c source file, and put so file to `<gem>/extensions/<arch>/2.0.0/abc-0.0.1`

Why need do this? the `<gem>/gems/abc-0.0.1/lib/` directory already has the `abc.so` .

**Comment by celesteking** [comment]
Re this issue, with 2.1 stable I see ext is placed into:
````
1) <gem>/extensions/<arch>/2.0.0/abc-0.0.1/abc.so
2) <gem>/gems/abc-0.0.1/lib/abc.so
```

Now, you're saying `2)` will be gone? Could you clarify, please?
If so, there should be programmic way of getting that `1)` directory location. I looked all over internets and couldn't find that. 

Also, with current state of affairs, abc.so is searched first in `2)` and only then in `1)`, which contradicts deprecation plan.

What I have also noticed is that `<gem>/extensions/<arch>/2.0.0/abc-0.0.1/gem.build_complete` file should be present, otherwise extension rebuild is automatically triggered.

**Comment by drbrain** [comment]
Yes. 2) will be gone. [Gem::Specification#extension_dir](https://github.com/rubygems/rubygems/blob/4e0518dab8c51c6ac074fb72df63bdd2729ff0f3/lib/rubygems/basic_specification.rb#L101)

**Comment by drbrain** [comment]
$LOAD_PATH order is a bug, can you create a separate issue?
