### ISSUE TITLE
post install steps

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems#957]
hello, i am not sure if this feature has been requested or implemented yet, but it would be useful if post install steps could be run without falling onto a Makefile or the compilation of C code. is it possible to do this with only ruby? my use case is to copy a rc file on install to the user's $HOME directory. maybe an interactive dialog could be started by rubygems if/when this process is requested by the gem? a simple y/n might work.

**Comment by krainboltgreene** [comment]
Super hesitant to keep this open, since the original user is gone ( :ghost: ) and drbrain is super right. This would require so many gems to basically change how they function (up to including rails and bundler) that it's basically a non-starter.

HOWEVER. If this were added we'd want an official specification for:

  1. how input is handled
  2. exiting/failing/fault tolerance
  3. non-interactive consumers
