### ISSUE TITLE
Changes for prelease gems breaking find_by_name

### ISSUE THREAD

**Issue by niedfelj** [rubygems/rubygems#988]
We are running spree beta code in our rails environment (latest rubygems and bundler).  Previously, we were using Gem::Specification.find_by_name to find the gem_dir for the spree gem.  With the latest changes to Gem::Dependency for prelease gems, find_by_name now returns nil.  Is this the intended behavior or is it an issue with Bundler not activating the gems as specified in the Gemfile.lock?  I would expect all of my gems as specified in the Gemfile.lock to be activated, but I'm also confused as to why the results of find_all_by_name and find_by_name would be inconsistent?

```
Loading development environment (Rails 3.2.18)
2.1.2 :001 > Gem::Specification.find_by_name 'spree'
 => nil 
2.1.2 :002 > Gem::Specification.find_all_by_name 'spree'
 => [#<Gem::Specification:0x81019060 spree-2.0.12.beta>] 
```

**Comment by wasnotrice** [comment]
For future travelers, I ran into this issue running rubygems 2.4.3, but after reading this issue, I updated rubygems to version 2.4.5, and the issue was solved. Thanks @drbrain for the thorough treatment :)

**Comment by wasnotrice** [comment]
Welp. I guess that upgrade didn't fix this error after all. I don't know if I can provide a sane failing case, because this project is very early stages. I'm compiling for Opal with prerelease dependencies that are loaded by Bundler, and it looks like my gem isn't activated. That might explain how I could get a failure even though the spec in 98d03c3 passes:

```ruby
# Gemfile
source 'https://rubygems.org'

# All 3 of these declarations for 'shoes-core' fail
# gem 'shoes-core', git: 'git@github.com:shoes/shoes4.git', branch: 'master'
# gem 'shoes-core', path: './vendor/shoes-core'
gem 'shoes-core', '~> 4.0.0.pre', path: './vendor/shoes-core-4.0.0.pre2'

gem 'opal', git: 'git@github.com:opal/opal.git', branch: 'master'
gem 'rake'
```


I added this code to the opal loader (no simple repl for the build environment):

```ruby
# lib/opal/paths.rb
spec = Gem::Specification.find_by_name(gem_name)
all_specs = Gem::Specification.find_all_by_name(gem_name)

puts "Gem::Specification.find_by_name('#{gem_name}') => #{spec.inspect}"
puts "Gem::Specification.find_all_by_name('#{gem_name}') => #{all_specs.inspect}"
puts "spec.activated? #{all_specs.last.activated?}"
```

Then running the build:

```
$ rake
Gem::Specification.find_by_name('shoes-core') => nil
Gem::Specification.find_all_by_name('shoes-core') => [#<Gem::Specification:0x3ffb1589a710 shoes-core-4.0.0.pre2>]
spec.activated? false
```

Modifying the version to have no letters works around the problem. Although the gem still reports not being activated, `#find_by_name` does find the gem, and the build succeeds:

```ruby
# lib/shoes/core/version.rb
class Shoes
  module Core
    #VERSION = "4.0.0.pre2"
    VERSION = "4.0.0.2"
  end
end
```

```
$ rake
Gem::Specification.find_by_name('shoes-core') => #<Gem::Specification:0x3fd27997f1f4 shoes-core-4.0.0.2>
Gem::Specification.find_all_by_name('shoes-core') => [#<Gem::Specification:0x3fd27997f1f4 shoes-core-4.0.0.2>]
spec.activated? false
```
